### ISSUE TITLE
Integrate Travis CI and Coveralls

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#1]
Let's run our tests through Travis CI and report all test coverage via Coveralls.

By default, Travis runs the `npm test` command found in `package.json`.

For an example of how this works, view any of the makeup modules:

https://github.com/makeup-js/makeup-expander/blob/master/.travis.yml

(Note that the location of our reports is different than in makeup).

Coveralls will be a new devDependency.

**Comment by yomed** [comment]
We should probably configure this to run both `lint` in addition to `test` so that it catches linting issues in PRs.

**Comment by ianmcburnie** [comment]
Yep, I thought that was happening already as part of `test`.

**Comment by ianmcburnie** [comment]
Will set it up without linting to begin with... less to go wrong :-)

**Comment by ianmcburnie** [comment]
First run of Travis:

<img width="1126" alt="screen shot 2018-03-02 at 3 45 16 pm" src="https://user-images.githubusercontent.com/38065/36927188-c5660cda-1e30-11e8-9ea7-12aa6e3f0770.png">

Poop.

**Comment by yomed** [comment]
@ianmcburnie The Travis part is fixed now. Can you check if Coveralls is working as you expected?

**Comment by ianmcburnie** [comment]
Nice work. 

Coveralls is kinda working, some issues with graph not showing up, so I'll look into that:

https://coveralls.io/github/eBay/ebayui-core

**Comment by ianmcburnie** [comment]
I will create a PR for what we have.

**Comment by ianmcburnie** [comment]
Done. Will create new task to add linting to CI.
