### ISSUE TITLE
ebay-select: option text

### ISSUE THREAD

**Issue by darkwebdev** [eBay/ebayui-core#1001]
# Discussion around `ebay-select` syntax

## Description
Is there any reason behind using a `text` attribute in `ebay-select-option` instead of just passing content as children like `<ebay-select-option>some text</ebay-select-option>` as it's done it HTML spec?
Maybe we'll be able to use icons inside in future, who knows...

**Comment by seangates** [comment]
I believe it's to enforce `text` as a string.

**Comment by ianmcburnie** [comment]
Yes, I think because we are limited by the HTML select tag, we have to enforce text only. For nested HTML, ebay-listbox should be used.

CoreUI v6.0.0 is going to be an API cleanup. We can look at this again then.

**Comment by ianmcburnie** [comment]
I think we can close this one, because the select element only allows text. Feel free to re-open if I've missed something.
