### ISSUE TITLE
Menu: menu expanded onload 

### ISSUE THREAD

**Issue by mcferrenm** [eBay/ebayui-core#1002]
# Bug Report

## Description
Trying to fix a bug with ebay-menu on homepage in the sub-interest module. We recently upgraded ebayui to 4.4.2 and now <ebay-menu> renders with the menu expanded onload. We also upgraded skin to 9.4.0 and are using marko 4.13.13.

[redacted internal URL]

No console errors.

## Screenshots
Expected:
![image](https://user-images.githubusercontent.com/10376398/71421566-a28f7480-2649-11ea-87b0-ec66d7de7f03.png)

Actual:
![image](https://user-images.githubusercontent.com/10376398/71421766-ff3f5f00-264a-11ea-8924-514d8744ac11.png)

**Comment by agliga** [comment]
Just to clarify, the issue is that now the menu is showing as expanded on page load? The reason I ask is the expected screenshot shows the menu expanded and the actual shows the non collapsed menu. From the description you expect the menu to be collapsed but is actually expanded?

**Comment by seangates** [comment]
@agliga If you notice you see "see all" and "choose your interests" below the kebab.

**Comment by agliga** [comment]
This is not an issue, I checked the page which was using this and they were loading skin CSS for `menu` and not for `menu-button`

**Comment by agliga** [comment]
Please reopen if there are any other issues found or anything else
