### ISSUE TITLE
Textbox: focus is not supported

### ISSUE THREAD

**Issue by seangates** [eBay/ebayui-core#1004]
# Bug Report

## Description
Presently `ebay-textbox` doesn't allow a developer to use `.focus()` to focus on the input, hindering some simple DOM API functionality usually available to them. Because the DOM element returned from `getEl` is the wrapper for the textbox, the developer loses some simple, yet helpful, capabilities, especially when working with forms.

What is requested is to be able to do something along these lines:

```
const textboxEl = this.getEl('myTextboxKey');
textboxEl.focus();
```

## Workaround
Yes, through direct DOM querying and subsequent API access.

**Comment by ianmcburnie** [comment]
Surprise we haven't run into this earlier! @seangates Okay if we put this in v5?

**Comment by seangates** [comment]
Sure. We have a workaround, but we'd rather not query the DOM directly to do it.
