### ISSUE TITLE
ebay-tooltip: overlay is hidden when the parent element has overflow hidden

### ISSUE THREAD

**Issue by uachladi** [eBay/ebayui-core#1005]
# Bug Report

## Description
When we add ebay-tooltip on the table header element which has overflow hidden, the overlay is not shown (shui-tooltip)

## Screenshots
![Screen Shot 2020-01-02 at 11 44 51 AM](https://user-images.githubusercontent.com/13039089/71688923-b2980a00-2d55-11ea-90ad-56ae8ee3e964.png)

**Comment by ianmcburnie** [comment]
Do you have a local override for workaround?

**Comment by ianmcburnie** [comment]
See https://github.com/eBay/ebayui-core/issues/1006#issuecomment-571790488 for details of problem and possible fix.

**Comment by uachladi** [comment]
@ianmcburnie , Thanks for details. I did try out this, it works only if there is no relative position for any child between the overflow:hidden element and position:absolute element. For the component I am working on, mostly it should be ok as it does not have any depth of child elements. I can close the ticket.
