### ISSUE TITLE
ebay-menu-button: menu is hidden when the parent has overflow hidden

### ISSUE THREAD

**Issue by swathip88** [eBay/ebayui-core#1006]
# Bug Report

## Description
When ebay-menu-button is used on shui-data-table, Menu gets hidden since data-table has overflow-y as hidden

## Screenshots
<img width="1260" alt="Screen Shot 2020-01-02 at 11 50 26 AM" src="https://user-images.githubusercontent.com/15898444/71689152-30f4ac00-2d56-11ea-95fa-c93ca2f54456.png">

**Comment by ianmcburnie** [comment]
Do you have a local override for workaround?

**Comment by ianmcburnie** [comment]
@swathip88 Did some investigation into this. Thanks Swathi!

Currently the widget root has relative positioning, and the overlay has absolute positioning. This is quite normal for overlays:

```
<div>
    <div style="overflow: hidden">
        <!-- widget start -->
        <span style="position: relative;">
            <button></button>
            <span style="position: absolute"></span>
        </span>
        <!-- widget end -->
    </div>
</div>
```

However, the overflow hidden on the outer element causes the overlay to be hidden. A way to fix is by moving the `position: relative` from the widget's root to an ancestor of the element with hidden overflow:

```
<div style="position: relative">
    <div style="overflow: hidden">
        <!-- widget start -->
        <span>
            <button></button>
            <span style="position: absolute"></span>
        </span>
        <!-- widget end -->
    </div>
</div>
```

**Comment by ianmcburnie** [comment]
Going to close this as this was an edge case that required some custom logic due to the way the table is constructed.
