### ISSUE TITLE
ebay-expand-button: add support for borderless

### ISSUE THREAD

**Issue by ZZS77** [eBay/ebayui-core#1009]
# Feature Request

## Description
Add support for borderless

## Screenshots
![image](https://user-images.githubusercontent.com/42783072/71917123-370ed200-3134-11ea-91a2-9bb82dc3144b.png)

**Comment by ianmcburnie** [comment]
@ZZS77 We have a new details component coming in v5.2.0 that should look and behave like the screenshot.

Here it is in Skin: https://ebay.github.io/skin/#details

I'm going to close this issue as I feel like details component is the correct choice. Considering moving expand-button onto the deprecation list too...
