### ISSUE TITLE
ebay-menu-button-item: does not support disabled 

### ISSUE THREAD

**Issue by swathip88** [eBay/ebayui-core#1017]
# Bug Report

## Description
We have a scenario where ebay-menu-button-item which is an anchor tag(fake-menu-button__item) needs to be disabled

## Screenshots
![Screen Shot 2020-01-13 at 4 24 24 PM](https://user-images.githubusercontent.com/15898444/72303168-32a95400-3621-11ea-8be9-a4fe4aaa6a48.png)

**Comment by ianmcburnie** [comment]
This will also require some work on the skin side, to style disabled anchor tags.

**Comment by ianmcburnie** [comment]
Disabling anchor tags requires absence/removal of `href` attribute.

Disabling ARIA menuitems requires `aria-disabled=true` and `tabindex=-1. Dynamically changing tabindex might cause problems for the makeup-roving-tabindex, so we might want to leave that part for later.

**Comment by ianmcburnie** [comment]
@swathip88 this feature will be available for you in 5.6.0.
