### ISSUE TITLE
Carousel: add a peek to all carousels

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#1021]
We recently made changes to the carousel, so that when a single item is presented, there is no peek. In that case we then had to permanently show paddles as affordance. However, after chatting with design, the direction is clear that they want to show a peek, not paddles, in that case.

May require some skin work too.

<img width="408" alt="Screen Shot 2020-01-14 at 2 17 46 PM" src="https://user-images.githubusercontent.com/38065/72387593-b7a37480-36d8-11ea-92d6-1702cd0ffd57.png">

**Comment by ianmcburnie** [comment]
@msendlakowski We are considering making this update in 5.1.0. I know that you have a carousel like this in production that would be affected. Your carousel currently shows 1 item, no peek and permanent paddles. After update it will show 1 item, with peek and no paddles. Are you okay with this going into a minor release?

**Comment by msendlakowski** [comment]
Yeah, we should be good with that.  We are using version 4 for now.  We'll let our PM and design team know that we are frozen there, until they are ready to update the UI to the latest design system guidance.
