### ISSUE TITLE
combobox bug: change event not triggered when user types into combobox

### ISSUE THREAD

**Issue by fraglord94** [eBay/ebayui-core#1026]
## Description
Type something into the combobox and mouse click outside the combobox. `this.valueChanged` remains `false` and `handleComboboxBlur` does not trigger `emitComboboxEvent` with `change` 

Bug occurs when user types quickly into the combobox

#1026 # Bug Report

## eBayUI Version: 4.5.2

**Comment by agliga** [comment]
Released in `@ebay/ebayui-core@4.5.6`
