### ISSUE TITLE
upgrading to skin 4.0.0-4 causes issues with ebay-select components

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#103]
upgrading to skin 4.0.0-4 causes issues with ebay-select components
This is how the components looks
![ebay-select issue with skin upgrade](https://user-images.githubusercontent.com/13157115/38961917-b88a9846-431f-11e8-8fe1-bf30e4a1334a.png)

**Comment by seangates** [comment]
This should be taken care of with the newest pre-release of 0.3.0.
