### ISSUE TITLE
Combobox: listbox overlay does not scroll with current active descendant

### ISSUE THREAD

**Issue by fraglord94** [eBay/ebayui-core#1033]
# Bug Report

## Description
Open the combobox by clicking on the textbox part of the combobox (not the dropdown arrow). Using arrows keys the current selection keeps on getting highlighed (as we move down), but the scroll bar does not scroll. 

## Screenshots
![Screen Shot 2020-01-22 at 12 37 08 PM](https://user-images.githubusercontent.com/13619560/72932149-0a51e180-3d14-11ea-9680-8196d4a1d0c5.png)
![Screen Shot 2020-01-22 at 12 36 55 PM](https://user-images.githubusercontent.com/13619560/72932150-0aea7800-3d14-11ea-8f74-251e3c9b627a.png)
![Screen Shot 2020-01-22 at 12 38 41 PM](https://user-images.githubusercontent.com/13619560/72932312-5f8df300-3d14-11ea-97d5-d48e61983fd4.png)

**Comment by ianmcburnie** [comment]
The reason for this is because the combobox items do not have any kind of real keyboard focus. The items have psuedo focus only (with aria-activedescendant) which does not natively trigger any kind of scroll events. We'll have to investigate whether the fix lies inside of makeup-active-descendant, the component, or a mix of both.

**Comment by agliga** [comment]
The simplest way would be to add this line 
`this._containerEl.scrollTop = toItem.offsetTop - this._containerEl.offsetHeight / 2;`
here
https://github.com/makeup-js/makeup-active-descendant/blob/master/index.js#L63-L64
And that makes it look like this:
![scroll](https://user-images.githubusercontent.com/1755269/73323178-64aede80-41fb-11ea-82a6-799fd7ca929d.gif)

**Comment by ianmcburnie** [comment]
Looks good to me!

**Comment by agliga** [comment]
Released in @ebay/ebayui-core@4.5.7
