### ISSUE TITLE
Renaming ebay-breadcrumb and ebay-tab components is causing build failure

### ISSUE THREAD

**Issue by ushrivastava123** [eBay/ebayui-core#1034]
#909 Bug Report
<ebay-breadcrumb> is renamed to <ebay-breadcrumbs> and <ebay-tab> is renamed to <ebay-tabs> in ebayUI 5.0.0-3. This is causing build failures and page is erroring out unless the modules names are changed in the code.

## Description
<ebay-breadcrumb> is renamed to <ebay-breadcrumbs> and <ebay-tab> is renamed to <ebay-tabs> in ebayUI 5.0.0-3. This is causing build failures and page is erroring out unless the modules names are changed in the code.
Expected behavior: Updating ebayUI version should be seamless without any code changes needed.

## Workaround
Code change is the workaround

**Comment by ianmcburnie** [comment]
@ushrivastava123 This is a major version update (i.e. going from major version 4 to major version 5). In semantic versioning, it is expected that major versions can contain breaking changes. They should of course be documented (and they be will in our final release notes). Having said that, we do try and continue backwards compatibility if we can. I think in this case though it just makes sense to move to the new names without leaving in old aliases for everything (events, etc).

Going to close as wontfix.
