### ISSUE TITLE
<ebay-pills> component should be marked deprecated 

### ISSUE THREAD

**Issue by ushrivastava123** [eBay/ebayui-core#1035]
#909 Bug Report

## Description
<ebay-pills> component has beed removed from the code which is causing build failures.
Expected: <ebay-pills> should be marked deprecated so that upgrading to ebayUI 5.0.0-3 is seamless.

## Workaround
Removing ebay-pills code.

**Comment by agliga** [comment]
Taking a page from #1034 and Ian's comment. Will close since we expect people to remove non existing components
