### ISSUE TITLE
Combobox: allow UP ARROW to act like DOWN ARROW key when in collapsed state

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#1036]
Scenario: combobox overlay has been positioned above the combobox instead of below (due to lack of screen real estate below). The user's inclination is to press UP ARROW key to access the list of suggestions (because the list is above). Currently though, UP ARROW will do nothing.

Let's scope out what it will take for the UP ARROW to behave the same as DOWN ARROW when the combobox is in an initial, collapsed state. It should expand the list and set aria-activedescendant on first item.

**Comment by agliga** [comment]
@ianmcburnie  A simple workaround/fix for this is to add `this.activeDescendant.wrap = true;`
This allows you to use up key and select the last element in the list when the list is closed.
However this also allows wrapping to occur. We could think about adding a new option to `makeup-active-descendent` and in `makeup-navigation-emitter` where this is happening specifically changing this line to allow up to work when list is shown above:
https://github.com/makeup-js/makeup-navigation-emitter/blob/master/index.js#L54-L58

**Comment by agliga** [comment]
A quick note, this can be done also from the application if it is urgent by getting the combobox component and doing `component.activeDescendent.wrap = true`. Although it is a bit hacky.

**Comment by ianmcburnie** [comment]
@agliga I'm pretty sure setting wrap to true and pressing UP will cause active descendant to go to last item, rather than the first:

https://makeup-js.github.io/makeup-active-descendant/

**Comment by agliga** [comment]
Exactly, isn't that kinda strange to basically press the up arrow and have the first item in the list focused? Especially if it's on top of the input field. I would expect when pressing up to have the last item in the list focused rather than the first. 
If I press the up arrow currently, it does show the drop-down but with no items selected until I press the down arrow. Having it so that you press the up arrow first to select the first item is also confusing because then you have to press down to scroll in the list.

**Comment by ianmcburnie** [comment]
That was my first expectation too, but the last item in the list is the least relevant suggestion, which isn't very helpful. So we'd then have to reverse the order of the list items, with most relevant at the bottom, which starts getting really weird.

Putting the overlay above the combobox definitely makes things more confusing overall.

Let's hold off on this one for now.

**Comment by ianmcburnie** [comment]
We have decided not to do this. Closing.
