### ISSUE TITLE
Disabled listbox doesn't look like disabled

### ISSUE THREAD

**Issue by ushrivastava123** [eBay/ebayui-core#1038]
# Bug Report
Disabled listbox should be greyed out to look disabled

## Description
It is confusing to the user whether listbox is enabled or disabled

## Screenshots
Before:
![image](https://user-images.githubusercontent.com/57548118/73344919-018f6d00-4238-11ea-8911-6af320f6fb45.png)

After:
![image](https://user-images.githubusercontent.com/57548118/73344898-f2a8ba80-4237-11ea-87e8-82a952d66309.png)

**Comment by ushrivastava123** [comment]
@agliga This is still not fixed in ebayUI `5.0.0-4`

**Comment by agliga** [comment]
> @agliga This is still not fixed in ebayUI `5.0.0-4`

Yes i has mentioned that i had not published the fix yet and that i was waiting for the badge one to be verified beforw publishing the listbox fix.

**Comment by ushrivastava123** [comment]
@agliga sounds good.
