### ISSUE TITLE
Dismiss icon is missing from page-notice

### ISSUE THREAD

**Issue by ushrivastava123** [eBay/ebayui-core#1040]
# Bug Report

## Description
Page notices dismisses but the icon is hidden

## Workaround
Close action happens when clicked.

## Screenshots
Before:
![image](https://user-images.githubusercontent.com/57548118/73345743-7a42f900-4239-11ea-83cc-9ac3ef01da0e.png)

After:
![image](https://user-images.githubusercontent.com/57548118/73345783-8cbd3280-4239-11ea-9336-d8794e7911cb.png)

**Comment by ushrivastava123** [comment]
@agliga Was the fix that Dismiss action won't happen for Page notice?

**Comment by agliga** [comment]
> @agliga Was the fix that Dismiss action won't happen for Page notice?

The dismiss code was removed. So the dismiss attribute shouldn't do anything

**Comment by ushrivastava123** [comment]
@agliga Ok I'll keep the dismiss attribute to make sure it doesn't actually dismiss.
