### ISSUE TITLE
bug: on combobox blur changeValue does not update when clicking on an option from the dropdown

### ISSUE THREAD

**Issue by fraglord94** [eBay/ebayui-core#1044]
# Bug Report

## Description
`this.currentValue` and `state.changeValue` are the same in `handleComboboxBlur`- when you select an option from the list. Issue occurs when you run the debugger. Also `handleOptionClick` is not executed, even though there is a click event. 

## Screenshots
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13619560/73569720-d0719100-441f-11ea-8bc3-93d544c5b785.gif)

**Comment by agliga** [comment]
So let me understand the right scenario:
When I click an item, I should set `this.changeValue`, then it will trigger `select`. Any further blurs or anything should not trigger `change`
However when I type and then blur, it triggers `change`. 
So should it be triggering `change` on select as well or not?

**Comment by agliga** [comment]
Published `ebayui-core@4.5.8` which should fix this issue.
