### ISSUE TITLE
Dialog: clicking or moving the browser scroll bar does not work

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#105]
Repo:
  create a dialog with long text content so that the dialog becomes scrollable.
when we scroll over the active region it works fine but when we scroll on the window scroll bar(on the right of the page)  it does not work.

The scroll bar should be either inside the dialog  or if its going to scroll along with the browser scroll bar then we need to make the browser scroll bar clickable. 

There is no quick way to scroll up and down

**Comment by hramakumar** [comment]
![image](https://user-images.githubusercontent.com/13157115/39020012-352859e0-43e0-11e8-8715-154b49b410ea.png)

**Comment by hramakumar** [comment]
in the above screenshot if look at the scrollbar on the side of the browser. I am not able to move that scroll bar when the mouse places at the edge of the browser.

**Comment by ianmcburnie** [comment]
Fixed in 0.3.0.
