### ISSUE TITLE
Disabled combobox is not greyed out

### ISSUE THREAD

**Issue by ushrivastava123** [eBay/ebayui-core#1051]
# Bug Report
Disabled combobox is not greyed out

## Description
Disabled combobox is not greyed out

## Screenshots
After:

![image](https://user-images.githubusercontent.com/57548118/73717364-70544680-46ce-11ea-89d3-b0483e1f2c98.png)

Before:
![image](https://user-images.githubusercontent.com/57548118/73717404-8d891500-46ce-11ea-9309-63c170261828.png)

**Comment by ianmcburnie** [comment]
Look like this is an existing issue. Here is the current production storybook for v4.5.x after manually disabling the input:

![Screen Shot 2020-02-04 at 11 13 20 AM](https://user-images.githubusercontent.com/38065/73778113-7c2c2100-473f-11ea-8f37-017172f78133.png)

Skin seems fine in 10.0.0 branch:

![Screen Shot 2020-02-04 at 11 15 54 AM](https://user-images.githubusercontent.com/38065/73778263-c1505300-473f-11ea-8339-58cca85f91a6.png)

**Comment by ushrivastava123** [comment]
This is fixed in skin 10.0.0-1
