### ISSUE TITLE
ebay-menu-button not collapsing for a single select

### ISSUE THREAD

**Issue by sharma46bhawana** [eBay/ebayui-core#1058]
## Description
Using the `<ebay-menu-button>` and `<ebay-menu>` with a single select is not collapsing the menu after an option is selected. It was a feature available in 2.1.0

## Workaround
Tried the workaround of setting the state expanded = true, but it isn't working.

**Comment by ianmcburnie** [comment]
Let's do this for menuitem and radiomenuitem only. I think checboxmenuitem may need to stay open for multi-selectionl

**Comment by agliga** [comment]
Released for on `@ebay/ebayui-core@4.5.11`

Keeping issue open since we need to fix it on `5.1.0` as well
