### ISSUE TITLE
Combobox: Typing in the combobox that doesn't have options throws errors

### ISSUE THREAD

**Issue by melquan** [eBay/ebayui-core#1059]
# Bug Report

## Description
When typing in the textbox of the combobox that doesn't have options, errors are thrown in the console, due to `this.activeDescendant` being `undefined`.

## Workaround
None

## Screenshots
```
index.js:129 Uncaught TypeError: Cannot read property 'reset' of undefined
    at index.js:129
    at handleNotKeydown (index.js:19)
    at Object.handleTextInput (index.js:64)
    at Widget.handleComboboxKeyUp (index.js:128)
    at event-delegation.js:68
    at Object.batchUpdate (update-manager.js:98)
    at HTMLBodyElement.<anonymous> (event-delegation.js:27)
```

There may be more places that might be missing null checks for `this.activeDescendant` and `this.expander` before calling functions on them.

**Comment by agliga** [comment]
Published `@ebay/ebayui-core@4.5.9` which should have this fix.
