### ISSUE TITLE
ebay-menu width increases as we add menu-items 

### ISSUE THREAD

**Issue by swathip88** [eBay/ebayui-core#1066]
## Description
While using `<ebay-menu>` , on adding every menu item, width of the menu increases.
To reproduce the issue: Try adding/removing the menu-item elements in browser debugger(width increases or decreases respectively)

## Workaround
Need to add `display: flex` and `flex-direction: column` to parent container

##Screenshots
Three menu items
![Screen Shot 2020-02-18 at 3 58 08 PM](https://user-images.githubusercontent.com/15898444/74788787-9568bd80-5267-11ea-9d1e-10110e3732d6.png)

Two
![Screen Shot 2020-02-18 at 3 58 30 PM](https://user-images.githubusercontent.com/15898444/74788807-a1547f80-5267-11ea-99f2-2f762e2681af.png)
 menu items

**Comment by agliga** [comment]
This should be a skin fix. 
Again as stated in the bug we should add 
```
display: flex;
flex-direction: column;
```
To 
`.menu__items, .fake-menu__items`

**Comment by swathip88** [comment]
@agliga Sure makes sense thanks!

**Comment by ianmcburnie** [comment]
Sounds like a new modifier in Skin, @agliga? We already have a `menu-button__menu--fix-width`, which works a little differently to what is required here. Let's reopen and transfer this over to Skin. I don't think it's urgent though.
