### ISSUE TITLE
Not able to check/uncheck items in <ebay-menu-button> with type="checkbox"

### ISSUE THREAD

**Issue by ushrivastava123** [eBay/ebayui-core#1068]
# Bug Report

## Description
Not able to uncheck tick on ebay-menu-button with type=checkbox
Item 1 and item 3 are checked originally in below code snippet. They are not getting unchecked now.

Below is the markup:

`<div id="menu_checkbox" class="grid__cell grid__cell--4of16 grid__cell--4of16-lg grid__cell--4of8-sm" draggable="true" ondragstart="drag(event)">
                    <h3>Checkbox</h3>
                    <ebay-menu-button text="eBay Menu" type="checkbox" on-menu-button-change(console.log.bind(console, 'menu-change event is triggered'))>
                        <ebay-menu-button-item checked>item 1</ebay-menu-button-item>
                        <ebay-menu-button-item>item 2</ebay-menu-button-item>
                        <ebay-menu-button-item checked>item 3</ebay-menu-button-item>
                    </ebay-menu-button>
                </div>

                <div id="menu_reverse" class="grid__cell grid__cell--4of16 grid__cell--4of16-lg grid__cell--4of8-sm" draggable="true" ondragstart="drag(event)">
                    <h3>reverse</h3>
                    <ebay-menu-button reverse text="eBay Menu" type="checkbox">
                        <ebay-menu-button-item checked>item 1 this is a very very very long text</ebay-menu-button-item>
                        <ebay-menu-button-item>item 2</ebay-menu-button-item>
                        <ebay-menu-button-item checked>item 3</ebay-menu-button-item>
                    </ebay-menu-button>
                </div>`

## Screenshots
![image](https://user-images.githubusercontent.com/57548118/75139969-cea79000-56a2-11ea-84eb-0deebafafc03.png)

**Comment by agliga** [comment]
I copied the markup locally, tested on the `5.1.0` branch with the given skin. It seems to be working properly. 
I also tested it on the test page and seemed to work fine. Will sync up and see what the problem is.
![menu-check](https://user-images.githubusercontent.com/1755269/75181018-30431b00-56f2-11ea-9fb2-fa5f63aa989d.gif)

**Comment by agliga** [comment]
Issue was with marko, after upgrading to `4.18.48` it went away.

**Comment by ushrivastava123** [comment]
It works fine after I upgraded marko to` 4.18.48`
