### ISSUE TITLE
Carousel: Pagination dots do not have a visible focus outline (IE11) (CoreUI v4)

### ISSUE THREAD

**Issue by mcferrenm** [eBay/ebayui-core#1073]
# Bug Report

## Description

Action Performed
1. Tab to focus the navigation icons of any carousel

Expected Result
Each interactive element has a visible focus outline.

Actual Result
The navigation icons of the carousel do not have a visible focus outline.

Notes:

This is a keyboard navigation issue. It is not observed using Firefox, Chrome or macOS Safari

**Comment by ianmcburnie** [comment]
Closing this as the pattern moved from pagination dots to a scrollbar, and also given that this is IE.
