### ISSUE TITLE
Carousel: Missing arrow on the carousel IE11

### ISSUE THREAD

**Issue by mcferrenm** [eBay/ebayui-core#1074]
# Bug Report

## Description

Action Performed
1. Load page with Carousel.

Expected Result
The user can navigate the carousel.

Actual Result
There is no way to navigate the carousel.

Reproducibility (x of y times)
5/5

Device Make + Model + OS Version
Dell Inspiron 7577, Windows 10

Browser
IE 11.592.18362.0

**Comment by ianmcburnie** [comment]
This issue was fixed in Skin 9.5.6. Team is upgrading. Closing issue. If they are unable to upgrade we can re-open and backport the fix.
