### ISSUE TITLE
ebay-dialog: Fill and left/right panel-close button does not dissapear as we scroll down

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#108]
In ebay-dialog. When there is a scrollable dialog, the close button stays in the same position as we scroll down. It hides the texts in the top right corner.

![image](https://user-images.githubusercontent.com/13157115/39023533-1280e4d8-43f0-11e8-8abd-2dedee32fac3.png)

**Comment by hramakumar** [comment]
in regular scrollable dialogs it goes away as we scroll. We need to fix this discrepancy in behaviour.

**Comment by DylanPiercey** [comment]
@hramakumar this is what was requested from design.

**Comment by ianmcburnie** [comment]
Closing as "by design"
