### ISSUE TITLE
expose focus method for relevant components

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/ebayui-core#1081]
# Feature Request

## Description
Please expose `focus` method on the relevant components. 

## Context
Consider a template like this
```
<ebay-menu-button
        key="menuKey"
        type="fake" />

const menuBtn = this.getComponent('menuKey');
menuBtn.querySelector('fake-btn').focus()
```
Not really an ideal way to do, since the underlying class/implementation would change, I would instead prefer, something like
```
const menuBtn = this.getComponent('menuKey');
menuBtn.focus();
```

**Comment by ianmcburnie** [comment]
Related issue: #1004
