### ISSUE TITLE
In window type of ebay-notice, can we get support to add status to icon and content

### ISSUE THREAD

**Issue by swathip88** [eBay/ebayui-core#1083]
# Feature Request
eBayUI Version: "4.5.15"

## Description
We have requirement for making notice status `attention` with type as `window-notice`
(We need icon to be red , also the title needs to be red in color and content needs to black in color)

## Screenshots
<img width="963" alt="Screen Shot 2020-03-12 at 1 50 40 PM" src="https://user-images.githubusercontent.com/15898444/76565752-880ab180-6468-11ea-98d9-dfe87e7e7817.png">

**Comment by ianmcburnie** [comment]
After discussion with design team we think it best not to support this use-case as it would be "off pattern". The window-notice is intended for success messaging only:

<img width="703" alt="Screen Shot 2020-03-13 at 1 41 29 PM" src="https://user-images.githubusercontent.com/38065/76658049-74c31900-6530-11ea-9a2e-3d6a547d4847.png">

Our recommendation is for you to move towards a page-level error message.

Closing ticket.
