### ISSUE TITLE
ebay-tooltip overlay closes when i try to hover on the overlay when it is open (CoreUI v4)

### ISSUE THREAD

**Issue by swathip88** [eBay/ebayui-core#1085]
# Bug Report

## Description
I have a link inside tooltip overlay. When overlay is open and i try to move my cursor on overlay, it closes. I am not able to reach overlay before it closes

**Comment by ianmcburnie** [comment]
@agliga I think mouseout event is triggering immediately due to position of the elements. We'll probably need to add a short "grace period" where mouseout is ignored/cancelled.

**Comment by agliga** [comment]
We're going to see if there is another component we can use for this, if not we will have to do the change in `makeup-expander`

**Comment by ianmcburnie** [comment]
Why wouldn't they use tooltip?

**Comment by agliga** [comment]
I think after talking it over, they will use infotip. We should keep this open and fix it later in case we want to add interactive content to tooltip.
