### ISSUE TITLE
<ebay-menu-button-label> is not able to reflect state update

### ISSUE THREAD

**Issue by CrazyTick** [eBay/ebayui-core#1087]
# Bug Report

## Description

`
<ebay-menu-button-label>
        <span class="custom-label-flag">
        <span>${state.variable}</span> 
</ebay-menu-button-label>
`

<ebay-menu-button-label> is not able to reflect the state update. `state.variable`
https://github.com/eBay/ebayui-core/blob/843698d107735aa778f54e3cd29f70bb5f90873f/src/components/ebay-menu-button/examples/11-custom-label/template.marko#L16

## Screenshots

please reproduce it locally

**Comment by CrazyTick** [comment]
This is happening again. I am able to reproduce it in my local

**Comment by ianmcburnie** [comment]
Ok, you are on a very old version of eBayUI. Are you able to update?

**Comment by CrazyTick** [comment]
I am able to reproduce it in my local with version 5.2.1

**Comment by CrazyTick** [comment]
please have a look at the video attached in the JIRA ticket @ianmcburnie

**Comment by agliga** [comment]
Released in `5.2.2`
