### ISSUE TITLE
Components with nested transform tags don't work outside demos

### ISSUE THREAD

**Issue by mlrawlings** [eBay/ebayui-core#11]
The [`marko.json`](https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-menu/marko.json) that specifies the nested tag transformer is only scoped to the demo and test components.

Any outside user of the components will not have their nested tags transformed:
```js
ebay_listbox_tag({
        name: "name"
      }, out, 0, function renderBody(out, ebay_listbox0) {
      out.w("<ebay-listbox-option value=\"1\" label=\"Option 1\"></ebay-listbox-option><ebay-listbox-option value=\"2\" label=\"Option 2\" selected></ebay-listbox-option><ebay-listbox-option value=\"3\" label=\"Option 3\"></ebay-listbox-option>");
    });
```

**Comment by ianmcburnie** [comment]
Closing as fixed in 0.1.0 branch. Will merge to master branch at release time.
