### ISSUE TITLE
ebay-dialog IE - close button diappears when scrolling down in right/left panel

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#110]
Repro:
In IE browser
Open a left/right panel dialog with scrollable content
scroll down
close button goes away as you scroll down

Actual:
close button diappears when scrolling down in right/left panel

Expected:
As per design it is expected that the close icon stays on the top right corner as we scroll down the right/left panel.

**Comment by ianmcburnie** [comment]
Yep, @DylanPiercey and I discussed this. Thanks for logging this ticket, but will close it as wont fix
