### ISSUE TITLE
ebay-dialog altering ebay deals grid when opened

### ISSUE THREAD

**Issue by pcanella** [eBay/ebayui-core#1112]
# Bug Report

## Description
Basically what's happening is that for whatever reason on the Deals Spoke page (and probably other pages too, not sure), when the dialog opens, it causes their grid to lose a column and compact it into less columns. Upon closing the dialog, it is magically fixed. 

Here's a video of that: 

## Workaround
Haven't found a workaround for this yet.

## Screenshots
This is a test page (Deals Spoke) with just an example `ebay-dialog` included on it:

**Before:**
![Screen Shot 2020-05-06 at 12 03 22 PM](https://user-images.githubusercontent.com/4923719/81217605-b9e45400-8f91-11ea-8ffe-6483c8f5c359.png)

**After**
![Screen Shot 2020-05-06 at 12 03 17 PM](https://user-images.githubusercontent.com/4923719/81217617-bf419e80-8f91-11ea-8821-4d70329713e0.png)

As you can see, on the far right, one of the columns is being collapsed due to the dialog being open. When you close it, it goes back to the correct state.

**Comment by ianmcburnie** [comment]
Assigning this to @agliga for investigation.

**Comment by agliga** [comment]
So this is actually a problem with the application. 
Our dialog is changing `role=main` to `role=presentation` in screenreader trap. https://github.com/makeup/makeup-js/blob/57ca4a04e269ec659bb8049de5992abe584b7cd8/packages/makeup-screenreader-trap/index.js#L64
This is needed for accessibility.
In order to fix this, the application should update the styles to not rely on `role=main`

**Comment by ianmcburnie** [comment]
Thanks @agliga . Let's add a quick note to the dialog README, then close this.

**Comment by agliga** [comment]
Added to readme

*Note: When opening the dialog the `<body>` and `role=main` elements are modified. Please do not rely on setting styles based on `role=main` since it is changed to `role=presentation`*
