### ISSUE TITLE
`listbox-change` is fired before updated happens in DOM

### ISSUE THREAD

**Issue by rajkumarsrk** [eBay/ebayui-core#1115]
# Bug Report

## Description
Component: https://github.com/eBay/ebayui-core/tree/master/src/components/ebay-listbox-button
Listening to `listbox-change` and doing form submit causes the newly selected values not getting updated. Can this event be triggered after it has updated selected filed in `select -> option` HTML

## Workaround
```
listbox.on('listbox-change', () => {
            setTimeout(() => {
                document.getElementById('formid').submit();
            },10);
        });
```

**Comment by agliga** [comment]
After taking a look at this we decided not to do this fix. 

Here is Ians response from the pr

> Now that I've actually sat down and fully read through this, I see that @DylanPiercey is right. We should not be making this change. Also, from an a11y point of view, nine times out of ten, we shouldn't be submitting a form when a listbox has its value changed. A submit button should be used instead. There are some edge cases though where it *might* be appropriate to auto submit.
> 
> 
> 
> Another approach might be to add an 'autoSubmit' option, so that the internals are handled by us? Also happy to go down the `originalEvent` route if that works for @rajkumarsrk?

**Comment by agliga** [comment]
This will be a breaking change to do this the right way. Will fix in next major version

**Comment by ianmcburnie** [comment]
Done in 5.5.0
