### ISSUE TITLE
Dialog: scroll position keeps old state when reopening on mweb

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#113]
Repro:
open scrollable dialog
scroll to a place in the dialog
close the dialog
open it again
it opens up at the place where we left(mweb)
it goes to the top(dweb)

**Comment by DylanPiercey** [comment]
As far as I can tell this is fixed, can you confirm @hramakumar.

**Comment by hramakumar** [comment]
@DylanPiercey  yes Now it goes to the top yet
when I open it, it opens in the old state and then goes to top.
In a fraction of second this happens. Just letting you know.

**Comment by hramakumar** [comment]
https://go/ebayui/test
