### ISSUE TITLE
ebay-textbox: Add actionable stateful post icon and double icon support

### ISSUE THREAD

**Issue by gemicci** [eBay/ebayui-core#1132]
# Feature Request
Ebay-textbox: Add actionable stateful post icon and double icon support

Possible new component inputs& actions:

```
<ebay-textbox    
    pre-icon-name="search" 
    post-icon-name="clear" 
    on-textbox-post-icon-click('handlePostIconClick') >
```
If post-icon-name attribute changes from "clear" to null, component should rerender with no icon. "clear" to "arrow-down" should also cause a rerender with the new icon

## Description

There is a product requirement for a complex multiselect dropdown.  We are planning to use ebay-textbox as the base. As per the design, the multiselect box needs to have a pre and post icon. Post icon needs to be actionable and changeable. Notice down arrow will change to X. On click, it will clear the input box content.

## Screenshots
<img width="304" alt="Screen Shot 2020-05-28 at 10 18 05 AM" src="https://user-images.githubusercontent.com/10719382/83153150-9d3cc700-a0cc-11ea-9308-44045ef057ce.png">
<img width="326" alt="Screen Shot 2020-05-28 at 10 16 50 AM" src="https://user-images.githubusercontent.com/10719382/83153148-9ca43080-a0cc-11ea-921a-5a0061d044f9.png">

**Comment by ianmcburnie** [comment]
We'll look into it, thanks. Might also need some work on the skin end to see if we support and/or document the use of two icons.

**Comment by ianmcburnie** [comment]
@gemicci Actually, what is the purpose of the first item being clickable?

**Comment by gemicci** [comment]
@ianmcburnie Thanks for looking into this feature. There is no product requirement for an actionable left icon. Just right one is needed. I just wrote the spec for the sake of consistency. I will update the ticket.

**Comment by ianmcburnie** [comment]
Done in 5.6.0. Closing.
