### ISSUE TITLE
Add support for node 12

### ISSUE THREAD

**Issue by agliga** [eBay/ebayui-core#1147]
# Bug Report

## Description
When running on node 12 it errors out when trying to launch the server. 
Need to try to get it working properly on node 12

## Workaround
Use node 10

**Comment by ianmcburnie** [comment]
Maybe something that @biaspro could investigate...

**Comment by ianmcburnie** [comment]
@bvi1994 Fancy a stab at this?

**Comment by agliga** [comment]
The fix for this is to simply remove `gh-highlight` package. It seems like that is unmaintained and uses older versions of packages which break when using newer versions of node.
