### ISSUE TITLE
Review all current examples for errors or outdated code

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#1165]
Prior to cleaning up the API, let's ensure that all of the examples are current. For example, we ran into an issue where breadcrumbs example is still showing a `hijax` attribute and we spent time discussing it, even though it is no longer relevant in the code. We probably have a few more like this, so a sweep through would be good before we do our next API review meeting.

**Comment by DylanPiercey** [comment]
We have some "Remove this when we switch to Marko 4" code as well which might be worth tackling alongside this?

**Comment by ianmcburnie** [comment]
Related issue: https://github.com/eBay/ebayui-core/issues/923

**Comment by ianmcburnie** [comment]
I'll add any inconsistencies I see as I come across them too...

In button, there is an 'icon' variant example, but its not mentioned in readme.

**Comment by ianmcburnie** [comment]
Done. Thanks Andrew.
