### ISSUE TITLE
ebay-dialog : Horizontal line below the header is broken (starts after a margin)

### ISSUE THREAD

**Issue by malughanshyam** [eBay/ebayui-core#1168]
# Bug Report

## Description

https://ebay.github.io/ebayui-core/?path=/story/ebay-dialog--with-footer
ebay-dialog : Horizontal line below the header is broken (starts after a margin)

## Workaround

Override the margin at app level

## Screenshots

![Screen Shot 2020-07-09 at 17 26 10](https://user-images.githubusercontent.com/5460329/87103682-98f6e400-c20a-11ea-95e8-a2692b5f4f8f.png)

**Comment by ianmcburnie** [comment]
Fix merged to 10.7.0 branch. Thanks Andrew.
