### ISSUE TITLE
ebayui-core 5.6.0: Need to add aria-roledescription to readonly-combobox

### ISSUE THREAD

**Issue by ushrivastava123** [eBay/ebayui-core#1170]
# Feature Request

## Description
Need to add `aria-roledescription` to readonly-combobox 
It should look like - `aria-roledescription="Use up and down arrow keys to navigate options"` as there is no autocomplete

## Context
Reference PR - https://github.com/eBay/ebayui-core/commit/7ef584083bd9829707cdf168328febab117e415a
Original Bug - https://github.com/eBay/ebayui-core/issues/1151

**Comment by ianmcburnie** [comment]
This component is deprecated/hidden, so there's no real hurry to add it. 5.7.0 is fine.

**Comment by ianmcburnie** [comment]
Closing as wontfix as this component is deprecated.
