### ISSUE TITLE
ebayui-core-4.5.0 : ebayui-listbox-button should allow class update on re-render

### ISSUE THREAD

**Issue by uachladi** [eBay/ebayui-core#1171]
# Bug Report

## Description
ebay-listbox-button allows to pass class attribute but does not allow change of class on re-render due to w-preserve-attrs.
 https://github.com/eBay/ebayui-core/blob/4.5.0/src/components/ebay-listbox-button/template.marko#L15

@dpiercey @ianmcburnie  . This is a high priority for us to get the sellerhub skin upgrade to be completed.

**Comment by ianmcburnie** [comment]
@uachladi We'll look into it. Just curious to know what kind of class are you changing? Is it a visual change? Or some kind of JS hook?

**Comment by uachladi** [comment]
@ianmcburnie , its just the text color. 
<img width="328" alt="Screen Shot 2020-07-13 at 3 59 41 PM" src="https://user-images.githubusercontent.com/13039089/87361815-e5e7fc80-c521-11ea-914e-01eba28171d8.png">

**Comment by ianmcburnie** [comment]
@uachladi Thanks. What does the red colour convey? I'm concerned about accessibility and using colour alone to convey meaning. Actually, I'll ping you offline to chat further...

**Comment by ianmcburnie** [comment]
@uachladi just checking in... do you still need this?

**Comment by uachladi** [comment]
@ianmcburnie , yes product wants to keep this.

**Comment by agliga** [comment]
Is this needed on the `4.5.x` branch or are you able to upgrade to 5.x` branch in the near future?

**Comment by uachladi** [comment]
We do not have upgrade in our planning until Q2 2021. It will be needed on 4.5.x branch.

**Comment by agliga** [comment]
This is also needed in `5.x` branch since it has `no-update` on class for listbox.

**Comment by agliga** [comment]
Released in `4.5.22`
