### ISSUE TITLE
ebay-textbox: new attributes added for prefix and postfix are being rendered on the textbox in the HTML output

### ISSUE THREAD

**Issue by melquan** [eBay/ebayui-core#1180]
# Bug Report

## Description
The new prefix and postfix attributes are being rendered on the textbox in the HTML output.

## Workaround
None.

## Screenshots
From [eBayUI Storybook](https://ebay.github.io/ebayui-core/?path=/story/ebay-textbox--both-icons):

![image](https://user-images.githubusercontent.com/19419138/88331591-111cd980-cce2-11ea-99d8-1ab6f08ea739.png)

**Comment by ianmcburnie** [comment]
Thanks @melquan. We'll get this and the skin issue fixed in a patch.

**Comment by ianmcburnie** [comment]
Fixed in 5.6.x. Thanks Andrew.
