### ISSUE TITLE
eBay Stepper Issue & feature

### ISSUE THREAD

**Issue by xuefengy** [eBay/ebayui-core#1189]
# Feature Request

## Description

Had a discussion with Andrew on eBay stepper. Two cases Identified to improve:

1. if there is three steps, all steps should be completed or marked without 'current'.

2. Three steps, mid stepper can be empty for some use cases. 

## Screenshots

<img width="1041" alt="Screen Shot 2020-07-30 at 11 48 23 AM" src="https://user-images.githubusercontent.com/69012966/88961987-a546ed80-d25a-11ea-8d79-6872e708460b.png">

**Comment by ianmcburnie** [comment]
Done in 5.7.0. Thanks Andrew.

**Comment by xuefengy** [comment]
Thank you Andrew & Ian!
