### ISSUE TITLE
Stepper - HR Accessibility warning

### ISSUE THREAD

**Issue by montoya332** [eBay/ebayui-core#1191]
#909 Bug Report

## Description

Ensure all values assigned to role="" correspond to valid WAI-ARIA roles.
https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-stepper/index.marko#L26

Doc:
https://dequeuniversity.com/rules/axe/3.5/aria-allowed-role?application=axeAPI

## Screenshots
![Screen Shot 2020-08-01 at 11 32 34 AM](https://user-images.githubusercontent.com/8145951/89108294-11a52680-d3ec-11ea-81b9-ca1544ae40ac.png)

**Comment by ianmcburnie** [comment]
Hmm, I'm pretty sure this is a false positive and that role=presentation is allowed on any tag. Its whole purpose is to strip the semantics from the tag.

It explicitly says in the HTML5 spec that role=presentation is an allowed role:

![Screen Shot 2020-08-03 at 11 22 35 AM](https://user-images.githubusercontent.com/38065/89214524-d174ae00-d57b-11ea-8a9b-d57167570ad1.png)

**Comment by ianmcburnie** [comment]
@montoya332 Maybe you could file an issue on the open source AXE project?

**Comment by montoya332** [comment]
@ianmcburnie -  great idea , closing this issue
