### ISSUE TITLE
Combobox: aria-selected=true is being applied to every option

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#1199]
This incorrect state could be causing an accessibility issue:

![Screen Shot 2020-08-11 at 4 42 07 PM](https://user-images.githubusercontent.com/38065/89959629-bc3df600-dbf1-11ea-8238-93ab4831d936.png)

**Comment by agliga** [comment]
This is due to the check where we check `state.selectedValue` to `item.value`. If `item.value` is not set `aria-selected` to all values initially
A fix would be to check against `item.value || item.text` instead.
