### ISSUE TITLE
Combobox: expanded/collapsed icon doesn't change after pressing "enter" key

### ISSUE THREAD

**Issue by joinfelipe** [eBay/ebayui-core#1201]
# Bug Report

## Description
Combobox's  caret icon no longer expands list options after making a selection using keyboard's "enter" key.
1. go to a page with combobox options, e.g: https://ebay.github.io/ebayui-core/ds4/?path=/story/ebay-combobox--lots-of-options
2. type "Basic Offer"
3. navigate with arrow-down key and select first option "Basic Offer" using keyboard's enter key
4. try clicking on the caret expand icon "v"
*Actual Behavior*
5. combobox does not expand
*Expected Behavior*
5. Combobox should expand and display available options

## Workaround
User can still expand options and make selection when using "arrow-down" key, or when leaving the field and clicking on it again.

## Screenshots
![image](https://user-images.githubusercontent.com/69696226/90433233-639eab00-e080-11ea-858a-3e5168287bc5.png)

**Comment by agliga** [comment]
The reason this is happening. Might need Ian's accessibility expertise on what the right way to do this is:
Combobox shows on focus. When selecting an option the focus is placed on the input, however the expander is closed. Clicking again does not trigger focus since you are already focused. 
A solution would be to trigger the expander on click if it the field is focused.

**Comment by ianmcburnie** [comment]
I was tempted to close as wontfix, as the user can click out and click back in again, or use down arrow key, to expand. However, looking at the MIND patterns example, I see I have it that combobox expands if it receives a mouse click:

https://ebay.github.io/mindpatterns/input/combobox/index.html

https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.0pattern/combobox-autocomplete-none.html

This is low priority, but we should make it consistent.
