### ISSUE TITLE
ebay-infotip: modal infotip should not have aria-expanded on the button

### ISSUE THREAD

**Issue by mkchang** [eBay/ebayui-core#1218]
# Bug Report

## Description

The new modal option for infotip should not have aria-expanded/collpased being announced, as it is not a dialog.

## Screenshots
![image](https://user-images.githubusercontent.com/6880917/91917972-5a176480-ec76-11ea-94b6-6071e166d06d.png)

**Comment by ianmcburnie** [comment]
Fixed in 5.7.0. Closing.
