### ISSUE TITLE
Dialog: Allow for a custom close button

### ISSUE THREAD

**Issue by melquan** [eBay/ebayui-core#1223]
# Feature Request

## Description
Allow for a custom close button.

## Context
Our design has a dialog with a button that says `Done` rather than an `X` icon so right now we are not using the dialog header from the component and have to have our own custom header.  We are hiding the `dialog__header` for the time being using CSS because it has some spacing associated with it.  We would like to use the dialog header as normal if it were able to accommodate a custom close button.

## Screenshots
![image](https://user-images.githubusercontent.com/19419138/92195226-465c3180-ee21-11ea-822e-3ba4029f98b9.png)

**Comment by ianmcburnie** [comment]
I'll have to run this by the design system team. Seems like this may be a candidate for a CTA button in dialog footer.

**Comment by ianmcburnie** [comment]
Fixed in 6.0.0. Closing.
