### ISSUE TITLE
Drawer requires a @header but its not documented

### ISSUE THREAD

**Issue by msendlakowski** [eBay/ebayui-core#1236]
# Bug Report

## Description
If you create a drawer component without a `<@header>` element the close icon will be centered and overlapping the handle icon.  It looks like the drawer requires a header element, but the documentation doesn't note this.  So the documentation should be updated or the location of the close icon should be fixed.

## Workaround
Add an empty `<@header>` element

### Without header
![Screen Shot 2020-09-16 at 11 07 03 AM](https://user-images.githubusercontent.com/1562843/93375651-586ca580-f80d-11ea-9176-13a9cedd70a5.png)

### With header
![Screen Shot 2020-09-16 at 11 09 04 AM](https://user-images.githubusercontent.com/1562843/93375665-5e628680-f80d-11ea-8a8c-e9b88b636a51.png)

**Comment by agliga** [comment]
This should be fixed in `5.7.0`
If its still broken please let me know.

**Comment by agliga** [comment]
Just looked, this is fixed in `5.6.4` 
https://github.com/eBay/ebayui-core/releases/tag/v5.6.4
* Removed conditional header in dialog (#1208)

Closing for now. Feel free to reopen if there is any more issues
