### ISSUE TITLE
fake-link button style is not loaded

### ISSUE THREAD

**Issue by xuefengy** [eBay/ebayui-core#1244]
# Bug Report

## eBayUI Version: x.x.x

for ebayUI version: 5.4.0 & 5.7.5

## Description

fake-link button will load a not styled button instead of fake-link. 

## Workaround

add @ebay/skin/link  in browser.json

## Screenshots

<img width="314" alt="Screen Shot 2020-09-25 at 4 21 29 PM" src="https://user-images.githubusercontent.com/69012966/94324525-15b67600-ff4f-11ea-8f63-956c985886a2.png">

**Comment by ianmcburnie** [comment]
Thanks for creating this ticket. Given that there's a workaround we will probably not go back as far as 5.4

I had a card here to track this for 6.0.0-beta: https://github.com/eBay/ebayui-core/projects/72#card-45775544

**Comment by agliga** [comment]
Released in `5.7.6`
