### ISSUE TITLE
Pagination - "Without the arrows" list shows the left and right arrows like buttons.

### ISSUE THREAD

**Issue by deenabay** [eBay/ebayui-core#1252]
# Bug Report

## Description
Pagination - "Without the arrows" list shows the left and right arrows like buttons.
### Previous version
![image](https://user-images.githubusercontent.com/71992704/96619600-39a17900-12bb-11eb-8847-75c909ecb63d.png)

CC: @agliga 

### version 6.0
![image](https://user-images.githubusercontent.com/71992704/96619630-40c88700-12bb-11eb-84fd-d8aaa2fef0e5.png)

### code:

`<div`
`    id="pagination_6"`
`    class="grid__cell grid__cell--8of16 grid__cell--8of16-lg grid__cell--4of8-sm"`
`    draggable="true"`
`    ondragstart="drag(event)">`
`    <h3>Without arrows input</h3>`
`    <ebay-pagination>`
`        <@item href="#" current>1</@item>`
`    </ebay-pagination>`
`</div>`

**Comment by agliga** [comment]
Need to add `icon-btn` and `icon-link` to pagination left/right arrows
