### ISSUE TITLE
textbox: additional types

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/ebayui-core#1254]
# Bug Report

## Description
The `type` attribute is currently not a [passthrough](https://github.com/eBay/ebayui-core/blob/6.0.0/src/components/ebay-textbox/index.marko#L56). 

Looks like this was discussed earlier here, https://github.com/eBay/ebayui-core/pull/579, but we are seeing the need for having at least `type=number` (and maybe `type=search`)

## Workaround
Maybe use `onMount` to change the `type`.

**Comment by agliga** [comment]
Relevant issue https://github.com/eBay/ebayui-core/issues/575

@ianmcburnie is there any reason not to support other types?

**Comment by ianmcburnie** [comment]
I don't believe there is any reason not to. Even though I know there have historically been a few issues with some of the types (especially in terms of a11y), we should allow full access to what HTML provides.
