### ISSUE TITLE
ebay-carousel -  card with long text overflows behind the other cards

### ISSUE THREAD

**Issue by deenabay** [eBay/ebayui-core#1258]
# Bug Report

## Description
ebay-carousel: For an item card with long text, shows the text overflowing behind the other cards.
This prevents the user from viewing the complete information.
CC: @agliga 

### Sample Code:
Please look at the card-1 in the below screenshot.
`<ebay-carousel>`
`<@item class="demo4-card demo4-card--1">`
` Card 1 - long text sgsgsgsgg sgsgsgggs gsgsgsgsgsgsgsgsgsgsgsgsgsgsgsgsgsgsgsgsgsgsg`
`</@item>`
`<@item class="demo4-card demo4-card--2">Card 2</@item>`
`<@item class="demo4-card demo4-card--3">Card 3</@item>`
`<@item class="demo4-card demo4-card--1">Card 4</@item>`
`<@item class="demo4-card demo4-card--2">Card 5</@item>`
`<@item class="demo4-card demo4-card--3">Card 6</@item>`
`<@item class="demo4-card demo4-card--1">Card 7</@item>`
`<@item class="demo4-card demo4-card--2">Card 8</@item>`
`<@item class="demo4-card demo4-card--3">Card 9</@item>`
`</ebay-carousel>`

## Screenshots
![image](https://user-images.githubusercontent.com/71992704/96924765-fc2e1e80-1467-11eb-9943-17567768fad3.png)

**Comment by ianmcburnie** [comment]
This is probably just an issue with the example page CSS, right @agliga ?

**Comment by agliga** [comment]
This is not really an issue, users that have a lot of text should either make larger widths or have the text wrap. 
They can also add `overflow: hidden` on each container if using a fixed width (as is here)
