### ISSUE TITLE
Android and iOS: Button alignment in ebay-page-notice and ebay-section-notice doesn't look correct

### ISSUE THREAD

**Issue by deenabay** [eBay/ebayui-core#1261]
# Bug Report

## Description
The alignment of button inside `ebay-page-notice` and `ebay-section-notice` component doesn't look correct.
The button is hovering over the component border.
The issue is observed in iOS Safari as well as Android Chrome browsers.

Please refer the screenshots attached.
CC: @agliga 

## Screenshots
Android Chrome:
![image](https://user-images.githubusercontent.com/71992704/97375755-da260900-1878-11eb-9f1a-94be633616d8.png)
![image](https://user-images.githubusercontent.com/71992704/97375766-e1e5ad80-1878-11eb-8c92-3380d2dd1245.png)
![image](https://user-images.githubusercontent.com/71992704/97375786-ee6a0600-1878-11eb-950e-dde6d2afa4ab.png)

**Comment by ianmcburnie** [comment]
Hmm, yes, the button should wrap onto next line for small screens. Looks like a fix is needed in Skin.

**Comment by deenabay** [comment]
@agliga I am still observing the issue with the `<ebay-section-notice>` component
`<ebay-page-notice>` is looking good though
![image](https://user-images.githubusercontent.com/71992704/97638459-cb1a9480-19f9-11eb-83ac-bd00a76edba1.png)

**Comment by deenabay** [comment]
Also, <ebay-notice> with the content still have issues.
![image](https://user-images.githubusercontent.com/71992704/97638704-5d229d00-19fa-11eb-9ccf-836c4887f439.png)

**Comment by agliga** [comment]
What is the markup for the `content` one?
I think `@content` has been removed.

**Comment by deenabay** [comment]
> What is the markup for the `content` one?
> I think `@content` has been removed.

Yes. We are using `@content` here
`        <ebay-notice
            type="section"
            status="information"
            a11y-heading-text="information"
            a11y-close-text="Dismiss notice">
            <@content>
                <p>
                    <strong>Congrats!</strong>
                    You just listed
                    <a href="#">"Spam and Eggs From the Cow's Perspective</a>
                    (paperback)."
                </p>
                <p>
                    You can check
                    <a href="#">your listing</a>
                    or
                    <a href="#">sell another item</a>
                </p>
            </@content>
            <ebay-button priority="secondary" transparent>Action Button</ebay-button>
        </ebay-notice>`

**Comment by agliga** [comment]
The issue seems to be that `<ebay-button>` is not wrapped in `<@footer>`

**Comment by deenabay** [comment]
I tried that too.
And that didn't help either.

**Comment by agliga** [comment]
I see that its section notice. 
It will be fixed by the pr i pushed
