### ISSUE TITLE
The alignment with the `ebay-fake-menu-button reverse` component doesn't look properly aligned in the mWeb

### ISSUE THREAD

**Issue by deenabay** [eBay/ebayui-core#1262]
# Bug Report

## Description
The alignment with the `ebay-fake-menu-button reverse` component doesn't look properly aligned in the mWeb.
It is observed in iOS Safari as well as Android  Chrome.
Please refer screenshots for more info.
@agliga 

## Screenshots
![image](https://user-images.githubusercontent.com/71992704/97376986-1e66d880-187c-11eb-8b4b-10c23b99ec65.png)

**Comment by agliga** [comment]
This is not an issue, we do not set any positioning styles for reverse, only that the text is on the left side.
You probably have a `margin-left: 200px;` which is what we have too locally
<img width="1675" alt="Screen Shot 2020-10-28 at 11 03 02 AM" src="https://user-images.githubusercontent.com/1755269/97477687-29b61480-190d-11eb-8757-2d3d7833162b.png">
