### ISSUE TITLE
ebay-fake-menu-button custom label doesn't contain the longer labels.

### ISSUE THREAD

**Issue by deenabay** [eBay/ebayui-core#1263]
# Bug Report

## Description
For `<ebay-fake-menu-button>` doesn't contain the longer labels.
@agliga 

## Screenshots
Android Chrome:
![image](https://user-images.githubusercontent.com/71992704/97377988-7ef71500-187e-11eb-93fd-9d8a9ae0a745.png)

iOS Safari:
![image](https://user-images.githubusercontent.com/71992704/97377882-422b1e00-187e-11eb-8aea-1986625345b7.png)

**Comment by ianmcburnie** [comment]
A fixed height and truncation needs to be applied. This should be documented on the component's README. If not, let us know!

**Comment by agliga** [comment]
I think this is related to the text page, I tried it locally and this is what I see.
I think it makes sense if you contain the text in a smaller container. 

This also happens on normal menu button so not an issue, if I have no constraints
<img width="799" alt="Screen Shot 2020-10-29 at 9 43 27 AM" src="https://user-images.githubusercontent.com/1755269/97604886-3b5df180-19cb-11eb-9ae3-2e68b7f481ac.png">

This is on current production if I add constaints:
<img width="1484" alt="Screen Shot 2020-10-29 at 9 45 02 AM" src="https://user-images.githubusercontent.com/1755269/97605076-73653480-19cb-11eb-8e2b-9a20860e465c.png">
