### ISSUE TITLE
Nice to have a border

### ISSUE THREAD

**Issue by samsgithub** [eBay/ebayui-core#1271]
# Feature Request

## Description
When we have a ebay-tabs used as clickable fake links, it would be nice to have a border under the tabs which is stretched to the full page. Just the border, not the tabs.

## Context
Like My eBay page 

## Screenshots

![image](https://user-images.githubusercontent.com/2053677/100178230-5ae02100-2e88-11eb-9ad2-742abb52e425.png)

**Comment by ianmcburnie** [comment]
Unfortunately, this would go against our design system guidance, therefore not something we would build in by default:

![Screen Shot 2020-11-24 at 8 22 58 PM](https://user-images.githubusercontent.com/38065/100183242-4a817380-2e93-11eb-8abd-e61d456c8421.png)
 
However, to create the style you are looking for you should be able to adjust the flex box properties. For example, setting a width value for each tab would be one way to do it:

![Screen Shot 2020-11-24 at 8 30 42 PM](https://user-images.githubusercontent.com/38065/100183593-2f633380-2e94-11eb-8391-89b5f0fb968c.png)

Let me know if that works.

**Comment by ianmcburnie** [comment]
Closing for now based on comment above.
