### ISSUE TITLE
Notice: migrator has a typo for 'a11y-heading-text' mapping

### ISSUE THREAD

**Issue by melquan** [eBay/ebayui-core#1282]
# Bug Report

## Description
The `ebay-notice` migrator has a typo on line 38.  It's mapping `a11y-heading-text` to `attyText`.

## Workaround
None

## Code
https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-notice/migrator.js#L38

**Comment by ianmcburnie** [comment]
Fixed.
