### ISSUE TITLE
Various components(docs): README updates

### ISSUE THREAD

**Issue by melquan** [eBay/ebayui-core#1283]
# Documentation

## Description
1. `ebay-expand-button`: missing event descriptions
2. `ebay-panel-dialog`: missing description for the `position` attribute
3. `ebay-fake-tabs`: README has formatting issues
4. `ebay-tabs` & `ebay-fake-tabs`: READMEs say they take an `index` attribute but the code looks for `selectedIndex`
5. `ebay-tabs`: README says the `select` event returns `{ index }` but it actually returns `{ selectedIndex }`
6. `ebay-section-notice`: missing description for `a11yRoleDescription` attribute and noting that it defaults to `Notice`

**Comment by ianmcburnie** [comment]
@melquan thank you for helping improve the quality of our component library & documentation!

**Comment by ianmcburnie** [comment]
Done.

**Comment by ianmcburnie** [comment]
I notice discrepancies in pagination too. Will fix.

![Screen Shot 2021-01-05 at 12 49 08 PM](https://user-images.githubusercontent.com/38065/103697803-49913680-4f55-11eb-92ac-4766671a66c0.png)
