### ISSUE TITLE
TODO comment in code

### ISSUE THREAD

**Issue by montoya332** [eBay/ebayui-core#1297]
https://github.com/eBay/ebayui-core/blob/c502cb10fa3259b198ebaa24211cc19f30dd81ca/src/components/ebay-section-title/index.marko#L23

we should probably create an issue or add TODO prefix to quick search

**Comment by ianmcburnie** [comment]
Not sure when this was added or if it's still relevant, but yes I agree we should use TODO prefix to make searchable.

**Comment by ianmcburnie** [comment]
I've added a TODO annotation. We can sweep through all of these some other time. Closing.
