### ISSUE TITLE
"ebay-listbox-button" value doesn't truncate 

### ISSUE THREAD

**Issue by nikitajain7007** [eBay/ebayui-core#1301]
Facing this issue in ebay-listbox-button  where the value doesn't truncate when the text length width is greater than the container width. ebay-button provides a truncate param https://ebay.github.io/ebayui-core/?path=/story/ebay-button--truncated can ebay-listbox-button support truncate param

<img width="386" alt="Screen Shot 2021-01-12 at 3 17 16 PM" src="https://user-images.githubusercontent.com/22912869/104297825-4d8afe80-54e9-11eb-9227-dc488b482cce.png">

**Comment by ianmcburnie** [comment]
Done in 7.1.0
