### ISSUE TITLE
CI: switch from Travis to GitHub Actions

### ISSUE THREAD

**Issue by agliga** [eBay/ebayui-core#1307]
# Bug Report
Seems like Travis CI is not working. No builds have run for two weeks or so.
We might want to look at Github workflows to have our CI working again.

**Comment by ianmcburnie** [comment]
Reason is that we ran out of free credits and sadly do not satisfy their criteria for open source software.

Let's move our CI over to GitHub actions.

**Comment by ianmcburnie** [comment]
Done in 7.2.0 branch
