### ISSUE TITLE
Pagination: add ellipses/truncation 

### ISSUE THREAD

**Issue by agliga** [eBay/ebayui-core#1317]
Let's scope out the work involved to add a story for ellipses/truncation

![Screen Shot 2021-01-22 at 1 12 08 PM](https://user-images.githubusercontent.com/38065/105547623-82e6d780-5cb3-11eb-9e23-4f0b6e203254.png)

This one might need backporting to v10 or v11.

https://github.com/eBay/skin/issues/1337

**Comment by ianmcburnie** [comment]
Done in 7.2.0
