### ISSUE TITLE
Breadcrumbs: incorrect white space around chevrons

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#1319]
# Bug Report

## Description

Regression from v6 to v7. Incorrect white space around chevrons. 

## Workaround

Yes. Override in local css.

## Screenshots

![Screen Shot 2021-02-01 at 4 58 23 PM](https://user-images.githubusercontent.com/38065/106537400-1b007000-64af-11eb-8e0b-7d480315ef5c.png)

**Comment by agliga** [comment]
Published in `skin@12.0.1`
