### ISSUE TITLE
Textarea: character counter feature

### ISSUE THREAD

**Issue by arrra** [eBay/ebayui-core#1332]
# Feature Request

## Description

The feature is to enhance textarea component to show the user char counter <strike>and when the user hits enter, the textarea increases by 1 with scrollbar</strike>.

## Screenshots

![Screen Shot 2021-02-12 at 3 15 41 PM](https://user-images.githubusercontent.com/7342797/107832415-3ab45580-6d45-11eb-933e-0bcd7865ddfc.png)
![Screen Shot 2021-02-12 at 3 08 32 PM](https://user-images.githubusercontent.com/7342797/107832053-4ce1c400-6d44-11eb-9330-f8930d11e125.png)
![Screen Shot 2021-02-12 at 3 14 40 PM](https://user-images.githubusercontent.com/7342797/107832362-19536980-6d45-11eb-870a-2befda96dca0.png)

**Comment by ianmcburnie** [comment]
We might want to do this as a separate component, ebay-textbox-counter. This component would listen to events of a given ebay-textbox. This ensure no tight coupling of logic and layout.

**Comment by agliga** [comment]
This is done
