### ISSUE TITLE
ebay-details: irregular keyboard focus indicator (Safari)

### ISSUE THREAD

**Issue by ZZS77** [eBay/ebayui-core#1334]
# Bug Report

## Description
Highlight border for 'details' has an extra nub on the bottom for Safari browser

## Screenshots
![Screen Shot 2021-02-19 at 1 39 32 PM](https://user-images.githubusercontent.com/42783072/108564955-c7689180-72b8-11eb-8270-dd32c29ef099.png)

**Comment by ianmcburnie** [comment]
Corresponding skin ticket: https://github.com/eBay/skin/issues/1370

**Comment by ianmcburnie** [comment]
Closing this and will track in Skin
