### ISSUE TITLE
<ebay-details>: giving a class to ebay-details causes the icons to not change

### ISSUE THREAD

**Issue by regoldberg** [eBay/ebayui-core#1335]
# Bug Report

## Description

When using `ebay-details` if you give it a class then it will not have the `details` class which causes issues with the dropdown icon switching:
`<ebay-details class="not-details" open text="Show me the details">
    The details
</ebay-details>`

## Workaround

When adding a class also specify `details` as a class:

`<ebay-details class="not-details details" open text="Show me the details">
    The details
</ebay-details>`

**Comment by ianmcburnie** [comment]
Fixed in 7.3.0
