### ISSUE TITLE
<ebayui-video> : "ReferenceError: window is not defined in webpack

### ISSUE THREAD

**Issue by shuli12** [eBay/ebayui-core#1345]
# Bug Report

## Description
Trying to use ebayui-video in webpack and go the following error.
Error "ReferenceError: window is not defined

    at marko_template..marko_src_runtime_components_renderer_WEBPACK_IMPORTED_MODULE_13__default.t (/dist/server/main.js:3883:13)

        -> /dist/components/ebay-video/index.marko:23:23

## Workaround
n/a

**Comment by agliga** [comment]
Need to upgrade `@marko-tags/subscribe` to the latest version. 
This should be done in `7.3.0`

For a workaround, make sure you have the latest `@marko-tags/subscribe` tag, or override it in `package.json` for `ebayui-core` in `resolutions`

**Comment by agliga** [comment]
Found out a bug in subscribe. 
Fix is to upgrade to `@marko-tags/subscribe@0.4.2`  
Bug fix reference:
https://github.com/marko-js/tags/pull/39
