### ISSUE TITLE
UnControlled snackbar gets triggered on top of the other snackbar

### ISSUE THREAD

**Issue by deenabay** [eBay/ebayui-core#1351]
# Bug Report

## Description
When `Uncontrolled snackbar` is added in the same page as any other snackbar, the `uncontrolled snackbar` component shows up on top of the other snackbar, everytime the other snackbar is triggered.

### Example: 
The page contains an Action Snackbar, triggered by a button. And an uncontrolled snackbar, with its state independent from the Action snackbar. The uncontrolled snackbar message pops up on top of the action snackbar, whenever the button to trigger the action snackbar is clicked.

##### index.marko
`<ebay-button on-click('snackBarActionHandleOpen')>
        Open Action snackbar
    </ebay-button>
    <ebay-snackbar-dialog open=state.snackBarActionOpen on-close('snackBarActionHandleClose') on-action("handleSnackbarAction")>
        Action Snackbar
        <@action access-key="Undo">Undo</@action>
    </ebay-snackbar-dialog>
<ebay-snackbar-dialog open>Uncontrolled Snackbar</ebay-snackbar-dialog>`

##### Component.js
`module.exports = {
    onCreate: function() {
        this.state = {
            snackBarActionOpen: false
        };
    },
    snackBarActionHandleOpen: function({ value }) {
        this.state.snackBarActionOpen=true;
    },
    snackBarActionHandleClose: function({ value }) {
        this.state.snackBarActionOpen=false;
    },
    handleSnackbarAction: function(){
        alert("action alert from Snackbar.");
    }
};`

**Comment by austingardner** [comment]
After further investigation, Andrew and I figured out that this issue is caused by having the uncontrolled snackbar in the same .marko file as another snackbar. Having the uncontrolled snackbar in a separate .marko file solves the issue. 

Because developers will generally have the uncontrolled snackbar behind an `<if>` statement, this shouldn't be an issue.
