### ISSUE TITLE
ebay-icon: not rendering in IE

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#1360]
As per description, icons not rendering in IE.

![image](https://user-images.githubusercontent.com/38065/114749648-00950f00-9d08-11eb-92bf-89a46115da3f.png)
![image (1)](https://user-images.githubusercontent.com/38065/114749651-01c63c00-9d08-11eb-8fea-7511708acb04.png)

**Comment by austingardner** [comment]
I'm not sure about this one... it does seem like the icons are rendering in IE. Here is what I see running the website locally and going to IE 11 on Windows 10: 

<img width="817" alt="Screen Shot 2021-04-09 at 3 03 30 PM" src="https://user-images.githubusercontent.com/25092249/114253206-f27c7280-9944-11eb-9107-f69e789ab487.png">
<img width="800" alt="Screen Shot 2021-04-09 at 3 03 48 PM" src="https://user-images.githubusercontent.com/25092249/114253211-f60ff980-9944-11eb-8af9-89b9831b28ec.png">

**Comment by ianmcburnie** [comment]
Unable to repro. Closing.
