### ISSUE TITLE
Various eBay issues

### ISSUE THREAD

**Issue by joejordanbrown** [eBay/ebayui-core#1361]
# Bug Report

## Description
An issue that customer support is failing to acknowledge and say it's impossible to be a bug with eBay. We all know as a software engineer that bugs happen especially with new features. I know this isn't the correct repo to report this in but we're looking for a contact that we can provide a full analysis of this issue and can escalate it to the right team within eBay.

This issue doesn't seem to just be with this account, reviewing various online discussion platforms it's been mentioned many times by other account owners that their promoted listings have just stopped working like this. This issue could cost people their companies, jobs and homes if it's not resolved urgently. 

I would be very grateful if you could direct me to the correct contacts at eBay UK to resolve this issue.

---

### Issue Timeline 

Account status **eBay Top-rated seller** with product listings marked as **eBay Premium Service**.

1. **17th February 2021** eBay switched the account to managed payments.

2. **10th March 2021** the account received the latest eBay invoice, which was the first eBay invoice after switching to managed payments. The payment was due by 31/03/2021 and the automatic payment method was set to use PayPal like normal for all previous payments.

3. **11th March 2021** the account manager noticed that there was hardly any sales on that day, they investigated by checking the performance stats which showed a near 100% drop in promoted traffic from ebay.co.uk sales, international sales accounted for most of the promoted sales that day.

4. **12th March 2021** the account was even worse, with nearly 0% promoted traffic. The account manager contacts eBay and they mention it's because of not paying the invoice on time which states 31/03/2021, which obviously doesn't add up. It was also mentioned the account has automatic payments linked to PayPal and customer service said this can't be paid with PayPal on managed payments which I believe is incorrect because the UI shows PayPal as the option and still shows the linked account.

5. **13th March 2021** account manager speaks with customer support they mentioned an internal case was automatically created (Promoted Listing Ineligibility issue open on your account) because the invoice wasn't paid and that there was no Automatic Payment Method (APM). Checked eBay and there was APM set up and the invoice wasn't due until 31st of March which would be taken automatically with the APM on the system. Customer support mentioned that if the APM was set up and the invoice was paid the promoted listings would be back up within 72 hours.<br>
The account manager decided to pay instantly using the link in the email with the invoice "Make a one-time payment to bring your account up-to-date", opens eBay's one-time payment page, clicking PayPal opens the redirect authentication and payment pop up, clicking the authorised pay button returns to eBay and shows a status of successful (But it wasn't, it was only realised on the 15th when reviewing PayPal records that this invoice wasn't paid)

6. **15th March 2021** important eBay message received "Friendly Reminder: Payment and Updated info needed", this was odd since it was paid manually using PayPal on the 12th via the one-time payment method. Checks the linked PayPal and notices there wasn't ever a payment taken on that day even though eBay showed the success message after returning to eBay. Try's the process again using the linked PayPal again returns to eBay with a success message, checks PayPal no record on the account of any payment being taken.<br><br> A few hours later it is decided to add a new payment method to eBay to test that, adding a credit card and using the one-time payment system takes the money instantly from that credit card. This was reported to eBay custom support who said it would be escalated and would have a response within 72 hours but no update email arrived.

7. **18th March 2021** still going in circles with to what's the issue with the account, first blamed on the invoice payment not being paid on time, when it obviously was paid on time and well before the due date of 31st of March.<br><br> After making the payment and speaking with another representative it was blamed on too many open cases which were not true, this support agent said he would escalate this issue because on his system it shows the eBay account had many cases unresolved but we have screenshots of the dashboard and top-rated seller stats showing totally different data.<br><br> It has since been confirmed by multiple other support staff that there is no issue with cases on this account, the account has only ever had 1 case not resolved with an item not received which an eBay representative confirmed was an outstanding reputation for the number of orders this account has processed.

8. **25th March 2021** Requested a callback from eBay cases team, they confirmed no issue with the account, transferred the phone call to the promoted listings team who also stated no issue with the account. They can't understand why promoted listings are not working on this account.<br><br> Asked them if they could see any updates on the issues that were raised that were created as internal case tickets with the relevant team and was promised updates with 72 hours which is now way past that point with it being 10 days at this point, they said no replies and that they couldn't reply to that ticket and only open a new one. Requested to speak to a manager which as of yet has not happened, promised phone calls back to speak with managers within hours but never happens.

9. **30th March 2021** Trying to reach a representative that can escalate this issue and at least provide an acknowledgement that it is being investigated with a realistic response & resolution timeframe because 20 days of loss of sales for any company without a resolution or response is ridiculous.

## Screenshots

![screenshot-www ebay co uk-2021-03-30](https://user-images.githubusercontent.com/10200431/112985333-f4318380-9157-11eb-95ac-a5970c137f30.png)

![screenshot-www ebay co uk-2021-03-30](https://user-images.githubusercontent.com/10200431/112985654-5a1e0b00-9158-11eb-8164-046851a3b047.png)

Thank you.

Joe

**Comment by ianmcburnie** [comment]
The relevant people are looking into this, but I'm afraid I still don't have a good contact for you. I'll keep you posted. Thank you for your patience!

**Comment by ianmcburnie** [comment]
@joejordanbrown, in order to assist you further we are going to need your seller username.

**Comment by ianmcburnie** [comment]
@joejordanbrown I'm going to close this ticket for our own housekeeping purposes here, but you should still be able to comment on it, so please keep it bookmarked if you like.
