### ISSUE TITLE
Carousel: Image Background Layering

### ISSUE THREAD

**Issue by davidhyunchoi297** [eBay/ebayui-core#1362]
# Feature Request

## Description

This is a small enhancement feature that allows image background layering with CSS on the ebay carousel. It solves an issue that not all the images received will be of complete transparency and this enhancement will enable consumers of the component to be able to add fluidity and consistency to the background of all images regardless of its nature.

## Screenshots

Example of images with white background

<img width="1477" alt="Screen Shot 2021-03-29 at 3 58 29 PM" src="https://user-images.githubusercontent.com/45369449/113040044-54c7bd00-9166-11eb-8986-cb77d36c6df1.png">

Desired Result:

<img width="1558" alt="Screen Shot 2021-03-29 at 7 04 54 PM" src="https://user-images.githubusercontent.com/45369449/113040080-60b37f00-9166-11eb-9b1d-c59b323041e0.png">

**Comment by austingardner** [comment]
Could you add an example of the code that worked to do this?

**Comment by davidhyunchoi297** [comment]
sure thing. here's a screenshot. 

<img width="1725" alt="Screen Shot 2021-03-30 at 2 54 33 PM" src="https://user-images.githubusercontent.com/45369449/113041393-e97eea80-9167-11eb-9d30-276aa273067b.png">

**Comment by ianmcburnie** [comment]
Thanks @davidhyunchoi297 for this idea. We'll have to run it by the design team and see what they think. Thanks again!

**Comment by ianmcburnie** [comment]
Merged to 7.5.0.
