### ISSUE TITLE
ebay-pagination: current page index looks clickable with blue color

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#137]
The current page index is clickable.

repro:
create a pagination component
set a page index as current
The current page is highlighted and is also clickable

expected behaviour: the current page index is highlighted and the index is disabled for clicking
We dont have a provision to set a page index as current and disable the page index from being clicked again.

blue color on the index is misleading. Disabled/ index without href link should bot be displayed in blue

when we are in the current page we shouldnt be able to navigate to the same page again and again.

**Comment by sharma46bhawana** [comment]
@hramakumar Can you try removing the `href` input from the current page? It shouldn't be clickable again if there is no `href` and as it is the current page the `href` shouldn't be present anyway. Please let me know if that helps.

**Comment by hramakumar** [comment]
@sharma46bhawana  Yes I agree. That should make it not clickable. My concern is just with the colour.
It looks like a clickable index.

**Comment by ianmcburnie** [comment]
Closing as the current colour is defined by DSL.
