### ISSUE TITLE
Checkbox & radio: emit the 'keydown' event

### ISSUE THREAD

**Issue by melquan** [eBay/ebayui-core#1377]
# Feature Request

## Description
Emit the `keydown` event for `ebay-checkbox` and `ebay-radio`.

## Context
There are usecases in our flow where we need to perform actions based on certain keys pressed when focused on checkboxes and radios.

**Comment by ianmcburnie** [comment]
@austingardner Let's sneak this into 7.4.0.

**Comment by ianmcburnie** [comment]
Also needs porting back to v5 for the stragglers

**Comment by ianmcburnie** [comment]
Done in 7.4.0
