### ISSUE TITLE
ebay-pagination: some page indexes are blue and some are black

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#139]
repro
go to  https://go/ebayui/test2
pagination indexes- some are blue and some are black.
pls fix the discrepancy

**Comment by sharma46bhawana** [comment]
@ianmcburnie We see this issue because global header is adding a more specific style. What I can do is add more specificity to the achor tags but I wanted to avoid it if I could. 

<img width="805" alt="screen shot 2018-05-05 at 5 37 06 pm" src="https://user-images.githubusercontent.com/6751429/39668730-3eb1153a-508b-11e8-9ba7-94ca107e35e2.png">

**Comment by sharma46bhawana** [comment]
@hramakumar This is a skin issue, but I am not sure how to track it at correct place.

**Comment by ianmcburnie** [comment]
@sharma46bhawana Please paste the conflicting skin styles in here and we can decide what to do.

@hramakumar In addition to the URLs, please ensure to add screenshots in tickets It makes things faster to triage and debug.

**Comment by sharma46bhawana** [comment]
Hi @ianmcburnie I am seeing these conflicting styles:
<img width="683" alt="screen shot 2018-05-08 at 4 38 06 pm" src="https://user-images.githubusercontent.com/6751429/39788222-4bfed1dc-52de-11e8-901a-7ab3e4d547d2.png">
<img width="680" alt="screen shot 2018-05-08 at 4 36 49 pm" src="https://user-images.githubusercontent.com/6751429/39788223-4c35bb16-52de-11e8-9d00-9ca5eb7a10ea.png">

**Comment by sharma46bhawana** [comment]
I can add `:link` pseudo selector that will make sure the correct color is rendered

**Comment by ianmcburnie** [comment]
Yep, let's go with that. You might need the `:active` too. Please copy the screenshot above into a new Skin issue and target the 4.1.0 release.

**Comment by sharma46bhawana** [comment]
@ianmcburnie Added the issue in the skin: https://github.com/eBay/skin/issues/188

**Comment by ianmcburnie** [comment]
Yes, let's close this. It should be fixed in 4.0.0-1
