### ISSUE TITLE
ebay-menu-button collapseOnsSelect is not getting handled on handleSelect

### ISSUE THREAD

**Issue by pranaykondekar** [eBay/ebayui-core#1391]
# Bug Report
ebay-menu-button not calling handleItemClick on item click.
`handleMenuSelect` is being called on selecting menu item but `handleItemClick` is not getting triggered.

## Description
Steps:
Click Menu to expand items
Click on any item

Expectation
Should call handleItemClick

**Comment by ianmcburnie** [comment]
Can you please describe your use case for needing this? The current API essentially delegates all items click events to a single `handleMenuSelect` event.

**Comment by agliga** [comment]
I think this was the issue of collapseOnsSelect is not getting handled on handleSelect. 
Should be renamed.

**Comment by ianmcburnie** [comment]
Fix merged to 7.5.0.
