### ISSUE TITLE
lightbox-dialog: default 'buttonPosition' is overwritten by input when 'undefined' is passed

### ISSUE THREAD

**Issue by melquan** [eBay/ebayui-core#1399]
# Bug Report

## Description
We have a wrapper component that passes through some attributes to the various dialogs.  When we add `buttonPosition` to our component that passes through `undefined` to the lightbox dialog, the close button is moved to the left of the header.

This is due to `...input` being at the end of the `ebay-dialog-base` tag.  If it is moved to above `button-position`, this would fix the problem.

## Workaround
None.

## Screenshots
_Actual:_
![image](https://user-images.githubusercontent.com/19419138/119036645-cef61000-b965-11eb-8e04-eb0f1514c91f.png)

_Expected (default button position):_
![image](https://user-images.githubusercontent.com/19419138/119036699-e3d2a380-b965-11eb-96f8-ab536dfbb4c3.png)

**Comment by agliga** [comment]
Published in `7.5.2`
