### ISSUE TITLE
Unnecessarily transforming nested tag syntax

### ISSUE THREAD

**Issue by mlrawlings** [eBay/ebayui-core#14]
The nested tag transformer is a bit aggressive and renames all nested tags, even if they are already using Marko's nested tag syntax. 

```marko
<ebay-menu>
    <ebay-menu:item>Item</ebay-menu:item>
</ebay-menu>
```

becomes:

```marko
<ebay-menu>
    <ebay:menu:item>Item</ebay:menu:item>
</ebay-menu>
```

Honestly, probably not much of an issue once #11 and #13 are fixed, but ran into this trying to work around those issues.

**Comment by ianmcburnie** [comment]
What's the time estimate for fixing this?
