### ISSUE TITLE
When changing buttonPosition on dialog via state, header moves in janky manner

### ISSUE THREAD

**Issue by pcanella** [eBay/ebayui-core#1404]
# Bug Report

## Description
When we change the `input` of `buttonPosition`via a state change or other kind of update and set it to `hidden` when it previously was not, the button totally disappears and move the `<@header>` up and to the left, instead of keeping the text/header where it is. 

## Workaround

Workaround would be editing/overriding the CSS

## Screenshots

https://user-images.githubusercontent.com/4923719/120047879-8b854c80-bfca-11eb-998d-7149701b785b.mov

One possible solution would be to instead of completely disappearing the button with `hidden`, we could use something that maintains its box model like `visibility:hidden` or something.

**Comment by ianmcburnie** [comment]
Thanks for filing this. Quick note: it's better for a11y if we use `hidden`, as then we are assured that screen readers and keyboard users cannot access anything in the dialog while it is closed. It _is_ technically possible to achieve this with aria-hidden on the root and tabindex=-1 on all nested interactive controls.... but that can be error prone and there are edge cases.

**Comment by pcanella** [comment]
@ianmcburnie Ahh got it! Our designers keep referring to this state as "high commit" where you can't escape the modal via X button or clicking outside the pane; until you choose a CTA button. If you did `visibility: hidden` as well as `disabled` and used something like `input.highCommit = true` would that work? It's actually really difficult/impossible to make this happen properly by overriding `panel-dialog`, which I obviously don't want to do. 

Something to consider since I keep hearing those words "high commit" 😂

**Comment by agliga** [comment]
Also, `buttonPosition` (being an internal attribute) was not built to support this kind of usecase. It is used for other components since we reuse common dialog parts. What is happening is that the button is actually making the header larger in this case, and then when it's removed the header shrinks. Adding a `min-height:40px;` to the header fixes this, but the header still shifts over to the left. 
My gut feeling is to use the `hidden`. The other fix would be to add a min-height to header in skin

**Comment by ianmcburnie** [comment]
Ah, I see what's happening now. Thanks, Andrew.

Patrick can you leave the close button in place, but set it to disabled perhaps? That will solve the jankiness of the header.

**Comment by pcanella** [comment]
@ianmcburnie Unfortunately I can't; I need to keep `buttonPosition="hidden"` because it disables the clicking outside of the panel, which is considered that "high commit" type design. Maybe if there was a separate input that would turn off the click-in-mask-area to hide, that would be ideal.

**Comment by ianmcburnie** [comment]
Ah, okay. So by "high commit" you're wanting this panel to have more of an "alert" or "confirm" dialog type interaction (which can't be quick dismissed with X, ESC or mask click). This would seem to go against our design system for your use case (and also usability). Let's chat offline.
