### ISSUE TITLE
ebay-pagination: `select` event returns text instead of index

### ISSUE THREAD

**Issue by darkwebdev** [eBay/ebayui-core#1407]
# "Bug" Report

## Description
[here](https://github.com/eBay/ebayui-core/blob/80c57957828de0f8cb9e2912f6a7ac9303b58ccf/src/components/ebay-pagination/component.js#L15):
```
handlePageNumberClick(originalEvent, el) {
	this.emit('select', {
	   	el,
    	originalEvent,
	    value: el.innerText,
	});
}
```

`value` returned is a text of the item clicked, that's why [in storybook example](https://github.com/eBay/ebayui-core/blob/80c57957828de0f8cb9e2912f6a7ac9303b58ccf/src/components/ebay-pagination/examples/06-buttons-interactive/template.marko#L14) we have to parse that text for number and use it as the current index inside the state. But what if the text was something like `1 out of 5`, `first`, etc...? It seems that we should return not the item text, but the index of the clicked item.

**Comment by ianmcburnie** [comment]
I agree that index should always be easily available (this goes for pretty much every component). It's a useful thing to have. We could return both `value` and `index`. @agliga?

**Comment by ianmcburnie** [comment]
Fixed in 12.x
