### ISSUE TITLE
using floating label in ebay-textbox add margin-top: 14px

### ISSUE THREAD

**Issue by BhavinPatel04** [eBay/ebayui-core#1416]
# Bug Report

## Description
using floating label in ebay-textbox add margin-top: 14px
Skin Issue: https://github.com/eBay/skin/issues/1481

## Workaround
Override skin style

## Screenshots
![image](https://user-images.githubusercontent.com/6559211/122828567-d9ccf900-d2b3-11eb-8c19-fba2cb597264.png)

**Comment by ianmcburnie** [comment]
Fix merged to 12.x branch.
