### ISSUE TITLE
Menu Button with Icon Needs Margin

### ISSUE THREAD

**Issue by austingardner** [eBay/ebayui-core#1422]
## Description
menu-button with icon needs margin. This might be related to recent changes to icon-button? 

## Screenshots
![Screen Shot 2021-06-22 at 3 44 56 PM](https://user-images.githubusercontent.com/25092249/123009099-ef542880-d370-11eb-96b1-b4efc4ebfeb7.png)

**Comment by ianmcburnie** [comment]
Seems like a duplicate of: https://github.com/eBay/ebayui-core/issues/1373

**Comment by austingardner** [comment]
whoops
