### ISSUE TITLE
video: closed captioning

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#1427]
details to follow...

**Comment by ianmcburnie** [comment]
@agliga I believe you already took care of this?

**Comment by agliga** [comment]
This is partially working. I think we need a video example with CC to see if it actually works. 
There is another fix needed from Shaka https://github.com/google/shaka-player/issues/2676

**Comment by nbcl** [comment]
Hello @agliga, I am chiming in from Shaka.

The following manifest `https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd` could work as a testing example.

In advance, once #3465 is merged, closed captions should work natively by adding `'captions'` to your control panel elements at `src/components/ebay-video/component.js`.

https://github.com/eBay/ebayui-core/blob/4c4e15f4e9b3c5509c5242b8937cabeb8439c95d/src/components/ebay-video/component.js#L9-L17

Let me know if you encounter any issues doing so, happy to help!

**Comment by austingardner** [comment]
As of today, the [PR](https://github.com/google/shaka-player/pull/3465) mentioned above hasn't been merged, but it should be soon.. it has one approval

**Comment by austingardner** [comment]
The [PR](https://github.com/google/shaka-player/pull/3465) was merged, so shaka just needs a bump. Will have to discuss with video team about where they want the CC icon.

**Comment by agliga** [comment]
Closing, we have cc in dropdown
