### ISSUE TITLE
Carousel: broken 2-finger scrolling when saving and setting index

### ISSUE THREAD

**Issue by benc3467** [eBay/ebayui-core#1431]
# Bug Report

## Description

This issue occurs when saving and setting the carousel index:

```
handleScroll({ index }) {
      this.state.index = index;
}
<ebay-carousel index=state.index on-scroll('handleScroll')>...</ebay-carousel>
```

This appears to occur when using the carousel-update event as well. 

When using 2-finger scrolling on mac, the carousel slide appears to "shake" slightly before resting into position. In addition, scrolling quickly sometimes results in the carousel rapidly shifting (see end of demonstration video).

## Screenshots
https://user-images.githubusercontent.com/43257212/124317513-4910db80-db45-11eb-81e1-8f12d4389cfa.mp4

**Comment by ianmcburnie** [comment]
Fixed in master. Will go out in 7.6.12
