### ISSUE TITLE
Breadcrumbs: add JSON-LD structured data 

### ISSUE THREAD

**Issue by nisanoshin** [eBay/ebayui-core#1432]
# Feature Request

## Description
Please add Google's structure data requirement for breadcrumbs as we will be losing out on SEO value without it. Please follow the requirements here: https://schema.org/BreadcrumbList

**Comment by ianmcburnie** [comment]
Thank you for creating this issue @nisanoshin

eBayUI dev note: Let's add a `schema-type` attribute with two possible values: “BreadcrumbList” (default) or “none”.

**Comment by ianmcburnie** [comment]
Blocked until further notice from SEO team.

**Comment by ianmcburnie** [comment]
We will be going with JSON-LD format: https://developers.google.com/search/docs/data-types/breadcrumb#json-ld_1

```
<script type="application/ld+json">
    [{
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      "itemListElement": [{
        "@type": "ListItem",
        "position": 1,
        "name": "Books",
        "item": "https://example.com/books"
      },{
        "@type": "ListItem",
        "position": 2,
        "name": "Science Fiction",
        "item": "https://example.com/books/sciencefiction"
      },{
        "@type": "ListItem",
        "position": 3,
        "name": "Award Winners"
      }]
    },
    {
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      "itemListElement": [{
        "@type": "ListItem",
        "position": 1,
        "name": "Literature",
        "item": "https://example.com/literature"
      },{
        "@type": "ListItem",
        "position": 2,
        "name": "Award Winners"
      }]
    }]
    </script>
```

We will make this optional via an attribuyte, eg. `structured-data=json-ld` (with `none` being the default)

**Comment by agliga** [comment]
Closing for now, please reopen if its needed.
