### ISSUE TITLE
Large button's size is 50px instead of 48px

### ISSUE THREAD

**Issue by BhavinPatel04** [eBay/ebayui-core#1433]
# Bug Report

## Description
Large button's size is 50px instead of 48px. I am using `size=large` attribute. Same issue with icon-only buttons

## Workaround
Use `fixed-height=true` attribute but this causes the text to not align to center vertically
![image](https://user-images.githubusercontent.com/6559211/124649495-943d2e00-de66-11eb-8ba2-465fd9a370ad.png)

## Screenshots
![image](https://user-images.githubusercontent.com/6559211/124649065-02352580-de66-11eb-9f18-8379a5cc0907.png)

**Comment by ianmcburnie** [comment]
@BhavinPatel04 Which browser? And can you repro in public storybook? (I cannot)

**Comment by BhavinPatel04** [comment]
Browser: Chrome
Storybook doesn't have large option for ebay-button
![image](https://user-images.githubusercontent.com/6559211/124650853-34e01d80-de68-11eb-8e38-c7a450d6fd62.png)

**Comment by ianmcburnie** [comment]
@BhavinPatel04 It does if you look under the knobs section

![Screen Shot 2021-07-06 at 11 51 51 AM](https://user-images.githubusercontent.com/38065/124652133-972d2400-de50-11eb-9d71-bfb0f1422335.png)

**Comment by BhavinPatel04** [comment]
I can't reproduce this issue on storybook either. Closing it.
