### ISSUE TITLE
video:  Volume and playback sliders are not operable using swipe up/down gesture.

### ISSUE THREAD

**Issue by shanelin1** [eBay/ebayui-core#1435]
# Bug Report
Volume and playback sliders are not operable using swipe up/down gesture.

## Description
Using iOS VoiceOver+Safari, swipe to start play video, Once the video starts to play, swipe to focus the volume slider control. Try to change the value by swiping up or down.

**Comment by agliga** [comment]
This could be related to https://github.com/google/shaka-player/issues/2239

**Comment by ianmcburnie** [comment]
Suggestion from Lauren is to hide volume sliders on small screen. Device's volume buttons can be used.

**Comment by ianmcburnie** [comment]
Closing due to #1463
