### ISSUE TITLE
Videos: Button ‘more settings’ announced without collapsed/expanded state

### ISSUE THREAD

**Issue by shanelin1** [eBay/ebayui-core#1439]
# Bug Report

## Description
Once the video starts to play, swipe to focus the button ‘more settings’.
Note how the element is announced.

Expected Result
The button should be announced with a collapsed/expanded state.

Actual Result
The button ‘more settings’ announces without mentioning collapsed/expanded state. However it opens/closes a layer when activated.

**Comment by agliga** [comment]
This isn't really an issue
There is a `a11yReportText` which is attached to the button. This can be said, expand the menu. There is no case where you can select the report menu in an expanded state.
