### ISSUE TITLE
Video: play timer is missing on the new version of the player

### ISSUE THREAD

**Issue by shanelin1** [eBay/ebayui-core#1443]
# Bug Report

## Description
Video play timer is missing on the new version of the player

## Screenshots
![image](https://user-images.githubusercontent.com/87088707/124835102-a5a13b80-df35-11eb-9ab7-890373a2c42a.png)

**Comment by agliga** [comment]
This has been fixed on `7.6.5`
See ebayui storybook 
<img width="670" alt="Screen Shot 2021-07-07 at 3 42 49 PM" src="https://user-images.githubusercontent.com/1755269/124837619-0468b400-df3a-11eb-8c12-ed1ded7eb657.png">
