### ISSUE TITLE
video: iPhone 12: Video player fullscreen button is missing

### ISSUE THREAD

**Issue by shanelin1** [eBay/ebayui-core#1446]
# Bug Report

## Description
Swipe to video thumbnail and tab on the image

The video starts playing using iOS native player

Now close the video player

Observed: videoplayer fullscreen icon [] is missing

**Comment by agliga** [comment]
https://github.com/google/shaka-player/issues/1909

IOS does not support shaka player fullscreen button. It is hidden intentionally.
