### ISSUE TITLE
video: iPhone SE: Video player control icons are not fully visible

### ISSUE THREAD

**Issue by shanelin1** [eBay/ebayui-core#1447]
# Bug Report

## Description
replay icon got cut off

## Screenshots
![image](https://user-images.githubusercontent.com/87088707/124970218-80b3d380-dfdc-11eb-98d2-8888be2ad4bd.png)

**Comment by agliga** [comment]
Changed size to fit container

**Comment by shanelin1** [comment]
still happening, opened new issue: https://github.com/eBay/ebayui-core/issues/1452
