### ISSUE TITLE
video - Unable to close Report layer by tapping anywhere on the screen

### ISSUE THREAD

**Issue by shanelin1** [eBay/ebayui-core#1457]
# Bug Report
click a video to play, Click on video report icon on the player

Try tap anywhere on the screen to close the report layer

Observed: Unable to close Report icon by tapping anywhere on the screen
## Screenshots
![image](https://user-images.githubusercontent.com/87088707/125709527-56e39eea-f681-4bdf-854f-645e136bfaf9.png)

**Comment by ianmcburnie** [comment]
I'm not sure if the intention from andrew was for the app to handle the state of the overlay after the report button is clicked, but either way it should probably auto-dismiss by default when tapped.

**Comment by austingardner** [comment]
closing, this isn't from our components.
