### ISSUE TITLE
video: click buttons on page causes JS error in console

### ISSUE THREAD

**Issue by shanelin1** [eBay/ebayui-core#1459]
# Bug Report

## Description
click a button on page that has video component throws error the console.

> _index-fRH1QQ8R.js:formatted:6156 Uncaught Error: Method not found: trackLastClick
>     at d.emit (index-fRH1QQ8R.js:formatted:6156)_

in node_modules/@ebay/ebayui-core/dist/components/ebay-video:

> _grep trackLastClick *.*
> index.marko:            on-click("trackLastClick")_

## Screenshots
![image](https://user-images.githubusercontent.com/87088707/125713557-15e5a937-b0aa-4af1-9365-d4efcc960946.png)

**Comment by austingardner** [comment]
Ebay UI only has that code in the dialog -> they're not using the ebay UI dialog
