### ISSUE TITLE
video: video throbber continues as video plys

### ISSUE THREAD

**Issue by shanelin1** [eBay/ebayui-core#1460]
# Bug Report

## Description
Sometimes observed a non-stoop throbber, and the video played when user interacted on the play icon with throbber surrounded. Screenshot is attached

## Screenshots
![image](https://user-images.githubusercontent.com/87088707/125844132-8e46d958-7735-46e0-b7f5-744a8c4942c1.png)

**Comment by austingardner** [comment]
We need more information on this one.. putting to blocked

**Comment by austingardner** [comment]
Probably related to 
https://github.com/google/shaka-player/issues/3482
