### ISSUE TITLE
ebay-video full-screen on Safari

### ISSUE THREAD

**Issue by tws2000** [eBay/ebayui-core#1473]
# Bug Report

## Description
On Safari, the video doesn't go full screen when using the full-screen control or by double clicking video. It gets bigger, but not full screen.

macOS 11.5
Safari 14.1.2

**Comment by StefanHeng** [comment]
I have the same problem. Entering full screen seems to be a known issue on safari tho.

**Comment by agliga** [comment]
Closing issue, this is not something we can fix.
