### ISSUE TITLE
ebay-carousel- cards with long text goes out of the card

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#148]
Repro:
go to https://go/ebayui/test2
search for "card with long text"

actual: the text goes outside the card
![image](https://user-images.githubusercontent.com/13157115/39726682-b4e831be-5204-11e8-8cad-571d27f3c302.png)

expected: The text gets truncated/stays within the card

**Comment by yomed** [comment]
I don't think this is a bug for us. We don't have any knowledge of content inside the cards, so it's up to consumers to make sure that their internal content is ok.

**Comment by ianmcburnie** [comment]
Yes, we can close this as invalid. It's up to the app developers to control the layout of their content inside the carousel.
