### ISSUE TITLE
Autocomplete option for ebay-combobox is case sensitive

### ISSUE THREAD

**Issue by abhinavrane** [eBay/ebayui-core#1484]
# Bug Report

## Description

Autocomplete option for ebay-combobox is case sensitive. Use case is as below. For example below autocomplete doesnt work if I type AUSTRA or in small austra in caps
![image](https://user-images.githubusercontent.com/88805818/129115213-eed13032-051a-44e1-8e56-a554dbefbc76.png)
![image](https://user-images.githubusercontent.com/88805818/129115226-0d61d8bc-68b7-4077-8a1e-9dfc2a0f7d76.png)

**Comment by austingardner** [comment]
They told me this issue was resolved - issue with their env / application
