### ISSUE TITLE
Carousel: layout and js breaks without any items

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#149]
go to https://go/ebayui/test2
search for "empty carousal"

actual:
![image](https://user-images.githubusercontent.com/13157115/39726863-551140ae-5205-11e8-895e-25fc028e7e5e.png)

**Comment by yomed** [comment]
In addition to the layout issue, the the js call stack can run out. Since there are no items, `lastIndex` becomes -1. Then the index continuously loops between 0 and -1, since it uses `lastIndex` as the upper bound.
