### ISSUE TITLE
ebay-infotip: Clicking anywhere on the page, can close the overlay using specific attribute

### ISSUE THREAD

**Issue by udaya888** [eBay/ebayui-core#1495]
# Feature Request

## Description
In the exisiting ebay-infotip component doesn't close overlay when we click anywhere on the page. 
Its good to close the ebay-infotip click anywhere outside of the page using specific attribute.

## Screenshots
![image](https://user-images.githubusercontent.com/8204473/130158642-8ef6bb05-4123-4038-91ae-147dd933b3c0.png)

**Comment by agliga** [comment]
So not going to fix this.
You can add this capability on your app by checking click on the page and then using the fixes from these bugs to programmatically close the infotip. 
https://github.com/eBay/ebayui-core/issues/1508 (for `8.0.0`)
https://github.com/eBay/ebayui-core/issues/1503 (for `7.x`)
