### ISSUE TITLE
ebay-carousel: samsung note 4- unable to scroll when only one card is in view

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#150]
![right arrow doesnt work](https://user-images.githubusercontent.com/13157115/39777664-007a15d4-52b9-11e8-9116-2aac88431f8b.png)

Repro: 
use samsung galaxy note 4
go to https://go/ebayui/test2
search for continuous in the carousel section
try to scroll right

**Comment by yomed** [comment]
@hramakumar The carousel component has different adaptive behavior based on lasso flags. Can you pass a `touch` lasso flag in your test app? 

Here are more details: https://github.com/eBay/ebayui-core/blob/d99d553085a34d7867228f84b2aee224514123fd/src/components/ebay-carousel/README.md#ebay-carousel-usage
