### ISSUE TITLE
ebay-combobox component's label acting weird in certain scenario.

### ISSUE THREAD

**Issue by sunil681** [eBay/ebayui-core#1500]
# Bug Report
ebay-combobox component's label acting weird in certain scenario.

## Description
In the ebay-combobox component when the background-color of the input is overridden from the code, the label goes floating. This is not suitable for cases when you want a custom background color (like information /warning state) of the combobox while loading the form.

## Workaround
So far, I haven't found a way to override the background color without kicking in the floating label. I have commented css code that sets the background color.

It would be better if the team can come up with different states for all the UI components with pre-built styles that can be used as default while development. Also, the flexibility to override these css properties should be available for certain business scenarios.

## Screenshots
with custom background color when the combobox is empty. 
![Screen Shot 2021-08-25 at 3 59 07 PM](https://user-images.githubusercontent.com/3440948/130875756-88758f3e-2b84-4037-8aa3-e8d597a96352.png)

with default background color when the combobox is empty. 
![Screen Shot 2021-08-25 at 3 59 39 PM](https://user-images.githubusercontent.com/3440948/130875762-9d929bd1-5db0-4130-b03c-f34546896f07.png)

**Comment by ianmcburnie** [comment]
MakeupJS floating-label does expose the allowed background colours:

https://github.com/makeup/makeup-js/blob/master/packages/makeup-floating-label/src/index.js#L9

That is something we could look into exposing in CoreUI. In the interim you could also choose to use a non-floating label as a workaround.
