### ISSUE TITLE
ebay-infotip: Add support for "open" attribute

### ISSUE THREAD

**Issue by okannivadikubendran** [eBay/ebayui-core#1503]
# Feature Request

## Description
`ebay-infotip` component doesn't have support for "open" attribute which can be used by the component consumers to dynamically open/close the infotip. e.g, Closing the infotip when user click anywhere outside the infotip

Similar to `eba-fullscreen-dialog`, `ebay-details` components, can  we have an `open` attribute for `ebay-infotip` component

**Comment by ianmcburnie** [comment]
Released in 7.x
