### ISSUE TITLE
ebay-combobox when input does not match any options, it should revert to the previous value

### ISSUE THREAD

**Issue by kennycto** [eBay/ebayui-core#1509]
# Feature Request

## Description

For `ebay-combobox` with autocomplete="list", when input does not match any options, it should revert to the previous value instead of doing nothing. 

See expectation like this combobox https://material-ui.com/components/autocomplete/

## Screenshots

![Aug-31-2021 21-28-46](https://user-images.githubusercontent.com/206663/131611985-62af51f5-dbfa-4c11-9859-d300469832e9.gif)

**Comment by ianmcburnie** [comment]
@kennycto I'm not entirely sure what you mean by revert to previous value. Do you mean the textbox value or the list of suggestions? Or something else?

**Comment by agliga** [comment]
So I tried out the one you sent and it seems to be doing the same as our combobox.

The only difference is if it does not match, it actually clears out the input. 
![autcomplete](https://user-images.githubusercontent.com/1755269/132574921-4ae52cba-ca8c-414d-a473-0e3e2b7f83fc.gif)

You can hook into `on-change` event or something to clear if if it doesn't match. There are ways to achieve that if that's what you wanted to do.

**Comment by ianmcburnie** [comment]
I strongly recommend NOT changing the value of the textbox from what was entered when it loses focus. That to me seems like unexpected behaviour of a combobox (it actually goes against one of its main purposes: to enter a custom value not present in the suggestions). So, this isn't something we would build into our core component, due to it breaking a core principle of combobox.

**Comment by kennycto** [comment]
> @kennycto I'm not entirely sure what you mean by revert to previous value. Do you mean the textbox value or the list of suggestions? Or something else?

The previously selected value. i.e. if the `The Godfather` is selected, then the user types in an input that does not match any of the options and tabs (lose focus), it would revert back to `The Godfather`, the previously selected input.

**Comment by kennycto** [comment]
> So I tried out the one you sent and it seems to be doing the same as our combobox.
> 
> The only difference is if it does not match, it actually clears out the input.
> ![autcomplete](https://user-images.githubusercontent.com/1755269/132575181-a432ae9a-e9fa-4a64-b701-e3831bf18c74.gif)
> 
> You can hook into `on-change` event or something to clear if if it doesn't match. There are ways to achieve that if that's what you wanted to do. Or give us an answer to Ian's question 👍

The difference is you had completed cleared out `The Godfather: Part II` from the input, so it essentially cleared the selected input. So when you type an input that does not match and tab (lose focus) it goes back to previous input, which is unselected.

**Comment by kennycto** [comment]
> I strongly recommend NOT changing the value of the textbox from what was entered when it loses focus. That to me seems like unexpected behaviour of a combobox (it actually goes against one of its main purposes: to enter a custom value not present in the suggestions). So, this isn't something we would build into our core component, due to it breaking a core principle of combobox.

Please see above comments. I'm not expecting a custom value not present in the suggestions. What should happen is that it should revert to the last selected valid suggestion. 

![Sep-08-2021 15-00-28](https://user-images.githubusercontent.com/206663/132591611-14b57819-ffef-4e3f-87c9-b4b2d6098b97.gif)

**Comment by ianmcburnie** [comment]
The purpose of a combobox is to provide two ways of setting a value:

1. A suggested value
2. An arbitrary value

By reverting to the suggested value, you are removing the ability of the user to set an arbitrary value. If you do not wish for users to enter arbitrary values then a combobox is not the correct component for you. Perhaps you should use a select or listbox button -  both of which have typeahead.

> Combobox widgets are useful for setting the value of a single-line textbox in one of two types of scenarios:
> The value for the textbox must be chosen from a predefined set of allowed values, e.g., a location field must contain a valid location name. Note that the listbox and menu button patterns are also useful in this scenario; differences between combobox and alternative patterns are described below.
> The textbox may contain any arbitrary value, but it is advantageous to suggest possible values to the user, e.g., a search field may suggest similar or previous searches to save the user time.
> https://www.w3.org/TR/wai-aria-practices-1.1/#combobox

**Comment by kennycto** [comment]
Ok, got it, we allow arbitrary values when `autocomplete` is not equal to `list`. I didn't consider that scenario. Thanks, I'll stick with the `select` instead. Thanks!
