### ISSUE TITLE
Carousel: discrete-third width- enough space to show only 2- the third card is skipped as we click the arrow

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#151]
Discrete-third width- 
When there is enough space to show only 2
 the third card is skipped as we click the arrow.
it is expected that the number of slides increase if we show less number of cards due to space available

repro:
android phone with less screen size
go to https://go/ebayui/test2
search for "discrete - third width"
you see only two cards instead of 3 
click next arrow on the right
The third card is skipped

![third width- only two cards visible](https://user-images.githubusercontent.com/13157115/39778192-7e9d0dd0-52ba-11e8-9e61-246ce0201007.png)
in the above screenshot only 2 cards are visible instead of three
when you go to next slide
Card 3 is skipped.
![after next click- card 3 is skipped](https://user-images.githubusercontent.com/13157115/39778256-ac967258-52ba-11e8-98e3-65f8ceff2f6d.png)

**Comment by yomed** [comment]
Closing per card content issue like #152
