### ISSUE TITLE
ebayui-tourtip - adding extra spaces after following workaround of setting position to relative.

### ISSUE THREAD

**Issue by Dkalyanasundaram** [eBay/ebayui-core#1517]
# Bug Report

## Description
https://github.com/eBay/ebayui-core/tree/master/src/components/ebay-tourtip
Followed above workaround for tourtip overlap issue - setting position to relative was giving very less flexibility to position the tourtip, and adding additional spaces to prevent overlap by the table itself when there is less number of rows.

Workaround - https://github.com/eBay/ebayui-core/issues/1401

## Workaround
No, after following workaround, there is a different issue.

**Comment by agliga** [comment]
Seems like the issue was due to some css on the customers app
