### ISSUE TITLE
Carousel: slide widget at the bottom is not selected

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#152]
Repro:
Android phone
go to https://go/ebayui/test2
some components do not have the slide status widget selected  at the bottom of the component
![after next click- card 3 is skipped](https://user-images.githubusercontent.com/13157115/39778764-129704cc-52bc-11e8-8c5c-605c0005b1c9.png)
there is no selected slide

**Comment by hramakumar** [comment]
The last dot has to be selected

**Comment by yomed** [comment]
@hramakumar Given that the app needs to control the content inside each card, can you do these tests in scenarios where the cards actually fit in the allotted width? You can remove the text (and provide more area for the entire carousel too).

**Comment by hramakumar** [comment]
but in the above example the text fits inside the card

**Comment by yomed** [comment]
Not exactly. There is too much text and too little space to fit the number of cards needed in these examples. I can see how this might be seen as a bug, but I think we should defer issues related to the content of the cards.
