### ISSUE TITLE
ebay-infotip width is not responsive to content

### ISSUE THREAD

**Issue by mkchang** [eBay/ebayui-core#1520]
# Bug Report

## Description
Infotip has a `min-width: 320px` which does not seem to be in DS spec anymore (no min is listed, and examples with smaller than 320px width are shown). Infotip does not seem like it expands to the `max-width` of 344px (small screen)/400px (large screens) specified either. This issue originally came up due to short content still having a large infotip. 

![image](https://user-images.githubusercontent.com/6880917/133531823-106cfa4d-ec3d-4332-954e-236f56d6ec55.png)
![image](https://user-images.githubusercontent.com/6880917/133532489-267d5e34-498f-44ce-8001-74bd06dfd21e.png)

## Workaround
From an earlier discussion with Ian, we discussed overriding it in the interim, however I'm not sure I've found a good way with the current structure. Without a min-width specified on `.infotip__overlay`, the infotip will collapse:
![image](https://user-images.githubusercontent.com/6880917/133532235-2d570d65-eae2-46e8-b38a-c88cf1bc34fc.png). This wouldn't happen if `.infotip` wasn't `position: absolute`, but we also need that to keep the infotip floating in the correct place. Open to suggestions on interim CSS based fixes though.

**Comment by agliga** [comment]
A way to fix this is to add:
`width: max-content;` and remove `min-width` property.

**Comment by agliga** [comment]
Closing, this is a skin issue

**Comment by mkchang** [comment]
For future reference, we ended up going with 
```less
.infotip__overlay {
    min-width: unset;
    width: 320px; // Edge 18 support
    width: intrinsic; // Safari < 11 support
    width: max-content;
}
```
and maintaining the old `320px` behavior for non-Chromium edge since we couldn't see a good solution otherwise at the time.
