### ISSUE TITLE
ebay-infotip icon is regular size when it should be small

### ISSUE THREAD

**Issue by mkchang** [eBay/ebayui-core#1524]
# Bug Report

## Description
Skin and DS playbook have an infotip default icon that appears to be the smaller info icon (thicker appearance), while ebayui-core is styling a regular sized info icon to be the smaller 16px size.

Left to right, Playbook, skin, ebayui-core storybook:
![Screen Shot 2021-09-23 at 12 01 58 PM](https://user-images.githubusercontent.com/6880917/134568151-6ff19a37-1c37-4e38-a012-a7de54eb0d0a.png)

## Workaround
Can workaround by passing in the small info icon directly, though since it should be default appearance, means changing it's use everywhere.
```marko
<ebay-infotip>
    <@icon>
        <ebay-information-small-icon/>
    </@icon>
    <@content>
        ...
    </@content>
</ebay-infotip>
```

**Comment by ianmcburnie** [comment]
Fix merged to 8.0.0
