### ISSUE TITLE
ebay-menu-button: originalEvent is not being emitted when onChange

### ISSUE THREAD

**Issue by ZZS77** [eBay/ebayui-core#1527]
# Bug Report

## Description
`originalEvent` is not emitted for change event

slack thread:
https://ebay-eng.slack.com/archives/CK8AX1L49/p1633026457061200?thread_ts=1632873913.051500&cid=CK8AX1L49

## Workaround
No workaround

## Screenshots
<img width="686" alt="Screen Shot 2021-10-01 at 12 02 18 PM" src="https://user-images.githubusercontent.com/42783072/135673271-568c2359-e628-4405-9867-4b6d64ea12fe.png">

**Comment by agliga** [comment]
Published in `@ebay/ebayui-core@7.6.17`
