### ISSUE TITLE
selectedIndex is not highlights 

### ISSUE THREAD

**Issue by santhosmca** [eBay/ebayui-core#1535]
# Bug Report

## eBayUI Version: 13
 "@ebay/skin": "^13", 
 "@ebay/ebayui-core": "^8.0.0",

## Description
selectedIndex is not highlight ebayfake tab

https://ebay.github.io/ebayui-core/?path=/story/ebay-fake-tabs--standard&args=selectedIndex:1

**Comment by agliga** [comment]
Published  `skin@13.0.1` with this fix
