### ISSUE TITLE
Dialog Base improvement

### ISSUE THREAD

**Issue by montoya332** [eBay/ebayui-core#1542]
https://github.com/eBay/ebayui-core/blob/406000378d778c0a62a9edb44aa49cac6869c909/src/components/components/ebay-dialog-base/component.js#L78

not really a issue but small improvement I believe 

i propose changing logic to
‘aria-live’:  (input.isModal == false) && ‘polite’
without side effect on onInput change

https://github.com/eBay/ebayui-core/blob/406000378d778c0a62a9edb44aa49cac6869c909/src/components/components/ebay-dialog-base/index.marko#L71

**Comment by ianmcburnie** [comment]
Can you clarify the purpose of this change? I'm not sure I follow, but are you suggesting making a non-modal dialog a live region?

**Comment by montoya332** [comment]
It shouldn't change current behavior . Its a really small change and probably not a big deal but just find it easier to read if we remove side effect

**Comment by agliga** [comment]
> It shouldn't change current behavior . Its a really small change and probably not a big deal but just find it easier to read if we remove side effect

Not sure if I understand it correctly.
the thing is, we are using `isModal` in a lot of different places. We set the `isModal` in case `isModal` is not passed in order to treat that as true.
We can set a component variable, but it seems fine to basically default it to a value.

**Comment by ianmcburnie** [comment]
Going to close based on Andrew's comments. Feel free to re-open again if you feel we've missed something here.
