### ISSUE TITLE
ebay-tourtip: horizontal positioning is off

### ISSUE THREAD

**Issue by agliga** [eBay/ebayui-core#1550]
# Bug Report

## Description
Tourtip positioning seems off based on host element, especially when doing left/right
It seems to be placing it not relative to the host correctly. 
We have to be careful because tooltip and infotip both work well

## Workaround
Manual overrides

## Screenshots
<img width="504" alt="Screen Shot 2021-11-03 at 10 11 45 AM" src="https://user-images.githubusercontent.com/1755269/140139066-f57cf5af-34e4-44c7-9a0f-3c445e6f447d.png">
<img width="428" alt="Screen Shot 2021-11-03 at 10 11 53 AM" src="https://user-images.githubusercontent.com/1755269/140139092-5a3376d4-1e03-4e48-99e8-d437cac4cd84.png">

**Comment by agliga** [comment]
Closing, the solution for this is related to https://github.com/eBay/ebayui-core/issues/1766

**Comment by cc-ebay** [comment]
As I understand it this is is not solved and currently captured in #535

**Comment by agliga** [comment]
> As I understand it this is is not solved and currently captured in #535

Yes
