### ISSUE TITLE
rendering colored icon inside ebay-icon-button renders it as black

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/ebayui-core#1557]
# Bug Report

## Description

Render a red icon, e.g. 
```
<ebay-attention-filled-small-icon/>
```
Now render it inside a `icon-button`
```
<ebay-icon-button>
  <ebay-attention-filled-small-icon/>
</ebay-icon-button>
```
It would render as black. This worked fine in core 7. 

You can also repro this issue in the demo page http://localhost:3000/ds6/ebay-infotip

```
<ebay-infotip
    a11y-close-text="Dismiss infotip"
    aria-label="Important information">
    <@icon>
        <ebay-attention-filled-small-icon/>
    </@icon>
    <@heading>Important</@heading>
    <@content>
        <p>This is some important info</p>
    </@content>
</ebay-infotip>
```
(PS: I could not get the `ebay-icon-button` demo page to work properly - hence  used `ebay-infotip` as an example)

## Screenshots

<img width="93" alt="Screen Shot 2021-11-11 at 3 05 03 PM" src="https://user-images.githubusercontent.com/5200733/141509717-885ede12-748c-4edf-a3de-ef7ebb56b47f.png">

**Comment by agliga** [comment]
Basically this line is causing that issue.
I think it should be removed. @ianmcburnie any thoughts on this?
https://github.com/eBay/skin/blob/master/src/less/icon-button/base/icon-button.less#L26

**Comment by ianmcburnie** [comment]
Hmm, by default we do want icon button icons to inherit from the color-text-primary in our new token based system. Icons using other colours are the exception. Have you tried setting the `--icon-button-icon-foreground-color` variable within the scope of your class? This may not be the ideal solution, but might mitigate for now.

**Comment by agliga** [comment]
Yeah, we should figure it out. We want the default color to be used, but also to be overriden by other colors, because we have icons that have various colors by default. 
Or we can think about having all icons have no colors, and adding color modifier to icons maybe?

**Comment by ianmcburnie** [comment]
> Or we can think about having all icons have no colors, and adding color modifier to icons maybe?

Yes, this might make sense. I will take a look.

**Comment by ianmcburnie** [comment]
This should be fixed when taking the latest Skin changes. Related PR: https://github.com/eBay/skin/pull/1602
