### ISSUE TITLE
ebay-button: hasLoaded should not be static

### ISSUE THREAD

**Issue by melquan** [eBay/ebayui-core#1558]
# Bug Report

## Description
Due to the `hasLoaded` being static, it is causing issues with fixture tests.

For example, if I have a list of fixtures like this:
* fixture1
* fixture2
* loading <-- bodyState='loading'
* fixture3
* fixture4

it will expect `aria-live="polite"` be rendered on the button in `fixture3` & `fixture4` .

After checking with @DylanPiercey, he mentioned it should probably not be a `static` var.

## Workaround
None

**Comment by agliga** [comment]
@ianmcburnie 
This was done by Austin. He mentioned that we need to have a way to know that the button has finished loading. Do we want to add another state to this or when we turn off loading, it should say loaded?

**Comment by melquan** [comment]
This issue is still happening.

**Comment by agliga** [comment]
Yes! We did not remove it because it needs to be there if the loading state is turned off. This is for accessibility. 
You need to pass: `body-state="reset"` to button to remove it. This should be done when the button is loaded after the user sees that is is finished loading.

**Comment by melquan** [comment]
This will be weird to have the fixtures after the `loading` fixture, in the same `fixture3` & `fixture4` with `body-state="reset"`.  I think I will just keep my workaround with renaming my `loading` fixture to `z-loading` to have it run last in the list then.
