### ISSUE TITLE
EbayUI Carousel Paddles Flicker upon any state changes to rerender

### ISSUE THREAD

**Issue by davidhyunchoi297** [eBay/ebayui-core#1566]
# Bug Report

## Description

Clicking the paddles to navigate and attaching an event handler that involves some state change causes a rerender, which causes the paddle to quickly disappear and appear. It results in a flicker each navigational step. The expected behavior would be that the paddles do not flicker.

## Workaround
 It would seem that in the ebay ui carousel there is a logic in which involves these flags 
data.bothControlsDisabled && carousel__container--controls-disabled

## Screenshots

![carousel-bug](https://user-images.githubusercontent.com/45369449/144140998-40508328-1413-4269-8e17-100d418b1b30.gif)

**Comment by ianmcburnie** [comment]
Fixed in 8.2.0 branch
