### ISSUE TITLE
Carousel: in iOS the horizontal scroll bar is invisible in continuous carousel

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#157]
Repo:
IOS phone- chrome browser
go to https://go/ebayui/test2
search for continuous carousal 
touch and scroll the carousel
the horizontal scroll bar below the carousel is not displayed
will update the screenshot soon

**Comment by yomed** [comment]
@hramakumar This seems to be native browser behavior (which wouldn't be a bug).
