### ISSUE TITLE
ebay-carousel: discrete half width and third width carousels not displayed properly in IE

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#158]
Repro:
   open discrete half width/third width carousel in ie
all slides are visible in first slide and second slide moves the entire .
![image](https://user-images.githubusercontent.com/13157115/39882024-7ab91d48-5437-11e8-83d9-72d0bfcc8fa5.png)

**Comment by yomed** [comment]
@seangates @ianmcburnie This is first component that needs its own styles outside of Skin. Do you think we should compile the LESS and run autoprefixer and then ship the compiled CSS files? Or should we rely on apps to do their own processing?

**Comment by yomed** [comment]
@hramakumar What version of IE?

**Comment by hramakumar** [comment]
11
