### ISSUE TITLE
infotip/textbox: gray background should not be present

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#1580]
The `icon-btn--transparent` class needs adding to the coreui markup for ebay-infotip. This will remove the default gray background for icon buttons (which infotip inherits from).

![Screen Shot 2021-12-07 at 4 00 25 PM](https://user-images.githubusercontent.com/38065/145124566-7f22d4a0-37cf-448d-adef-1fbe30d566be.png)

**Comment by PrashantAshok** [comment]
This issue happens in `ebay-textbox` with `postfix-icon` as well. This needs to have `icon-btn--transparent` class as well. https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-textbox/index.marko#L73

<img width="131" alt="Screen Shot 2021-12-09 at 12 06 21 PM" src="https://user-images.githubusercontent.com/5200733/145468610-954b7226-bdeb-4d22-a96b-5bf9fdf2b3ad.png">

```
<ebay-textbox placeholder="name" button-aria-label="clear icon">
    <@postfix-icon><ebay-clear-small-icon/></@postfix-icon>
</ebay-textbox>
```

**Comment by PrashantAshok** [comment]
@agliga @ianmcburnie - #1585 only fixes the first part of the problem. Second problem (mentioned above) of outline exceeding the textbox is still present. I am not sure if this issue should be kept open or should I open another one (should be a Skin bug)?


<img width="297" alt="Screen Shot 2021-12-16 at 9 26 18 AM" src="https://user-images.githubusercontent.com/5200733/146419599-97b0b2c3-c022-4690-83b7-879d40af089e.png">

**Comment by austingardner** [comment]
When you say `outline` are you talking about the outline when you tab through?

**Comment by austingardner** [comment]
Mine looks like this when it has tab focus:


<img width="150" alt="Screen Shot 2021-12-16 at 10 02 47 AM" src="https://user-images.githubusercontent.com/25092249/146425033-cba4c20a-6458-4372-8934-93d35f405daa.png">

Is it possible you have some class that makes it look different? I can't seem to reproduce the screenshot you have there.

**Comment by austingardner** [comment]
What version of ebay UI are you on? @PrashantAshok

**Comment by PrashantAshok** [comment]
I pulled the `master` branch - running this repo locally using demo site. http://localhost:3000/ds6/ebay-textbox
```
<ebay-textbox placeholder="name" button-aria-label="Clear">
    <@postfix-icon><ebay-clear-small-icon/></@postfix-icon>
</ebay-textbox>
```

**Comment by agliga** [comment]
I see the same as Prashant locally on ebayui. 
It looks odd on skin (I think we're missing the transparent icon button there in examples)
<img width="261" alt="Screen Shot 2021-12-21 at 3 21 40 PM" src="https://user-images.githubusercontent.com/1755269/147010242-e61c9c3a-7823-446f-8e7c-b1182644401d.png">

But this is what I see locally
<img width="260" alt="Screen Shot 2021-12-21 at 3 11 56 PM" src="https://user-images.githubusercontent.com/1755269/147010278-633c39a5-a600-45c2-a663-b12e48ac357b.png">

Maybe doing some `outline-offset: -6px;` seems to be better
<img width="246" alt="Screen Shot 2021-12-21 at 3 23 32 PM" src="https://user-images.githubusercontent.com/1755269/147010379-95f27dce-c42f-419a-8647-804f2dce6e7e.png">

**Comment by austingardner** [comment]
Figured out why I didn't see this issue before - edge has different outline styling - I didn't know that. Here is what I was seeing, just to illustrate: 

<img width="347" alt="Screen Shot 2021-12-22 at 10 37 35 PM" src="https://user-images.githubusercontent.com/25092249/147199176-fe5ff4e8-f6d6-4d9d-8e75-37635ce90aa7.png">

**Comment by austingardner** [comment]
Will put in a PR for this tomorrow
