### ISSUE TITLE
ebay-menu @item is still clickable when disabled=true

### ISSUE THREAD

**Issue by jmdiego** [eBay/ebayui-core#1586]
# Bug Report

## Description
for the `ebay-menu` component with `type="radio"`, when the disabled attribute is added to an `@item` it's still clickable, selects the disabled item and triggers the on-change event.

The expected result is that the click/touch/keyboard enter events are ignored for the disabled items.

## Workaround
Disabling pointer-events for the disabled items is almost a perfect workaround, the keyboard events are still enabled and the disabled option can be still selected that way:
```css
.menu-button__item[disabled] {
  pointer-events: none;
}
```

**Comment by agliga** [comment]
Will be released in `8.3.0`
