### ISSUE TITLE
Design Update: Update Color Codes from "Gray" to "Neutral

### ISSUE THREAD

**Issue by mumagnusson** [eBay/ebayui-core#1604]
# Feature Request

As part of Brand and Product Evolution, please update the color codes from Gray to Neutral. See attached. 

<img width="856" alt="Screen Shot 2022-01-21 at 1 22 35 PM" src="https://user-images.githubusercontent.com/95254242/150602682-2a01e12f-8138-4927-8424-2e246f9efb56.png">

Brand Playbook for reference: https://playbook.corp.ebay.com/PlaybookApp#/building-blocks/color/our-colors

**Comment by agliga** [comment]
Issue is a skin change. Will open an issue on skin
