### ISSUE TITLE
Menu: still has empty span when there is no label

### ISSUE THREAD

**Issue by seangates** [eBay/ebayui-core#162]
Skin supports having an "icon only" button, but it require that icon to be the "only child". Therefore, we need to fix the menu's `<ebay-button>` to remove the extra span if there is no label, or if an empty label string is supplied.

```
<span if(data.label)>${data.label}</span>
```

**Comment by ianmcburnie** [comment]
Not a blocker for 0.4.0. Moving to 0.5.0
