### ISSUE TITLE
ebay-details: storybook issue

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#1627]
The details justification/position seems to jump around in the story:

Before click

![Screen Shot 2022-02-17 at 1 34 12 PM](https://user-images.githubusercontent.com/38065/154574656-f9449736-d13c-4cb3-ac2d-da92b2f2dedd.png)

After click

![Screen Shot 2022-02-17 at 1 34 25 PM](https://user-images.githubusercontent.com/38065/154574677-7689a22a-b0ac-46a5-b9f1-5bb5133e431d.png)

**Comment by agliga** [comment]
I think this is due to the flexbox and the layout is flexible for the container. 
I'm not sure how this would be fixed from that perspective since we need to change it for all stories.
