### ISSUE TITLE
LESS is not currently compiled/processed

### ISSUE THREAD

**Issue by yomed** [eBay/ebayui-core#163]
While we transpile our JS for shipping, we don't apply this to the LESS files. The carousel is the first component to have this issue come up, because it has styling that isn't present in Skin. A few options:
1) Only allow styling in Skin, never in ebayui-core.
2) Allow styling, but ship the LESS files as-is so that pages can determine what processing to do
3) Allow styling, run compilation and autoprefixing (and maybe others), and ship CSS

**Comment by senthilp** [comment]
I don't think Option 1 is always possible. Let's discuss between 2 & 3. We are currently doing 2, so the question is should be go to 3.

**Comment by ianmcburnie** [comment]
Closing, as we no longer have any LESS in CoreUI (carousel was moved to skin).
