### ISSUE TITLE
combobox: add expanded attribute

### ISSUE THREAD

**Issue by agliga** [eBay/ebayui-core#1673]
# Bug Report
combobox used to support an expanded attribute. We should set it. `onSetupMakeup` if combobox has expanded attribute then we should expand it. Something like this:
```
if(input.expanded && !this.expander.expanded) { this.expander.expanded = true } else if (!input.expanded && this.expander.expanded) { this.expander.expanded = false }
``` 
(Would need to check if the second part of the if statement is needed, since it might rerender closed on rerenders)

**Comment by ianmcburnie** [comment]
Merged to 8.6.0 branch.
