### ISSUE TITLE
Accessibility issue `ARIA attribute is not allowed: aria-expanded="true"`

### ISSUE THREAD

**Issue by joinfelipe** [eBay/ebayui-core#1688]
# Bug Report

## Description
Component has accessibility issue. The following error is given when running accessibility validation tool: 
```
ARIA attribute is not allowed: aria-expanded="true"
Element source:
<span class="tourtip__host" aria-expanded="true" aria-controls="s0-0-0-24-17-4-1-3-18[0]-overlay"></span>
```

## Screenshots
<img width="1003" alt="Screen Shot 2022-04-18 at 11 53 19 AM" src="https://user-images.githubusercontent.com/69696226/163860719-3004020b-7508-4057-aeaf-576b1ab437d2.png">

**Comment by agliga** [comment]
Will either need to:
Fix tourtip to not use expander
OR 
Fix expander to not add aria-expanded

**Comment by ianmcburnie** [comment]
Same issue for `aria-controls` too, I'd imagine. It shouldn't be showing up here.
