### ISSUE TITLE
ebay-filter-menu: Add support for disabling individual options

### ISSUE THREAD

**Issue by Vaishnavi-Thiyagaraj** [eBay/ebayui-core#1693]
# Feature Request

## Description

We have a requirement to disable particular options in ebay-filter-menu. To achieve this we want the component support   `disable` attribute in `item` to ebay-filter-menu.

## Screenshots

<img width="151" alt="Screen Shot 2022-05-12 at 10 47 57 AM" src="https://user-images.githubusercontent.com/49796069/168139881-df8620f2-93cf-4283-9a6e-e5c7548b469a.png">

**Comment by agliga** [comment]
We should use `--foreground-disabled` color when disabled. 
Will create a skin issue for this
