### ISSUE TITLE
ebay-listbox-button: attributes

### ISSUE THREAD

**Issue by cynthiahhc** [eBay/ebayui-core#1718]
For the `ebay-listbox-button` attributes, can we set most of the input attributes to the `button` tag instead of the `div/span` tag? For example the `id`, `aria-label`, `aria-required`, etc. are all set to the `div/span` which is not really useful in this case. https://github.com/eBay/ebayui-core/blob/9.1.0/src/components/ebay-listbox-button/index.marko#L27

**Comment by ianmcburnie** [comment]
Discussed offline, and the solution is to use the `prefixId` attribute which allows developer to build up an `aria-labelledby` relationship on the button using external and internal text. So we can close this ticket.

However, there is a bug with this behavior: https://github.com/eBay/ebayui-core/issues/1724
