### ISSUE TITLE
add args to ebay-details component span element - like role = "button"

### ISSUE THREAD

**Issue by ruimzhao** [eBay/ebayui-core#1723]
# Feature Request

## Description

Shipping tracking team requests to be able to add role="button" arguments to the span element inside the ebay-details component. This is to make this UI element trackable in the platform heatmap for user click action tracking.

**Comment by ianmcburnie** [comment]
@ruimzhao Click tracking should go on the details or summary element (whichever triggers the click event). Not the span.

**Comment by agliga** [comment]
Closing issue for now, please reopen with more information.
