### ISSUE TITLE
combobox label doesn't move when using keyboard

### ISSUE THREAD

**Issue by msendlakowski** [eBay/ebayui-core#1732]
# Bug Report

## Description
Using the combobox on the demo page with a floating label
https://opensource.ebay.com/ebayui-core/?path=/story/form-input-ebay-combobox--floating-label

Use the keyboard to select a value. The floating label collides with the selected value.  It stays that way even after selecting.

This was seen on Chrome.

## Screenshots

![Screen Shot 2022-08-19 at 10 45 03 AM](https://user-images.githubusercontent.com/1562843/185677976-452f3aea-65b1-47bd-a004-79d6297daa0c.png)
![Screen Shot 2022-08-19 at 10 48 21 AM](https://user-images.githubusercontent.com/1562843/185677981-20fb17e1-a9a6-46d7-a0d1-a93d0c75763f.png)

**Comment by agliga** [comment]
This has possibly been fixed in the latest beta
Will verify

**Comment by agliga** [comment]
This should be fixed, verified it is working
