### ISSUE TITLE
ebay-drawer-dialog touch/drag actions cause console errors

### ISSUE THREAD

**Issue by mkchang** [eBay/ebayui-core#1741]
# Bug Report

## Description
1. Go to https://opensource.ebay.com/ebayui-core/?path=/story/dialogs-ebay-drawer-dialog--standard in mweb view or on a phone (with dev tools open)
2. Try to tap to collapse OR drag to collapse
3. See console errors for `Uncaught TypeError: event.changedTouches.forEach is not a function` 

Saw this issue in our actual app, but also reproducible in storybook.

## Workaround
Not completely sure, but actual functionality seems to be fine, just raises a lot of errors in the console.

## Screenshots
![image](https://user-images.githubusercontent.com/6880917/186259188-f92a83dd-9ff0-4e29-9487-39582cf46644.png)

**Comment by franciscoyip** [comment]
We also encountered this issue. I traced the prototype of 'changedTouches', it's not a native array and hence doesn't support forEach
