### ISSUE TITLE
ebay-listbox-button: collapseOnSelect should default to "true"

### ISSUE THREAD

**Issue by LuLaValva** [eBay/ebayui-core#1746]
# Bug Report

## Description
To match with MIND patterns, the default behavior for listbox buttons should be to collapse when an option is selected.

## Workaround
Until this patch is out, `collapseOnSelect` can be manually added to each `ebay-listbox-button`.

**Comment by agliga** [comment]
We can add this in `onInput` something like:
`this.collapseOnSelect = input.collapseOnSelect === false ? false : true;`
And then use `this.collapseOnSelect` when checking.
