### ISSUE TITLE
Deprecated `ebay-stepper` references non-existent skin file

### ISSUE THREAD

**Issue by DylanPiercey** [eBay/ebayui-core#1748]
# Bug Report

https://github.com/eBay/ebayui-core/blob/7ba7f4e994b85da5fea069a6cd1dd30ece1e5c93/src/components/ebay-stepper/style.js References a no longer existent module from `@ebay/skin`. If this module is loaded it will cause a build error.

This is especially an issue when the module is used with Vite where it is unconditionally prebundled.

## Description
If you try to load `ebay-stepper` it should error. Also if you load `@ebay/ebayui-core` at all within a Vite project it will also error.

## Workaround
N/A

## Screenshots
N/A

**Comment by agliga** [comment]
Stepper has been removed in 10.0.0. It was used for migration only.
