### ISSUE TITLE
Carousel: movement controls don't apply for native scrolling

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#176]
Filing this ticket to keep track of the issue as we have closed the old ticket.

In the mWeb use case, whether or not a start index is defined, the continuous carousel starts with the first card. Currently, a touch-enabled carousel with `type="continuous"` will use native scrolling which has more limited functionality.

**actual**
![image](https://user-images.githubusercontent.com/13157115/40027587-91595706-578f-11e8-8804-11292b82da77.png)

**expected:**
![image](https://user-images.githubusercontent.com/13157115/40027609-aeb70d7a-578f-11e8-97ca-6290b1f027c1.png)

**Comment by yomed** [comment]
Note: This is currently expected behavior, but we should look to improve it in the future. Using `touch` with type="continuous" will use native scrolling. For that case, we don't fire typical movement events, and developers also can't control position through `index`.
