### ISSUE TITLE
Positioning of tourtip

### ISSUE THREAD

**Issue by cc-ebay** [eBay/ebayui-core#1766]
# <strike>Bug Report</strike> Feature Request

## Description
According to the Playbook:
> Preferred placement
> Tourtips can have a preferred placement in relation to their anchor element. The tourtip will default to this placement as long as it will fit within the viewport. Otherwise, it **will adjust its placement to fit**.

Currently the tour tip is pretty dumb when it comes to positioning. A good solution requires more JS code.
Good examples of adaptive positioning are in [TippyJS](https://atomiks.github.io/tippyjs/) and the good old [qTips2]( https://github.com/qTip2/qTip2/blob/master/src/position/viewport.js).

I would also add that the `style-*` attributes are not very useful. When used they also remove the `transform: translate...` that most of the time is useful. 

The tooltip should definitely be "centered" accordingly to the target and ideally should also change the position according to the space available in the viewport.

## Workaround
None at the time. Pick a good position and cross your fingers.

## Screenshots
This is Tippy:

![tippy](https://user-images.githubusercontent.com/64445558/192067863-c67df964-8249-4a26-a17d-6a32f4d0838a.gif)

**Comment by agliga** [comment]
Closing: dup of https://github.com/eBay/ebayui-core/issues/535
