### ISSUE TITLE
Carousel: broken when updating index via parent state

### ISSUE THREAD

**Issue by bhoomisatasiya** [eBay/ebayui-core#177]
I am setting the Index to animate the carousel to selected index. 
it works fine when I load the page from the server side. 
but when Click a pill by scrolling to that pill, I make an ajax call,
which updated all the components on the page including the Carousel, 
the selected index is not in the view port, and the right arrow is broken too.

![giphy](https://user-images.githubusercontent.com/11545472/40028319-012e7f5e-5793-11e8-902d-d17f6f35206d.gif)

**Comment by yomed** [comment]
Related to #161 
Users have a workaround by triggering a `resize` event manually.

**Comment by yomed** [comment]
@bhoomisatasiya Thanks for the bug report. This will be fixed in `0.5.x`.
