### ISSUE TITLE
Able to add html attributes for footer button in ebay-filter-menu-button

### ISSUE THREAD

**Issue by doahuang** [eBay/ebayui-core#1770]
# Feature Request

## Description

Allow developers to add html attributes for the footer button when using `<ebay-filter-menu-button footerText="footer button text">`

## Context

Currently `<ebay-filter-menu-button>` supports passing the input `footerText` to the footer button
https://github.com/eBay/ebayui-core/blob/v10.0.0/src/components/ebay-filter-menu-button/index.marko#L43
I want to have a `footerAttributes` or similar param so I can add html attributes to it, 
e.g. `<ebay-filter-menu-button footerText="footer button text" footerAttributes={"data-tracking": ...}>`

**Comment by agliga** [comment]
We can probably add a `@footer` attribute tag which can probably pass through to `filter-menu`.
