### ISSUE TITLE
Carousel: frame can exceed fps budget at end of animation

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#178]

**Comment by hramakumar** [comment]
![image](https://user-images.githubusercontent.com/13157115/40029981-7e6f22b2-579c-11e8-9fb5-d5ee2bd84c35.png)

**Comment by hramakumar** [comment]
repro:
scroll action on discrete carousel

**Comment by ianmcburnie** [comment]
@senthilp Would this be considered a blocker in terms of DoD?

**Comment by yomed** [comment]
I'm not sure if this is a real issue. The entire animation runs at something like ~58fps, but if you look at individual frames, you'll hit a few that are higher.

**Comment by ianmcburnie** [comment]
Yeah, I don't see any huge spikes which would signify jank. Just a few dips here and there.

**Comment by ianmcburnie** [comment]
@hramakumar Remember that you can save the performance profile and attach it to this bug for us to inspect.

**Comment by senthilp** [comment]
@ianmcburnie It is a DoD blocker in Buyer Experience. But we should not block the release for this. We should go ahead and be transparent in our Sprint review.

**Comment by mlrawlings** [comment]
Does the frame-rate degrade further when there is real-world content in the carousel, not just a placeholder?

**Comment by yomed** [comment]
@senthilp From what I can see, the animation itself runs fine. At the end of the animation, the very last frame takes a few extra ms to do update/paint/composite. Those steps are expected for a transform animation, so I still don't have a good sense of whether or not there's an actual issue here.

**Comment by senthilp** [comment]
@yomed Fair enough. 18-20ms is still good. But how do we suggest this as a guideline to other teams? Is there a particular pattern that we can grant an exception? I do not want teams to come up with random excuses and miss the frame rate.

**Comment by senthilp** [comment]
Agree, this issue can be closed. But we need to track it somewhere.
