### ISSUE TITLE
Combobox multiple options selected on keyboard input

### ISSUE THREAD

**Issue by cc-ebay** [eBay/ebayui-core#1782]
# Bug Report

## Description

I changed the story on https://github.com/eBay/ebayui-core/blob/397db2c44b40d9e329ca764f1ffbc735417db7bf/src/components/ebay-combobox/combobox.stories.js with: 
```javascript
FloatingLabel.args = {
...
    floatingLabel: 'Default Label',
    'onSelect': function(...args) {console.log('SELECT', args);}
};

for(let i = 5000; i > 4; i--){
    FloatingLabel.args.options.push({text: i % 2 ? `Basic Offer ${i}`: `August Campaign ${i}`} )
}
```
Beside taking forever to load and being quite slow in responding to input, I get this weird multi-selection. You can see around the ned of the video.

## Screenshots

![combobox-bug-small](https://user-images.githubusercontent.com/64445558/194189522-b47a6296-602e-4349-97bb-9cb9d680fb28.gif)

**Comment by cc-ebay** [comment]
In general, the logic of the `ebay-combobox` seems overly complex and optimizable. 

For example: `_getVisibleOptions()` seems to be called a lot when it could be called only when the text in the combobox change.

**Comment by agliga** [comment]
I believe it's coming from there being too many options and it's probably lagging behind. 
I have seen that multi highlight thing before. We had a fix where we were clearing the selected item, but it caused other issues. This has been a known issue for a while now. We can take a look.

**Comment by agliga** [comment]
> In general, the logic of the `ebay-combobox` seems overly complex and optimizable.
> 
> For example: `_getVisibleOptions()` seems to be called a lot when it could be called only when the text in the combobox change.

Unfortunately, from what I remember, this is because of the filtering logic.

**Comment by cc-ebay** [comment]
> I believe it's coming from there being too many options and it's probably lagging behind. I have seen that multi highlight thing before. 

Well, it is clearly a problem that should be fixed. 

>We had a fix where we were clearing the selected item, but it caused other issues.

In my option this is a hint that the logic is "overly complex"

> This has been a known issue for a while now. We can take a look. This bug is actually a bug with makeup-active descendant not with combobox itself.

Well, regardless, it is affecting the combobox and should be fixed.

**Comment by cc-ebay** [comment]
> > In general, the logic of the `ebay-combobox` seems overly complex and optimizable.
> > For example: `_getVisibleOptions()` seems to be called a lot when it could be called only when the text in the combobox change.
> 
> Unfortunately, from what I remember, this is because of the filtering logic.

I worked on a refactor version that does not need that and fixed #1771. I thought I had introduced some bugs but when I noticed some other quirks on `master` like the one described here and in #1783 I started questioning if this component may need a more in-depth refactoring.

**Comment by cc-ebay** [comment]
Update: I am able to reproduce consistently without changing the story with few items:
![combobox-bug-shortlist](https://user-images.githubusercontent.com/64445558/194429669-04b7b85a-7664-4a26-8e68-621aa1f5e077.gif)

**Comment by cc-ebay** [comment]
I was like: "How is possible I am the only one pointing out this problem and it is not a P1?"
Is this component even used on the site? From my investigation the answer may be no.

**Comment by agliga** [comment]
> I was like: "How is possible I am the only one pointing out this problem and it is not a P1?"
> Is this component even used on the site? From my investigation the answer may be no.

Its definitely not a p1. Its not blocking any use of the component normally and seems like an edge case.

**Comment by cc-ebay** [comment]
How do you define an edge case? Did you see https://github.com/eBay/ebayui-core/issues/1782#issuecomment-1270762860 ? It happens with a short list and I can consistently reproduce it.

**Comment by agliga** [comment]
so i just played with combobox for about 2 mins and was not able to reproduce it. 
it seems like there has to be a specific order of commands to input to cause that issue. 
Hence why its an edge case.

**Comment by cc-ebay** [comment]
Reproduction steps: 
1. Go to https://opensource.ebay.com/ebayui-core/?path=/story/form-input-ebay-combobox--floating-label
2. With mouse click on `v` to open the drop down
3. Select "Best Offer 2"
4. With mouse click on `v` to open the drop down
5. Select "Best Offer 3"
6. With mouse click on `v` to open the drop down
7. Press Arrow down

**Comment by agliga** [comment]
Okay, got it.

So from what it looks like, a possible fix would be to add `this.activeDescendant.reset();` before this line:
https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-combobox/component.js#L66
I tested it locally and it seems to be working. Chris, can you verify that this works for you? If so we can look to possibly include this next release.

**Comment by cc-ebay** [comment]
But how it is possible that 2 selections are going on at the same time?
Does not probably mean that the root cause is that there are 2 instances of `createLinear` in `makeup-active-descendant`? Should not the solution to either making sure that you create only one instance (maybe having that logic only in `onMount`) or having a clean out before the new instance is created?

**Comment by agliga** [comment]
So it is due to makeup-active-descendant. I believe part of the issue is the marko integration which requires us to call on destroy and then reinitialize it when a state changes. 
We can file an issue on makeup (which I was planning on doing), but it seems like this was a quick and easy solution which resolves this bug. 
https://github.com/makeup/makeup-js here is the repo

**Comment by cc-ebay** [comment]
I am not sure how it works. But I see a [`destroy` method](https://github.com/makeup/makeup-js/tree/master/packages/makeup-active-descendant#methods). Intuitively it feel like it need to be called before  another is build (calling `createLinear).

**Comment by cc-ebay** [comment]
I find awkward though that a library that modify the DOM is used with Marko.js. It would be clearer and mre efficient if marko does this kind of  work instead.

**Comment by ianmcburnie** [comment]
> It would be clearer and more efficient if marko does this kind of work instead.

Yes, that's part of our plans. A Marko specific version of Makeup.

**Comment by cc-ebay** [comment]
The problem is definitely that the instance of a previous `activeDescend` is still active when a new one is created. This is what I see after selecting and deselecting multiple times:
<img width="268" alt="Screen Shot 2022-10-07 at 1 14 11 PM" src="https://user-images.githubusercontent.com/64445558/194646169-212b15dc-d532-4990-ac83-f010cf0b1976.png">

Notice also the different shade in the selected items. The darker shade probably means that that option is selected more than once.
