### ISSUE TITLE
listbox-button: update to reflect DOM changes required for Skin update

### ISSUE THREAD

**Issue by ArtBlue** [eBay/ebayui-core#1786]
Because of skin updates needing the DOM changes, we need to update the js to make the proper text replacements.

Going from `<span class="btn__text"></span>`

to this:

`````html
<span class="btn__label">Color: </span>
<span class="btn__text">Yellow</span>

`````

**Comment by agliga** [comment]
I believe this will also require a makeup change since i think makeup is actually injecting the text into listbox (on skin side)
