### ISSUE TITLE
ebay-dialog: in IE when dialog opens up, The parent screen goes to the top

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#180]
In IE  when the dialog open up the background screen goes to the top instead of staying where it is.

before dialog opens
![image](https://user-images.githubusercontent.com/13157115/40084674-ca5abf00-584c-11e8-8dea-7933a8301646.png)

after dialog opens
![image](https://user-images.githubusercontent.com/13157115/40084698-d7d967da-584c-11e8-8442-f5ed859e847a.png)
 **expected**

![image](https://user-images.githubusercontent.com/13157115/40084732-f81cdeaa-584c-11e8-9de7-962c4158a03f.png)

**Comment by ianmcburnie** [comment]
Seems like a non-blocker if IE11 only, as it does not affect functionality.

**Comment by DylanPiercey** [comment]
This was a simple fix, just created a PR.
