### ISSUE TITLE
Menu : type="fake", button font-family and links font-family do not match

### ISSUE THREAD

**Issue by bhoomisatasiya** [eBay/ebayui-core#182]
ebay-Menu with type fake, has button and links combination, the font-family for button and links does not match, making the button color a little lighter.
<img width="1639" alt="screen shot 2018-05-16 at 7 41 19 am" src="https://user-images.githubusercontent.com/11545472/40124106-a2e872b0-58dc-11e8-8eaf-c55c329db527.png">
<img width="1630" alt="screen shot 2018-05-16 at 7 41 06 am" src="https://user-images.githubusercontent.com/11545472/40124107-a303c132-58dc-11e8-9eca-ca32de1ad5b6.png">

**Comment by yomed** [comment]
This is an existing issue being tracked in Skin https://github.com/eBay/skin/issues/83

**Comment by ianmcburnie** [comment]
We have an open question regarding setting Market Sans outside of the ebay-font loading mechanism:

https://github.com/eBay/skin/pull/195/files#r188684603

**Comment by yomed** [comment]
This was fixed in Skin for the menu case https://github.com/eBay/skin/issues/83
