### ISSUE TITLE
Combobox: depends on the wrapper to have a width, this is an issue when we have dynamic text length

### ISSUE THREAD

**Issue by bhoomisatasiya** [eBay/ebayui-core#184]
ebay-select takes the width of the parent wrapper, I think it should take the width of the label, 
- when expanded it should support reverse open,
- on our page I have to give the wrapper a min width, which has chances of breaking if the text is longer
and when the text is shorter, the arrow is too far from the label,  its a problem when we use borderless select

**Comment by ianmcburnie** [comment]
Closing as this in no longer valid. Combobox no longer depends on a wrapper width. 

Related PR: https://github.com/eBay/skin/pull/360
