### ISSUE TITLE
ebay-listbox-button form  button CSS overrides aria-invalid red border

### ISSUE THREAD

**Issue by triptych** [eBay/ebayui-core#1849]
# Bug Report

## Description

When using ebay-listbox-button and the variant="form" attribute, the `listbox-button--form` class border color overrides the `aria-invalid="true"` state so that the element doesn't show up with a red border:
<img width="437" alt="Screen Shot 2023-02-06 at 7 19 00 PM" src="https://user-images.githubusercontent.com/8691/217306016-b8e01b33-30a3-4d82-b885-d57cfe77140f.png">

For example: with the variant:
<img width="293" alt="Screen Shot 2023-02-06 at 7 21 28 PM" src="https://user-images.githubusercontent.com/8691/217306173-9d7e7f01-37fc-42a7-bc02-a0a6e0f37354.png">

Without the variant: ( disabled the css rule in inspector )  
<img width="260" alt="Screen Shot 2023-02-06 at 7 22 17 PM" src="https://user-images.githubusercontent.com/8691/217306700-e07f5330-de15-4acc-a791-5efd94ebab98.png">

**Comment by agliga** [comment]
Thanks for the bug Andrew. 
I will close this and open one on skin.
