### ISSUE TITLE
ebay-dialog: Clicking within dialog whitespace closes it?

### ISSUE THREAD

**Issue by tcorley** [eBay/ebayui-core#188]
I'm not sure if this is part of the pattern, but tapping/clicking within the dialog that's not content causes it to close.

**Comment by hramakumar** [comment]
This happens only in the white space at the bottom of the content.

**Comment by tcorley** [comment]
Here's a screen grab from clicking in the margins
https://www.useloom.com/share/b17b47f1f1d040b39b3a1df7331a13cf

**Comment by hramakumar** [comment]
oh ok. I see. so any section of the page outside the content borders
