### ISSUE TITLE
ebay-confirm-dialog: onOpen arguments are wrong

### ISSUE THREAD

**Issue by darkwebdev** [eBay/ebayui-core#1887]
# Bug Report

## Description
Readme says that `onOpen` callback should use `{ originalEvent }` as argument, but when I click/keypress in storybook I get this: `on-open: {name: "on-open", args: undefined}`

Not sure if that's a bug or readme mistake.

**Comment by saiponnada** [comment]
Not an issue. The events listed above use `{ originalEvent }` as argument as per documentation.

**Comment by darkwebdev** [comment]
I'm not saying that code is wrong, maybe storybook documentation is not updated. I don't see any properties of `OriginalEvent` here:

<img width="1005" alt="image" src="https://github.com/eBay/ebayui-core/assets/2737310/10d5cedf-09c3-4763-91ea-c1c9a0a1c18a">
