### ISSUE TITLE
ebay-drawer-dialog: callbacks use wrong arguments

### ISSUE THREAD

**Issue by darkwebdev** [eBay/ebayui-core#1890]
# Bug Report

## Description
Documentation reads that:
- `onOpen/onClose/onExpand/onCollapse` callbacks should use `{ originalEvent }` as argument

but in storybook I get something else:
<img width="576" alt="image" src="https://user-images.githubusercontent.com/2737310/233406305-655b4507-8b17-418c-a0ca-d9b856cfd487.png">

**Comment by saiponnada** [comment]
Not an issue. The events listed above use `{ originalEvent }` as argument

**Comment by darkwebdev** [comment]
If you look at the labels of this issue you can notice an aspect called `documentation`. It's a hint that code and documentation have discrepancies. If you look at the screenshot you can see that there are two arguments for on-open callback: `0: ComponentClass and 1: ComponentClass`. Which of them is `OriginalEvent` and what is another one and why does it look different from other components (maybe there's a bug somewhere, hopefully only in documentation)?

If I'm spending my time on creating an issue please try to understand the reason behind it and don't just close it. If you have questions go ahead and ask me. I'm going to create more issues regarding similar problems with other components and I don't want to waste my time.

Thank you in advance.

**Comment by saiponnada** [comment]
ebay-drawer-dialog will be **deprecated** and removed from the ebay UI core in next release.

**Comment by ianmcburnie** [comment]
Hmm, not sure why this is closed. It doesn't sit well with me that we are keeping a known documentation discrepancy around. I can understand @darkwebdev 's frustration here. This should be a quick fix unless I'm missing something?
