### ISSUE TITLE
ebay-fake-menu-button: callbacks use wrong arguments

### ISSUE THREAD

**Issue by darkwebdev** [eBay/ebayui-core#1892]
# Bug Report

## Description
Documentation reads that:
- ~`onSelect/onKeydown` callbacks should use `{ el, index, checked }` as argument~ - fixed, thanks!
- ~`onExpand/onCollapse/onMouseDown` shouldn't pass any arguments~ - fixed, thanks!

but in storybook I see:
- `on-select: {el: HTMLAnchorElement, originalEvent: MouseEvent, index: 1}`
- `on-collapse: {el: undefined, originalEvent: undefined, index: undefined}`
- `on-expand: {el: undefined, originalEvent: undefined, index: undefined}`
- `on-mousedown: {el: undefined, originalEvent: undefined, index: undefined}`

I've failed to trigger `onKeydown` event (should it be triggered on menu button keyDown or on menu item keyDown?)
One more mistake: storybook reads `onMousedown`: `Triggered on mouse down on menu item`, but in reality it's also triggered on menu button click.

**Comment by darkwebdev** [comment]
I'm afraid the problem here is not with documentation, but with the code: when I click on the menu button most of the arguments are undefined:
<img width="1244" alt="image" src="https://github.com/eBay/ebayui-core/assets/2737310/a47532c1-a7c3-4121-a80a-1a4d99c23029">

**Comment by saiponnada** [comment]
@agliga  @darkwebdev 

Okay I have reviewed the code again(apologies for quick review & fix) and noticed that previous changes were pretty accurate and looks like we need to roll back documentation.  Mainly there are two types of events here...

DOM events
- `on-select` event is a component event that triggers a dom `select` event and works as expected.
-  `on-keydown` event is a dom event and works as expected. It might not be visible on storybook but using keyboard, try pressing enter or spacebar on the menu button and that triggers the event. @agliga If storybook defines an event is it mandatory to output every event in actions tab?

Hence below statement is not true.
> I've failed to trigger onKeydown event (should it be triggered on menu button keyDown or on menu item keyDown?)

Component events
- `onExpand/onCollapse/onMouseDown` shouldn't pass any arguments and docs need to be rolled back to previous state. Currently we just emit these events with undefined event object across the storybook.

```js
handleExpand() {
    this.emitComponentEvent({ eventType: "expand" });
},
emitComponentEvent({ eventType, el, originalEvent, index }) {
    const eventObj = {
            el,
            originalEvent,
            index,
        };
        this.emit(`${eventType}`, eventObj);
},
```
Should we really change handleExpand to show like below image? It can be done if we say
```
this.emit("expand");
```
is it necessary? 
<img width="498" alt="image" src="https://github.com/eBay/ebayui-core/assets/6342519/d874e674-e240-43bd-8d0a-477d8c455654">

**Comment by agliga** [comment]
We can also remove `originalEvent` from dialogs as part of this change. 
https://github.com/eBay/ebayui-core/issues/1890

**Comment by agliga** [comment]
> @agliga @darkwebdev
> 
> Okay I have reviewed the code again(apologies for quick review & fix) and noticed that previous changes were pretty accurate and looks like we need to roll back documentation. Mainly there are two types of events here...
> 
> DOM events
> 
> * `on-select` event is a component event that triggers a dom `select` event and works as expected.
> * `on-keydown` event is a dom event and works as expected. It might not be visible on storybook but using keyboard, try pressing enter or spacebar on the menu button and that triggers the event. @agliga If storybook defines an event is it mandatory to output every event in actions tab?
> 
> Hence below statement is not true.
> 
> > I've failed to trigger onKeydown event (should it be triggered on menu button keyDown or on menu item keyDown?)
> 
> Component events
> 
> * `onExpand/onCollapse/onMouseDown` shouldn't pass any arguments and docs need to be rolled back to previous state. Currently we just emit these events with undefined event object across the storybook.
> 
> ```js
> handleExpand() {
>     this.emitComponentEvent({ eventType: "expand" });
> },
> emitComponentEvent({ eventType, el, originalEvent, index }) {
>     const eventObj = {
>             el,
>             originalEvent,
>             index,
>         };
>         this.emit(`${eventType}`, eventObj);
> },
> ```
> 
> Should we really change handleExpand to show like below image? It can be done if we say
> 
> ```
> this.emit("expand");
> ```
> 
> is it necessary? <img alt="image" width="498" src="https://user-images.githubusercontent.com/6342519/261474320-d874e674-e240-43bd-8d0a-477d8c455654.png">

So we document the event args, if they're not present or undefined, they are not being set. Even if we emit an event we don't have to define arguments for them. 
If they're undefined we are setting the key but not the value. It could also be related to storybook.
