### ISSUE TITLE
Provide options to add Localization (i18N) support for the underlying high charts module

### ISSUE THREAD

**Issue by dsathyakumar** [eBay/ebayui-core#1903]
# Feature Request

## Description
Provide options to add Localization (i18N) support for the underlying high charts module

## Context
In components like `<ebay-line-chart/>`, the high charts module is used. 
But right now `<ebay-line-chart/>` doesnt provide a way to pass `lang` attrs via the `window.Highcharts.setOptions` method.
This feature request is to add opts to provide i18N support for the module.

## Screenshots
It would render something similar to
![image](https://github.com/eBay/ebayui-core/assets/5446493/f603abb5-a090-41f0-8680-3b0939a7ef02)

## References
https://api.highcharts.com/highcharts/lang

**Comment by agliga** [comment]
You should be able to call `this.getComponent('chart').chartRef.setOptions`. If that works, that should be the solution to this and I will close this issue.

**Comment by agliga** [comment]
Closing for now
