### ISSUE TITLE
ebay-menu/filter-menu: emit keydown event when arrow keys are pressed.

### ISSUE THREAD

**Issue by cynthiahhc** [eBay/ebayui-core#1916]
# Feature Request

Add emit keydown events for arrow keys for `ebay-menu` and `ebay-filter-menu`.

## Description

We have a design which we added 2 `ebay-menu`s or `ebay-filter-menu`s inside and expand button, and the user would like to navigate from one menu to another by using the down/up arrow keys.

## Context

Currently, only the keydown event only fires when `escape`, `enter` or `space` keys are pressed down.
https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-menu/component.js#L44
https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-filter-menu/component.js#L26

**Comment by agliga** [comment]
Closing as dup
