### ISSUE TITLE
ebay-textbox: disabled styles are being overwritten by invalid styles

### ISSUE THREAD

**Issue by BhavinPatel04** [eBay/ebayui-core#1942]
# Bug Report
The disabled styles get overwritten by invalid styles and the input doesn't look disabled.

## Description
When we have a use case where we need to disable the invalid input temporarily till a particular task is complete and we try to disable the invalid input, the input does not look disabled but it's actually disabled.

This issue cannot be reproduced if you use a standard `<input aria-invalid=true disabled=true>...</input>`

## Workaround
Make input valid and disable it.

## Screenshots
<img width="1595" alt="image" src="https://github.com/eBay/ebayui-core/assets/6559211/d42dea46-9945-4eaf-8145-f085bc7a2acf">

### Standard input box
<img width="1339" alt="image" src="https://github.com/eBay/ebayui-core/assets/6559211/fd83de4e-9973-4cb4-800d-88dad284609b">

**Comment by agliga** [comment]
This is not a valid usecase or combination. 
We do not support disabled invalid inputs. 

Remove the invalid if you want to disable it.
