### ISSUE TITLE
Allow badges editable

### ISSUE THREAD

**Issue by AlexwithM2M** [eBay/ebayui-core#1995]
In the current component, it shows 99+ but for Messages, we need to show 10+ only.
The dev team not able to make edit of it and we have to keep showing the 99+, is this a easy fix. Can we get this asap cause the badge itself is existing and all we need is to have one other component to show "10+". Thanks 
<img width="268" alt="10+" src="https://github.com/eBay/ebayui-core/assets/146994220/88d17524-c6e1-4bec-9a12-7a727fdc9584">

**Comment by agliga** [comment]
We wont be doing this for now.
