### ISSUE TITLE
Radio: clicking corner generates an event with value: "undefined" - option is not selected

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#200]
## eBayUI Version: 0.5.0-0

when you click near the borders of the radio button. the click does not work.

![image](https://user-images.githubusercontent.com/13157115/40517486-68eee97e-5f6a-11e8-9b5a-ea9ebb22e21c.png)

video: https://www.useloom.com/share/0af190c2fde1434dbac2515ce5de26ad

**Comment by ianmcburnie** [comment]
This should be resolve when we update to latest skin patch release.

**Comment by hramakumar** [comment]
@ianmcburnie I already verified this issue while testing 0.5.0-2
This can be closed

**Comment by ianmcburnie** [comment]
Thanks!
