### ISSUE TITLE
Icon: SPA support for ebay-stamper

### ISSUE THREAD

**Issue by DylanPiercey** [eBay/ebayui-core#202]
# Feature Request

## Description
Currently the `ebay-stamper` component does not work properly when used in a SPA.

## Potential Solutions / Notes
* Expose the `ebay-stamper` and allow teams to manually specify which svg's to inline.
* Setup all symbols in an external svg on a cdn.
* Potentially expose the logic for getting the icons used in a page.

**Comment by ianmcburnie** [comment]
Fix will be available in 0.6.0.
