### ISSUE TITLE
ebay-fake-menu: badge-number/badge-aria-label not working

### ISSUE THREAD

**Issue by darkwebdev** [eBay/ebayui-core#2024]
# Bug Report

## Description

Both `badge-number` and `badge-aria-label` are ignored.

## Screenshots

<img width="926" alt="image" src="https://github.com/eBay/ebayui-core/assets/2737310/9b2a95f2-e81a-4406-b61b-a098539a2cf3">
<img width="529" alt="image" src="https://github.com/eBay/ebayui-core/assets/2737310/89915af0-7532-4a14-b8ac-d48926b9a962">

**Comment by agliga** [comment]
Not an issue. This works fine.
This is due to storybook how it picks up arguments and doesnt transform them
Locally these should be picked up
