### ISSUE TITLE
ebay-select: does not handle text size manipulation via bookmarklet to WCAG standards

### ISSUE THREAD

**Issue by lorenzolevy** [eBay/ebayui-core#2027]
# Bug Report

## Description

Currently in the storybook page when applying a common accessibility bookmarklet snippet, the floating label used in `ebay-select` is intersecting/overlapping with the selected option.

**As a WCAG requirement** 

[WCAG Link](https://www.w3.org/WAI/WCAG21/Understanding/text-spacing)

In content implemented using markup languages that support the following [text](https://www.w3.org/WAI/WCAG21/Understanding/text-spacing#dfn-text) [style properties](https://www.w3.org/WAI/WCAG21/Understanding/text-spacing#dfn-style-property), no loss of content or functionality occurs by setting all of the following and by changing no other style property:
```
Line height (line spacing) to at least 1.5 times the font size;
Spacing following paragraphs to at least 2 times the font size;
Letter spacing (tracking) to at least 0.12 times the font size;
Word spacing to at least 0.16 times the font size.
```
JS snippet to apply these alterations: 

```
(function(){var d=document,id='phltsbkmklt',el=d.getElementById(id),f=d.querySelectorAll('iframe'),i=0,l=f.length;if(el){function removeFromShadows(root){for(var el of root.querySelectorAll('*')){if(el.shadowRoot){el.shadowRoot.getElementById(id).remove();removeFromShadows(el.shadowRoot);}}}el.remove();if(l){for(i=0;i<l;i++){try{f[i].contentWindow.document.getElementById(id).remove();removeFromShadows(f[i].contentWindow.document);}catch(e){console.log(e)}}}removeFromShadows(d);}else{s=d.createElement('style');s.id=id;s.appendChild(d.createTextNode('*{line-height:1.5 !important;letter-spacing:0.12em !important;word-spacing:0.16em !important;}p{margin-bottom:2em !important;}'));function applyToShadows(root){for(var el of root.querySelectorAll('*')){if(el.shadowRoot){el.shadowRoot.appendChild(s.cloneNode(true));applyToShadows(el.shadowRoot);}}}d.getElementsByTagName('head')[0].appendChild(s);for(i=0;i<l;i++){try{f[i].contentWindow.document.getElementsByTagName('head')[0].appendChild(s.cloneNode(true));applyToShadows(f[i].contentWindow.document);}catch(e){console.log(e)}}applyToShadows(d);}})()
```

Reproduction Steps:
1. Go to the [floating label storybook](https://opensource.ebay.com/ebayui-core/?path=/story/form-input-ebay-select--floating&args=options[1].text:123;options[1].value:123)
2. Run the JS snippet from above in the web console
3. Select an option, see floating label is cutoff by the option text after animating up.

## Workaround

N/A
## Screenshots

<img width="372" alt="image" src="https://github.com/eBay/ebayui-core/assets/44483499/f0225f94-3f28-4942-9bf6-4f9af4bf0c42">

**Comment by agliga** [comment]
Closing, opening issue on skin side.
