### ISSUE TITLE
Float label support for date-textbox

### ISSUE THREAD

**Issue by fer-de-s-ebay** [eBay/ebayui-core#2035]
# Feature Request
Float label support for date-textbox

## Description
The new ads dashboard design needs float labels for the `ebay-date-textbox` component, attached screenshot to show the use of `start` and `end` text as float labels in the component

## Context
New ads dashboard Figma design: https://www.figma.com/file/Lw6GFDvYTKRKyoSjLzmWdQ/Ads-Dashboard-2.0---April2024?node-id=6038%3A356632&mode=dev

## Screenshots

![image](https://github.com/eBay/ebayui-core/assets/153042539/1d078ff2-c82b-48cd-906d-f5f3315b78b1)

**Comment by randybascue** [comment]
The title can float like other text fields
