### ISSUE TITLE
BUG: Select: checked icon for selected item per page option is cut on the bottom in IE 11

### ISSUE THREAD

**Issue by bhoomisatasiya** [eBay/ebayui-core#204]
# Bug Report
Checked icon for selected item per page option is cut on the bottom in IE.

## Workaround
Workaround would be to override locally, but that is not desired.

## Screenshots
![_thumb_1171641](https://user-images.githubusercontent.com/11545472/40680358-b33176fe-633a-11e8-88d3-6a7b39b28756.png)

![image 2](https://user-images.githubusercontent.com/11545472/40686448-2ae22994-634c-11e8-8875-28d3a5e09041.png)

**Comment by seangates** [comment]
@bhoomisatasiya Can you at least put the version of eBayUI in there? Thanks!

**Comment by seangates** [comment]
@bhoomisatasiya Also, which version of IE?

**Comment by bhoomisatasiya** [comment]
ebayui-select  "version": "0.5.0-0",
IE 11

**Comment by msendlakowski** [comment]
@seangates looks like a skin issue, can you take a look

**Comment by seangates** [comment]
Yes, this is a Skin issue. I've seen it. Can you migrate this over there?

**Comment by msendlakowski** [comment]
Moved to Skin: https://github.com/eBay/skin/issues/334
