### ISSUE TITLE
Pagination: buttons not centered vertically

### ISSUE THREAD

**Issue by BryceEWatson** [eBay/ebayui-core#205]
# Bug Report

## Description
The buttons are not being vertically centered, and there is padding added to the previous/next buttons which makes it obvious. See screenshot below.

**Update** This seems to be an issue with skin when ds6 + ds4 styles are combined. I believe a fix would be to add `align-items: center` to the `.pagination` class in https://github.com/eBay/skin/blob/master/docs/archive/v3.0/static/ds4/skin-full.css#L1943

Tested in:
- Safari Version 11.1 (11605.1.33.1.4)
- Chrome Version 67.0.3396.62 (Official Build) (64-bit)

## Workaround 1:
Removing the extra padding around the previous/next buttons reduces the height and aligns the buttons.
Removing the below padding reduces the height and aligns the items.
```
.pagination__next, .pagination__previous {
    color: #555555;
    padding: 8px 8px 8px 0;
}
```

## Workaround 2:
Adding the style: `align-items: center` to the parent wrapper `<nav class="pagination">` fixes this issue.

## Screenshots
![image](https://user-images.githubusercontent.com/1322843/40729157-a85034e0-63e0-11e8-848d-68219e8bb26f.png)

**Comment by seangates** [comment]
@BryceEWatson Can you add which browsers you've tested this in?

**Comment by ianmcburnie** [comment]
Bryce made the fix in skin. When we update to skin 5.0.2 this issue should be resolved.
