### ISSUE TITLE
Carousel: causes entire page freeze in IE 11

### ISSUE THREAD

**Issue by bhoomisatasiya** [eBay/ebayui-core#207]
# Bug Report
V0.5.0-2 ebay-carousel is freezing in IE 
## Description
ebay-carousel is freezing the whole page after couple of actions/clicks on the carousel. Not able to do any actions. scorll, click on the page. only page refresh restores the page. I am not seeing any errors in the console either.

**Comment by senthilp** [comment]
@bhoomisatasiya Which version of IE is this?

**Comment by bhoomisatasiya** [comment]
Its IE 11.
<img width="379" alt="screen shot 2018-05-31 at 5 12 28 pm" src="https://user-images.githubusercontent.com/11545472/40814582-d7fab56a-64f5-11e8-84db-2ec95eec0c3c.png">

**Comment by bhoomisatasiya** [comment]
![carousel-ie-issue-2](https://user-images.githubusercontent.com/11545472/40814636-2eff7c60-64f6-11e8-9f56-638d4c3aecf8.gif)

**Comment by ianmcburnie** [comment]
Not an issue. The issue was with app page.
