### ISSUE TITLE
Select: attributes pass through

### ISSUE THREAD

**Issue by oxala** [eBay/ebayui-core#208]
Hey guys,

I'm trying to use `ebay-select` component on my page and stumbled upon some limitations.

There are cases, when i need to pass `aria-required` or `aria-invalid`, etc. And i expect such attributes to be passed-through to the `select` element that component produces. But in reality it's being appended to the root element instead.

As far as i believe, the only attribute to be applied to the root element of produced component should be `class`. Everything else should be applied to the 'control' element.

**Comment by ianmcburnie** [comment]
@seangates please can you take a look? We should try and get this into 0.5.0 release.

**Comment by seangates** [comment]
@ianmcburnie Yes, I asked Gleb to create the issue. He and I discussed what it would take to make this usable for him. 👍
