### ISSUE TITLE
Carousel component animation crashes after changing index multiple times

### ISSUE THREAD

**Issue by fer-de-s-ebay** [eBay/ebayui-core#2085]
# Bug Report

## eBayUI Version: x.x.x
13
## Description

I discovered this issue on ebay-ui carousel: The carousel stops working after changing the item to be shown using the index property. Could you please help me to fix this issue?

## Screenshots

[](https://github.com/eBay/ebayui-core/assets/153042539/1b0da15c-5fde-4c5d-91e7-240a2176d21b)

**Comment by agliga** [comment]
Closing for now, please reopen if you have more information to add.
