### ISSUE TITLE
education-notice: update visual treatment

### ISSUE THREAD

**Issue by randybascue** [eBay/ebayui-core#2088]
# Feature Request
Update the education notice visual treatment to differentiate further from the alert notice. Increase sizing and spacing to make it more prominent for feature and recommendation callouts. 

## Description
Education notices are supplemental, contextual messages that educate users about programs, features, and opportunities.
[Figma branch](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/branch/rSJeczAN0rQ0jA41TOSJrY/eBay-Design-System?type=design&node-id=90732-97759&mode=design&t=CmHqFcVODBrP7uxl-11)

## Context
1. Seller hub
2. Listings
3. Campaign management
4. Ads
5. Coupon creation

## Screenshots
![image](https://github.com/eBay/ebayui-core/assets/35155833/1d7bdaef-80c9-4c3e-bdc7-33c34b5f5074)
![image](https://github.com/eBay/ebayui-core/assets/35155833/5e1cd9a8-b1c1-4ccd-8317-7dc10d4f1c86)

**Comment by agliga** [comment]
Can we file this on skin? Seems like a CSS issue.

**Comment by randybascue** [comment]
> Can we file this on skin? Seems like a CSS issue.

Yes. That's where it was suppose to be. That's on me
