### ISSUE TITLE
ebay-listbox-button - Add support for suffix label

### ISSUE THREAD

**Issue by agunaganti** [eBay/ebayui-core#2103]
# Feature Request

## Description

ebay-listbox  - Show Urgency signal only in selected state, but not in any of the dropdown list.
so that Signal will be shown always to user - irrespective of dropdown selection.

## Screenshots

<img width="379" alt="Screenshot 2024-02-21 at 7 02 15 PM" src="https://github.com/eBay/ebayui-core/assets/110565292/d9dea96a-a15c-4ed8-9860-ac49fbed61af">

**Comment by agliga** [comment]
Closing this issue for now, we are not planning on doing this.
