### ISSUE TITLE
ebay-textbox: display null when the value is empty for multiline

### ISSUE THREAD

**Issue by MaiDeveloper** [eBay/ebayui-core#2108]
# Bug Report

## Description

The following display `null` on initial render.
```
<ebay-textbox value="" multiline /> 
<ebay-textbox multiline />
```

## Screenshots

<img width="222" alt="Screenshot 2024-03-04 at 2 52 16 PM" src="https://github.com/eBay/ebayui-core/assets/48327829/6e95a4df-a392-4e52-a232-e5eba093381e">

**Comment by LuLaValva** [comment]
- Resolved by https://github.com/marko-js/marko/pull/2145
