### ISSUE TITLE
ebay-listbox-button: `borderless` doesn't render properly

### ISSUE THREAD

**Issue by darkwebdev** [eBay/ebayui-core#2126]
# Bug Report

## eBayUI Version: latest
https://opensource.ebay.com/ebayui-core/?path=/story/buttons-ebay-listbox-button--default&args=borderless:!true

## Description

When using `borderless` option button still shows border.

## Screenshots
How it looks like now:
<img width="917" alt="image" src="https://github.com/eBay/ebayui-core/assets/2737310/eb964108-bdee-44d9-b556-2c56f8064ab7">

How it should be:
<img width="922" alt="image" src="https://github.com/eBay/ebayui-core/assets/2737310/4ed953f6-025b-49a8-ae0b-2fbfada88bf2">

## How to fix it
Don't use `btn-form` together with `btn-borderless`, they are multually-exclusive.

**Comment by agliga** [comment]
Yes, they are not supposed to be used together
Is this requesting a docs change or did you want to use both together?

**Comment by darkwebdev** [comment]
@agliga `borderless` in one of the `ebay-listbox-button` properties, but it doesn't work.
