### ISSUE TITLE
Need option to change current date in ebay-calendar component.

### ISSUE THREAD

**Issue by baburammy** [eBay/ebayui-core#2144]
# Feature Request
Currently ebay-calendar component supports to show future dates and enable/disable dates and select some dates. But It is not supporting to overriding current date.
## Description
Provide option to override current date.

## Context
Let's say we want to show appointment of store which is in NewYork and someone looking at in SanJose. Requirement is to show Appointments based on the NewYork date and time. But Calendar component figuring out current date based on the browser's timezone.

## Screenshots
<img width="508" alt="image" src="https://github.com/eBay/ebayui-core/assets/286382/dbce24b8-4b7b-4aca-9b1b-3a9032defd45">

**Comment by agliga** [comment]
This is fixed in makeup-floating-label 0.3.3
