### ISSUE TITLE
Menu: label can't be an icon; chevron toggle can't be hidden

### ISSUE THREAD

**Issue by trg** [eBay/ebayui-core#217]
# Feature Request

## Description

Currently, the ebay-menu does not let the developer customize the icon that is to the right of the label.  With the introduction of ebay-icon, I would like to be able to choose contextually relevant icons for the dropdown menu open/closed states.

**Comment by ianmcburnie** [comment]
Yes, good idea, we could probably add new attributes to the menu root tag:

* icon-collapsed
* icon-expanded

The value would be passed through to the <ebay-icon> tag internally.

**Comment by ianmcburnie** [comment]
To avoid abuse, or perhaps people getting a little *too* creative, I'm thinking of limiting this to a subset of our icons. 

@trg Which icons did you have in mind for your use case?

This also has a dependency on Skin, as we need to add SVG support to the DS6 expand button. Not only that, but because skin currently just flips the icon 180 degrees, we probably need to refactor the markup to allow for two symbols rather than just one.

**Comment by trg** [comment]
^ Synced up on Slack.

**Comment by seangates** [comment]
@yomed @trg If we could post the icons here (for documentation and transparency), that would be helpful for the rest of us. 😉

**Comment by yomed** [comment]
Here's a screenshot showing the DS6 overflow menu:
![image](https://user-images.githubusercontent.com/3595986/42462715-e2a1435e-8358-11e8-9755-9078e48c5785.png)

Given this use case, I believe we should 1) expose something like `no-default-icon` to hide the default chevon icon, and 2) allow arbitrary HTML for the label, which would allow use of a single `<ebay-icon>`.

**Comment by seangates** [comment]
Thanks, @yomed.

**Comment by yomed** [comment]
@senthilp This would be HTML through Marko like:
```marko
<ebay-menu>
    <ebay-menu-label>
        <ebay-icon type="inline" name="settings"/>
    </ebay-menu-label>
    <ebay-menu-item>item 1</ebay-menu-item>
    <ebay-menu-item>item 2</ebay-menu-item>
    <ebay-menu-item>item 3</ebay-menu-item>
</ebay-menu>
```

**Comment by senthilp** [comment]
Got it, this works and matches our design. I earlier misunderstood that you are suggesting to use the `label` attribute on `<ebay-menu>` for passing in HTML.

**Comment by ianmcburnie** [comment]
Could this be adapted to support two different icons for collapsed and expanded state?

**Comment by yomed** [comment]
@ianmcburnie We can do that, but it wouldn't be for this use case. That would basically entail applying this same behavior to allow arbitrary HTML for the icon portion. Just to note, if we allow users to just pass in the icon name, then the menu would have to include all possible icons that might be used.

**Comment by ianmcburnie** [comment]
We don't want to allow all icons. Just a subset.

**Comment by yomed** [comment]
There are 2 separate issues here: 
1) This issue was created for having an icon as a label, and having an option to remove the default chevron toggle.
2) Your comments reflected the possibility of customizing the default chevron toggle.

For both of these cases -- if you want to only allow certain icons, you need to include all icons in that set on the page. So if our subset is 5 icons, then every user of `<ebay-menu>` will have to include all those icons in the page unnecessarily, though there could be some magic to fix this (@DylanPiercey correct me if I'm wrong).

That's why I am allowing arbitrary HTML, especially for this first issue. It doesn't seem too grievous to allow HTML in the label, just as we allow HTML in most tags.

**Comment by ianmcburnie** [comment]
Yep, I'm trying to understand how both of those issues could be solved with arbitrary HTML. I want to make sure we can solve the 2nd issue before we bake in the 1st. It's still not clear to me how we would handle two states. Are you proposing something like this:

```html
<ebay-menu>
    <ebay-menu-label-collapsed>
        <ebay-icon type="inline" name="x"/>
    </ebay-menu-label-collapsed>
    <ebay-menu-label-expanded>
        <ebay-icon type="inline" name="y"/>
    </ebay-menu-label-expanded>
    <ebay-menu-item>item 1</ebay-menu-item>
    <ebay-menu-item>item 2</ebay-menu-item>
    <ebay-menu-item>item 3</ebay-menu-item>
</ebay-menu>
```

**Comment by yomed** [comment]
Yeah, it would be something like that for the 2nd issue. I don't see why we need to handle the 2nd issue now, since it seems we don't have an actual use case for it.

**Comment by ianmcburnie** [comment]
We don't need to handle it right now. But I like to design things, or at least consider things, with the future in mind. Especially when it comes to public APIs like this and Skin.

**Comment by ianmcburnie** [comment]
From a user point of view, setting an attribute is easiest, but yes it comes at a cost on the performance side like you say. I'd like us to investigate whether we can lazy load those icons in some manner.

**Comment by yomed** [comment]
I think that would be overcomplicating things, because these are fundamentally different issues. 

Skin allows users to put any icon they want into buttons -- so why not expand buttons as well? 

The chevron toggle itself is a fundamental part of the menu design, so I agree we should restrict those customizations more closely. But that's not really related to the first issue, except that they both involve icons in some way.

**Comment by ianmcburnie** [comment]
So I guess here are the options on the table:

1A Arbitrary HTML handling the use case only
```html
<ebay-menu>
    <ebay-menu-label>
        <ebay-icon type="inline" name="settings" accessibility-text="Settings"/>
    </ebay-menu-label>
    <ebay-menu-item>item 1</ebay-menu-item>
    <ebay-menu-item>item 2</ebay-menu-item>
    <ebay-menu-item>item 3</ebay-menu-item>
</ebay-menu>
```

1B Arbitrary HTML handling future/potential use case

```html
<ebay-menu>
    <ebay-menu-label>
        <ebay-icon type="inline" name="settings" accessibility-text="Settings"/>
    </ebay-menu-label>
    <ebay-menu-label-expanded>
        <ebay-icon type="inline" name="settings-alt" accessibility-text="Settings"/>
    </ebay-menu-label-expanded>
    <ebay-menu-item>item 1</ebay-menu-item>
    <ebay-menu-item>item 2</ebay-menu-item>
    <ebay-menu-item>item 3</ebay-menu-item>
</ebay-menu>
```

NOTE: `settings-alt` icon does not exist. It is a theoretical alternative for the expanded state. DS4 had some different states for icons (e.g. `notifications-null`), but the concept has not been carried over into DS6.

2A Attribute handling the single use case only:

```html
<ebay-menu icon="settings" accessibility-icon-text="Settings">
    <ebay-menu-item>item 1</ebay-menu-item>
    <ebay-menu-item>item 2</ebay-menu-item>
    <ebay-menu-item>item 3</ebay-menu-item>
</ebay-menu>
```

Note: the value of icon can be `default`, `settings` or `hamburger`. This would mean menu carrying an additional SVG payload. If we want to increase the list, we increase the payload.

2B Attribute handling the potential/future use case:

```html
<ebay-menu icon="settings" icon-expanded="settings-alt" accessibility-icon-text="Settings">
    <ebay-menu-item>item 1</ebay-menu-item>
    <ebay-menu-item>item 2</ebay-menu-item>
    <ebay-menu-item>item 3</ebay-menu-item>
</ebay-menu>
```

Again, `settings-alt` is a theoretical icon in DS6, for a "on/expanded" state.

--

Given that the DS6 icon set right now doesn't really offer a lot of candidates for the potential "expanded" icon state use-case, but *does* offer a lot of candidates for a single icon state (e.g. hamburger, settings, cart, notifications) I think it would be fine to go with option 1, the arbitrary HTML. Even though I do prefer the simplicity of an attribute, I think the arbitrary HTML offers up more flexibility.

**Comment by ianmcburnie** [comment]
Actually, @yomed. See my 1st comment right at the top. Couldn't we pass through the attribute name to <ebay-icon> internally? So a dev never has to manually add the ebay-icon tag, but we use it under the hood. I might be missing something though. Thoughts?

**Comment by yomed** [comment]
I have this working in Marko v3 on https://github.com/eBay/ebayui-core/tree/217-menu-icon-label
Unfortunately there are some issues in Marko v4 in preserving transcluded content on client render. The team is aware of the issues: https://github.com/marko-js/marko/issues/912

I have not yet been able to figure out any workaround for this specific case.

**Comment by trg** [comment]
@yomad Is it accurate that this component does not work with Marko 4?

**Comment by yomed** [comment]
@trg It does work in v4 -- we ended up using some workarounds. The workaround is only needed when it is not inside another component, noted here: https://github.com/eBay/ebayui-core/pull/273/files#diff-e9d5842ff3425e2177264650b9495759R1

There are some minor UI issues that are still pending fixes, here:
https://github.com/eBay/skin/issues/261
