### ISSUE TITLE
ebay-listbox-button keyboard selection is scrolling

### ISSUE THREAD

**Issue by azoreG** [eBay/ebayui-core#2183]
# Bug Report

## Description
 I’m noticing in ebay-listbox-button component, whenever I change the options with the keyboard, the scrollbar is moving

**Comment by agliga** [comment]
Can you provide more information please?
This is actually a feature. When scrolling up and down, the scrollbar should move to keep the currently selected listbox option into view. 


![Image](https://github.com/eBay/ebayui-core/assets/1755269/3b911ee9-0ac6-4c59-afb1-66b6121dd3cb)

**Comment by agliga** [comment]
Closing for now, please reopen with more information if needed.
