### ISSUE TITLE
DS Component: Data Table

### ISSUE THREAD

**Issue by namtheho** [eBay/ebayui-core#2185]
The Data Table component is designed to spec and is ready for code development:

**Resources**
* [Design File](https://www.figma.com/design/jFbAR0o364WhsjELfxl2SI/Playbook-2.0-%2F-Components?node-id=207-124816)
* [Project Brief](https://docs.google.com/document/d/11tSSVs2aD0CtfmEP7wRx27lVUJ2KWRrkBdUpdZ2fbpA/edit#heading=h.859l5crh4sv0)

**Lead Designer:** [Anderson, Wesley](https://jirap.corp.ebay.com/secure/ViewProfile.jspa?name=weanderson)

**Comment by namtheho** [comment]
This relates to — https://github.com/eBay/skin/issues/1900

**Comment by agliga** [comment]
https://github.com/eBay/ebayui-core/issues/2234 duplicate
