### ISSUE TITLE
Menu: Support "priority" attribute

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/ebayui-core#219]
# Feature Request

## Description
Make ebay-menu support `priority` attribute similar to how ebay-button has the priority attribute.

## Context
To support cases where a `ebay-button` (priority="primary") would be placed alongside `ebay-menu`

## Screenshots
<img width="312" alt="screen shot 2018-06-20 at 4 41 57 pm" src="https://user-images.githubusercontent.com/5200733/41749584-1ff34e0a-756c-11e8-9794-554dbb7bb979.png">

**Comment by yomed** [comment]
Currently waiting on Skin 5.1.0-1

**Comment by ianmcburnie** [comment]
Skin 5.1.0-1 is now ready.
