### ISSUE TITLE
Set columns options don't match options values in UI

### ISSUE THREAD

**Issue by ArtBlue** [eBay/ebayui-core#2203]
The default state of this example that has columns defined (see markup) doesn't match the options underneath that are all `null`.  That might be confusing to devs.

<kbd><img width="1347" alt="image" src="https://github.com/eBay/ebayui-core/assets/1675667/2e4c718a-1193-4289-b5e2-cf5c8d40f753"></kbd>

If/when there are columns set, they should be reflected in the options values. 

_Originally posted by @ArtBlue in https://github.com/eBay/ebayui-core/pull/2199#discussion_r1653380799_

**Comment by agliga** [comment]
Complete
