### ISSUE TITLE
Combobox (previously Select): when starting with zero items, adding items dynamically doesn't enable the expander

### ISSUE THREAD

**Issue by seangates** [eBay/ebayui-core#221]
# Bug Report

## Description
When the combobox starts with zero items, the expander is never initialized. Therefore when items are added, the combobox never initializes the expander.

## Workaround
~No workaround.~ Yes, if the app developer re-renders the component in their app.

## Screenshots
n/a

**Comment by ianmcburnie** [comment]
@seangates not sure if this one will still be relevant for editable combobox or the listbox? Or perhaps just readonly-combobox (in which case it's low priority)? Maybe worth checking while you're working on that.

**Comment by ianmcburnie** [comment]
@seangates I wonder if this one is related to makeup and marko state?

**Comment by seangates** [comment]
Very likely, given what we now know.

**Comment by ianmcburnie** [comment]
We should add this scenario to the demo page as part of PR #566 . Quite often comboboxes start with no suggestions at all and are only fetched from the server as user types.

**Comment by ianmcburnie** [comment]
Merged and in testing for 2.2.0 release
