### ISSUE TITLE
Combobox (previously Select): when disabled, the combobox still expands

### ISSUE THREAD

**Issue by seangates** [eBay/ebayui-core#222]
# Bug Report

## Description
When the combobox is in a disabled state, the expander still expands the items in a dropdown.

## Workaround
No workaround.

## Screenshots
![image](https://user-images.githubusercontent.com/105656/41880295-7945df50-789a-11e8-824a-b387bfb17664.png)

**Comment by ianmcburnie** [comment]
Fixed.
