### ISSUE TITLE
The List view in <ebay-combobox /> does not follow if scrolling down the list with keyboard

### ISSUE THREAD

**Issue by don-siu** [eBay/ebayui-core#2230]
# Bug Report

## Description
The List view in <ebay-combobox /> does not follow if scrolling down the list with keyboard

https://opensource.ebay.com/ebayui-core/?path=/story/form-input-ebay-combobox--search-filtering

## Workaround
NA

## Screenshots

https://github.com/user-attachments/assets/40dad40b-0bae-475a-8538-b666393db67e

**Comment by saiponnada** [comment]
Fixed this issue as part of makeup PR - https://github.com/makeup/makeup-js/pull/175

@agliga we need to update `makeup-active-descendant` dependency to `0.7.1`

**Comment by agliga** [comment]
Updated as part of our dev deps
