### ISSUE TITLE
<ebay-menu-button> doesn't work with only one <@items>

### ISSUE THREAD

**Issue by rcscr** [eBay/ebayui-core#2241]
# Bug Report

```
TypeError: (input.items || []).filter is not a function
    at default_1.getInputState (/Users/rcrrea/Workspace/my-fashion/node_modules/@ebay/ebayui-core/dist/common/menu-utils/index.js:52:42)
```

## Description

When there's just one item on the list it is actually interpreted as an iterable object instead of an array. 

## Workaround

Real fix: 
`[...(input.items || [])].filter`

Workaround: 
Add a second <@items> element and hide it:
```
.menu-button__item:last-child {
  display: none !important;
}
```

**Comment by LuLaValva** [comment]
We should add the spread fix for compatibility and the eventual phasing out of `marko-tag.json`, but this is only broken if you use `<@items>` instead of `<@item>`.

The best fix here is to use `<@item>`

**Comment by rcscr** [comment]
`<@item>` seems to work on the browser but not when building.
<img width="570" alt="Screenshot 2024-08-27 at 20 13 34" src="https://github.com/user-attachments/assets/08e4b8d6-344b-4de0-bb66-f3b37cde03fc">
![Uploading Screenshot 2024-08-27 at 20.23.40.png…]()

**Comment by rcscr** [comment]
`<@item>` seems to work on the browser but not when building.
<img width="570" alt="Screenshot 2024-08-27 at 20 13 34" src="https://github.com/user-attachments/assets/08e4b8d6-344b-4de0-bb66-f3b37cde03fc">
<img width="807" alt="Screenshot 2024-08-27 at 20 23 40" src="https://github.com/user-attachments/assets/079e8699-e3e2-46b2-a5d1-f93febb4ccc0">

**Comment by rcscr** [comment]
<@item> seems to work on the browser but not when building.
<img width="570" alt="Screenshot 2024-08-27 at 20 13 34" src="https://github.com/user-attachments/assets/f9f69103-9573-4487-93a6-6c94827196eb">
<img width="807" alt="Screenshot 2024-08-27 at 20 23 40" src="https://github.com/user-attachments/assets/354ee292-e1d1-470b-bd22-539da286078e">
