### ISSUE TITLE
textbox: Prefix-text not working for Marko 4

### ISSUE THREAD

**Issue by ManvithaC** [eBay/ebayui-core#2260]
# Bug Report

## Description

@prefix-text and @postfix-text is not showing up for textbox, as per documentation, with Marko 4
looks like the input is not being normalized for some reason (see prefix-text="{}" in below screenshot)
eBayUI should add prefix-text and postfix-text to marko-tag.json

## Workaround

Use @prefixText and @postfixText.

## Screenshots

![image](https://github.com/user-attachments/assets/0a2e625f-27d0-4c75-8ded-0506a26357eb)

**Comment by sairam0903** [comment]
+1

Seeing the same issue in [ebay-phone-input](https://opensource.ebay.com/ebayui-core/?path=/docs/form-input-ebay-phone-input--documentation). Country code is not showing when passed one.
