### ISSUE TITLE
Combobox: when there are many options - When expanded, there is no scroll inside the component. It scrolls with the page

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#228]
# Bug Report

## Description
when there are many options - When expanded, there is no scroll inside the componenet. It scrolls with the page

repro:
https://go/ebayui/test2
go to ebay-combobox nested - too many options - scroll
expand it

Issue: it scrolls with the page.
There is no scroll bar inside the component

https://www.useloom.com/share/49d0bea18e9d4d6987acebba68d09817

**Comment by msendlakowski** [comment]
Moved to skin: https://github.com/eBay/skin/issues/335
