### ISSUE TITLE
ebay-tooltip: In touch devices, If the tooltip host is a button that opens a modal on click, the click on button is opening the tooltip but not the modal

### ISSUE THREAD

**Issue by snagarajugari** [eBay/ebayui-core#2290]
# Bug Report

## Description
 In touch device, go to https://opensource.ebay.com/ebayui-core/?path=/docs/notices-tips-ebay-tooltip--documentation and click on `View options` link shown below. The tooltip showing up before the navigation happens. This is an issue & it's more problematic  when tooltip host is a button.

If the tooltip host is a button that opens a modal on click, the click on button is opening the tooltip but not opening the modal in touch devices.

<img width="1278" alt="Screenshot 2024-10-09 at 4 49 09 PM" src="https://github.com/user-attachments/assets/0a4aaace-84cc-412b-9eeb-0a0db8cff4a8">

**Comment by agliga** [comment]
Im curious, what is the usecase for this?
Do you want the user to click a button twice to navigate? If a link takes a user to another place it probably shouldn't have a tooltip associated with it. 
You can probably put an infotip in this case.

**Comment by snagarajugari** [comment]
In our use case, we want click on the button open a modal. I see click on button is opening the tooltip but not the modal in touch devices eg: mweb

**Comment by agliga** [comment]
This is part of the implementation of tooltip. There's no way to show a tooltip on a button on touch devices. There are usecases for it, but there are also limitations. 
I recommend that you have a separate button for an infotip for that case. Or you can have a tourtip show on top of the button on load.
