### ISSUE TITLE
ebay-select: in iphone- once expanded, clicking outside the area does not collapse the expanded options

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#230]
# Bug Report

## Description
First of all: pls look into the screenshot tell me if this look is ok?

About the issue:
Iphone x chrome and safari
ebay-select once expanded, clicking outside the area does not collapse the expanded options
after modifying the option without clicking on 'done' when I click outside to cancel the change I couldn't do it.
The modified change gets selected. and the only way to close the expanded options is through clicking the done. 

## Screenshots
![clicking ouside does not collapse the options](https://user-images.githubusercontent.com/13157115/42057511-646a3682-7ad2-11e8-8a5f-8367a4c808d8.png)

**Comment by seangates** [comment]
This is expected behavior.
