### ISSUE TITLE
Select: Nexus 10: android tablet - clicking on the component again does not close the options list

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#232]
# Bug Report

## Description
Android tablet Nexus 10 Safari and chrome
https://go/ebayui/test
click on ebay-select and expand the options list
now click on the top of the component to collapse it
It collapses and then opens again

**Comment by ianmcburnie** [comment]
Assigning to @seangates for investigation/scoping only.

**Comment by yomed** [comment]
@seangates Did you end up looking into this one at all? I reproduced this issue on a virtual Nexus 10 through Android Studio, and this looks like expected browser behavior. I see the exact same behavior in interacting with basic `<select>` tags.

**Comment by seangates** [comment]
I have not looked at this. I would actually welcome help setting up Android Studio. It was difficult for me to set up and use in the past.

**Comment by yomed** [comment]
@hramakumar Closing, as this is default browser/device behavior.

**Comment by hramakumar** [comment]
ok
