### ISSUE TITLE
ebay-video: UI controls not localized

### ISSUE THREAD

**Issue by jsakalys** [eBay/ebayui-core#2323]
# Bug Report

## Description

Dash player UI used by ebay-video does not use anything other than the default English language label for all UI elements (play/pause/mute/report/expand/fullscreen/etc.).

We expect this is impacting all instances of ebay-video across the site, so essentially no matter the locale every user on eBay is currently seeing english language controls with the video player.

## Workaround

There is no way to change the locale using shakaConfig or other configuration object. shakaConfig only allows specifying preference for audio and subtitle text, not interface text. The interface locale must be set using internal APIs. Example code:
```
const ui = new shaka.ui.Overlay(player, videoContainer, video);
ui.getControls().getLocalization().changeLocale(["de"]);
```
Reference doc: https://github.com/shaka-project/shaka-player/issues/3464

This change should be made at the ebay-video component layer.

## Screenshots
![image](https://github.com/user-attachments/assets/25f93984-bb43-44eb-a76c-8fde2f9c8e31)

**Comment by UDAY556** [comment]
@LuLaValva Please add me to this repo
