### ISSUE TITLE
ebay-date-textbox: date picker shows two-month view on low-resolution or small screen sizes

### ISSUE THREAD

**Issue by damonsauve** [eBay/ebayui-core#2333]
# Bug Report

On Android/mobile, the `ebay-date-textbox` shows date picker box as a single month. But on web browsers with small screen sizes (or older, low-resolution displays), the datepicker show two months, which is a problem for these smaller screen.

## Description

Might be related to this code:

- https://github.com/eBay/ebayui-core/blob/14.5.0/src/components/ebay-date-textbox/component.ts#L98-L103

## Screenshots

Android showing single-month view:
![1732564556572](https://github.com/user-attachments/assets/1ac209a2-ee0e-4ec1-b130-bb41fd0be477)

Screenshot from actual user screen showing two-month view:

![Screenshot 2024-11-25 at 12 10 35 PM](https://github.com/user-attachments/assets/059113e2-d926-4db0-8f6d-96f13a9df8e8)

Screen recording showing two-month views:

https://github.com/user-attachments/assets/f47693a0-64a7-42b6-abfc-5b5c9ba84aa8

**Comment by LuLaValva** [comment]
Fixed by [this commit](https://github.com/eBay/ebayui-core/commit/baade147a795ea23827b8b3cfc9ab9c784cc6fbc), will be included in `14.5.0`
