### ISSUE TITLE
ebay-select: Currently selected option is not highlighted in the options list - no tick mark or bold text

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#234]
# Bug Report

## Description
Android tablets Nexus 10 and Samsung galaxy tab - chrome browser -There is no way to see which option is currently selected in the options list
There is no tick mark or bold text.

## Screenshots
![selected option not bold](https://user-images.githubusercontent.com/13157115/42107138-22648aee-7b8b-11e8-9b8c-4ee2c366d3b7.png)

**Comment by ianmcburnie** [comment]
Closing as wont fix as we have no control over the browser's rendering of select overlay. Apps should use combobox if they require custom rendering.
