### ISSUE TITLE
ebay-combobox: Is not filtering lists anymore

### ISSUE THREAD

**Issue by agrananadosbarrantesebay** [eBay/ebayui-core#2343]
# Bug Report

## Description

We have detected that ebay-combobox no longer filters listings in our code after switching from ebayui-core 14.4.0 to ebayui-core 14.5.0

## Screenshots

- Behavior using ebayui-core 14.4.0: 

![example-ebayui-core-14 4](https://github.com/user-attachments/assets/2737a52b-2c8b-43af-a19b-2808ae90f885)

- Behavior using ebayui-core 14.5.0: 

![example-ebayui-core-14 5](https://github.com/user-attachments/assets/13f67769-5f42-438a-96c5-fe75ba62f44e)

**Comment by agliga** [comment]
Workaround: set `viewAllOptions` to false and it will work
