### ISSUE TITLE
ebayui-dialog class attribute

### ISSUE THREAD

**Issue by oxala** [eBay/ebayui-core#262]
# Bug Report

## Description
When i set a `class` for `<ebayui-dialog>` i expect this class to be rendered on the root element of ebayui-dialog, so i can control the style (if needed) from my component. (using `> .dialog` etc...). Right there is another element rendered between my class dialog and my component (.dialog-placeholder).

## Workaround
The current workaround is to couple my styles with the `.dialog-placeholder` that comes from ebayui-dialog. And i don't like coupling.

![image](https://user-images.githubusercontent.com/1775318/42846251-3abb7512-89cd-11e8-98cd-24f5d9fc8bf5.png)

**Comment by oxala** [comment]
I have a bad example here, since i have className `dialog` as a custom class name. :-(

But anyway, `.dialog` is coming from the ebayui-dialog component (hence - the coupling). My app should not know about it existence. Because internally within ebayui-dialog it can be changed to whatever without breaking my app.

**Comment by yomed** [comment]
Right, I would avoid hooking into the Skin classes as much as possible to avoid implicit coupling. That said, Skin intentionally does not namespace these classes, so any users of Skin have to avoid using those same names in their applications. What's your use case for overriding the styles?

**Comment by DylanPiercey** [comment]
I think the `dialog-placeholder` element is a remnant of the original plan to have a dialog that portaled to the body. As we've discussed before I think it would make sense to revisit that functionality when we move to Marko v4, however in Marko v4 this extra div is not needed. I can double check to see if I am using this div for anything currently but I think we could remove it.
