### ISSUE TITLE
ebayui-dialog outside click close

### ISSUE THREAD

**Issue by oxala** [eBay/ebayui-core#263]
# Bug Report

## Description
When i click on the margin part of the dialog content (orange color on the screenshot) 
![image](https://user-images.githubusercontent.com/1775318/42846469-e71c2446-89cd-11e8-927f-af538d594311.png)
The dialog is being closed. It should not be closed.

## Workaround
Don't click on the orange area of the screenshot.

**Comment by ianmcburnie** [comment]
@DylanPiercey This is fairly low priority, but please do a quick investigation/scoping effort if you get a chance.

**Comment by oxala** [comment]
My bad. I should have upgraded `ebayui-core` before creating this issue. Closing.
