### ISSUE TITLE
carousel: unable to override the carousel margin with gap attribute

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#276]
# Bug Report

## Description
carousel: unable to override the carousel margin with gap attribute

## Screenshots

                         <div class="grid__cell grid__cell--8of16 grid__cell--8of16-lg grid__cell--4of8-sm" draggable="true" ondragstart="drag(event)">
                 
                            <h3>Continuous - overriding gap value- issue #220 hems2</h3>
                            <style>
                                .demo1-card {
                                    color: #0a1c6b;
                                    background: #c2f5ff;
                                    font-size: 24px;
                                    font-weight: bold;
                                    width: 200px;
                                    height: 120px;
                                    line-height: 120px;
                                    text-align: center;
                                }
                            </style>
                            <ebay-carousel gap="1500px">
                                <ebay-carousel-item class="demo1-card">Card 1</ebay-carousel-item>
                                <ebay-carousel-item class="demo1-card">Card 2</ebay-carousel-item>
                                <ebay-carousel-item class="demo1-card">Card 3</ebay-carousel-item>
                                <ebay-carousel-item class="demo1-card">Card 4</ebay-carousel-item>
                                <ebay-carousel-item class="demo1-card">Card 5</ebay-carousel-item>
                                <ebay-carousel-item class="demo1-card">Card 6</ebay-carousel-item>
                            </ebay-carousel>
                        </div>

for the above code
 I see the following with default margin size
![gapnotworking](https://user-images.githubusercontent.com/13157115/42971696-0f286176-8b62-11e8-80dd-5e02cfe7c772.png)

**Comment by DylanPiercey** [comment]
Fixed in https://github.com/eBay/ebayui-core/pull/275
