### ISSUE TITLE
Carousel: scrolling till the end does not disable the carousel right arrow - galaxy s5 and s6

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#277]
# Bug Report

## Description
carousel: touch and move till the end . It  does not disable the carousel right arrow. clicking on the next arrow takes to a card.
This happens everytime in samsung galaxy s6
repro:
https://go/ebayui/test2
 move the cards in the continuous carousel till the end.
The next arrow is still enables and clicking on it moves the cards

## Screenshots

![6card_carousel](https://user-images.githubusercontent.com/13157115/42974956-6cf82bc2-8b6e-11e8-980c-063572fb3cd2.png)

**Comment by DylanPiercey** [comment]
IIRC the issue here was that the card was too big which is a use case we don't and shouldn't support since then the carousel item could never be fully seen. @hramakumar can you verify that's what this was? If so I think we can close this one.

**Comment by hramakumar** [comment]
@DylanPiercey @msendlakowski https://github.com/eBay/ebayui-core/issues/278
as part of this fix we removed the right and left arrows in mweb continuous carousels.
I guess we dont need to worry abt this issue anymore.
pls let me know if I am missing something.
