### ISSUE TITLE
New Component: Switch

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#280]
This will be available for DS4 and DS6 in upcoming Skin v6 release. Should be a simple component to squeeze into v1.0.0.

Sneak peak:

<img width="665" alt="screen shot 2018-07-20 at 2 48 27 pm" src="https://user-images.githubusercontent.com/38065/43026780-0addc99c-8c2c-11e8-9b43-68b27b297449.png">

New markup:

```html
<span class="switch">
    <input role="switch" type="checkbox" />
    <span class="switch__inner"></span>
</span>
```

**Comment by ianmcburnie** [comment]
Moving this to 0.9.0. Good first issue.

**Comment by ianmcburnie** [comment]
Just a heads up that the markup for the 0.9.0 version must match the 5.1.x version of Skin and will be for DS4 only.

The 1.0.0 version will match the 6.0.x version of skin and will also support DS6. The only difference in skin 6.0.x is that two new classnames are required, so I feel we might as well do the bulk of the work now, and the do a quick update later.

**Comment by yomed** [comment]
@ianmcburnie Why not support DS6 from the start? The differences in that version are additive, so it should be fully backwards compatible with DS4.

**Comment by ianmcburnie** [comment]
DS6 switch is only available in skin v6 branch. We can't set 0.9.0 to use skin v6 due to the many other breaking changes. We want to line up all those breaking changes with v1.0.0 of coreui.

**Comment by sendlo** [comment]
So the 0.9.0 version will be based on 5.1.x skin.
The 1.0.0 version will have the same markup, but will be based on skin 6.0.0 and support DS4 and DS6.  And the only change from 0.9.0 to 1.0.0 will be 2 new classnames?

Is that an accurate summary?

**Comment by ianmcburnie** [comment]
Yes, that's how I see it.

**Comment by seangates** [comment]
Skin v5.2.x, but yeah, @yomed.
