### ISSUE TITLE
Icon: Abstract out stamping capabilities for use by external components

### ISSUE THREAD

**Issue by seangates** [eBay/ebayui-core#285]
# Feature Request

>**Note:** This issue stems from conversations around PR #281 which aimed to allow custom icons in `<ebay-icon>`. We prefer to limit `<ebay-icon>`'s set of icons to those in the DS4/DS6 set, but agree it might be beneficial to abstract the stamping capability for any component to perform their own stamping.

## Original PR details 👇 

I've coped the PR description from @dsathyakumar below as it is helpful to understand this issue's motivation.

----

## Description
Expand `ebay-icon` capabilities to stamp custom inline icons.

## Context
- Currently `<ebay-icon/>` stamps inline SVG icons that are available in `/symbols` folder within it
- More often, there are repeated custom icons given, which currently cannot utilize the one time stamping inside `<body>`, as done by `<ebay-icon/>`.
- Now, adding a custom icon is as simple as
>`<ebay-icon type="inline" name="my-awesome-icon" custom="true"/>` 

(this causes the transformer to look within the project root for a `/symbols/my-awesome-icon.marko`)

## Screenshots
![image](https://user-images.githubusercontent.com/5446493/43033460-c26040f6-8c7f-11e8-914f-04ad9594a881.png)

**PS**: I'm a newbie to this project 🙂, pls excuse if the PR doesn't meet your standards!

**Comment by ianmcburnie** [comment]
This would be nice to have, but I'm going to close it for now and we can always revisit in future.
