### ISSUE TITLE
Combobox: needs accessibility support  

### ISSUE THREAD

**Issue by yzhao888** [eBay/ebayui-core#288]
# Bug Report

## Description

ebay-combobox doesn't provide a way to specify accessibility text for voice-over use case.

I'm following https://www.coolfields.co.uk/2011/04/accessible-forms-should-every-input-have-a-label/ to provide accessibility to the dropdown. The <input> tag needs either an id or a title attribute. 
It would be nice to have a way to pass in a string as generated <input> tag's title attribute, or a way to specify id of the generated <input> tag.

## Workaround

No
## Screenshots

N/A

**Comment by yzhao888** [comment]
This is also highlighted from WAE tool.

 1 . The input with id= needs a title or label: 1) title attribute, 2) label text from a wrapped label (the label tag wraps the input tag) or 3) label text from a referrence label (the label for attribute references the input id attribute). Try <label for='inputElement'>Input Label</label><input id='inputElement' />

**Comment by ianmcburnie** [comment]
Yes, thanks for reporting this.

Please ensure ID can be set on input element. We do not need title attribute (as it's inaccessible to keyboard users)

**Comment by seangates** [comment]
😱 Thanks for reporting this.
