### ISSUE TITLE
Carousel: cannot scroll items without Prev/Next button on touch device

### ISSUE THREAD

**Issue by abiyasa** [eBay/ebayui-core#289]
# Bug Report

## Description

The carousel Prev & Next button only appears when you hover the mouse. However, since there is no hover event on touch/mobile device (or mobile), those buttons are only visible when carousel get focus.

This is not a problem when you can tap the carousel item to gain focus. Unfortunately, it's a problem when carousel items are linked items (see PLUSDEAL card on screenshot below). 

This means when a user taps an item, he/she will accidentally click the link. Since you cannot swipe to scroll items horizontally, there is no way for mobile user to see the next carousel items.

A quick solution is to always display prev/next button on touch device. This can be enabled by carousel attribute, for example, `always-show-nav-button`. A proper solution is to handle swipe left/right on touch device.

## Workaround

None.

## Screenshots

![image](https://user-images.githubusercontent.com/1072047/43206306-ae02c832-9025-11e8-919a-31c7de2c6c4a.png)

**Comment by seangates** [comment]
@abiyasa We're stretched thin, to say the least. I will work with @ianmcburnie to see if we can get release notes out for v0.7.0 as soon as possible.

**Comment by abiyasa** [comment]
Thanks @seangates ! Sorry, I didn't mean to push you guys for the release notes updates. 
I thought I saw release note for v0.5.0 before and it was deleted somehow, but I realized was confused this one with Skin v5.x 😬

**Comment by seangates** [comment]
Oh! Gotcha. Yes, the numbering was very similar for a little while there. Getting closer to v1.0, though! Exciting!
