### ISSUE TITLE
Carousel - autoplay: 1 slide - carousel should not display the next/prev and play buttons 

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#290]
# Bug Report

## Description
Carousel - autoplay: when there is only one slide to show, the carousel should not display the next/prev and play buttons 

actual: the next,prev and play buttons are displayed even when there are no more slides to show

expected: next and prev buttons should not be displayed or should be enabled. The play button should not be displayed as the slide will not move.

## Screenshots

![autoplay_one_slide](https://user-images.githubusercontent.com/13157115/43220954-3cad4d6c-9000-11e8-8345-0932916804cd.png)

**Comment by ianmcburnie** [comment]
Fixed in 8.0.0-1
