### ISSUE TITLE
menu: reverse does not work

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#298]
# Bug Report

## Description
                 <ebay-menu label="eBay Menu" style="margin-left:200px">
                        <ebay-menu-item>item 1 this is a very very very long text</ebay-menu-item>
                        <ebay-menu-item>item 2</ebay-menu-item>
                        <ebay-menu-item>item 3</ebay-menu-item>
                    </ebay-menu>
I use the above 
I see the menu component has moved to the right but the options are not left aligned

https://www.useloom.com/share/67ae5ac5379b46e7a81a937775c8cd4d

**Comment by yomed** [comment]
Can you see if this is a bug in isolation? If not, can you determine what the conditions are for the bug to occur?

**Comment by hramakumar** [comment]
yes happens occurs in isolation as well

as mentioned above I used the style="margin-left:200px and expected the options to be left aligned but its not.

**Comment by hramakumar** [comment]
https://10.0.0.210:8080/ebayUIStaging

**Comment by seangates** [comment]
I think you mean right aligned?

**Comment by hramakumar** [comment]
yes. my bad.
Right aligned

**Comment by yomed** [comment]
@hramakumar You would need to add the `reverse` boolean attribute, which isn't present in your example above. I.e.:

```marko
<ebay-menu reverse label="eBay Menu" style="margin-left:200px">
    <ebay-menu-item>item 1 this is a very very very long text</ebay-menu-item>
    <ebay-menu-item>item 2</ebay-menu-item>
    <ebay-menu-item>item 3</ebay-menu-item>
</ebay-menu>
```

**Comment by hramakumar** [comment]
got it.
I am closing it
