### ISSUE TITLE
Limit combobox visible area.

### ISSUE THREAD

**Issue by oxala** [eBay/ebayui-core#300]
# Feature Request

## Description
There should be a way to limit amount of visible options inside combobox. As right now, it's very difficult to scroll through combobox with hundreds or in some cases thousands of entries.

## Screenshots
![image](https://user-images.githubusercontent.com/1775318/43489346-99033cd6-94d1-11e8-846e-ab303429094a.png)

**Comment by seangates** [comment]
Can you report that over here? => https://github.com/eBay/skin/issues

**Comment by seangates** [comment]
Then I'll close this one.

**Comment by seangates** [comment]
Wait ... we are already tracking this: https://github.com/eBay/ebayui-core/issues/228

**Comment by seangates** [comment]
No worries! Is it blocking you?
