### ISSUE TITLE
Carousel: code coverage is low

### ISSUE THREAD

**Issue by sendlo** [eBay/ebayui-core#309]
## Description
Latest code coverage for the carousel component is pretty low (79%) and that's dragging overall coverage low.  
Looks like adding tests for handleScrollEnd will probably bring it up to standards.

**Comment by sendlo** [comment]
@DylanPiercey   Low priority.  If you can't get your test case working, ignore this for now.

**Comment by yomed** [comment]
Not much to verify here `Overall coverage increased (+5.0%) to 93.287%`.
