### ISSUE TITLE
Carousel: Items are not visible when items count is less than items-per-slide

### ISSUE THREAD

**Issue by sraone** [eBay/ebayui-core#316]
# Bug Report

## Description
Items are not visible when the items count is less than `items-per-slide`;

```marko
<ebay-carousel type="discrete" items-per-slide="5" gap="0">
    <ebay-carousel-item for(item in data.items)>
		content
    </ebay-carousel-item>
</ebay-carousel>
```

If `data.items` length is less than 5(which is `items-per-slide`), the component would not displaying any items in `carousel`.

https://github.com/eBay/ebayui-core/blob/d2d28a6d9d35f205a8a2d53987db9dd91289ea66/src/components/ebay-carousel/index.js#L40

If items length is 4 and `items-per-slide` is 5, above logic sets the total item count is 0 could be the possible reason.  

## Workaround
Have conditional `item-per-slide` and overwrite style to set the `width` of each item.

```marko
<ebay-carousel type="discrete" items-per-slide=(data.items.length > 5 ? 5 :data.items.length ) gap="0">
```

**Comment by sendlo** [comment]
@sraone  I'm changing this to an enhancement because this is intentional.  When "items-per-slide" is set we expect the client to pass the correct number of items to fill a whole page for each slide.  We drop any extra items that don't fit a full slide.

But we'll update the documentation to make sure this is clear.

**Comment by msendlakowski** [comment]
@sraone We ended up making a change that should support this.  Pages of the carousel can now show "partial pages" so your use cases should be covered.

**Comment by sraone** [comment]
@msendlakowski thank you. I tested its working as expected
