### ISSUE TITLE
pagination in ie11 throws an error

### ISSUE THREAD

**Issue by martin-ebay** [eBay/ebayui-core#317]
# Bug Report

## Description
trying to use the pagination buttons in ie11 throws an error.

## Workaround
The fix is to fix the conditional in emitAndFire.js as it is checking

```
if (window.CustomEvent) {
   event = new CustomEvent(.....
```
the window.CustomEvent object exist in ie11 but ie11 does not support `new CustomEvent`.

**Comment by yomed** [comment]
Better feature check: https://github.com/Modernizr/Modernizr/blob/5eea7e2a213edc9e83a47b6414d0250468d83471/feature-detects/customevent.js#L23

**Comment by yomed** [comment]
Thanks for the bug report and PR -- Fix is out in `0.9.0`
