### ISSUE TITLE
Revisit event naming

### ISSUE THREAD

**Issue by yomed** [eBay/ebayui-core#320]
# Feature Request

## Description

`checkbox-select`, `radio-select`, `switch-select` can be misleading, since they fire for both selection and deselection. These are opposed to events where they are actually only used for selection, like `pagination-select` and `tab-select`.

If we want to change the name, we should change them all at the same time.

Brought up in #310

**Comment by yomed** [comment]
Earlier discussion https://github.com/eBay/ebayui-core/pull/134#issuecomment-390281822
> ianmcburnie commented on May 18
>
>@PrashantAshok Sorry to do this to you, I know first we had the event as radio-change, but that overlapped with the DOM change event, then we moved to radio-click as that was more explicit this was a pass through of the click event. But then I remember we have breadcrumb-select and maybe a few others using "select" that are pass throughs for the click event. So in the interest of consistency maybe we go with radio-select for now, and then review all these names later.@yomed @seangates thoughts?

**Comment by yomed** [comment]
All of our current events, with some notes around which are inconsistent:

Old | New | Notes
--- | --- | ---
`breadcrumb-select` |  | 
`button-click` |  | 
`carousel-update`  |  | 
`carousel-next`  |  | 
`carousel-prev`  |  | inconsistent with `pagination-previous`
`carousel-slide`  |  | 
`carousel-play` |  | 
`carousel-pause` |  | 
`checkbox-select` | `checkbox-change` | inconsistent with selection
`combobox-collapse` |  | 
`combobox-expand` |  | 
`combobox-change` |  | 
`dialog-show` |  | 
`dialog-close` |  | inconsistent with `notice-hide`
`menu-expand` |  | 
`menu-collapse` |  | 
`menu-change` |  | 
`menu-select` |  | 
`notice-show` |  | 
`notice-hide` |  | inconsistent with `dialog-close`
`pagination-previous` |  | inconsistent with `carousel-prev`
`pagination-next` | | 
`pagination-select` |  | 
`radio-select` | `radio-change` |  inconsistent with selection
`select-collapse` |  | 
`select-expand` |  | 
`select-change` |  | 
`switch-select` | `switch-change` |  inconsistent with selection
`tab-select` |  |

**Comment by sendlo** [comment]
OK. You sold me.
My vote is to use the "*-change" events for those you mention.  
And "*-prev".  
And "*-hide". 

I see menu-select is still a select, but by your logic that's because its always a select action, never a "de-select".

Thanks for the clear summary.

Any objections?

**Comment by DylanPiercey** [comment]
Sounds good although I still need to take some time to look over everything. One thing to note is that the ‘eBay-dialog’ close event is based off of the native dialog close event. Not picky over close vs hide but that’s why it is what it is.

**Comment by sendlo** [comment]
I don't think we NEED to stick with those.  I think its more important to be understandable and consistent.  For example, our menu uses the "select" event at the item level, but native select elements use the change event at the root level.  
And I personally think show/hide makes more sense than show/close.

**Comment by DylanPiercey** [comment]
I don’t disagree. However one of our core goals was to be like the DOM. @senthilp what do you think?

**Comment by senthilp** [comment]
Yes, that is right. Being close to DOM is one of the values. For dialog, the existing event name `dialog-close` seems appropriate. This is not a silver bullet, for some scenarios we may need adjust them accordingly.

**Comment by sendlo** [comment]
OK. Works for me.  So lets change notice to close then, for consistency.

**Comment by DylanPiercey** [comment]
One other thing that I think we should change is that the `ebay-dialog` and `ebay-notice` both use `aria-` prefixed accessibility attributes while everything else uses the `accessibility-` prefix. Maybe there is some reason for this that I have missed though.

My personally vote is that these become `a11y-` so that they don't necessarily conflict with pass through `aria-` htmlAttributes while also being brief.

**Comment by yomed** [comment]
@DylanPiercey Yeah, we should do that for v1. There's actually another issue for it here https://github.com/eBay/ebayui-core/issues/214

**Comment by yomed** [comment]
Does anyone else have an opinion regarding `carousel-previous` vs `carousel-prev`?

I'd be inclined to go with `previous` since we don't abbreviate other terms (and I don't think the native API does either).
