### ISSUE TITLE
CI: BrowserStack can't run on PRs from forks

### ISSUE THREAD

**Issue by yomed** [eBay/ebayui-core#324]
# Bug Report

## Description

We've had a few PRs recently from external contributors who opened up PRs from their personal forks:
https://github.com/eBay/ebayui-core/pull/304
https://github.com/eBay/ebayui-core/pull/319

In both of these, builds failed at the automated browser tests. But when putting those exact commits in an upstream branch, the builds passed fine. In discussing with @DylanPiercey, we found that there are security restrictions in place which prevent loading BrowserStack. Theoretically a rogue PR could dump the environment variables and get access to our private BrowserStack key.

Some notes:
https://github.com/travis-ci/travis-ci/issues/7412#issuecomment-283651393
https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions

>If your build relies on encrypted variables to run, for instance to run Selenium tests with BrowserStack or Sauce Labs, your build needs to take this into account. You won’t be able to run these tests for pull requests from external contributors.

This is obviously a pretty significant limitation for us, since we rely on those builds for all code that enters the repo. One partial solution might be to run headless Chrome in fork PRs, but run BrowserStack against upstream PRs.

## Workaround

None.

**Comment by sendlo** [comment]
To avoid merging their code without a full browserstack run, we could ask all external PRs to go to a "bugfix" branch which runs the headless Chrome.  Once its on the bugfix branch we can do a quick PR to master with the full tests.

Its extra maintenance for us, but less risk of a broken master branch.
