### ISSUE TITLE
Menu: Emits incorrect element on client side rerender

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/ebayui-core#327]
# Bug Report

## Description
**Repro Steps**
1. First time server render, `event.el` emitted has the right `el` that was clicked. 
2. On subsequent client side re-render, `event.el` emitted has the incorrect (older) `el` that was clicked. 

Looks like `this.itemsEls` needs to be recalculated on re-render (onRender) as well. A quick test seems to fix the issue. Relevant code [link](https://github.com/eBay/ebayui-core/blob/79841fb66900ad1e87848d9acdfcd1f4b3cea12b/src/components/ebay-menu/index.js#L143)

## Workaround
None

**Comment by sendlo** [comment]
@yomed  Let's see if we can get this in the final 0.9.0 release.  I can create a second pre-release with this later this week.

**Comment by yomed** [comment]
One workaround for the interim -- Don't rely on `event.el`. Instead, use `event.index` to get the correct `el`.

**Comment by yomed** [comment]
Fixed in `0.9.0-2`
