### ISSUE TITLE
tab: clicking on the fake tab has no indication that the tab is selected

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#331]
# Bug Report

## Description
When I click on the fake tab I dont see any indication which tab is selected before navigating to the new url.
This looks confusing when the tabs have no clear borders.
What I assume the expected behaviour here is
the tab get selected first then the navigation to the url happens.

Pls correct me if I am wrong

https://www.useloom.com/share/f6842de9c1514c63be96e03d3c7e72b9

**Comment by yomed** [comment]
This is expected, as it's the way it works in Skin: https://ebay.github.io/skin/#tab

**Comment by seangates** [comment]
The idea of fake tabs, though, is that they are usually full page changes (taking a user to a different route). We are simply showing the tab design in the page, and then taking someone away from the current page.

BTW, this is the way fake tabs have been in DS4 as well. So, this is not a "broken" experience from Skin's point of view.

**Comment by senthilp** [comment]
Point taken. We can close the issue if everyone agrees.

**Comment by seangates** [comment]
Looks like me @sendlo, and @yomed agree. Closing.
