### ISSUE TITLE
textbox:  iphone - touch outside the textbox- cursor still stays in the textbox

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#336]
# Bug Report

## Description
text box does not loose focus when clicked outside.

repro: 
iphone
chrome browser
open the https://go/ebayui/test
click on any text box
click in some area outside the textbox

actual: the focus is still there in the textbox and cursor is bliking
expected: textbox should loose focus (works fine in desktop)

**Comment by seangates** [comment]
This is expected behavior. Use any other site and you will notice that every other form on an iPhone works this way.

**Comment by hramakumar** [comment]
No The issue happens in chrome as well and its not the same behaviour everywhere
I checked it against ebay write a review page. We need to maintain the same behaviour.

**Comment by hramakumar** [comment]
https://www.qa.ebay.com/urw/write-review/1005727280?_itm=100750061347
