### ISSUE TITLE
switch: performance issue android- click acts slow

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#337]
# Bug Report

## Description
android samsung galaxy s6
go to https://go/ebayui/test2
look for switch at the end of the page
click on the switch
you can visually see the switch working slow

**Comment by yomed** [comment]
I can see this issue on both Chrome simulator and a real Android device. But, this issue is exactly the same for an HTML checkbox input on any site. Closing, since it is not our issue.
