### ISSUE TITLE
Docs: listbox/select README consistency.

### ISSUE THREAD

**Issue by DylanPiercey** [eBay/ebayui-core#34]
There are currently some inconsistencies with the `ebay-listbox` components README.md vs the other components:

1. Headings contain code blocks.
2. "Examples" used instead of "Usage".
3. Headings prefixed with component name.

I'm not sure which format works best but I do believe we should make these consistent.

---

*ebay-listbox readme*
![screen shot 2018-03-08 at 9 51 28 am](https://user-images.githubusercontent.com/4985201/37167277-52c49edc-22b6-11e8-85f0-5f726aab8243.png)

*ebay-button readme*
![screen shot 2018-03-08 at 9 52 22 am](https://user-images.githubusercontent.com/4985201/37167318-6fc09bbc-22b6-11e8-9c82-07b7322719f6.png)

**Comment by yomed** [comment]
The `examples` section of `ebay-select` also looks outdated, since it is not using the `label` attribute (as the actual `examples/` do).
