### ISSUE TITLE
textbox: broken in ie - no blinking cursor

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#344]
windows IE latest version
# Bug Report

## Description
unable to type in text box.
blinking cursor is missing.

## Screenshots
https://www.useloom.com/share/be7dc4eb495f4ca0a0dc391eefffeb1f

**Comment by dasarianudeep** [comment]
@hramakumar Can you confirm it is only in IE 11 and not Edge?

**Comment by hramakumar** [comment]
yes It does not work in IE 11

**Comment by yomed** [comment]
FWIW, looks like a double click gets the textbox focus correctly in IE11  ¯\\_(ツ)_/¯

**Comment by msendlakowski** [comment]
Found that the issue was in the test environment.  Caused by the drag events on the container holding the text fields.
