### ISSUE TITLE
tab: IE 11- too many tabs, long text labels- overwrites over the other

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#345]
# Bug Report

## Description
in ie the when tab label length is long it overwrites over the next tab's label.

actual(ie): 
![image](https://user-images.githubusercontent.com/13157115/44062486-68bd6bce-9f11-11e8-830a-d37a21dcbbc4.png)

expected(chrome):
![image](https://user-images.githubusercontent.com/13157115/44062513-8976322e-9f11-11e8-802a-c0a1779ab691.png)

**Comment by yomed** [comment]
I think we should defer this until we decide on the details for tab wrapping.

**Comment by seangates** [comment]
From what I understand from design, tabs should wrap. https://ebay-eng.slack.com/archives/C72MEP885/p1533590388000228

And also, as reference, there is wrapping in the spec: https://ebay.invisionapp.com/share/CWN9X1JF6MA#/278353515_Tabs

**Comment by seangates** [comment]
Granted, their examples are only two lines of wrapping, which is very hard to make that specific constraint in CSS.

**Comment by seangates** [comment]
@yomed Should we close this so we don't have dupe issues between here and Skin?

**Comment by yomed** [comment]
This is a Skin issue, but actually slightly different than the other issue. The other one is just that wrapping doesn't happen. This one is for text overlappping other tabs in IE11 specifically. See the IE vs Chrome screenshots above. Most likely an IE flexbox bug.

**Comment by seangates** [comment]
Okay. Should we create a new one then?

**Comment by msendlakowski** [comment]
Closing as I moved this to skin
