### ISSUE TITLE
textbox: firefox - clicking on a prefilled text box always take cursor to the start of the value text

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#347]
# Bug Report

## eBayUI Version: 0.9.0-2

windows firefox
## Description
clicking on the textbox takes us to the start of the value text in the pre-filled in textbox.
expected behavior is It should take the blinking cursor to the exact location when the click happens in the text box

actual behaviour(firefox):
https://www.useloom.com/share/1e181ac02b12412cb626f2b294b24c5b
expected behaviour(chrome):
https://www.useloom.com/share/3115c84131c54c02959d9981c8bb3e86

**Comment by yomed** [comment]
@hramakumar What version of Firefox?

**Comment by dasarianudeep** [comment]
It is occuring in latest version of FF as well. Let me dig into it...

**Comment by hramakumar** [comment]
This could be a test issue as well...The test page drag and drop does not work fine with textbox.
Looks like it is working fine in marketplace

**Comment by hramakumar** [comment]
lets close this
