### ISSUE TITLE
Docs: show secondary button instead of raw button by default

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#35]
Looks better if we show the secondary button instead of the raw button:

![screen shot 2018-03-08 at 11 19 56 am](https://user-images.githubusercontent.com/38065/37171436-bf708396-22c2-11e8-9190-93086b825025.png)

Also tempted for us to make secondary the default instead of raw. Raw button has practical aspects for people consuming skin directly (horrible imagery there!) - but perhaps not so useful in ebayui.

**Comment by yomed** [comment]
Sounds ok to me to make `secondary` default. In that case we would probably need to shuffle the attributes. Maybe `priority="none"` for the raw case?

**Comment by ianmcburnie** [comment]
Yep, sounds good. This won't block our pre-release. But let's try and get it in before final release tomorrow.
