### ISSUE TITLE
Documentation: standardize on patterns for deprecation

### ISSUE THREAD

**Issue by msendlakowski** [eBay/ebayui-core#352]
# Feature Request

## Description
We should discuss and document how we want to notify user's of deprecated features. 

## Context
See https://github.com/eBay/ebayui-core/pull/346#issuecomment-413041149

**Comment by ianmcburnie** [comment]
In skin if I want to deprecate something I will usually mark it as deprecated in the code comments and release notes. I will also try and give some clue as to which major version it will be removed permanently. Usually it's the next one, but if the deprecated thing is fairly harmless or still used widely, I will leave it around longer (but removed from all documentation).

**Comment by ianmcburnie** [comment]
I've added some brief notes to the docs in 4.5.0
