### ISSUE TITLE
Select/Combobox: encompass native and custom styling in a single component

### ISSUE THREAD

**Issue by seangates** [eBay/ebayui-core#365]
# Feature Request

## Description
Currently, the combobox is based on a read-only `<input>` with a combobox aria role. Because of the way some browsers handle the focus of a readonly `<input>` it produces an undesirable experience for users.

By changing the current combobox, only slightly, to use a `<button>` to open/close the listbox, along with a hidden `<select>` to capture form input, we can address the issues which have been raised, as well as keep in line with the design system as its been 

This should be part of the `select` component which can decide when to use native vs. custom styling for the options.

## Context
Reported issues from current implementation that would be addressed: #229, #287

**Comment by yomed** [comment]
I thought we were postponing combobox work until we have typeahead functionality for that. And in the mean time we can basically revert `select` to an earlier version of itself that had a listbox for use on desktop.

**Comment by seangates** [comment]
@yomed This task needs to be rewritten with the newly agreed track we just came up with.

**Comment by ianmcburnie** [comment]
Closing this as the feature request is now a little out of sync with the new addition of editable Combobox and new Listbox module in Skin. I will create a new ticket, but I think we all agree the general sentiment is an "uber" dropdown component that makes life a little easier for devs.
