### ISSUE TITLE
combobox: combobox content is empty(ds4 and ds6)

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#379]
# Bug Report

## Description
in ds4 and ds6 pages combobox content is empty
repro
http://ebayuicomponentstestenv.vip.qa.ebay.com/ebayUIStagingIsolation/ds4?type=combobox_2

## Screenshots
![comboboxds4](https://user-images.githubusercontent.com/13157115/44680058-89dd6300-a9f1-11e8-89b7-75bcb69f0c73.png)

https://www.useloom.com/share/0e62b06d98054eec8c088ddecd798434

**Comment by yomed** [comment]
Perr #346, please update your `label` attributes to `text`.
