### ISSUE TITLE
button: disabled buttons shading is light - looks confusing with other secondary buttons

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#380]
# Bug Report

## Description
disabled buttons are lighter in shade when compared to secondary buttons.
in design docs
https://ebay.github.io/skin/#button
disabled buttons have darker shades

actual:
![button_disabled](https://user-images.githubusercontent.com/13157115/44680969-06714100-a9f4-11e8-9f4a-bff28d391750.png)

expected:
![expected_disabled](https://user-images.githubusercontent.com/13157115/44681014-2b65b400-a9f4-11e8-9e43-14c258295148.png)

**Comment by seangates** [comment]
Doing a quick comparison ...

**Using the DS4 site for buttons:**
![image](https://user-images.githubusercontent.com/105656/44738931-92966d80-aab3-11e8-99dd-3f059cadc93b.png)

**Using the eBayUI demo site:**
![image](https://user-images.githubusercontent.com/105656/44739018-d4271880-aab3-11e8-84b2-8e77ad299c24.png)

**Your test page:**
![image](https://user-images.githubusercontent.com/105656/44738956-a6da6a80-aab3-11e8-956c-d26d836ed7b6.png)

They look the same to me.

**Comment by seangates** [comment]
I see, you took this from the existing Skin site. Let me have a look.

**Comment by hramakumar** [comment]
verified
