### ISSUE TITLE
notice: mweb - notice status top border coloring is absent

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#381]
# Bug Report

## Description
samsung galaxy s6 , chrome browser.
in notice component the border color has Is absent

**_actual_**:

![screenshot_20180827-123941](https://user-images.githubusercontent.com/13157115/44681914-ccee0500-a9f6-11e8-8446-a62e59dcbf48.png)

**_expected_**:

![notice_expected](https://user-images.githubusercontent.com/13157115/44681955-eabb6a00-a9f6-11e8-8cb4-fb142c59dbaa.png)

**Comment by msendlakowski** [comment]
@hramakumar @seangates it looks like the correct behavior on 7- screens is to lose the border color.
What do you think?

This is from the 7- version of the skin website:
![screen shot 2018-08-29 at 9 27 29 am](https://user-images.githubusercontent.com/1562843/44801454-f7160300-ab6d-11e8-9848-efdad4e3f85a.png)

This is from one instance of it that I am aware of in production:
![screen shot 2018-08-29 at 9 29 26 am](https://user-images.githubusercontent.com/1562843/44801488-0eed8700-ab6e-11e8-930b-eaf44bfb4011.png)

**Comment by seangates** [comment]
I believe that's correct behavior as designed. It is very similar in DS6, where there are no background colors behind the icon but rather the icon colors change.
