### ISSUE TITLE
ebay-select: mweb IOS - when expanded - empty option list is shown

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#385]
# Bug Report

## Description
go to http://ebayuicomponentstestenv.vip.qa.ebay.com/ebayUIStaging/ds4 in Iphone x
in chrome or safari
expand any of the ebay select component in the test page
it shows an empty optionlist

## Screenshots
![ada627e4-54bc-4413-af17-cd22cfb2f834](https://user-images.githubusercontent.com/13157115/44691643-5233e280-aa14-11e8-8547-b77df908564f.png)

**Comment by yomed** [comment]
@hramakumar You'll need to update your markup to use `text="..."` rather than `label="..."` for the attribute. This was done as part of #346
