### ISSUE TITLE
Menu dropdown - hover to show full text for truncated text.

### ISSUE THREAD

**Issue by ZZS77** [eBay/ebayui-core#387]
# Feature Request
eBay-menu dropdown hover to show full text

## Description
When hover over for truncated text it doesn't show the full text. For example, German text tends to be longer.

## Screenshots
![image](https://user-images.githubusercontent.com/42783072/44743443-5ebd4700-aab7-11e8-8c10-626f1ae9024a.png)

**Comment by msendlakowski** [comment]
Thanks.  We'll get some feedback from the design team on how to handle this and update the issue.

**Comment by hramakumar** [comment]
I believe selecting the option will show the entire string though

**Comment by j05eph** [comment]
Is there a reason we're not showing full text? It seems arbitrary to concatenate at dropdown width.

**Comment by msendlakowski** [comment]
This is a custom UI, not a standard HTML `<select>` element, so the default is to take the width of the parent.  We'll have to add logic to make it expand to fit the content.  And we'll have to add custom logic to have it move left or right to stay in the page view.

We should be able to address this in the v1.1.0 release.

**Comment by yomed** [comment]
@msendlakowski In DS6, the menu fits to the content by default. We'd have to decide whether we want to backport that functionality to DS4.

**Comment by msendlakowski** [comment]
Actually, I see the DS4 menu is expanding too. @ZZS77 can you provide a link to where you are seeing this behavior, and what version of the components you are using?

![screen shot 2018-08-28 at 3 44 24 pm](https://user-images.githubusercontent.com/1562843/44755064-6db4f100-aad9-11e8-947b-dea6db24bf40.png)

**Comment by ZZS77** [comment]
Hmmm. Here is the link: https://www.ebay.com/slr/prd/status @msendlakowski

**Comment by seangates** [comment]
@ZZS77 That is a custom-built menu in the Seller Hub components. I cannot share the code here as it's inside the eBay network. Suffice it to say, that is not our eBayUI component.

**Comment by msendlakowski** [comment]
@ZZS77  We're closing this since its not a skin or eBayUI issue.  Ideally your team can move to ebayUI components and the issue should go away.  Otherwise you're going to have to do a custom solution for your implementation.

**Comment by ZZS77** [comment]
@seangates It is not custom built menu. I am using ebayui-core. The version is 0.9.1.

**Comment by seangates** [comment]
@ZZS77 You sent us a production link, which does not have our menu. Our menu uses the `.menu` class.

**Comment by seangates** [comment]
@ZZS77 Apologies. You're using the `.fake-menu`. Let me look closer at this.

**Comment by seangates** [comment]
Oh, but 0.9.1 doesn't have DS4 CSS in it. Something doesn't make sense.

**Comment by seangates** [comment]
Okay! Got to the bottom of it. They are using our component, v0.9.1, which _does_ currently truncate. This is fixed in v1.0.0-2 beta version and they will try that and let us know.

They'll also have to remove some Skin overrides they made so the button looked like a DS4 button.
