### ISSUE TITLE
combobox: IOS- mweb - combobox doesnt expand the second time

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#389]
# Bug Report

## Description
In Iphone x -  chrome and safari
go to http://ebayuicomponentstestenv.vip.qa.ebay.com/ebayUIStaging2/ds4
scroll to the combobox section
expand any of the combobox 
collapse it
try expanding the same again

**Comment by seangates** [comment]
When changing this to a `<input type="button" ...` I see some styling issues. I will need a Skin PR to fix both things.

![image](https://user-images.githubusercontent.com/105656/44750473-b917d100-aad2-11e8-8d5c-89201783b4d8.png)

**Comment by msendlakowski** [comment]
For this release we are recommending that applications use `ebay-select` for mobile and the read-only version of the 'ebay-combobox' only for desktop.  This strategy will be rethought in a future release.
