### ISSUE TITLE
button: too much of space is wasted at the left and right margins

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#390]
# Bug Report

## Description
When text label comes in centre it looks like too much of space is wasted at the left and right margins.
http://ebayuicomponentstestenv.vip.qa.ebay.com/ebayUIStagingIsolation/ds4?type=dialog_scrolling.

## Screenshots

![image](https://user-images.githubusercontent.com/13157115/44749263-dc3c8380-aac6-11e8-8606-6d850e7845eb.png)

**Comment by seangates** [comment]
As designed.
