### ISSUE TITLE
dialog: header comes as a white strip at the top and the body is grey

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#391]
# Bug Report

## Description

The dialog header comes as white strip at the top while the body is grey.
I know this is how  it looks like in the skin doc.
This looks bad to me.
Let me know what you guys think.

## Screenshots

![image](https://user-images.githubusercontent.com/13157115/44749658-09d5fc80-aac8-11e8-8fa8-57191b778b12.png)

**Comment by seangates** [comment]
As designed.
