### ISSUE TITLE
Breadcrumb - IOS- hyper links- root is black and the rest are blue

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#392]
# Bug Report

## Description
In phone x  -  safari and chrome
the breadcrumb hyper links- some are black and some are read.
repro:
go
http://ebayuicomponentstestenv.vip.qa.ebay.com/ebayUIStaging/ds4
scroll down to the breadcrumb section

## Screenshots
![ee2f5b3f-cfbc-4466-9640-80f70d270dfd](https://user-images.githubusercontent.com/13157115/44750252-b2389080-aac9-11e8-9b43-bfc576d1c64b.png)

**Comment by seangates** [comment]
This (on face value) appears to be a Skin issue.

**Comment by msendlakowski** [comment]
@hramakumar  if it looks like a styling issue, can you file it on the skin repo?   (We won't blame you for getting a few wrong)

@seangates It looks like they should all be black.  Do you know if a11y approved of that?

**Comment by seangates** [comment]
@msendlakowski This was spec'd for only DS6. If this is DS6's version we know what the colors should be. If it's DS4 we will need to simply align it to whatever we "think" DS4 should look like.

**Comment by hramakumar** [comment]
@msendlakowski  done.
https://github.com/eBay/skin/issues/355

**Comment by msendlakowski** [comment]
Closing this, as its moved to skin
