### ISSUE TITLE
combobox: Desktop- borderless - when expanded the option list width does not align 

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#398]
# Bug Report

## Description
In desktop chrome browser
when expanded the option list width does not align with the component head
actual(in ds4 it happens in borserless combox and in d6 it happens in all comboboxes)
![image](https://user-images.githubusercontent.com/13157115/44937070-5752a380-ad2c-11e8-8f80-0e97abb68908.png)

expected
![image](https://user-images.githubusercontent.com/13157115/44937112-8d902300-ad2c-11e8-89e8-9079a9669be5.png)

**Comment by msendlakowski** [comment]
@hramakumar Can you add a test URL and DS6 screenshot

**Comment by msendlakowski** [comment]
This works as designed.  According to the invision specs:

![screen shot 2018-09-11 at 1 37 50 pm](https://user-images.githubusercontent.com/1562843/45386353-05c9d480-b5c8-11e8-9c63-bbee1a7e6d02.png)
