### ISSUE TITLE
textbox: win7 and ie 11 and firefox-long text- when focus removed- it does not move to the start of the text

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#399]
# Bug Report

## Description
when long text is typed in a text box and the clicked outside.

expected: 
the text box value string is expected to be displayed from the start

actual:
it doesnt move to the beginning. it displays from somewhere in the middle.

## Screenshots
before
![image](https://user-images.githubusercontent.com/13157115/45050817-1e217880-b037-11e8-8ca2-c51ea01c45ed.png)

after
![image](https://user-images.githubusercontent.com/13157115/45050771-0a761200-b037-11e8-8c98-9596075ec998.png)

**Comment by ianmcburnie** [comment]
Closing. This is browser behaviour. You can validate here:

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_form_submit
