### ISSUE TITLE
pagination: ds4-firefox- selected page index- improve color contrast

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#400]
# Bug Report

## Description

![image](https://user-images.githubusercontent.com/13157115/45051687-a012a100-b039-11e8-82e1-d6bdbbc9b0b1.png)

**Comment by msendlakowski** [comment]
We can't fix this because we have to keep to the original DS4 skin design.  The applications will have to make sure their background color is appropriately light colored.  In the current DS4 skin demo its white.
