### ISSUE TITLE
Tabs: document differences in fake tabs

### ISSUE THREAD

**Issue by seangates** [eBay/ebayui-core#402]
# Bug Report

## Description
Per @DylanPiercey, the fake option on `ebay-tabs` does not prevent default on the links in the examples.

We should <strike>correct this and </strike>make sure the documentation accurately shows how to use the fake tabs.

**Comment by DylanPiercey** [comment]
To be consistent here we should probably change tabs to use the same pattern as the pagination and breadcrumb components: https://github.com/eBay/ebayui-core/issues/299

**Comment by msendlakowski** [comment]
@DylanPiercey Are you suggesting that we remove the "fake" attribute, and just render each `ebay-tab-heading` as either an `a` or `button` based on whether or not it has an href?  If so, I agree.

**Comment by msendlakowski** [comment]
@seangates What is the use case for adding `prevent default`?  If its a fake tab then it should be a navigation link to another page so we shouldn't want to prevent default.  Right?

**Comment by seangates** [comment]
@msendlakowski I'm advocating for whatever the breadcrumb pattern is.

**Comment by ianmcburnie** [comment]
@msendlakowski That is correct. Fake tabs should NOT prevent default. The only time it should prevent default is if it is progressively enhanced into a real tab. But that is very rare.

**Comment by ianmcburnie** [comment]
Done in 4.3.0 branch.
