### ISSUE TITLE
Menu: Support hoverable link (and stealth button) activated menu

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/ebayui-core#405]
# Bug Report

## Description
Based on [mindpatterns](https://ebay.gitbooks.io/mindpatterns/content/navigation/fakemenu.html) & demo [site](http://ebay.github.io/mindpatterns/navigation/fakemenu/), shouldn't `ebay-menu` support opening the menu on mouse hover? Or atleast for `type=fake`?

## Workaround
None

**Comment by msendlakowski** [comment]
I think we only have to support hover if the fake-menu type is a link.  In this case its a button so if I'm reading the patterns right, click is OK.

But we should create a "hover" version of the component, so putting this is the backlog for @ianmcburnie to review.

**Comment by ianmcburnie** [comment]
@msendlakowski is correct. For a11y reasons, buttons should not be activated on hover.

**Comment by ianmcburnie** [comment]
Closing this in favor of #548
