### ISSUE TITLE
ebay-select: arrow icon cut off in Edge with DS6

### ISSUE THREAD

**Issue by martin-ebay** [eBay/ebayui-core#407]
The right portion and looks like maybe a bit of the bottom of the icon are clipped like so

![screen shot 2018-09-10 at 5 03 12 pm](https://user-images.githubusercontent.com/37809937/45330707-90082f00-b51b-11e8-999f-ba77114c072e.png)

Edge  version 41.16299.611.0

**Comment by msendlakowski** [comment]
See in progress skin issue https://github.com/eBay/skin/pull/386
