### ISSUE TITLE
Select: after clicking an option the button text remains selected/highlighted (IE11)

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#411]
# Bug Report

## Description
 IE clicking an option has the entire component selected
clicking outside once again ouside the component takes the focus away.
## Screenshots
step 1:
![image](https://user-images.githubusercontent.com/13157115/45565667-09986980-b809-11e8-9dac-447208e3f779.png)
step 2: 
![image](https://user-images.githubusercontent.com/13157115/45565637-f1c0e580-b808-11e8-8973-37625433e09c.png)

**Comment by hramakumar** [comment]
when you select an option. The collapsed ebay-select shouldn't be in the selected stated. in step 2 you can see the blue area.

**Comment by ianmcburnie** [comment]
Closing as wontfix for IE11 according to browser policy (fit & finish, visual glitches).
