### ISSUE TITLE
Storybook: Update Storybook site with tailored examples

### ISSUE THREAD

**Issue by seangates** [eBay/ebayui-core#421]
# Feature Request

## Description
The (soon to be) Storybook site shows a default Markdown based on the current Markdown file for each component. The first couple of components (breadcrumb, button, carousel) have tailored example code for each. We should expand this to be tailored examples for each of the components. The current examples live in a `readme.md.js` which would be replicated in each component story.

(More details to be added later.)

**Comment by seangates** [comment]
Tracked here: https://github.com/eBay/ebayui-storybook/issues/3

**Comment by ianmcburnie** [comment]
Closing as we plan to integrate storybook as a first class citizen into our repo and work process.
