### ISSUE TITLE
Carousel: Do not animate after first render

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/ebayui-core#426]
# Feature Request

## Description
When the starting index of the carousel > 0, it animates to that slide once the page loads. It should not animate for first render either server side or after page transition after SPA.

## Context
Can be reproduced on http://app.uimarketplace.svc.32.tess.io/?pkg=@ebay/ebayui-core&tag=ebay-carousel.

**Comment by DylanPiercey** [comment]
Just going to post a work around here until we can get to this:

```marko
class {
  onCreate() {
    this.state = {
      skipAnimation: true
      ...
    }
  },
  onMount() {
    this.getComponent("carousel").once("update",  () => this.state.skipAnimation = true);
  }
}

style {
  .carousel.skip-animation .carousel__list {
    transition-duration: 0;
  }
}

<ebay-carousel key="carousel" class={ "skip-animation": state.skipAnimaiton }>
...
```

Basically this just waits for the carousel to update/calculate it's styles and then allows it to animate after that.

---

Also as I mentioned offline, ideally we would either implement a solution to just make this work with server side rendering, or pick one of the possibilities (IE: Either the first update just snaps, or animations, not configurable).

**Comment by msendlakowski** [comment]
Address when we move to Marko v4

**Comment by ianmcburnie** [comment]
Punting this to v6 as part of #963

**Comment by agliga** [comment]
Closing for now. Will address this in carousel refactor in marko 6
