### ISSUE TITLE
Carousel: touch scroll will not allow scroll to last item

### ISSUE THREAD

**Issue by scttdavs** [eBay/ebayui-core#432]
# Bug Report

## Description

When there is not a full page of items on the last page (let's say only 1 where we show 2 items per page), I cannot touch scroll to it. Tapping the next button works however. Touch scrolling between other pages works correctly, it is only the partial last page that has an issue.

## Workaround

Tapping next button?

## Screenshots

![snap-grid](https://user-images.githubusercontent.com/3631216/46440413-3c12f380-c731-11e8-8b81-3993bbbc889b.gif)

**Comment by ianmcburnie** [comment]
Fix went out in 1.0.7.
