### ISSUE TITLE
combobox: disabled- arrow icon

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#434]
# Bug Report

## Description
go to https://go/ebayui/test2
scroll down to the combobox section.
look at the arrow in the disabled combobox
![image](https://user-images.githubusercontent.com/13157115/46688736-faf86480-cbb2-11e8-847b-c56f8c96946a.png)

**Comment by ianmcburnie** [comment]
@hramakumar Is this a regression from previous version? Or a new found issue?

**Comment by hramakumar** [comment]
previous version...I have addressed it as 1.0.5

**Comment by ianmcburnie** [comment]
Fixed in Skin. Will be available in Skin v6.1.0 and Core v1.1.0
