### ISSUE TITLE
Carousel: In mobile occasionally the final scroll position can be off by a bit.

### ISSUE THREAD

**Issue by DylanPiercey** [eBay/ebayui-core#439]
# Bug Report
Currently we determine when the native scrolling has finished by polling the `scrollLeft` of the carousel element. In chrome it (no longer?) seems to be updating this every animation frame. This means that the final resting position of the carousel can be off by however much inertial scrolling is remaining.

## Description
Open the chrome dev tools or chrome on a mobile device and swipe through the carousel a bunch.

**Comment by ianmcburnie** [comment]
Fix went out in 1.0.7.
