### ISSUE TITLE
Menu: does not close on clicking the checkbox icon directly on desktop and mweb

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#44]
Repro:
ebay-menu
1) in mac safari- open up the ebay menu
2) select any item
3) click on the menu box directly- its is expected to collapse but it doesn't

**Comment by hramakumar** [comment]
[ebay ui menu close issue.zip](https://github.com/eBay/ebayui-core/files/1816687/ebay.ui.menu.close.issue.zip)

**Comment by yomed** [comment]
Fixed per https://github.com/eBay/ebayui-core/pull/129
