### ISSUE TITLE
Carousel: Hide paddles when peek enabled for mobile devices

### ISSUE THREAD

**Issue by DylanPiercey** [eBay/ebayui-core#440]
# Feature Request

## Description
Currently on mobile the paddles are always visible to allow the proper affordance needed for accessibility. This can also be achieved (and is done  on the eBay home page) by using a peeking carousel.

As discussed earlier today I recommend that we change it so that in mobile peek carousels no longer display paddles. This declutters the already space constrained mobile interface.

Alternatively we could implement a `no-controls` attribute, similar to `no-dots`. The reason I don't like that approach is because then it allows developers to make inaccessible carousels and it also requires additional knowledge from the developers to remember the attribute.

## Screenshots
![image](https://user-images.githubusercontent.com/4985201/46972716-0268b380-d074-11e8-89a7-4c4b31dac813.png)

**Comment by ianmcburnie** [comment]
I like the suggested approach. Remember that the paddles must appear when they gain keyboard focus (aka "Stealth buttons").

**Comment by seangates** [comment]
Do both need to appear, or just the one with focus?

**Comment by ianmcburnie** [comment]
Good question! I think it would be nice if both appeared.

**Comment by ianmcburnie** [comment]
Fix merged to 1.1.0 branch.
