### ISSUE TITLE
Dialog: right panel close icon position (Safari)

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#448]
# Bug Report

## Description
repro:
open a rightpanel scrollable dialog in iphone 8 plus
issue  - check for the position of the close button - it should be slightly misplaced on the top right corner.If you dont see it first. then try closing and opening it multiple times. 

## Screenshots
![image](https://user-images.githubusercontent.com/13157115/47381611-49c6f380-d6b5-11e8-9852-798c2e8d22b2.png)

**Comment by seangates** [comment]
@hramakumar I can't reproduce this. Can you confirm the steps?

![image](https://user-images.githubusercontent.com/105656/47379534-67498c80-d6b8-11e8-9e98-bfc766fdf652.png)

**Comment by hramakumar** [comment]
i believe you are trying issue 1
try moving the screen a little more to the left a little
if that does not help then try it in the test page instead of the local

**Comment by hramakumar** [comment]
also try opening and closing the dialog multiple times

**Comment by hramakumar** [comment]
and also are you using iphone 8 plus?

**Comment by seangates** [comment]
Yes, using iPhone 8 Plus. Responded via Slack:
>I think the dialog issue you’re seeing in #448 is related to your environment as your mWeb version is not truly mWeb because the page width is much wider than the screen width. This is causing a whole host of other issues. Specifically, in a normal mWeb page you _can’t_ zoom as it’s disabled. Whereas with your test page you _can_ zoom. Let’s try and fix that and see if it makes a difference.

**Comment by ianmcburnie** [comment]
Needs re-verification.

**Comment by DylanPiercey** [comment]
@hramakumar I just checked this out on the latest version with the Marketplace and I'm not seeing the issue now. Can you confirm this is fixed in your sample app?

**Comment by ianmcburnie** [comment]
Assigning to @hramakumar for verification in latest build.

**Comment by hramakumar** [comment]
its working fine now
