### ISSUE TITLE
Dialog: right panel pinch and zoom issues (Safari)

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#449]
# Bug Report

## Description
open the right panel scrollable dialog...try moving the dialog towards left- it moves out of focus. also try using two fingers to zoom in and  zoom out...sometimes it gets stuck outside in the background area.
repro:
in iphone 8 plus safari
go to http://ebayuicomponentstestenv.vip.qa.ebay.com/ebayUIStaging/ds4
 try moving the dialog to the left. it moves out of focus

also try try few other actions like use two fingers to zoom in zoom out- sometimes it hangs(does not happen frequently) 

## Notes

Dylan: it appears to only happen for me when you grab the dialog as it is animating in

**Comment by ianmcburnie** [comment]
We are going to reinvestigate this for 2.7.0

**Comment by DylanPiercey** [comment]
@hramakumar I just checked this out on the latest version with the Marketplace and I'm not seeing the issue now. Can you confirm this is fixed in your sample app?

**Comment by ianmcburnie** [comment]
Assigning to @hramakumar for verification in latest build.
