### ISSUE TITLE
Menu: clicking on a checkbox menu item collapses the menu sometimes

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#45]
repro:
open the ebay-menu checkbox
select on a couple of items
it is expected to stay expanded until I collapse it by hitting the menu head
but it collapses at some selections

**Comment by yomed** [comment]
@hramakumar The menu uses `autocollapse` functionality so that it collapses when the user's mouse leaves the menu area. Can you confirm that the collapsing here is not due to that?

**Comment by hramakumar** [comment]
no its not because the mouse leaves the menu area. It happens while selecting an item.

**Comment by hramakumar** [comment]
[ebay ui check box issue.zip](https://github.com/eBay/ebayui-core/files/1816759/ebay.ui.check.box.issue.zip)

**Comment by yomed** [comment]
@hramakumar Can you verify if this is still an issue? The menu expansion was refactored recently.

**Comment by yomed** [comment]
Verified by @hramakumar. Fixed per https://github.com/eBay/ebayui-core/pull/129
