### ISSUE TITLE
Dialog: close button issues with scrollable right panel

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#450]
# Bug Report

## Description
Repro

repro:
open a rightpanel scrollable dialog in iphone 8 plus
check for the position of the close button - it should be slightly misplaced on the top right corner. try closing and opening it multiple times. once after we get the misplaced the close icon.
then try zooming the dialog a little
issue  - a new close button appears at the  top left

## Screenshots
![closeicon](https://user-images.githubusercontent.com/13157115/47326802-54cf4480-d61f-11e8-9e60-2fb9520e4bb7.jpg)

**Comment by ianmcburnie** [comment]
Assigning to @hramakumar for verification in latest build.

**Comment by hramakumar** [comment]
The issue still happens only on IE

**Comment by ianmcburnie** [comment]
Thanks for the clarification. Demoting to backlog.

**Comment by ianmcburnie** [comment]
Closing as wontfix for IE11 according to browser policy (fit & finish, visual glitches).
