### ISSUE TITLE
Carousel: Native scrolling animation slow in IOS

### ISSUE THREAD

**Issue by DylanPiercey** [eBay/ebayui-core#454]
# Bug Report

## Description
Currently the native inertial scrolling deceleration in mobile safari is much slower than chrome which makes the snap animation look a bit too delayed.

## Screenshots

![carousel-ios-native-scrolling](https://user-images.githubusercontent.com/4985201/47389788-8a7d3780-d6ca-11e8-95a6-5aadbff313e5.gif)

**Comment by ianmcburnie** [comment]
Fix merged to 1.1.0.
