### ISSUE TITLE
Textbox: add icon capabilities

### ISSUE THREAD

**Issue by seangates** [eBay/ebayui-core#456]
# Feature Request

## Description

The textbox has been spec'd in DS4 & DS6 with prefix and postfix icons. These prefix and postfix icons should be added to the component and allowed to be configured by the developer.

## Context

This capability is already available in Skin for DS4 and DS6.

## Screenshots

![image](https://user-images.githubusercontent.com/105656/47453647-831d6300-d78a-11e8-903c-38eec06640a4.png)

**Comment by ianmcburnie** [comment]
Merged to 1.3.0 branch.
