### ISSUE TITLE
Menu/Select: button takes two clicks to expand

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#46]
takes first click to select the component and second click to expand the menu.
it does not happen always but happens pretty frequently.
the same happens with collapse

**Comment by seangates** [comment]
Desktop or mWeb?

**Comment by hramakumar** [comment]
happens on both. more frequent in desktop.

**Comment by hramakumar** [comment]
[ebayui test recording.zip](https://github.com/eBay/ebayui-core/files/1816709/ebayui.test.recording.zip)

**Comment by yomed** [comment]
Verified by @hramakumar. Fixed per https://github.com/eBay/ebayui-core/pull/129
