### ISSUE TITLE
Select: Selecting first element emits the wrong data

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/ebayui-core#460]
# Bug Report

## Description
`ebay-select` is not returning the right `index/selected/el` when you try to select the first element. For. e.g. the select has 3 elements, when you try to select the first element it returns index: 1. 
Use marko 4.13.7 you would notice the bug.

## Context
It should invoke `this.update()` outside the `.map` function. 

```
options = options.map((option, i) => {
  if (option.value === newOptionSelectedValue) {
    option.selected = true;
    this.setState('selectedIndex', i);
    this.setState('value', option.value);
  } else {
    option.selected = false;
  }
  this.update();
  return option;
});
```
Make this change, resolves the issue. 

## Workaround
None

**Comment by ianmcburnie** [comment]
Fix went out in v0.9.2. Closing.
