### ISSUE TITLE
Carousel:continuous -  chrome - Native scrolling animation slow in android

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#463]
# Bug Report

## Description
pls refer to the issue for IOS here.
https://github.com/eBay/ebayui-core/issues/454

its the same in android

https://www.useloom.com/share/ae118b3f471a4ace9a428843c6c6571e

**Comment by ianmcburnie** [comment]
Merged to 1.2.0 branch. Needs verification in 1.2.0-0 release.
