### ISSUE TITLE
Carousel: continuous-  auto-adjust - decrease 20%  snap back threshold for large slides

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#464]
# Bug Report

## Description
Since there has to be atleast 20% of the next slide to be in view to auto adjust to the next slide. When the slide is is big it is required to move  the slide more than usually expected, without removing the finger,  to get to the next slide
We need to reduce this threshold
https://www.useloom.com/share/de1c3f0c5dd64cb79128ff32206ca0df

This is for continuous, auto adjust carousel.

**Comment by DylanPiercey** [comment]
Since #477 the carousel has switched to using the native browser scrolling. Because of this these thresholds have changed and they are no longer configurable (left up to the browser).
