### ISSUE TITLE
Carousel: adjust speed and reach of the carousel "flick" movement

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#465]
# Bug Report

## Description
In IOS Safari, after the auto adjust feature added in 1.1.0, it is no longer easy to get to the end of the carousel (>10 cards) in one flick.
The flick speed and the speed with which the carousel moves does not match.

**Comment by ianmcburnie** [comment]
Merged to 1.2.0 branch. Needs verification in 1.2.0-0 release.
