### ISSUE TITLE
Carousel: continuous -the white space that appears and disappears when we try to scroll past the last card is no longer present 

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#466]
# Bug Report

## Description
the white space that appears and disappears when we try to scroll past the last card is no longer present.
With the current design it looks more like the carousel is stuck in the position when I try to scroll past the last card.

**Comment by seangates** [comment]
How can this be both a bug and an enhancement?

**Comment by seangates** [comment]
(Per the labels.)

**Comment by ianmcburnie** [comment]
Merged to 1.2.0 branch. Needs verification in 1.2.0-0 release.
