### ISSUE TITLE
Carousel: auto adjust to the right  when cards are moved to the left

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#467]
# enhancement

## Description
when cards are moved to left, the users are viewing it to their right and we expect the auto adjust to adjust the card to the right instead of left. 

https://www.useloom.com/share/e91a5233c39043618bf0aacd3cb789cb

when cards moved to the right- the cards are auto-adjusted to the left
when moved to left- the cards are still auto-adjusted to the left- it would make more sense to auto adjust the cards to the right.

**Comment by seangates** [comment]
Title says but, but issue says enhancement. Which is it?

**Comment by msendlakowski** [comment]
Let's evaluate or close this while working on the Carousel DS6.5 enhancements.

**Comment by ianmcburnie** [comment]
Not really sure this ask is valid, but bringing forward so I don't forget to discuss it with designers.

**Comment by ianmcburnie** [comment]
Closing this one for now. It's not something that teams or designers are asking for.
