### ISSUE TITLE
Carousel- continuous-chrome android- left scroll/reverse scroll movements need the the next card to be exposed 80% instead of 20%(as in right side scroll), to auto-adjust.

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#468]
# Bug Report

## Description
right scroll movements need the next card to be exposed 20% to auto-adjust to the next card
but for left scroll we expect the threshold to be same but instead, it is 80%
https://www.useloom.com/share/e91a5233c39043618bf0aacd3cb789cb

here we expect the auto adjust to take in card 2 but instead, it snaps back to card 3

**Comment by ianmcburnie** [comment]
Not entirely convinced yet that this is a blocker, but @DylanPiercey is this potentially a quick fix?

**Comment by hramakumar** [comment]
this hinders the reverse scroll functionality and there is no workaround . The user has to scroll a lot more to move to the next slide. This is not as subtle as https://github.com/eBay/ebayui-core/issues/464 as this is 80% it looks more obvious which is why I filed it as blocker and yes I spoke with dylan , he is working on the patch.

**Comment by ianmcburnie** [comment]
Thanks for the clarification @hramakumar

**Comment by DylanPiercey** [comment]
Patch is here: https://github.com/eBay/ebayui-core/pull/469 a very simple fix.

**Comment by senthilp** [comment]
Less optimal is the feedback that I received from Hemnath. It is a trade-off now. Can we make the call on Friday?

**Comment by ianmcburnie** [comment]
Well, there's also a few of us that don't think it's less optimal. This is highly subjective territory of course! Let's demo it on Friday and make the call then.

**Comment by ianmcburnie** [comment]
This issue is fixed. Closing ticket, but we will still discuss the larger topic of whether we want to keep the new scrolling experience.
