### ISSUE TITLE
Tests: Improve integration and v4 testing

### ISSUE THREAD

**Issue by yomed** [eBay/ebayui-core#47]
Porting over some notes from the old repo:
- Improve cleanup in failure case
- Use `npm pack`
- Verify no errors in browser console
- Move main functionality to standalone package
- Investigate improvements to Marko to allow multiple versions to be installed at the same time
- Improve local debugging of testing against v4

**Comment by ianmcburnie** [comment]
Closing, as I'm not sure how relevant this still is and it's been on the backlog a long time.
