### ISSUE TITLE
Carousel: update LESS variables because of Lasso changes in Skin v7

### ISSUE THREAD

**Issue by seangates** [eBay/ebayui-core#470]
This issue is created to track an issue which arises by splitting the DS6 and DS4 variables in Skin based on the `skin-ds6` Lasso flag. The issue is described in https://github.com/eBay/skin/pull/406/files.

Therefore, we must update the carousel to support the appropriate variables with whichever design system is used.

The issue was found when attempting to switch to DS4 in the demo app of this project.

**Comment by ianmcburnie** [comment]
Merged to 2.0.0 branch. Closing.
