### ISSUE TITLE
Carousel: Switch to native scroll snapping implementation.

### ISSUE THREAD

**Issue by DylanPiercey** [eBay/ebayui-core#476]
# Feature Request

## Description
Currently we have a hybrid approach of using native scrolling with snap points taken care of by JS. The shortcomings of this approach has been performance degradation and lack of control in some cases. As discussed we have opted to try using the native scroll snap points for browsers that support it.

**Comment by ianmcburnie** [comment]
Merged to 1.2.0 branch. Needs verification in 1.2.0-0 release.
