### ISSUE TITLE
Polyfill strategy

### ISSUE THREAD

**Issue by DylanPiercey** [eBay/ebayui-core#48]
### Details
Currently in IE there are two runtime features being used that are not polyfilled.

1. `Array.prototype.find` (https://github.com/eBay/ebayui-core/blob/0.1.0/src/components/ebay-select/index.js#L31)
2. `Promise` (used by Marko internally).

### Possible Fix
1. We should probably just avoid Array methods added post IE9.
2. I'm not sure if it was intended for `Promise` to sneak into the Marko codebase, @mlrawlings what are your thoughts? For now we could just include a promise polyfill with this library, or at least recommend a polyfill.

**Comment by ianmcburnie** [comment]
Strategy for now, as we only have one offending method, is to avoid use of poly fills until (if) we reach a critical mass.

Please keep this list of methods updated:

* Array.prototype.find (no IE support)

**Comment by ianmcburnie** [comment]
I'm going to close this because it's not an immediate issue. We can still find it under closed issues in order to edit the above list.
