### ISSUE TITLE
Dialog: Unable to scroll on body after quickly re-rendering dialog multiple times

### ISSUE THREAD

**Issue by dkallus** [eBay/ebayui-core#480]
# Bug Report

## Description
I’m using `ebay-dialog` full screen and (1) if I re-render dialog soon after it's first opened and (2) then close the dialog by clicking (X) button, scrolling on main page/body is still blocked. 

## Screenshots
Screenshot of body styles after has already been opened and then re-rendered again:
<img width="342" alt="css_dialog_opened" src="https://user-images.githubusercontent.com/844822/48649916-140de580-e9a9-11e8-9b18-8f38474a8a9d.png">

Screenshot of body styles after clicking (X) button to close dialog:
<img width="344" alt="css_dialog_closed" src="https://user-images.githubusercontent.com/844822/48649935-2851e280-e9a9-11e8-8abb-d3e9c37f30a7.png">

**Comment by ianmcburnie** [comment]
Thanks for finding and creating this issue @dkallus!

**Comment by ianmcburnie** [comment]
Merged to 1.3.0
