### ISSUE TITLE
Combobox: when options have long text, the font size of option is bigger than usual -ds4-IOS-

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#482]
# Bug Report

## Description
when options have long text, the font size of option is bigger than usual

## Screenshots
![combo jpg](https://user-images.githubusercontent.com/13157115/48866579-22347b00-ed88-11e8-92be-b2650dc9ade5.png)

**Comment by seangates** [comment]
I'll have a look.

**Comment by ianmcburnie** [comment]
We are deprecating the current combobox as we know it, in v2. We will not be fixing this issue in v1.x branch. Closing ticket.
