### ISSUE TITLE
ebay-icon: Support server side only rendering (split component).

### ISSUE THREAD

**Issue by DylanPiercey** [eBay/ebayui-core#483]
# Feature Request

## Description
Currently the `<ebay-icon>` needs to be rendered under a component because it expects that component to pass it the appropriate icons to render. This means that if you use the `ebay-icon` on a static page for example it will cause an error in the browser.

This should be fixable by switching this component to be a split component.

**Comment by ianmcburnie** [comment]
Merged to 1.3.0 branch.
