### ISSUE TITLE
Replace GitHub services with GitHub Apps

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#486]
GitHub services have been officially deprecated and will stop working on January 31, 2019.

We need to replace the Travis service with the [Travis app](https://github.com/marketplace/travis-ci) from GitHub marketplace. Only a member with admin rights can do this (cough, @seangates). Make sure to select the free version for open source.

GitHub docs:
https://developer.github.com/changes/2018-04-25-github-services-deprecation/

Travis docs:
https://docs.travis-ci.com/user/open-source-on-travis-ci-com/

Once the app is in place we should be able to access it from PRs via the "checks" tab.

<img width="1011" alt="screen shot 2018-11-28 at 9 15 14 am" src="https://user-images.githubusercontent.com/38065/49169197-27487b80-f2ee-11e8-9c65-c3124cb08d77.png">

**Comment by seangates** [comment]
I've enabled the app. Can you confirm, @ianmcburnie?

**Comment by ianmcburnie** [comment]
I see it's installed now, thanks. We can probably confirm if it's working next time we push some code.

**Comment by ianmcburnie** [comment]
On the Travis side of things, it looks like this repo needs migrating from the old travis-ci.org to the new travis-ci.com. But that option isn't available yet:

<img width="621" alt="screen shot 2018-11-28 at 10 04 26 am" src="https://user-images.githubusercontent.com/38065/49172175-2830db80-f2f5-11e8-8315-99a972fb85d8.png">

 Oh well, at least we have this GitHub piece in place for now.

**Comment by seangates** [comment]
😞

**Comment by seangates** [comment]
https://github.com/travis-ci/travis_migrate_to_apps

**Comment by ianmcburnie** [comment]
Looks like they've added an easier way to migrate apps from .org to .com. I'll do Skin first and see how it goes...

**Comment by ianmcburnie** [comment]
Skin and CoreUI now migrated to Travis.com. Please update your bookmarks. Closing.
