### ISSUE TITLE
textbox: icons not displayed in multiline textboxes

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#487]
# Bug Report

## Description
icons are not displayed in multiline texboxes
## Screenshots
go to http://ebayuicomponentstestenv.vip.qa.ebay.com/ebayUIStaging
under the textbox section look for the headings
"icon with placeholder- multiline"
![image](https://user-images.githubusercontent.com/13157115/49545330-29807c00-f892-11e8-91e6-cc5212874635.png)

**Comment by seangates** [comment]
This is the expected behavior. It's only available on single-line versions of the component.
