### ISSUE TITLE
Carousel: carousel-slide event provides incorrect slide data

### ISSUE THREAD

**Issue by ipmincubus** [eBay/ebayui-core#488]
# Bug Report

## eBayUI Version: x.x.x
1.0.5
## Description

Click right arrow for a couple times, and click left arrow, and observe the slide data provided by carousel-slide event. Even I am on the first slide, the slide data shows me slide is 2
## Screenshots

<img width="1423" alt="screen shot 2018-12-05 at 1 11 19 pm" src="https://user-images.githubusercontent.com/39746572/49544370-8c244880-f88f-11e8-89fd-38461187e4ef.png">

**Comment by ianmcburnie** [comment]
Merged to 1.3.1. branch. Closing ticket.
