### ISSUE TITLE
badge: we display negative, decimal numbers and 0- pls do the validation to check all nos are positive whole numbers

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#490]
# Bug Report

## Description
we display negative, decimal numbers and 0- pls do the validation to check all nos are positive whole numbers
repro:
go to https://go/ebayui/test
look at the badge section
search for labels badge_negative and badge_0
## Screenshots
![image](https://user-images.githubusercontent.com/13157115/49605665-fc8da100-f945-11e8-81dc-5db5851229b5.png)

it also accepts decimal numbers. WIll post that screenshot later

**Comment by ianmcburnie** [comment]
Fixed by @BhavinPatel04 and merged to 2.0.0 branch. Closing.
