### ISSUE TITLE
badge: disabled and partially disabled buttons does not showing badge

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#491]
# Bug Report

## Description
Disabled and partially disabled buttons does not show badge.
http://ebayuicomponentstestenv.vip.qa.ebay.com/ebayUIStagingIsolation/ds4?type=badge_6

**Comment by seangates** [comment]
@hramakumar @ianmcburnie @gbeckpdx What was the final decision on this.

**Comment by ianmcburnie** [comment]
We decided not to show a badge when button is disabled. So I will close this.
