### ISSUE TITLE
Replace occurrences of background icons (span tag) with foreground icons (svg tag)

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#500]
Any internal dependency on the skin background icon module causes a perf hit due to the significant CSS payload it imports. Let's convert any occurrences of background icons (i.e. the span) tag to foreground icons (i.e. the svg tag).

**Comment by ianmcburnie** [comment]
Let's see if we can fix this in a 1.3.x or 1.4 release. Otherwise, 2.0.0 it will have to be.

**Comment by seangates** [comment]
Completed in #511.
