### ISSUE TITLE
Touch carousel does not work after deploying

### ISSUE THREAD

**Issue by scttdavs** [eBay/ebayui-core#504]
# Bug Report

## Description
The touch version of the carousel works locally but not after deploying. It seems the compressor the resource server uses affects some css that is needed. See the diff below.

After reproducing locally, applying the correct uncompressed style inline fixes it.

## Screenshots
![image](https://user-images.githubusercontent.com/3631216/50991039-bb0e8980-14e1-11e9-827a-21366d4abb03.png)

**Comment by ianmcburnie** [comment]
Fixed in v1.3.2
