### ISSUE TITLE
Menu: menu item with nested button/anchor object index is handled incorrectly

### ISSUE THREAD

**Issue by FlyingWHR** [eBay/ebayui-core#514]
# Bug Report

## Description

for ebay-menu-item with nested anchor tag, the item index from on-menu-select event handler is incorrect

this logic of getting item index only goes one level up, if the click event is triggered by nested item it would fail to find the correct menu-item index
https://github.com/eBay/ebayui-core/blob/5af1b7b0280fc3b87dccb60c96a68da9e8f62d05/src/components/ebay-menu/index.js#L327-L329

## Workaround

not using nested anchortag element / use manual event binding

**Comment by FlyingWHR** [comment]
@seangates You had some accessibility concerns regarding this one, let me know if we want this change so i can work on a PR

**Comment by ianmcburnie** [comment]
We shouldn't be nesting interactive elements like anchors inside of the menuitem. The menuitmem itself *is* the interactive element.

**Comment by ianmcburnie** [comment]
@seangates Can we close this as "wont fix", or is there any additional information in README you'd like to add to prevent users from doing this?

**Comment by seangates** [comment]
Assigned to myself to take on. Let's leave it open for now for tracking.

**Comment by ianmcburnie** [comment]
Any updates on this? Otherwise, let's close.

**Comment by seangates** [comment]
No additional information.
