### ISSUE TITLE
ebay-menu item wraps very easily

### ISSUE THREAD

**Issue by scttdavs** [eBay/ebayui-core#517]
# Bug Report

## Description

Between v1.2 and v1.3, a span tag that was rendered for ebay-menu items is no longer rendered. Skin used to apply a truncation mixin to this which kept the items from wrapping. This mixin is no longer applying. The result is that the menu items wrap very easily. The issue is more pronounced when using an icon button.

## Workaround

The work around is to apply your own truncation class or logic to the menu item, which keeps it from wrapping.

## Screenshots

From marketplace:
![image](https://user-images.githubusercontent.com/3631216/51913240-137bcd00-23a4-11e9-87e7-a1f8694cb451.png)

https://github.com/eBay/ebayui-core/compare/v1.2.0...v1.3.0
![image](https://user-images.githubusercontent.com/3631216/51913294-2db5ab00-23a4-11e9-950a-f600558fdaf8.png)

Skin css that used to apply to it:
https://github.com/eBay/skin/blob/d8cf68c914be6162557943121aaf527896a8384e/src/less/dropdown/base/dropdown.less#L115-L123

**Comment by ianmcburnie** [comment]
Thanks for reporting this in detail, @scttdavs. We will begin investigating and scoping out the fix.

**Comment by seangates** [comment]
Out in pre-release to be able to test: v1.4.0-1

@scttdavs Please confirm if you have time. We will still QA it through normal means, but your feedback is appreciated.

https://github.com/eBay/ebayui-core/pull/515/files#diff-680e9f2db0d343bf92888173a21bccd4R36

**Comment by ianmcburnie** [comment]
Closing.
