### ISSUE TITLE
ebay-icons:  Inline Icons- size is shrunk

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#519]
# Bug Report

## Screenshots
before
![image](https://user-images.githubusercontent.com/13157115/52019613-2923ec00-24a3-11e9-818e-160f384b3587.png)
after
![image](https://user-images.githubusercontent.com/13157115/52019624-380a9e80-24a3-11e9-8402-0c18337e2a71.png)

**Comment by ianmcburnie** [comment]
Fixed (hopefully), in Skin 6.3.4.

**Comment by hramakumar** [comment]
verified.
