### ISSUE TITLE
Textbox: does not support passing input/button id value

### ISSUE THREAD

**Issue by kmlhossen** [eBay/ebayui-core#520]
I was trying out ebay-textbox from https://github.com/eBay/ebayui-core/tree/2.0.0/src/components/ebay-textbox
But seems like if I pass a value for textbox id field, like below
 

`<ebay-textbox id="userid" floating-label="Email or username" fluid=true/>`

 
The rendered textbox get an auto generated id like s0-0-15-7-4 it does not honor the passed in value.

Passing name value works fine.

**Comment by ianmcburnie** [comment]
Thanks for reporting this @kmlhossen . We will make sure this is fixed before final release.

**Comment by seangates** [comment]
Merged, ready for QE.

**Comment by ianmcburnie** [comment]
I'll let you verify this one @seangates
