### ISSUE TITLE
Menu: default "growth" behaviour seems to be broken

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#521]
# Bug Report

## Description
when menu options have more than one line....it looks like two menu options. There is no way to distinguish between a two-line menu options and regular one-line menu option without hover over.
need some boundary lines distinguishing the menu oprions. 

EDIT BY IAN: the menu should be growing in width with the menu item text, not wrapping. So it's a bug. Updating to title to reflect this.

## Screenshots
before mouse over
![image](https://user-images.githubusercontent.com/13157115/52079872-62b03200-254b-11e9-9894-2c4b660c0047.png)
after mouse over
![image](https://user-images.githubusercontent.com/13157115/52079930-7fe50080-254b-11e9-871b-6bf90a3fe7e1.png)

**Comment by ianmcburnie** [comment]
@seangates Shouldn't that menu be growing with the text?

**Comment by seangates** [comment]
Yes.

**Comment by ianmcburnie** [comment]
Ok. I guess this will need investigating/fixing for v2. The skin side seems to be working fine. So possibly a coreui or test page issue.

**Comment by seangates** [comment]
@hramakumar I can't seem to recreate the issue. I'm having trouble connecting to the corp network from my Windows laptop, so I ask that you confirm on your side if you're still seeing this issue.

Chrome on Mac:
![image](https://user-images.githubusercontent.com/105656/52320747-3ef74c80-298e-11e9-9970-bcdeb8bada01.png)

**Comment by ianmcburnie** [comment]
I'm also unable to repro. Also, given that grow is the default behaviour now, you can probably remove the grow test. Up to you.

**Comment by ianmcburnie** [comment]
Unable to repo in demo or marketplace. Closing
