### ISSUE TITLE
Checkbox: label height is a little lower than ususal

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#522]
# Bug Report

## Description
check box if you look at the options label. Its not aligned with the center in height.
Happens only in desktop.
## Screenshots
![image](https://user-images.githubusercontent.com/13157115/52081972-70b48180-2550-11e9-8a66-fe93306ad476.png)

**Comment by hramakumar** [comment]
![image](https://user-images.githubusercontent.com/13157115/52082060-a194b680-2550-11e9-996a-a1f918773c0d.png)

**Comment by ianmcburnie** [comment]
Not seeing this issue in skin v7.0.0:

<img width="299" alt="screen shot 2019-02-05 at 9 49 27 am" src="https://user-images.githubusercontent.com/38065/52293320-5e10c280-292b-11e9-98f1-c8f1242eea91.png">

@hramakumar can you please reverify this in coreui v2 prerelease.

I'm not sure we will go back and fix this in v1.x branch.

**Comment by hramakumar** [comment]
i still see it in the test page
![image](https://user-images.githubusercontent.com/13157115/52296404-1f7f0600-2933-11e9-98e5-d89bea37db28.png)
http://ebayuicomponentstestenv.vip.qa.ebay.com/ebayUIStagingDesktop2

**Comment by ianmcburnie** [comment]
Thanks @hramakumar . Can you compare with Marketplace and see if you get similar results?

**Comment by hramakumar** [comment]
yes the issue is there in marketplace but its towards the top
![image](https://user-images.githubusercontent.com/13157115/52296934-6de0d480-2934-11e9-80b6-dfb4b170eb2e.png)

**Comment by hramakumar** [comment]
windows and chrome browser

**Comment by ianmcburnie** [comment]
Dev note:

Discrepancy in Marketplace/demo page is due to these two factors:

1. This hack in global module
1. Global module is not imported on demo page

On the skin side, I need to investigate that hack a little more and see why it's in the global module and if we can move it.

**Comment by ianmcburnie** [comment]
This raises another issue that we should really be including the global module in all of our demo pages.

**Comment by ianmcburnie** [comment]
Opened related ticket: https://github.com/eBay/ebayui-core/issues/545

**Comment by ianmcburnie** [comment]
I remember now why this hack was there. At the time we didn't have the field module in ds6. Now we do, these rules can be moved over.

**Comment by ianmcburnie** [comment]
Skin PR is here: https://github.com/eBay/skin/pull/553

**Comment by ianmcburnie** [comment]
Fixed in Skin. Available in next prerelease. Closing.

**Comment by ianmcburnie** [comment]
Verified.

<img width="282" alt="screen shot 2019-02-15 at 8 16 14 am" src="https://user-images.githubusercontent.com/38065/52869226-07a93e00-30fa-11e9-9908-92e294dff900.png">

On a side note, the ds4 labels are now a little too close to the checkbox. I'll quickly add a fix to skin for that:

<img width="267" alt="screen shot 2019-02-15 at 8 17 22 am" src="https://user-images.githubusercontent.com/38065/52869275-24457600-30fa-11e9-8b94-a23148262d0f.png">
