### ISSUE TITLE
Icon: inline icons are broken - v7.0.0-5

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#524]
ebayui 2.0.0-2 and skin 7.0.0-5

Inline icons are broken on ds4 page
![inlineicons](https://user-images.githubusercontent.com/13157115/52146680-51cdf200-2619-11e9-87b5-d2fdc542525e.png)
http://ebayuicomponentstestenv.vip.qa.ebay.com/ebayUIStaging2/ds4

**Comment by ianmcburnie** [comment]
Couple of reason for this:

1. Some icons were renamed, e.g. `icon--download` became `icon--skin` (look under "New DS4 aliases here: https://github.com/eBay/skin/pull/525)
1. I have a feeling you are running into this bug: https://github.com/eBay/skin/issues/540 (I am working on a fix for this)

**Comment by ianmcburnie** [comment]
Skin PR is here: https://github.com/eBay/skin/pull/542

**Comment by ianmcburnie** [comment]
Fix will be available in Skin v7.0.0-6. In the meantime, please update any old icon names with the new names.

**Comment by ianmcburnie** [comment]
Needs additional work on coreui side to update symbols.

**Comment by seangates** [comment]
Closing since it was moved to "Done".
