### ISSUE TITLE
tooltip: when style is given and pointer not given- the default pointer is pointing down instead of up

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#532]
# Bug Report

## Description

when style is given and pointer not given- the default pointer is pointing down instead of up

## Screenshots
![arrow_pointing_down](https://user-images.githubusercontent.com/13157115/52285050-8512c880-291a-11e9-936c-0bf1f03de3a8.png)

**Comment by ianmcburnie** [comment]
@seangates Is this expected behaviour? Not sure this is a blocker in any case.

**Comment by ianmcburnie** [comment]
I think we might be able to close this one as not an issue. Will let @seangates comment.

**Comment by seangates** [comment]
I believe we expect folks to use the `pointer` attribute as it will add the necessary classes to the tooltip content container, as well as to the arrow. If folks get confused down the road, I'm sure we'll hear of it, and we can add some to the documentation. As of now, I don't think this is an issue.
