### ISSUE TITLE
change attribute name location to pointer in market place for infotip and tooltip

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#533]
# Bug Report

## Description
change attribute name location to pointer in market place

**Comment by ianmcburnie** [comment]
Done in v2.0.0 branch.

**Comment by ianmcburnie** [comment]
Verified in marketplace

<img width="927" alt="screen shot 2019-02-15 at 11 11 03 am" src="https://user-images.githubusercontent.com/38065/52878821-74303700-3112-11e9-8d7e-641a1ba0496e.png">
