### ISSUE TITLE
Pill: "primary" priority doesn't work as expected

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#534]
# Bug Report

## Description
when priority primary is given it displays only secondary

## Screenshots
https://www.useloom.com/share/c6319d6e082c4b34b979c3cc4e3850a8

**Comment by hramakumar** [comment]
2 bugs here
1) priority primary doesnt work fine
2) when I explicitly mention the priority as secondary- it has the above behaviour as shown. the default secondary works fine

**Comment by seangates** [comment]
Merged.

**Comment by hramakumar** [comment]
So the priority attribute does not have values ready yet? When are we expecting to have a primary? if I give priority its not defaulting to the secondary.
Secondary behaviour here is not as expected.
pls check how the pill with priority behaves. once the pill is pressed it turns blue...while in case of a secondary button only the border focus turns blue (edited) 
and when clicked on the page..it still retains the blue color and looks like a primary.

**Comment by seangates** [comment]
The pill is not a traditional button. There is no concept of a primary or secondary pill, but rather those styles become the “pressed” or “un-pressed” state of the button.

**Comment by ianmcburnie** [comment]
@seangates While working on the CTA button backport I noticed this:

Pill Button

Use the pill modifier to create a button styled as a pill. It should be used in conjunction with primary/secondary modifiers for full styling. Note that the Button only supports one size, so it should not be used together with sizing modifiers. Additionally, JavaScript should be used for multi-line ellipsis truncation.

This text seems to conflict with the previous comment.
