### ISSUE TITLE
Infotip: close button goes outside the component with long words (mweb/dweb)

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#536]
# Bug Report

## Description
In mweb, both Android and IOS
When the infotip body is long The close button goes outside the component boundary

## Screenshots

![image](https://user-images.githubusercontent.com/13157115/52298237-640ca080-2937-11e9-8ba4-5d7a021e43b9.png)

**Comment by hramakumar** [comment]
reproducible in chrome simulation

**Comment by ianmcburnie** [comment]
Reproducible in Skin on desktop when there is a really long word:

<img width="809" alt="screen shot 2019-02-05 at 11 35 50 am" src="https://user-images.githubusercontent.com/38065/52299450-44c34280-293a-11e9-8e0f-1097ef73afd9.png">

**Comment by ianmcburnie** [comment]
@hramakumar This appears to only happen with really long unbroken words, so could we reduce this to a non-blocker?

**Comment by hramakumar** [comment]
but isn't it common to have long texts in infotips?

**Comment by ianmcburnie** [comment]
Long text is behaving fine for me. It appears to be the really long word that breaks things.

**Comment by ianmcburnie** [comment]
Can you verify that is same for you?

**Comment by hramakumar** [comment]
yes I did.  you are right

**Comment by ianmcburnie** [comment]
Fixed in Skin. Will be in next coreui pre-release. Closing.
