### ISSUE TITLE
Tooltip: tooltip on text box does not disappear when clicking page

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#537]
# Bug Report

## Description
When a tooltip shows up on a textbox there is no way to make it disappear.
moving the focus out does not help

## Workaround

https://www.useloom.com/share/8d0d5dd3517d48fba39b59203e0e9c55>

**Comment by ianmcburnie** [comment]
Note to self: expander does currently support this ability to collapse when clicking page:

https://github.com/makeup-js/makeup-expander/blob/master/src/index.js#L11

For some reason the auto collapse feature is not setting this (by accident or design):

https://github.com/makeup-js/makeup-expander/blob/master/src/index.js#L130

**Comment by ianmcburnie** [comment]
Fixed merged to 2.0.0 branch. Closing.

**Comment by ianmcburnie** [comment]
Verified in demo page and marketplace.
