### ISSUE TITLE
Badge: the position of the badge is wrong

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#542]
# Bug Report

## Description
The position of the badge number is wrong when it comes with a button. it is expected to be towards right  of the button but it is actually at the bottom of the button 
## Screenshots
![badge button icon](https://user-images.githubusercontent.com/13157115/52146116-b7b97a00-2617-11e9-9f4e-0146539d3b39.png)

**Comment by seangates** [comment]
Yeah, apologies. 😞

**Comment by ianmcburnie** [comment]
@seangates Good spot regarding the missing code. Is there an easy way to figure out everything that's missing?

**Comment by seangates** [comment]
No easy way, other than going through the files line by line. Luckily, I know this code pretty well.

It also shows that we should be _very_ careful when we're merging/rebasing and have conflicts. Blame shows it's my fault, and I'm happy to take that blame, but there might have been another action throughout which showed the issue.

**Comment by seangates** [comment]
Merged.

**Comment by ianmcburnie** [comment]
Fix verified in demo page and marketplace.
