### ISSUE TITLE
Textbox: floating label text clashes with browser autofill text

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#557]
Screenshot:

![screen shot 2019-02-19 at 12 29 39 pm](https://user-images.githubusercontent.com/38065/53045336-36008380-3442-11e9-94a1-2d70a2d7ed67.png)

Last time we checked, the browser doesn't give us an event for when this autofill takes place.

Possible solutions:

1. The underlying `makeup-floating-label` module has a `refresh()` method. We could expose that and allow app to handle the logic (maybe calling the method after some arbitrary delay).
2. Add a polling mechanism (possibly opt-in via an attribute) that will check for any non-user entered text (I guess we could detect this based on whether the textbox has fired a focus event or not)

Other ideas?

**Comment by seangates** [comment]
Want to leave this open as I still need the all clear from Kamal. Will close once it's been deemed fixed by him.

**Comment by seangates** [comment]
Okay, this has been vetted and fixed per Kamal's tests.
