### ISSUE TITLE
Build: hide known deprecation warnings from Marko

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#56]
If these things are going to be around for ever, and we know about them, can we at least hide them and reduce noise in our test output:

<img width="579" alt="screen shot 2018-03-16 at 4 39 26 pm" src="https://user-images.githubusercontent.com/38065/37548926-b976521e-2938-11e8-8677-abf5e8800325.png">

**Comment by yomed** [comment]
Fixed for our users (just not for us inside the repo) via https://github.com/mlrawlings/complain/commit/4f363905544b4f2c34c28075136a9d6b5e793999
