### ISSUE TITLE
Docs: following Marko Widgets v7 link leads to confusion

### ISSUE THREAD

**Issue by aturpeinen** [eBay/ebayui-core#561]
# Bug Report

**Comment by aturpeinen** [comment]
I used marko create my-app and npm install @ebay/ebayui-core and skin.
Error: Unable to compile template at path "...\my-app\node_modules\@ebay\ebayui-core\dist\components\ebay-menu\template.marko". Error: el.addDynamicAttributes is not a function.

Documentation is bad.

**Comment by DylanPiercey** [comment]
The very first thing mentioned in the readme for this project is it’s [requirements](https://github.com/eBay/ebayui-core/blob/master/README.md#requirements). There you can see that when using ebayui with Marko 4 you also need to have `marko-widgets@7` installed (this is the Marko v3 compatibility layer for use in v4).

I don’t think the documentation is lacking there.

Can you trying installing the correct dependencies and letting us know if there is still an issue?

**Comment by aturpeinen** [comment]
Ok, thanks for letting me know that I should use @7. I show "Marko v4 requires Marko Widgets v7" link EbayUI ui page which leads to https://github.com/marko-js/marko-widgets/tree/v7. That page already shows deprecated, and it shows 6.6.6. Does not say anything about @7 ? "See the new components docs on markojs.com." Components link is incorrect, it leads to 404.

**Comment by ianmcburnie** [comment]
It seems that following the link is what leads to the confusion. We'll see what we can do to make that a less confusing experience. Thanks for reporting this. I'll update the title of this bug so we can track.

**Comment by ianmcburnie** [comment]
I think we can close this one. Besides, the page in question belongs to Marko ;-)
