### ISSUE TITLE
Menu: Shows incorrect data on client side rerender

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/ebayui-core#564]
# Bug Report

## Description
On client side rerender, the menu shows incorrect data. 

## Workaround

None

## Possible fix
AFAIK child DOM nodes are preserved when rerendering the component when using `w-preserve-body`. Removing it from this [line](https://github.com/eBay/ebayui-core/blob/97c8459791d1413097ee534878fdf4d87833c25c/src/components/ebay-menu/template.marko#L36) seems the fix the issue.

## Screenshots

Ideally after rerender it should show the same content as on page load. 
**On load**
![screen shot 2019-02-22 at 11 17 10 am](https://user-images.githubusercontent.com/5200733/53296279-d945f580-37c0-11e9-9580-a7987b494c57.png)

**After rerender**
![screen shot 2019-02-22 at 11 17 22 am](https://user-images.githubusercontent.com/5200733/53296281-dfd46d00-37c0-11e9-8d76-763263a8f1a1.png)
_[Ignore the styling issues]_

**Comment by ianmcburnie** [comment]
Thanks for reporting. Assigned to @seangates .

**Comment by ianmcburnie** [comment]
Fixed by @seangates in v2.0.5
