### ISSUE TITLE
Icon: update to newly updated icon sets from Skin

### ISSUE THREAD

**Issue by seangates** [eBay/ebayui-core#573]
## Description
Skin v7 added icons and updates existing icons, requiring a new import to Core.

### Updated icons
- arrow-right-bold
- information
- pause
- play
- priority

### New icons
- check
- follow
- mail
- mail-open
- notifications
- notifications-null
- sell-null
- view-detail
- view-grid
- view-list

**Comment by ianmcburnie** [comment]
I believe those "new" ones are actually deprecated ones. They were removed on purpose.

**Comment by seangates** [comment]
So ... closing per conversations on Slack, as these were removed as background icons, but left in the DS4 `icons.svg` file.
