### ISSUE TITLE
Textbox: type attribute is hard-coded

### ISSUE THREAD

**Issue by seangates** [eBay/ebayui-core#575]
Presently, we hardcode the type to text, even though there are other data types which are available (e.g. `number`, `email`, `date`, etc.). We should decide if we want to allow all data types, a limited set, or create other components _on top of textbox_ to cast other types.

In src/components/ebay-textbox/template.marko

```
type="text"
```

Posted via CodeStream

**Comment by ianmcburnie** [comment]
For 2.1.0 let's open it up to a few other types that will work safely with our current component.

**Comment by seangates** [comment]
Merged.
