### ISSUE TITLE
Menu: Menu options click event is not working when menu is re-rendered after ajax call

### ISSUE THREAD

**Issue by bhoomisatasiya** [eBay/ebayui-core#576]
# Bug Report

## Description
On client side rerender, one of the menu item click doesnt work.
- We have two menu components.
- When I make a choice on one menu, and  re-render after ajax, I lose state of the  second menu selection.

## Workaround

removing the  w-preserve-attrs from menu-item tag seems to be fixing the issue. 
[line #34 ](https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-menu/template.marko#L34)

**Comment by bhoomisatasiya** [comment]
@seangates  @ianmcburnie

**Comment by ianmcburnie** [comment]
Assigning to @seangates for further investigaton/triaging.

**Comment by seangates** [comment]
Looks like they had the menu as `radio` which produced `<div href="..." ...>` type of menu options. This has undesirable results when the item is clicked, as it believes it to be non-focusable, and the event bubbles to the next focusable element, causing the weird behavior.

The suggestion is for them to move to a `fake` menu, which will render the options as `<a href="..." ...>` which is correct given the markup they are trying to achieve.

Will follow up to confirm this is the right course.

**Comment by seangates** [comment]
So ... it actually looks like now the issue has been traced to Marko. Downgrading to Marko 4.13.13 appears to restore the re-rendering issue. @DylanPiercey will investigate further. @bhoomisatasiya is presently unblocked.

**Comment by bhoomisatasiya** [comment]
It seems this issue started happening from Marko 4.14.5.

**Comment by DylanPiercey** [comment]
@bhoomisatasiya this issue should be resolved in Marko [4.16.2](https://github.com/marko-js/marko/blob/master/CHANGELOG.md#4162). I tried it in your app and all seems well, would be good for you to double check though.

**Comment by ianmcburnie** [comment]
Closing.
