### ISSUE TITLE
Textbox floating label does not come down when setting textbox value to empty

### ISSUE THREAD

**Issue by kmlhossen** [eBay/ebayui-core#581]
## eBayUI Version: x.x.x
2.0.6-1

## Description
Textbox floating label does not come down when textbox value is updated to empty by state change.

## Screenshots
![screen shot 2019-03-07 at 1 58 05 pm](https://user-images.githubusercontent.com/2268244/53993383-1b860580-40e4-11e9-98c2-94954561752d.png)

**Comment by seangates** [comment]
Found out this isn't a regression, but another use case where state outside the component is changed which affects the child component. I have a PR coming which will address this.
