### ISSUE TITLE
Textbox: emit an event when textbox is updated by Marko, or the floating label is refreshed

### ISSUE THREAD

**Issue by seangates** [eBay/ebayui-core#594]
# Feature Request

## Description
When the textbox is updated, or when the floating label is initialized or "refreshed", it should emit an event with the current value of the textbox. This allows a developer to handle scenarios such as validation, or enabling/disabling form controls. Specifically, this is to account for the use case when browser autofill occurs, the floating label has been refreshed, but the normal DOM `change` event isn't emitted from the textbox.

## Context
The identity team is using the textbox, and need a way to listen for when the value of the textbox is not an empty string, and to validate the input, before enabling the submit button on the form.

**Comment by ianmcburnie** [comment]
Is this going in 2.1.0?

**Comment by seangates** [comment]
It’s still up for discussion. I hadn’t determined. Seeing as the team needing it is going out with their new flow soon, 2.1.0 is probably the right place.

**Comment by ianmcburnie** [comment]
Merged. Will be available in v2.2.0.
