### ISSUE TITLE
Checkbox: rendering redundant classes

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#595]
Checkbox and radio components are rendering some redundant Skin classes that can lead to specificity issues. More details at https://github.com/eBay/skin/issues/592

The solution is to add the `no-skin-classes` boolean to `<ebay-icon>` tag inside of checkbox and radio components.

**Comment by seangates** [comment]
Merged with #597 and published with 2.0.7. Closing.
