### ISSUE TITLE
Infotip: add ability to disable infotip button

### ISSUE THREAD

**Issue by melquan** [eBay/ebayui-core#599]
# Feature Request
Add the ability to disable infotip button.

## Description
We have a usecase where the infotip button should be disabled when a checkbox is unchecked, so we'd like to have an attribute added to the component to accommodate that.

## Screenshots
![image](https://user-images.githubusercontent.com/19419138/55089826-47edcb80-506b-11e9-9307-0a4f5cc58703.png)

**Comment by ianmcburnie** [comment]
@melquan Did you try just adding `disabled` attribute? Would think it is a simple pass through to the button, but @seangates could probably verify that.

**Comment by melquan** [comment]
I did try that, but the pass through attribute is applied to the `<span>` around the button instead of on the button.

**Comment by ianmcburnie** [comment]
Ah, ok. Yeah, sometimes we need to give the attributes a bit of a helping hand on our side.

**Comment by ianmcburnie** [comment]
Merged. Will be available in v2.2.0.
