### ISSUE TITLE
IOS- the ebay-button raw looks different

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#60]
IOS- the ebay-button raw looks different.

![image](https://user-images.githubusercontent.com/13157115/37626657-2226997a-2b8e-11e8-93e0-502705eea05f.png)

**Comment by seangates** [comment]
I believe this is a skin issue, and not an issue with components. Any objections about moving it over there?

/cc @hramakumar @ianmcburnie

**Comment by seangates** [comment]
Moved to Skin: https://github.com/eBay/skin/issues/100
