### ISSUE TITLE
Documentation: distinguish and/or separate Marko API from imperative API

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#600]
A common cause of issues here on GitHub is that developers are using a mix of stateful Marko API (e.g. state.dialogOpen = true) and the imperative API (e.g.` querySelector('.dialog').open = true`). Marko apps should ALWAYS use the Marko API. Setting aside the issue (for now) of whether we should support two APIs or not, it is clear that we need to improve our documentation so that these issues and misconceptions become less common.

**Comment by msendlakowski** [comment]
Closing, since we removed support for the imperative API
