### ISSUE TITLE
Infotip: makeup-expander does not get re-attached

### ISSUE THREAD

**Issue by seangates** [eBay/ebayui-core#601]
# Bug Report

## Description
When re-rendering the `<ebay-infotip/>` the makeup-expander does not get re-initialized/re-attached to the component. This is also likely to affect the `<ebay-tooltip/>` and `<ebay-tourtip/>`, but I haven't confirmed that yet.

## Workaround
None.

**Comment by ianmcburnie** [comment]
@seangates 2.0.8 patch for this then?

**Comment by seangates** [comment]
Yes, 2.0.8.

Yes, we need re-rendering tests.

**Comment by ianmcburnie** [comment]
For all components, we currently have:

`test.server.js`, (server render)
`test.browser.js` (client side behaviour)

Maybe we could have:

`test.rerender.js` (client side re-render)

What do you think?

**Comment by seangates** [comment]
That seems like a great way to do it.

**Comment by DylanPiercey** [comment]
The `.server` and `.browser` extensions are what tells Marko-cli how to run the file (either in nodes for `.server` or in WebdriverIO for `.browser`).

In this case we want to test rerendering which can only happen in the browser so these tests must exist in the `.browser` spec (or at least be imported from there).

**Comment by ianmcburnie** [comment]
Thanks Dylan. I think some kind of file separation would be nice, so we don't pollute our current test setup with the parent test fixture. Or maybe there won't actually be much "pollution" at all. I'll let Sean investigate how that would look in either case.
