### ISSUE TITLE
Menu: can't collapse by clicking outside the menu area in iOS

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#61]
unable to collapse the menu by clicking outside the menu area

**Comment by seangates** [comment]
@hramakumar For the sake of helping us clearly document the issue, and clearly understand the steps you go through to reproduce the bug, can you make sure to add more specifics? The steps to reproduce is the most obvious, but also environment information, too.

This is also a reminder for future bugs as well. It should be pretty clear how you reached the bug.

**Comment by hramakumar** [comment]
yes will add those

**Comment by hramakumar** [comment]
The issue happens in IOS safari

repro:

click on the ebay-menu. The menu will expand
select an item
click out side the component area.

expected behavior: the menu should collapse

actual: the menu doesn't collapse

**Comment by hramakumar** [comment]
I think I saw this happening sometimes in select as well. But that was long time back. Combobox was fine.
I am sorry I myself borrow the iphone from a different team during testing and I give it back after the testing.
I don't have it right now. I will get it back only next week.

**Comment by yomed** [comment]
@msendlakowski You should be able to debug it on the iOS Simulator.

**Comment by seangates** [comment]
**All**, let me know if you need help getting to the simulator. It's a little ... quirky.
