### ISSUE TITLE
ebay-select: expanded options right and bottom borders missing -  WIndows chrome

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#614]
# Bug Report

## Description
in windows chrome
click on the ebay select, expanded options right and bottom borders are not defined clearly

## Screenshots
[_removed unusable URL_]

**Comment by seangates** [comment]
@hramakumar Please post an actual screen shot. 😉 

I removed the URL because it was for your local machine.

**Comment by hramakumar** [comment]
oh ok

**Comment by ianmcburnie** [comment]
Again, this feels like it's just going to be the browser's built in experience for a select tag, as we don't/can't style the overlay.

**Comment by seangates** [comment]
This is expected behavior given the way Chrome is set up for Windows.
