### ISSUE TITLE
Icon: "missing" icon does not have viewbox

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#615]
# Bug Report

## Description
ds4 icons are broken

## Screenshots
https://www.useloom.com/share/909d4da8ac3f4b8db57327521ac7987c

**Comment by ianmcburnie** [comment]
I don't believe there were any skin related changes to icon in [7.1.0](https://github.com/eBay/skin/projects/18) so I suspect this to be a test env issue or perhaps related to some of the icon change(s) that @DylanPiercey made recently.

**Comment by DylanPiercey** [comment]
Looks fine in the demo and marketplace, I'll sync up with @hramakumar to see what is going on.

**Comment by hramakumar** [comment]
the `missing` icon (when there is not a compatible ds4 version) does not have a view box which we should probably fix.
changing this from blocker to non blocker

**Comment by agliga** [comment]
@ianmcburnie Can you provide what the expected fix should be for this?

**Comment by ianmcburnie** [comment]
I'm not sure. From the description it's not clear.  Let's punt this one for now.

**Comment by agliga** [comment]
The more I think about it, I think the better solution is to make the icon larger. The thing is if we make a small icon people might miss it being broken. If it's large it will make people want to double check it. 
Again this is only in the case where someone is switching between DS4 and DS6 and the icon is not in the corresponding version. If a user specifies an icon that does not exist in either DS4 or DS6, there will be a compile error.

This could be a possible fix:
<img width="705" alt="Screen Shot 2019-07-11 at 2 34 26 PM" src="https://user-images.githubusercontent.com/1755269/61086983-27af0600-a3e9-11e9-9c48-ac663882856d.png">
