### ISSUE TITLE
ebay-select: IOS-safari -once options are scrolled - there no way to go back to the prev selected option

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#617]
# Bug Report

## Description
IOS safari
click on the ebay select with many options
scoll down to see some more options...when clicked outside it takes the option that is currently highlighted during the scroll. instead of reverting back to the previously selected option.

expexted behaviour:  clicking on done should select the current option and clicking outside the option list to revert back to the previously selected option

**Comment by ianmcburnie** [comment]
@seangates Isn't this just IOS' default behaviour for a select? If you can confirm, we can close.

**Comment by seangates** [comment]
This is expected behavior.
