### ISSUE TITLE
combobox: blinking cursor appears on read only combobox

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#619]
The issue is intermittent and is more frequent in IE ds4
# Bug Report

## Workaround
clicking on the combo box shows a blinking cursor

## Screenshots
![image](https://user-images.githubusercontent.com/13157115/55826940-e2173000-5abd-11e9-8c85-ae2879b9e61a.png)

**Comment by ianmcburnie** [comment]
This is IE's default behaviour for readonly textboxes.

Solution for cursor is to put `pointer-events: none` on the textbox element, **but** this then prevents the combobox list from opening on click. We could have the listbox only open when the chevron icon is clicked, or move the icon into it's own separate button element, but I don't think this is worth all the trouble at this time.

**Comment by ianmcburnie** [comment]
Going to move this to wontfix for now. @hramakumar you can use the 'wontfix' label filter to resurface any old issues we may have closed like this.
