### ISSUE TITLE
Menu: in IE options get truncated based on the size of the menu button

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#620]
# Bug Report

## Description
I remember filing this issue long time back. couldn't find it now.
creating this new one to keep track of this. 
in IE options get truncated based on the size of the menu button

## Screenshots

![image](https://user-images.githubusercontent.com/13157115/55827610-703fe600-5abf-11e9-8462-606d8ccdb728.png)
![image](https://user-images.githubusercontent.com/13157115/55827644-82ba1f80-5abf-11e9-85a7-3b8e6b5f5b27.png)

**Comment by ianmcburnie** [comment]
Hmm, thought this one had been fixed. We'll need to fix this in Skin. Looks pretty bad for the icon case.

**Comment by ianmcburnie** [comment]
This should get fixed as part of this skin issue:

https://github.com/eBay/skin/issues/589

We are taking this skin fix in CoreUI 2.7.0.

**Comment by ianmcburnie** [comment]
Actually, I was bit premature closing this. The skin issue is still open:

https://github.com/eBay/skin/issues/589

**Comment by agliga** [comment]
Should be complete in `2.8.0`, updated Skin to `7.4.2` to fix this: https://github.com/eBay/ebayui-core/commit/f21c095de3d77151ce5cabb482c7c2af032e1867
