### ISSUE TITLE
combobox: ds4 combobox selected option highlighting in not clearly visible

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#622]
# Bug Report
## Description
combobox: ds4 combobox selected option highlighting in not clearly visible

## Screenshots
![55909063-e6ac1900-5b8f-11e9-83d6-34eb6811b969](https://user-images.githubusercontent.com/105656/59799412-27fc2b80-9299-11e9-9efd-b2a37a9058cd.png)

**Comment by ianmcburnie** [comment]
@seangates Isn't the text supposed to be bolded?

**Comment by ianmcburnie** [comment]
This may have been fixed already. Let's verify.

**Comment by ianmcburnie** [comment]
Assigning to @hramakumar for verification in latest build.

**Comment by seangates** [comment]
We no longer show the check mark:
![image](https://user-images.githubusercontent.com/105656/59799646-9b9e3880-9299-11e9-8c5d-80afb2d1025a.png)

I believe this is no longer an issue.

**Comment by ianmcburnie** [comment]
...but we do show the background highlight, so closing ticket.
