### ISSUE TITLE
Refactor components to use recommended data organization & other best practices

### ISSUE THREAD

**Issue by DylanPiercey** [eBay/ebayui-core#624]
# Refactor

### State vs Input vs Computed
Currently most components do not have a clear strategy for what parts of data is state vs input vs computed which can make digging into the components a bit more tricky.

Marko 3 does not have the most clear separation of these concepts but it is possible to at least make the intent clear by explicitly only including actual state (and not input) in `getInitialState`.

Computed values typically go in `getTemplateData` in Marko 3, however in Marko 4 the recommendation is to inline these computed values into the template and to extract out helper functions if necessary which can be imported.

In Marko 3 `input` is usually just merged in (which makes it easy to loose track of) but I think a refactor to make the intent clear will improve maintainability and make it easier to have an optimized migration to Marko 4.

### Minimizing state
In some of our components (as mentioned above) we put things that are not state, into the state object (mostly because of Marko 3 limitations). Because the boundaries are blurred here I think some components have been mutating the input which is not ideal or recommended and further complicates the state management.

### querySelector's
It is never recommended to use `querySelector` in Marko (3 or 4) however we are in a few components. Where these selectors are passed to makeup there is not much we can do, but in the other cases we can improve by using the recommended api (w-id="key" & widget.getEl("key")). This is not only going to improve performance, but also decouple us from these specific class names.

### Stateless components
A large number of the ebayui components should be stateless (that is they can never update by themselves such as button, badge, etc). However all of these components still are incorrectly using API's like `getInitialState`. These components should be refactored to either not have component logic at all, or only have logic for handling events (since many forward events and that's it).

**Comment by ianmcburnie** [comment]
Wow, yes. I think these changes are going to be a big improvement all round. Thanks for leading this effort @DylanPiercey

**Comment by aselvaraj** [comment]
@DylanPiercey glad to see this one. Looking forward to it.

**Comment by ianmcburnie** [comment]
Merged. Currently in 2.4.0-0 pre-release for QA.
