### ISSUE TITLE
tourtip: unable to close

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#627]
# Bug Report

## Description
unable to close after clicking the close button in tourtip
expected behavior in 2.1.0-0 and 7.1.0-0
https://www.loom.com/share/8262d85d6bfa4b16a10745db1e0b9ee8
actual behavior in 2.2.0-1 and skin 7.1.1
https://www.loom.com/share/c3c34dc424e044cabded3e561126cfc8

**Comment by seangates** [comment]
@DylanPiercey I started looking at this, and can look later tonight, but I'm off camping tomorrow.

**Comment by hramakumar** [comment]
verified
