### ISSUE TITLE
Checkbox and Radio -  when selected the icon dot and tick color overrides to blue

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#628]
# Bug Report

## Description
when selected the icons and checkbox selected icons color defaults to blue. it also overrides the explicitly mentioned colors
https://www.loom.com/share/e90b7464ddea4462ad126fb7e3ecfe67

**Comment by msendlakowski** [comment]
@hramakumar Looking at the latest documentation, it looks like the color needs to be set on the SVG itself.  Here is an example:

```
<svg aria-hidden="true" class="checkbox__checked" focusable="false" style="color: #5ba71b">
   <use xlink:href="#icon-checkbox-checked"></use>
</svg>
```

Can you update the CSS in your tests from:
```
.custom {
    color: red;
}
```

To:
```
.custom svg {
    color: red;
}
```

**Comment by hramakumar** [comment]
done
