### ISSUE TITLE
combobox: after selecting an option when expanded again, I see only the selected option in the option list

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#629]
# Bug Report

## Description
combobox: after selecting an option when expanded again, I see only the selected option in the list

repro:
click on the combobox
expand the options
select an option
take focus out and click the combox again to expand. 
https://www.loom.com/share/3613be0053a04b729ec4d99836c1d1a7

**Comment by seangates** [comment]
This is expected behavior.
