### ISSUE TITLE
combobox: in DS6 when an empty option is pushed- it occupies a row in which cannot be selected

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#630]
# Bug Report

## Description
In DS6 - when an empty option is pushed- it occupies a row in the option list. Could be a P3 or P4 issue. 

Expected behavior: In  DS4 it removes the option from the list.
https://www.loom.com/share/91ad214540614c27946fca0b3443c2eb

**Comment by seangates** [comment]
Please share your template markup here, too.

**Comment by hramakumar** [comment]
verified.
