### ISSUE TITLE
combobox: does not work in IE- unable to expand

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#631]
# Bug Report

## Description
Unable to expand the combobox is IE

**Comment by seangates** [comment]
ES6 issue. Using `NODE_ENV=production` works, but we should also have things working in a dev environment, too.

**Comment by hramakumar** [comment]
Its a marko issue. Dyaln sent the PR. I am  waiting for the npm registy issue to be fixed to verify the bug

**Comment by hramakumar** [comment]
verified
