### ISSUE TITLE
tooltip and info tip : not working in IE

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#632]
# Bug Report

## Description
In IE - tool tip are info tip are not working. clicking on the does not open anything.

**Comment by seangates** [comment]
ES6 issue. Using `NODE_ENV=production` works, but we should also have things working in a dev environment, too.

**Comment by hramakumar** [comment]
Its a marko issue. Dyaln sent the PR. I am waiting for the npm registy issue to be fixed to verify the bug

**Comment by hramakumar** [comment]
verified
