### ISSUE TITLE
Combobox: two items highlighted as selected

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#633]
# Bug Report

## Description
click on one item then remove focus and again click on the combobox and again remove focus.
The  third time open it up 
You can see two options selected
https://www.loom.com/share/7c78709452004b7a98bed2ab8d9d6726

<h3>no tag properties</h3>
                <ebay-combobox name="example2text">
                    <ebay-combobox-option text="August Campaign"/>
                    <ebay-combobox-option text="4th of July Sale (paused)"/>
                    <ebay-combobox-option text="Basic Offer"/>
                    <ebay-combobox-option text="Basic Offer 1"/>
                    <ebay-combobox-option text="Basic Offer 3"/>
                </ebay-combobox>

**Comment by ianmcburnie** [comment]
So long as the user can still select an item to fill the textbox, I don't see this being a blocker.

**Comment by seangates** [comment]
I agree. The text box is still free-form.

**Comment by hramakumar** [comment]
happens in ds4 as well(also with attributes)

**Comment by ianmcburnie** [comment]
Let's reverify in 2.5.0

**Comment by ianmcburnie** [comment]
Still an issue in 2.8.0 branch. The `listbox__option--active` class is not being cleared when focus exits the combobox widget. The `makeup-active-descendant` and `makeup-focus-exit` modules are supposed to handle this, so possibly some conflict going on with Marko.

![Screen Shot 2019-07-12 at 11 46 23 AM](https://user-images.githubusercontent.com/38065/61152102-63ef6e80-a49c-11e9-9855-548a4ce51ec0.png)

**Comment by seangates** [comment]
Correct, I have not yet addressed it. Doing so now using the method mentioned in comments for #756.
