### ISSUE TITLE
Combobox: When long text is selected, the blinking cursor is not seen

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#638]
# Bug Report

## Description
When a long text option is selected, the blinking cursor is not seen.
https://www.loom.com/share/3426a4efd80042d4ad1c2a19b2fb40c7

**Comment by ianmcburnie** [comment]
We would have to verify if this is default browser behaviour when a textbox value is programatticaly update via javascript. 

FYI I do not see this behaviour when I _copy and paste_ long text.

In any case, it's low priority. User can easily jump to cursor using arrow keys.

**Comment by ianmcburnie** [comment]
Possibly related to #702. Possibly...

**Comment by seangates** [comment]
Native browser behavior is this way. I'm going to close as "not an issue". The behavior can be mimicked exactly in the MIND Patterns combobox example page.
