### ISSUE TITLE
BUG: transform does not walk the tree of all nested tags

### ISSUE THREAD

**Issue by seangates** [eBay/ebayui-core#64]
Currently the transform expects direct nested tags, and does not allow any other Marko tags.

For example, the `<ebay-select>` expects a direct nested tag `<ebay-select-option>`, and if you add any control tags, like `<if()>` or `<for()>`, you will break rendering.

The fix is to walk the entire tree of children tags and apply the transform to _any_ tag that matches, regardless of whether the nested tag is an immediate child of the tag.

**Comment by mlrawlings** [comment]
Sounds good.  As an optimization, you should be able to short circuit the walk once you hit a nested tag.  IE, once `<ebay-select-option>` is found, you don't need to go any deeper on that part of the tree.
