### ISSUE TITLE
Combobox/Textbox: Edge / IE clear button should be removed on input field

### ISSUE THREAD

**Issue by seangates** [eBay/ebayui-core#640]
# Bug Report

## Description
The combobox and textbox input fields have an `X` that appears in the input that allows a user to "clear" the contents. This doesn't follow the way our pattern library works, and should be removed.
All the other options disappear.
1)focus out and focus in. You see the options of only the previously cleared text. It is expected to show all options. When you start typing. all the options re-appear
2)selecting the displayed option also does not work
moved it to blocker
## Workaround
Add CSS similar to the following:
```
.someinput::-ms-clear {
    display: none;
}
```
https://stackoverflow.com/questions/14007655/remove-ie10s-clear-field-x-button-on-certain-inputs

### Edge

![combobox-input-edge](https://user-images.githubusercontent.com/105656/56619086-a8781600-65e1-11e9-9408-5a379439ed9a.PNG)

### IE

![combobox-input](https://user-images.githubusercontent.com/105656/56618866-09ebb500-65e1-11e9-81f1-80c3fb98c79f.PNG)

**Comment by seangates** [comment]
@hramakumar has shown me how this now becomes a blocker given the way Edge/IE behave after clicking the `X`. Moving this up to 2.2.0.

**Comment by seangates** [comment]
Skin is updated with 7.1.2 with this fix. The next pre-release of 2.2.0 will have Skin v7.1.2 applied.

**Comment by ianmcburnie** [comment]
Fix goes out in 2.2.0
