### ISSUE TITLE
Combobox: unable to edit text in the middle or pre-pend text to an existing text

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#641]
# Bug Report

## Description
Repor;
Click on a combobox
type some text
Try adding/deleting some text in the middle of the currently added text
The cursor automatically shifts to the right
https://www.loom.com/share/3b19029c733c4683bc91efa4ad0b3cb9

## Workaround
The user has to delete the entire text and start again

**Comment by ianmcburnie** [comment]
This is an annoying issue for users. I'm going to promote this from the backlog to an upcoming release.

**Comment by ianmcburnie** [comment]
Done. Awaiting QA in 2.5.0.

**Comment by hramakumar** [comment]
The handleExpand() is called when modifying the text as well. Options list can collapse and expand while editing the text and everytime it expands while typing, it calls handleExpand() and gets the cursor to the end.

 handleExpand() {
        const index = this.getSelectedIndex(this.state.options, this.state.currentValue);
        elementScroll.scroll(this.getEls('option')[index]);
        **this.moveCursorToEnd();**
        emitAndFire(this, 'combobox-expand');
    },

**Comment by ianmcburnie** [comment]
Done in 2.8.0
