### ISSUE TITLE
Combobox: default value is not highlighted when clicking on the combobox first time

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#642]
Bug reported by consuming team.
# Bug Report

## Description
Combobox: When combobox has a default value-when clicked on the comobox first time. Its not highlighted.
When I start typing in the textbox, then the highlighting starts happening

**Comment by seangates** [comment]
This should be fixed by #636. We can verify once a new version is pre-published.

**Comment by hramakumar** [comment]
verified
