### ISSUE TITLE
Combobox: name attribute is not passed through.

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#645]
# Bug Report

## Description
in combobox the name attribute is passed through in the browser

<ebay-combobox name="example1text" autocomplete="list">
    <ebay-combobox-option text="August Campaign"/>
    <ebay-combobox-option text="4th of July Sale"/>
    <ebay-combobox-option text="Basic Offer"/>
</ebay-combobox>

the actual html in browser
![image](https://user-images.githubusercontent.com/13157115/56764531-c8324a00-6759-11e9-9dd8-84f81e275e0f.png)

**Comment by melquan** [comment]
Same issue when passing `id`.

**Comment by seangates** [comment]
@melquan Given the nature of the component we currently let Marko create the ID.

@DylanPiercey Do we have any other options with the combobox's `id` attribute?

**Comment by melquan** [comment]
Just for more info on `id`, it's to match the `for` of the `<label>` we have on the app side.

**Comment by seangates** [comment]
Correct. That's the first thing I thought of with the context of your question. It's also super important that we're able to use the `for` attribute to tie the two together, and we have to be able to set the `id` or, know what the `id` is going to be ahead of time.

**Comment by seangates** [comment]
Verified by @hramakumar.

**Comment by seangates** [comment]
@melquan I think the ID can be derived from the component. Chat with me and I can talk to you about my idea.

/cc @DylanPiercey
