### ISSUE TITLE
combobox: autocomplete attribute is off in chrome browser

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#646]
# Bug Report

## Description
In chrome the autocomplete attribute is off.
![image](https://user-images.githubusercontent.com/13157115/56764710-38d96680-675a-11e9-9485-8bd67a1d7147.png)
## Workaround
It does not block the functionality

**Comment by seangates** [comment]
@hramakumar Isn't this the same as #639?

**Comment by hramakumar** [comment]
yes it is. I will close it
