### ISSUE TITLE
combobox: copied and pasted text does not show the options

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#648]
# Bug Report

## Description
copy and paste a text that matched some of the options.
it does no show the options that matches the text.
it works only when letters are typed one by one

## Screenshots
https://www.loom.com/share/f28c3bfecbcd4d98b99cd8f659729b54

**Comment by msendlakowski** [comment]
Looks like the paste event is fairly well supported.  We may want to start listening for this, even if it isn't supported in all browsers yet.
https://caniuse.com/#feat=clipboard

**Comment by agliga** [comment]
This is actually working in the latest ebayui 
![autocomplete-paste](https://user-images.githubusercontent.com/1755269/84919493-d5557b00-b076-11ea-9c5c-9dff48247936.gif)
