### ISSUE TITLE
Combobox: when focused with a default value combobox should show all options

### ISSUE THREAD

**Issue by seangates** [eBay/ebayui-core#649]
# Bug Report

## Description
Given that a combobox has a default value, when focused it should show all the options. Currently it shows only the filtered option of the default value. Users not know that there are more options if the removed the default value, or if they began to type a new value.

## Workaround
n/a

## Screenshots
The following combobox has 20 options, but you wouldn't know it.
![image](https://user-images.githubusercontent.com/105656/56997260-71b37a00-6b64-11e9-9d23-88d6f4f2dccc.png)

**Comment by ianmcburnie** [comment]
This seems to be an invalid issue. If autocomplete is on, and a default value is present, we shouldn't see the full list. Full list of options should only show if textbox has no value and `expand-on-focus` is true. Let's discuss again offline.

**Comment by seangates** [comment]
I've reverted the changes in the PR. We'll need to discuss with the team that requested this change about their options going forward.
