### ISSUE TITLE
combobox: when there are no options -no expansion-exception in expand event

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#651]
# Bug Report

## Description
typing on the combobox throws an exception in expand event

## Screenshots
![image](https://user-images.githubusercontent.com/13157115/57039568-df69af80-6c11-11e9-9bdd-2e29aa34c29c.png)

**Comment by ianmcburnie** [comment]
This would be an issue if options are added on CSR after SSR, but @seangates  mentions that expander bindings will be added as soon as this happens.

**Comment by ianmcburnie** [comment]
Might be fixed. Sean to check.

**Comment by seangates** [comment]
And ... it's not fixed.

**Comment by hramakumar** [comment]
verified
