### ISSUE TITLE
readme doc: invalid link

### ISSUE THREAD

**Issue by oguzzkilic** [eBay/ebayui-core#655]
File: README.md
Url: https://ebay.gitbooks.io/mindpatterns/content
Error: This site can’t be reached

**Comment by seangates** [comment]
Hmmm. Works for me. Maybe try again?

**Comment by oguzzkilic** [comment]
I think, an error on my internal network mistook me. I saw there wasnt any problem when I tried with a different connection.

**Comment by seangates** [comment]
No worries. Thanks for following up!
