### ISSUE TITLE
Combobox: provide the functionality to expand and show all options and collapse the listbox with an outer control

### ISSUE THREAD

**Issue by melquan** [eBay/ebayui-core#659]
# Feature Request

## Description
The current combobox shows only the filtered options in the listbox upon expansion when there is a default value.  There is a request to show all options on the click of an outer control (similar to a traditional select dropdown); and collapse the listbox when the outer control is clicked again.

eBayUI version: 2.2.0

**Comment by DylanPiercey** [comment]
To move away from these imperative API's we should simply expose something like an `expanded` attribute on the component which consumers can control via their state, just like the dialog has an `open` attribute.

**Comment by seangates** [comment]
@DylanPiercey That would be on top of the `autocomplete` attribute, to do what Ian is proposing, correct?

**Comment by ianmcburnie** [comment]
Yep, an `expanded` property would be my preference too. We just don't have that right now.

**Comment by DylanPiercey** [comment]
@seangates @ianmcburnie I don't know all of the details and I am confused as to how `autocomplete` relates to this issue of expanding and collapsing the combobox from a parent component?

**Comment by ianmcburnie** [comment]
Done. Awaiting QA in 2.5.0.
