### ISSUE TITLE
ebay-badge: Error while applying option of "<ebay-badge>".

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#663]
# Bug Report

## Description
I am seeing this issue after I upgraded to ebay ui 2.4.0
Error while applying option of "<ebay-badge>". Cause: Error: Unable to load tag ([/Users/hramakumar/ebayui3/ebayUITestenv/node_modules/@ebay/ebayui-core/marko.json → <ebay-badge>]): Error: Error while applying option of "template". Cause: Error: Template at path "/Users/hramakumar/ebayui3/ebayUITestenv/node_modules/@ebay/ebayui-core/src/components/ebay-badge/index.marko" does not exist.

**Comment by DylanPiercey** [comment]
Fixed in https://github.com/eBay/ebayui-core/pull/662

**Comment by hramakumar** [comment]
verified
