### ISSUE TITLE
Combobox: disabled state still allows you to expand and interact

### ISSUE THREAD

**Issue by seangates** [eBay/ebayui-core#664]
# Bug Report

## Description
When the `disabled` attribute is applied the combobox component still allows you to expand the list.

## Workaround
None.

## Screenshots
![Screen Shot 2019-05-10 at 1 40 37 PM](https://user-images.githubusercontent.com/105656/57558016-6537da00-7339-11e9-94fd-1595132d7292.png)

**Comment by hramakumar** [comment]
I had this scenario tested. can you send me the code on how you disable it.

**Comment by seangates** [comment]
This is working correctly. I have verified that they were using CSS to override the styles of the combobox.
