### ISSUE TITLE
Button: on-button-click handler is triggered twice when using Enter or Space

### ISSUE THREAD

**Issue by dkallus** [eBay/ebayui-core#666]
# Bug Report

## Description
Expected: When pressing {space} or {enter} on ebayui-button, the on-button-click handler should only be triggered once.

Actual: on-button-click handler is being triggered twice.

Reproduce:
1. Tab over to button element
1. Press {space} or {enter}
1. Handler is triggered twice

Sample code with issue:
```
<ebay-button priority="primary" size="large" on-button-click("handleAprove")>Approve</ebay-button>

handleApprove() {
  console.log("Hello world");
}
```

**Comment by ianmcburnie** [comment]
@dkallus Is this a blocker for you? Or do you have a workaround. Oh, and thanks for reporting!

**Comment by dkallus** [comment]
@ianmcburnie This isn't a blocker. Replacing <ebay-button> with <button> works.

**Comment by ianmcburnie** [comment]
Thanks. Would be nice to have you using the button though. @seangates if this is a simple fix (?), maybe this can be done in 2.3.x along with #664. What do you think? Are you able to look at these two?

**Comment by seangates** [comment]
I haven't had a chance to look at it yet. Let me jump on it first thing tomorrow.

**Comment by ianmcburnie** [comment]
Here's another related one found by Hemnath: https://github.com/eBay/ebayui-core/issues/669

I've just realised we might want to fix these in 2.4 or 2.5, rather than 2.3, because otherwise we are going to have to fix each of them twice (once in the pre-refactored code, and again in the refactored code). I'll change the project.

**Comment by seangates** [comment]
It appears a button will fire events for keydown as well as click when the space bar and enter key are pressed. I'm removing the redundant keydown event for `space` and `enter` (action) keys. PR forthcoming.

**Comment by hramakumar** [comment]
verified
