### ISSUE TITLE
New Component: Tooltip

### ISSUE THREAD

**Issue by senthilp** [eBay/ebayui-core#67]
https://ebay.invisionapp.com/share/CWN9X1JF6MA#/screens/299234476

Some additional thoughts:

- The component should allow the application to suggest a position to open the tooltip, but use JS to override that in order to keep the tooltip on page.
- A11y guidelines:
    - Tooltip: https://ebay.gitbooks.io/mindpatterns/content/disclosure/tooltip.html
    - Infotip: https://ebay.gitbooks.io/mindpatterns/content/disclosure/bubblehelp.html
    - Tourtip: Guidelines need to be established. They are unique since they are usually meant to be open when the page is loaded and grab the user's focus.
- Based on my implementation of tourtips in the past
    - It looks bad if there are many tourtips open on the page at the same time. They can even overlap each other. It would be good to add some management to prevent this.
    - Tourtips usually only show up once and then the user never sees them again (using local storage).  We could create this functionality to prevent applications from having to duplicate it.  Applications will probably also want ways to reset the timeout period.

**Comment by ianmcburnie** [comment]
This task will be unblocked by first pre-release of skin 7.0.0. At the time of writing, DS4 tooltip is done in skin, and that would be enough to start this task.

**Comment by seangates** [comment]
Completed in #499.
