### ISSUE TITLE
combobox: editable combobox select from option does not work in ie 11

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#675]
# Bug Report

## Description
editable combobox - not able to select from the option list

**Comment by ianmcburnie** [comment]
@seangates to investigate

**Comment by seangates** [comment]
@ianmcburnie This isn't coming as quickly as I'd hoped. Let's punt.

**Comment by ianmcburnie** [comment]
Ok, will do, thanks for the update.

**Comment by ianmcburnie** [comment]
If we can't find out the root issue,  we could *potentially* hide the combobox overlay for IE11 users via CSS `supports`. Only problem would be that the textbox would still announce as a combobox for IE11 users with screen readers. Might be better than the current situation though.

**Comment by ianmcburnie** [comment]
Done in 2.8.0
