### ISSUE TITLE
Select: Support optgroup

### ISSUE THREAD

**Issue by melquan** [eBay/ebayui-core#689]
# Feature Request
Support optgroup for Select 

## Description
We have a need to show groupings in our dropdowns and would like to request the support of `optgroup` in the select component

## Screenshots
In our current flow:
![image](https://user-images.githubusercontent.com/19419138/58643042-5ea2df80-82b3-11e9-814b-e65a6f547ccf.png)

**Comment by ianmcburnie** [comment]
Going to split this into two tickets. One for select, one for combobox.

**Comment by ianmcburnie** [comment]
Done. Will be available in 2.7.0.
