### ISSUE TITLE
Menu: giant icon in examples

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#695]
Not sure of the impact of this, may just be our example page, but should be fixed nonetheless:

<img width="809" alt="Screen Shot 2019-06-05 at 8 21 04 AM" src="https://user-images.githubusercontent.com/38065/58968696-50e5d200-876b-11e9-8eb6-105ea16a6dce.png">

**Comment by agliga** [comment]
This has to do with the fact that the DS6 version of this file has styles to limit the height of the mic icon but that file is not being loaded in this version. 
DS4 does not have the mic icon. So either we add the mic icon to DS4, load DS6 on this page correctly, or change the icon to something else.

**Comment by seangates** [comment]
I vote for an icon which both support.

But also, fixing the DS6 files. 👍

**Comment by agliga** [comment]
Added an issue in skin for fixing the reference issue. Will provide a PR to have a different icon
https://github.com/eBay/skin/issues/676

**Comment by agliga** [comment]
Fixed by updating skin to 7.4.1 in 2.7.0 https://github.com/eBay/ebayui-core/commit/052db526cbf2929a04cb719c2b66bae4c05fe469

Will include a better icon in 2.8.0

**Comment by ianmcburnie** [comment]
Done in 2.8.0
