### ISSUE TITLE
Menu: check mark is near the right border (IE11)

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#699]
# Bug Report

## Description

clickin on menu with checkbox expands the menu with check mark on checked option towards the very right of the component. It is near the component border.
![image](https://user-images.githubusercontent.com/13157115/59069040-d2705980-886a-11e9-8ae3-d2aae862d699.png)

**Comment by ianmcburnie** [comment]
Closing as wontfix for IE11 according to browser policy (fit & finish, visual glitches).
