### ISSUE TITLE
menu and listbox: change events are triggered even when clicking an already selected option

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#700]
# Bug Report

## Description
In menu and listbox the change events are triggered even when clicking an already selected option from the list. Ideally, we need to have it triggered only when there is a change in the menu option

**Comment by hramakumar** [comment]
with 2.6.0 its fixed in ebay select but the issue is still present in combobox and listbox

**Comment by ianmcburnie** [comment]
I don't even think this was targeted as a fix for 2.6.0, so not sure how it got fixed. Currently we have it for 2.8.0. We could maybe bring it forward to 2.7.0 though.

**Comment by seangates** [comment]
@hramakumar The combobox change event only happens on "blur". For combobox, are you listening to another event besides `combobox-change`? Maybe `combobox-select`?

**Comment by seangates** [comment]
If the above is the case, then I will remove the combobox from this issue.

**Comment by seangates** [comment]
Per conversation, I will look at `listbox` too. Also, `combobox` works as expected.

**Comment by ianmcburnie** [comment]
This is in 2.7.0 pre-release. Closing.
