### ISSUE TITLE
Combobox: First attempt to selecting an option from the list gets the cursor to go the start.

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#701]
# Bug Report

## Description
when I open up the editable combo box first time and select an option then the cursor is moved to the start instead of the end.

**Comment by ianmcburnie** [comment]
Seems related to the issues we've been seeing in https://github.com/eBay/ebayui-core/issues/641 Let's try and fix these together.

**Comment by ianmcburnie** [comment]
Done in 2.8.0
