### ISSUE TITLE
Combobox: cursor is pushed to the right edge of the box (iOS Safari)

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#702]
# Bug Report

## Description
when selected option text is long the cursor is pushed to the right border of the component

![cursor](https://user-images.githubusercontent.com/13157115/59070422-8247c600-886f-11e9-8762-aab709e3c069.png)

**Comment by ianmcburnie** [comment]
We closed this as cantfix/wontfix on the skin side. Doing the same here.
