### ISSUE TITLE
Listbox: missing type="button" attribute on button

### ISSUE THREAD

**Issue by rkdh** [eBay/ebayui-core#703]
# Bug Report

## Description
button element is missing type attribute which triggers form submit when used inside a form.

**Comment by seangates** [comment]
@ianmcburnie Jumping on this before I release 2.5.0 so that it can be pulled in. It's a blocker for anyone using the listbox.

**Comment by seangates** [comment]
Also, we should have these controls tested inside of forms. We tend to create examples in pure isolation, when in reality we should always have them inside of a form.
