### ISSUE TITLE
Dialog: Screen stays zoomed in when the dialog is closed (iOS)

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/ebayui-core#708]
# Bug Report

## Description
1. Open a dialog with text field(s). 
2. Focus on any field. 
3. Screen is zoomed in. 
4. Close the dialog. 
5. Screen stays zoomed in. After closing the dialog, ideally the screen should go back to previous state. 

This happens in iPhone, and is reproducible in the marketplace using either a iPhone simulator or Browserstack. 

## Workaround
- Manually pinch to un-zoom.

**Comment by ianmcburnie** [comment]
@seangates did some research on this and it appears to be the default behaviour of iOS when textbox size is under 16px. 

Two options:

1. Leave as is
2. Design system updates our textbox font size to 16px

**Comment by ianmcburnie** [comment]
Going to close this as it's the default zooming behaviour of iOS and not much we can do about it.
