### ISSUE TITLE
combobox: throws a JS error when typing in the textbox if there are no options

### ISSUE THREAD

**Issue by melquan** [eBay/ebayui-core#710]
# Bug Report

## Description
When there are no options and user starts typing in the textbox of the combobox, a JS error is thrown and the the entered value cannot be emitted.

## Screenshots
![image](https://user-images.githubusercontent.com/19419138/59518119-db1feb80-8e79-11e9-8994-2e44868a4789.png)

![image](https://user-images.githubusercontent.com/19419138/59518333-4ff32580-8e7a-11e9-8999-dbbf5f670453.png)

**Comment by hramakumar** [comment]
#651

**Comment by melquan** [comment]
@hramakumar I thought there was already a ticket filed but didn't find it.  Sorry I overlooked it!

**Comment by hramakumar** [comment]
no problem. Let's get this fixed.
We will keep you posted

**Comment by hramakumar** [comment]
verified

**Comment by ianmcburnie** [comment]
Fixed in 2.6.0. Closing.
