### ISSUE TITLE
Menu: make independent of button

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#713]
The MIND patterns have been updated to make menu independent of any button. This has the following benefits:

* Menu can be embedded directly in the page without any button (similar to how we made form controls independent of any label)
* Better support for mWeb, which is also often embedded directly on page without button

Examples:

* https://ebay.github.io/mindpatterns/input/menu/index.html
* https://ebay.github.io/mindpatterns/input/menu-button/index.html
* https://ebay.github.io/mindpatterns/input/combobox/index.html

Related tickets:

* https://github.com/eBay/skin/issues/630

**Comment by msendlakowski** [comment]
@ianmcburnie  We should have time to do this in 4.1.0 if its still high priority.

**Comment by ianmcburnie** [comment]
Done in 4.2.0.
