### ISSUE TITLE
Dialog: close button issues in IE & Edge

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#714]
# Bug Report

## Description
1)On left and right panel scrollable dialog
the close button has to be clicked twice to close the dialog.
1st click removes focus and second click closed the dialog

2)On left and Right panel dialog
The close button first appears onone side then disappears and re-appears on the other end

will post the screenshots later

## Screenshots

**issue 1:**
befoe close icon click
![image](https://user-images.githubusercontent.com/13157115/59713174-aa1a2080-91c3-11e9-88a6-dcb0acc81249.png)

after close icon first click
![image](https://user-images.githubusercontent.com/13157115/59713217-bbfbc380-91c3-11e9-83b5-0830a2a0b849.png)

it looses focus. only the next click closes the dialog

**issue  2:**
after opening a left panel dialog
![image](https://user-images.githubusercontent.com/13157115/59713015-4132a880-91c3-11e9-83c7-1e39dfcf7601.png)
immediately the close icon moves to left
![image](https://user-images.githubusercontent.com/13157115/59713073-5f98a400-91c3-11e9-864b-a13730ba36d5.png)

**Comment by ianmcburnie** [comment]
Closing this as it's IE, it's old, and we've not heard any more complaints about it.
