### ISSUE TITLE
New Component: Pulldown List (part of expansions)

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#72]
[removed prior content as it was confusing]

![screen shot 2018-03-28 at 1 52 08 pm](https://user-images.githubusercontent.com/38065/38056174-9a02e134-3290-11e8-9cf0-98dfb6f7fe84.png)

**Comment by ianmcburnie** [comment]
@JeffNixonCreative Can you please add the expansion PDF spec. Thanks!

**Comment by gbeckpdx** [comment]
https://playbook.corp.ebay.com/PlaybookApp#/executional-guidelines/product-design-system/patterns/expansions

**Comment by ianmcburnie** [comment]
Here's the eBay MIND pattern for a "Pulldown List", which is based on the pattern:

https://ebay.github.io/mindpatterns/disclosure/pulldown-list/index.html

Given that the playbook pattern is pretty abstract, and could be used to show more of anything (not just lists), I'm not sure if a component even makes sense. But perhaps a utility method or makeup plugin.

**Comment by ianmcburnie** [comment]
Moving to superbacklog
