### ISSUE TITLE
Listbox: rename to ebay-listbox-button

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#726]
As a segway to v4, let's rename the current `ebay-listbox` to `ebay-listbox-button`. API will remain unchanged in this version and listbox will still be coupled to button.

In v4 we will completely separate the menu from the button #690 

Doing it like this means we get to Markov4 quicker, but can go back and add an `ebay-listbox` to CoreUI v3.1 if it is asked for.

**Comment by DylanPiercey** [comment]
@ianmcburnie I think it might be worth writing an auto migration for this.

**Comment by ianmcburnie** [comment]
Good idea. That would be a good practice for us to get into with CoreUI.

**Comment by ianmcburnie** [comment]
Changes merged to 2.8.0 branch. Closing.
