### ISSUE TITLE
Dialog: always closes when user releases mouse button outside of modal

### ISSUE THREAD

**Issue by bhoomisatasiya** [eBay/ebayui-core#734]
# Bug Report
Modal closes when user is trying to select something on the modal and mouse goes out of the modal content area

## Description

- The modal is closing when user tries to select some content on the modal body and mouse goes out side the modal area. 

## Screenshots

![Large GIF (640x367)](https://user-images.githubusercontent.com/11545472/60541988-a3150700-9cc7-11e9-852e-3fbb6daf56f1.gif)

**Comment by ianmcburnie** [comment]
Maybe something to do with this logic:

https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-dialog/index.js#L39

We shall investigate.

**Comment by agliga** [comment]
Looks like the issue is the fact that onclick is triggering on mouse up. If you click in the dialog and drag out, when you let go of your mouse button, it triggers onclick.

**Comment by ianmcburnie** [comment]
Fix will go out in 2.8.0
