### ISSUE TITLE
Combobox: Adjust the width to the width of the longest option

### ISSUE THREAD

**Issue by melquan** [eBay/ebayui-core#735]
# Feature Request

## Description
Adjust the width of the combobox to be the width of the longest option.

**Comment by melquan** [comment]
So the thing is we have a usecase where the component is disabled and the user is only able to see the clipped portion of the visible text.

**Comment by ianmcburnie** [comment]
I could see how this might create a really wide textbox and create a bad looking UI, if one of the options is long. In an effort to keep our API as clean as possible, I'm going to shelve this one for now. If more teams ask for it, or design team asks for it, we may reconsider in future.

**Comment by seangates** [comment]
@ianmcburnie Well, teams were asking for it, which is why it was created.

That probably leaves @melquan with having to override some things or doing her own calculations for the Seller Hub / Cub NextGen / and Bolt tools (they'll all use this component).

**Comment by ianmcburnie** [comment]
@seangates I'm aware of that, see my comment:

`If more teams ask for it, or design team asks for it, we may reconsider in future.`

I don't feel good about having our core component in a potentially broken state (extra wide) and deviating from how a textbox behaves. If selling teams wants to create an app component that wraps our core component, they should be able to do that.

**Comment by seangates** [comment]
Seller Hub / Cub / Bolt are about 12 teams altogether. 😉

**Comment by ianmcburnie** [comment]
Again, completely aware.
