### ISSUE TITLE
editable combobox- change event is triggered on every select and blur

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#740]
# Bug Report

## Description
editable combobox xhange event is triggered even when the same item is selected again and again and also on every collapse.
https://www.loom.com/share/0f2a1494ff9244ef8f3863604c7afc18

**Comment by seangates** [comment]
If this no longer fired on blur, it would be a breaking change for developers who relied on it on every `blur`. That said, I think we could possibly add a guard so it only fires when the value actually changes.

**Comment by ianmcburnie** [comment]
Yep, it should be consistent with `<input type="text">` which I believe only fires a change event on blur if the value actually changed. Don't we just piggy back off of the DOM event? i.e. fire our custom event when the DOM event fires?

**Comment by seangates** [comment]
We presently do not piggyback. Let me do some testing to see if that would work.

**Comment by ianmcburnie** [comment]
Due for QA in 4.3.0-0
