### ISSUE TITLE
badge:In IE 11  when badge is used in a menu. It is not rendered properly

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#741]
# Bug Report

## Description
In IE 11  when badge is used in a menu. It is not rendered properly
also the badges are truncated with the button size
![image](https://user-images.githubusercontent.com/13157115/60835413-dd731e00-a177-11e9-9a6b-342e3d9ba8f1.png)

**Comment by ianmcburnie** [comment]
We have a few known, open issues with badge in IE11, so this might be a duplicate (check on Skin github too). We are treating anything for IE11 as low priority right now.

**Comment by hramakumar** [comment]
duplicate of https://github.com/eBay/skin/issues/663
