### ISSUE TITLE
Carousel: autoplay does not work (IE11, Edge)

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#743]
# Bug Report

## Description
autoplay carousel does not work as intended.
The carousal auto slide and clicking on pause and play button wont work.

**Comment by agliga** [comment]
I tried this on `4.1.0` branch  with edge I was able to see the autoplay work correctly.

**Comment by ianmcburnie** [comment]
@hramakumar To verify as part of 4.2.0

**Comment by hramakumar** [comment]
The issue still exists.
The autoplay carousal does not work in IE edge, windows 10

**Comment by agliga** [comment]
Can you also provide a screenshare of the issue?

**Comment by hramakumar** [comment]
![image](https://user-images.githubusercontent.com/13157115/65646588-5bdda000-dfb0-11e9-822b-3e6594d93892.png)

**Comment by hramakumar** [comment]
it just stays still when i pause and pay. It does not move slides.
also I see that the paddles dont work

**Comment by ianmcburnie** [comment]
Okay. Let's try and squeeze a fix into 4.2.0-1

**Comment by seangates** [comment]
@hramakumar As with @agliga's assessment, I can't reproduce the issue either. Closing for now, and you can open a new issue with more information, if you see it not working again.

FWIW, I tested both your published site (ebayuicomponentstestenv.vip.qa.ebay.com) and pulled the test site code and ran it locally. Both had the same result that I could use the carousel as intended.

**Comment by hramakumar** [comment]
@seangates  did you try it in edge?  I know ie 11 works fine now
