### ISSUE TITLE
Combobox: Thin gray line shows up when refocusing into the combobox and there are no matching options

### ISSUE THREAD

**Issue by melquan** [eBay/ebayui-core#745]
# Bug Report

## Description
A thin gray line shows up when refocusing into the combobox and there are no matching options.

Steps:
1. Enter something in the combobox that doesn't match any existing options.
2. Blur out of the comboxbox.
3. Focus in the combobox again.

## Workaround
None.

## Screenshots
![image](https://user-images.githubusercontent.com/19419138/60849483-c34d3600-a19f-11e9-8f6f-f61d1f2d2736.png)

**Comment by ianmcburnie** [comment]
Unable to reproduce on ds4 or ds6, so perhaps this got fixed. If not please reopen.

**Comment by melquan** [comment]
Yep, appears to fixed in the latest version.  Thanks!

**Comment by melquan** [comment]
Actually I was able to reproduce it in the latest version 4.4.3 if I blur out and focus into the combobox again:

![image](https://user-images.githubusercontent.com/19419138/70286093-a16fd380-177e-11ea-98cd-44de38b410cb.png)

**Comment by ianmcburnie** [comment]
Ah yes, I see it on coreui. I also see it on Skin when I delete all options and set expanded to true.

![Uploading Screen Shot 2019-12-05 at 4.50.15 PM.png…]()

Reopening, Thanks!

**Comment by ianmcburnie** [comment]
@agliga Another combobox one for you :-)

**Comment by agliga** [comment]
I tried this on `5.6.0` branch, and was unable to reproduce.
![combobox-filter](https://user-images.githubusercontent.com/1755269/84921381-3f6f1f80-b079-11ea-83dc-648ea3010c57.gif)
I tried safari, firefox and chrome (video is on safari so Ian can be happy)

**Comment by agliga** [comment]
@ianmcburnie  can you try again or let me know the steps to reproduce? Keeping open just in case I missed something.

**Comment by ianmcburnie** [comment]
Thanks. The only odd thing I notice is that the textbox bottom border sometimes disappears and can look a bit odd, but it's mild, and a different issue, so I'm closing this one.
