### ISSUE TITLE
Documentation: Ensure component READMEs have a "required" column for attributes

### ISSUE THREAD

**Issue by seangates** [eBay/ebayui-core#750]
# Feature Request

## Description
Add a required column to the attribute table of any component READMEs which don't have one.

## Context
Presently, developers don't know if certain A11Y attributes are required or not. Adding this column would help them know what they are required to add to be A11Y compliant.

Some have them, like [Listbox](http://app.uimarketplace.svc.32.tess.io/?tag=ebay-listbox), but some don't, like [Notice](http://app.uimarketplace.svc.32.tess.io/?tag=ebay-notice).

**Comment by ianmcburnie** [comment]
Excellent idea!
