### ISSUE TITLE
Infotip: DS4 icon is not 16x16 as per SKIN documentation

### ISSUE THREAD

**Issue by melquan** [eBay/ebayui-core#751]
# Bug Report

## Description
The D4 infotip icon is not 16x16 as per the SKIN documentation so when displayed in proximity to an inline informational `ebay-notice`, you can see the size difference.

## Workaround
None.

## Screenshots
![image](https://user-images.githubusercontent.com/19419138/60993280-f825ce00-a302-11e9-9e1e-75c01c72758d.png)

**Comment by agliga** [comment]
Issue needs to be fixed in skin, need to add CSS to resize infotip button 
Will do it as part of a `7.4.3` release
