### ISSUE TITLE
Button: classname coming as ${variant}-btn when rendered

### ISSUE THREAD

**Issue by pranaykondekar** [eBay/ebayui-core#752]
button component have invalid classnames when passed a variant.
Rendered markup is coming as 
`<button class="${variant}-btn ${variant}-btn--no-text ${baseClass}--${size} ${variant}-btn--secondary" type="button">
  <svg class="expand-btn__icon" xmlns="http://www.w3.org/2000/svg" focusable="false" aria-hidden="true"><use xlink:href="#icon-chevron-down-bold"></use></svg>
</button>`

**Comment by ianmcburnie** [comment]
Closing as invalid.
