### ISSUE TITLE
Create Browserlist repository for enforcing eBay's browser policy

### ISSUE THREAD

**Issue by seangates** [eBay/ebayui-core#76]
## Description

Refer to #74.

We should create a repository to house a set of Browserlist definitions, specifically to keep eBay in lock-step around browser policy.

## Resources

[Browserlist](https://github.com/browserslist/browserslist)
[Browserlist is a Good Idea](https://css-tricks.com/browserlist-good-idea/#article-header-id-1)

**Comment by senthilp** [comment]
@seangates I think this should be tracked outside of eBayUI. Can we create this issue under [eslint-config-ebay](https://github.com/eBay/eslint-config-ebay) and we will pick it up over there? What we need is a [sharable config](https://github.com/browserslist/browserslist#shareable-configs).

**Comment by seangates** [comment]
Sure. Didn't quite know where to put it.

**Comment by seangates** [comment]
Moved to https://github.com/eBay/eslint-config-ebay/issues/12.
