### ISSUE TITLE
Carousel: Continuous status text issues

### ISSUE THREAD

**Issue by DylanPiercey** [eBay/ebayui-core#764]
# Bug Report

## Description
Currently with continuous carousels the `a11y-status-text` option is omitted since there is no `totalSlides` (no `items-per-slide` is set). After discussion it sounds like we also need another a11y attribute in order to accommodate this.

Essentially we need one a11y attribute for the `slide x of y` text, and another for a prepending heading (for the complete a11y text of `Heading - slide x of y` where the continuous variant would just use `Heading`.

**Comment by ianmcburnie** [comment]
Done in 4.4.0
