### ISSUE TITLE
ebay-menu: build error- unable to recognize ebay-menu and ebay-menu-item tags

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#766]
# Bug Report

## Description
 [src/ui-modules/ebayuitestpage1/index.marko:297:20] Unrecognized tag: ebay-menu - More details: https://github.com/marko-js/marko/wiki/Error:-Unrecognized-Tag
[src/ui-modules/ebayuitestpage1/index.marko:306:24] Unrecognized tag: ebay-menu-item - More details: https://github.com/marko-js/marko/wiki/Error:-Unrecognized-Tag

**Comment by ianmcburnie** [comment]
Fixed.
