### ISSUE TITLE
Filter Menu: new component

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#770]
A menu specifically used for filtering. Potentially we need two variants:

* Form based (i.e. full page reload)
* ARIA based (i.e. AJAX/SPA)

Can be placed directly on page (no use case for this yet, but thinking ahead...)

Can be used inside of a filter menu button (our DS6.5 use case)

**Comment by msendlakowski** [comment]
I'm removing this from the project and milestone since there isn't any design pattern for this, outside of the filter-menu-button.  I'll leave it in the backlog in case you still think it needs to be an independent component.

**Comment by ianmcburnie** [comment]
Architecturally, it makes sense to have this as a separate component. But I agree, if it's not a priority for DS6.5, it should go to the backlog. I would have thought however, that the filter-menu-button would make use of the filter-menu component...

**Comment by seangates** [comment]
Yeah, it's the same argument for `menu`.
