### ISSUE TITLE
carousal: hover over carousel stops autoplay slide movement

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#775]
# Bug Report

## Description
mouse over autoplay carousal stops the slide movement in autoplay carousal
https://www.loom.com/share/9cc0d5362ce144fb9db7376e2218fa74

**Comment by seangates** [comment]
I believe this is expected behavior, given recent changes to the carousel.

**Comment by DylanPiercey** [comment]
Yes this is expected behavior https://github.com/eBay/ebayui-core/issues/586
