### ISSUE TITLE
Icon: some incompatible icons in ds4 are not replaced with '?'

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#776]
# Bug Report

## Description
down arrow and download icon needs to fixed
ci-slc.altus.vip.ebay.com/ebayuicomponentstestenv-5292

**Comment by ianmcburnie** [comment]
If it's just two icons that need fixing, we prob don't need another pre-release & QA just for this. We can push a commit just before final release.

**Comment by ianmcburnie** [comment]
Nevermind, looks like we will need another pre-release as we have a few issues building up now:

https://github.com/eBay/ebayui-core/projects/44

**Comment by agliga** [comment]
I tried this out,  these seem to work now with the fix for #779 
If it's still broken we can address it.
