### ISSUE TITLE
breadcrumbs-last page as parent-right arrow is displayed at the right of the leaf element

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#78]
I have added the components to the ebayui test page.
http://go/ebayuitest

Breadcumbs- last page as parent 
I see a right arrow to the right  of the leaf element pointing to nothing.
This is what I used
<ebay-breadcrumb heading-text="Page navigation">
                <ebay-breadcrumb-item href="http://www.ebay.com/">eBay</ebay-breadcrumb-item>
                <ebay-breadcrumb-item href="https://www.ebay.com/rpp/cell-phone-pda">Cell Phones, Smart Watches & Accessories</ebay-breadcrumb-item>
                <ebay-breadcrumb-item href="https://www.ebay.com/b/Smart-Watch-Accessories/182064/bn_16565905">Smart Watch Accessories</ebay-breadcrumb-item>
                <ebay-breadcrumb-item href="https://www.ebay.com/b/Smart-Watch-Bands/182068/bn_16565906">Smart Watch Bands</ebay-breadcrumb-item>
            </ebay-breadcrumb>

screenshot attached

You can see a right arrow to the right of "Smart Watch Bands"

**Comment by ianmcburnie** [comment]
@RajaRamu please can you investigate breadcrumb issue.

**Comment by RajaRamu** [comment]
As we investigated, some styles from GH is colliding with skin.breadcrumb. Solution is that use following GH configure to resolve this, 
`<gh-configure layout="FULL"
   searchFormAction="/keywords" footerLayout='NORMAL'/>`

Test App is used to have which was have some colliding styles. we 

```
<gh-configure layout="FULL" categoryId="0" dsVersion="5" searchKeywords
    searchFormAction="/keywords"/>
```

**Comment by RajaRamu** [comment]
this is just a setup issue hence closing it.
