### ISSUE TITLE
listbox: resizing and line wrapping changes the size of the listbox when different options of different length are selected

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#780]
# Bug Report

## Description
list box line wrapping causes resizing of the component

## Screenshots
https://www.loom.com/share/90387c5e10cb42449008fc2c6fe2c366

**Comment by ianmcburnie** [comment]
Given that we don't want listbox buttons to go to two lines, and this is something of an edge case, I feel like we can move this to backlog for now.

**Comment by ianmcburnie** [comment]
This can be solved by using fixed height and width on button. Closing.
