### ISSUE TITLE
Breadcrumbs: long text end of line - new line starts with the arrow

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#79]
Added the new component to the ebayui test env page
When I use long text to fill the line- the new line starts with the arrow

expected behavior- The new line takes in the last word with it

http://go/ebayuitest

screenshot attached

**Comment by hramakumar** [comment]
pls look at the last line in the screenshot

<ebay-breadcrumb heading-text="Page navigation">
                <ebay-breadcrumb-item href="https://www.ebay.com/rpp/cell-phone-pda" navsrc="{}" _sp="p2345.m909.l34">Cell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches AccessorieshhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phoneshdhdhkkkk kkkk</ebay-breadcrumb-item>
                <ebay-breadcrumb-item href="https://www.ebay.com/b/Smart-Watch-Accessories/182064/bn_16565905">Smart Watch Accessories</ebay-breadcrumb-item>
            </ebay-breadcrumb>

**Comment by hramakumar** [comment]
<ebay-breadcrumb heading-text="Page navigation">
                <ebay-breadcrumb-item href="https://www.ebay.com/rpp/cell-phone-pda" navsrc="{}" _sp="p2345.m909.l34">Cell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches AccessorieshhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phones, Smart Watches & Accessories-hhhhhhhhCell Phoneshdhdhkkkk kkkk</ebay-breadcrumb-item>
                <ebay-breadcrumb-item href="https://www.ebay.com/b/Smart-Watch-Accessories/182064/bn_16565905">Smart Watch Accessories</ebay-breadcrumb-item>
            </ebay-breadcrumb>

**Comment by hramakumar** [comment]
pls look at the last line

**Comment by hramakumar** [comment]
![arrow](https://user-images.githubusercontent.com/13157115/38386747-927614dc-38ca-11e8-888b-4c8b25aec5d7.png)

**Comment by hramakumar** [comment]
1) the leaf node goes to the next line - Raja will fix it
2)can a new line start with an arrow?-question to the design team

**Comment by RajaRamu** [comment]
PR is open - https://github.com/eBay/skin/pull/130

**Comment by hramakumar** [comment]
![screenshot_2018-04-05-01-03-36](https://user-images.githubusercontent.com/13157115/38396386-a389bf90-38ec-11e8-9b02-43f84ebb7957.png)
the fix broke mweb styling

**Comment by hramakumar** [comment]
compare the first one"element with last page as current" and "element until end of line" and

**Comment by ianmcburnie** [comment]
@RajaRamu Can you investigate & provide more information on whether this is expected or not.

**Comment by hramakumar** [comment]
I downgraded to skin version 3.5.1 and this issue goes away.
It has something to do with the skin upgrade 3.5.2(fix version)

**Comment by hramakumar** [comment]
![skin-3 5 1](https://user-images.githubusercontent.com/13157115/38397396-5270a96a-38f2-11e8-9d64-8e9215b2aacc.png)![skin 3 5 2](https://user-images.githubusercontent.com/13157115/38397397-5289672a-38f2-11e8-947f-0d050b84063a.png)

**Comment by hramakumar** [comment]
**Actual**
![skin-3 5 1](https://user-images.githubusercontent.com/13157115/38397431-68dcd14c-38f2-11e8-940a-57b3dfc904e1.png)

**Expected**
![skin 3 5 2](https://user-images.githubusercontent.com/13157115/38397432-68f06ee6-38f2-11e8-95cf-97a6584062f6.png)

**Comment by hramakumar** [comment]
**actual**
![skin_3 5 2](https://user-images.githubusercontent.com/13157115/38397558-24ab4700-38f3-11e8-92e2-0e5d72346c64.png)

**expected**
![skin-3 5 1](https://user-images.githubusercontent.com/13157115/38397559-24c1b2f6-38f3-11e8-9d9f-f2b57f35e278.png)

**Comment by hramakumar** [comment]
# **actual**


![skin_3 5 2](https://user-images.githubusercontent.com/13157115/38397594-699d2b44-38f3-11e8-89b8-1f4fe648e259.png)

# **expected**


![skin-3 5 1](https://user-images.githubusercontent.com/13157115/38397617-866aa896-38f3-11e8-99ff-362e1b16fae7.png)

**Comment by ianmcburnie** [comment]
@RajaRamu Can you please investigate.

**Comment by RajaRamu** [comment]
Yes. i will have to test it mobile devices. i will check it out in device lab. thanks

**Comment by ianmcburnie** [comment]
Original issue was resolved.
