### ISSUE TITLE
Listbox-button: support fluid version

### ISSUE THREAD

**Issue by melquan** [eBay/ebayui-core#799]
# Feature Request

## Description
Add support for a fluid version of the of the listbox-button.

## Context
ebayui-core version: 2.8.0

## Screenshots
![image](https://user-images.githubusercontent.com/19419138/62170329-e6bb5a80-b2df-11e9-946d-5ce9738387b3.png)

**Comment by msendlakowski** [comment]
I don't see this in the pattern guide, but it makes sense to me.  I marked it for discussion when we address the DS6.5 listbox updates.

**Comment by seangates** [comment]
@msendlakowski Yeah, some parts of the design system aren't clear on things like this. But, as a form control, there are very good reasons to make it fluid, just like textbox, select, etc.

**Comment by ianmcburnie** [comment]
On the skin side this is currently supported via `expand-btn--fluid`

**Comment by ianmcburnie** [comment]
Done in 4.4.0
