### ISSUE TITLE
New Component: Pill

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#8]
Design doc:
https://ebay.invisionapp.com/share/CWN9X1JF6MA#/screens/293357159

**Comment by msendlakowski** [comment]
@seangates @yomed 
Based on our skin discussion we need a JS solution for line-clamp.  This is something I created a while ago.  

https://github.corp.ebay.com/eBayUI/ebayui-ellipsis

Do you have any other solutions or should I modify this for the component? 

Also, whatever solution we come up with, I'm thinking to add it as a common utility. What do you think?

**Comment by ianmcburnie** [comment]
I guess adding a `pill` boolean to ebay-button is the simplest way to go, but if there are going to be some button attributes not suitable or relevant to the pill, I wonder if it's worth creating an ebay-pill which acts as a simplified facade to ebay-button?

**Comment by seangates** [comment]
Well, a lot of the attributes will be handled with state inside the `ebay-pill` component (e.g. checked state) so we wouldn't want to expose those the same was as the `ebay-button`. It's a button ... but more of a button type with limited button options.

So, I'm 100% in line with your thinking.
