### ISSUE TITLE
infotip: infotip without icon attribute - broken- does not open on click

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#810]
# Bug Report

## Description
info tip is broken when no icon is explicitly mentioned
The default icon is not aligned with shape and size and it does not open up the infotip content on click
## Screenshots

![image](https://user-images.githubusercontent.com/13157115/62394544-5b7dd700-b522-11e9-9e5f-e71cba2d43a1.png)

**Comment by agliga** [comment]
Need to change icon to information from info
