### ISSUE TITLE
listbox: when expanded does not expand with option text size instead it line wraps

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#814]
# Bug Report

## Description
options line wraps when texts are long.
**actual**
![image](https://user-images.githubusercontent.com/13157115/62396119-21fb9a80-b527-11e9-86ae-d2995ecf6bc4.png)

**expected**
![image](https://user-images.githubusercontent.com/13157115/62396092-0a241680-b527-11e9-8f1c-b10c4674e48e.png)

**Comment by agliga** [comment]
Need to add class listbox-button__value to span with text
