### ISSUE TITLE
ds4- focus boundary is very light

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#817]
# Bug Report

## Description
In ds4. when clicked on a component. The focus indicator is displayed very light.
in the below example partially disabled button is clicked. It used to be darker in the previous releases.
![image](https://user-images.githubusercontent.com/13157115/62403593-2fbf1900-b543-11e9-8618-5645dc90fa4f.png)

**Comment by msendlakowski** [comment]
This looks like its fixed in the 9.0.0 build.
![Screen Shot 2019-09-05 at 2 36 25 PM](https://user-images.githubusercontent.com/1562843/64383369-9e800e00-cfea-11e9-9fb8-974ef4c91766.png)
