### ISSUE TITLE
Combobox: Chrome's autocomplete suggestions are not suppressed

### ISSUE THREAD

**Issue by melquan** [eBay/ebayui-core#819]
# Bug Report

## Description
Chrome's autocomplete suggestions still show up when focusing in the combobox.

## Screenshots
![image](https://user-images.githubusercontent.com/19419138/62558821-950a5700-b82e-11e9-9eba-d8185eccbd9a.png)

**Comment by msendlakowski** [comment]
@melquan Can you check to see if you're passing an "autocomplete" attribute in `html-attributes`.  
The final HTML should have `autocomplete='new-password'` according to this PR:
https://github.com/eBay/ebayui-core/commit/4ab6cacb52ccd54338675d447d8b785e614b1c71#diff-854be3f0318a650eed139adb0e266c38

That was supposed to be a clean cross-browser fix, but according to this thread, that may not work in newer versions of Chrome:
https://gist.github.com/runspired/b9fdf1fa74fc9fb4554418dea35718fe#gistcomment-2973376

**Comment by msendlakowski** [comment]
@melquan Can you also add the version of Chrome you are using.

**Comment by melquan** [comment]
@msendlakowski We are passing in an `autocomplete` attribute to the ebay-combobox of either `none` or `list` based on the README and direction from @seangates & @ianmcburnie to support our functionality.

Will get you the Chrome version soon (getting it from my teammate who could encountered the issue).

**Comment by msendlakowski** [comment]
@melquan Nevermind... I see it now too.  It looks like it broke in newer versions of Chrome.

**Comment by msendlakowski** [comment]
This is a Chrome bug.  I'll put this in our backlog so we can address it once they have a working solution (again).
https://bugs.chromium.org/p/chromium/issues/detail?id=914451

There is a work around where we mark it as read-only until the field gets focus.  But its a hack and would probably create accessibility issues.
https://stackoverflow.com/questions/12374442/chrome-ignores-autocomplete-off/32578659#32578659

**Comment by seangates** [comment]
@msendlakowski Thanks for tracking down the bug report!

**Comment by austingardner** [comment]
It seems this could be a bug that is never fixed for political / business reasons... so a better workaround might be a good idea. 

I ran into this issue when adding readonly to the combobox in [this PR]().

Looking in the comments on this issue on bugs.chromium.org, I found the suggestion [here, comment 139](https://bugs.chromium.org/p/chromium/issues/detail?id=914451#c139) to use a textarea with a hidden input to solve this. Apparently this is what gmail does. 

```
<div id=":pu" class="oj">
 <div class="wO nr l1">
  <input class="wA" tabindex="-1" aria-hidden="true">
  <textarea rows="1" id=":q7" class="vO" name="to" spellcheck="false" autocomplete="false" autocapitalize="off" autocorrect="off" tabindex="1" dir="ltr" aria-label="Para" role="combobox" aria-autocomplete="list" style="width: 1143px;"></textarea>
 <div class="aA6"></div>
  </div>
</div>
```

I think we should try something like this, because 
1. We are still facing issues with this
2. This could never be solved / could take a very long time to be solved by the Chrome team

**Comment by PrashantAshok** [comment]
@austingardner @ianmcburnie - Looks like `autocomplete="off"` now works for Chrome 91 Mac + Windows(I tried 88 - that seems to work as well) 

https://stackoverflow.com/a/30976223/13047179

![2021-06-22 11 41 30](https://user-images.githubusercontent.com/5200733/122982129-595bd600-d34f-11eb-901b-b79d55ad2aaf.gif)

Can the team please relook into this, we are planning to use `combobox` - would be helpful, if we can figure out a solution.

**Comment by austingardner** [comment]
Does it really? That's great news! We'll take a look and then implement it if there are no issues.
