### ISSUE TITLE
Add grow reverse for menu items

### ISSUE THREAD

**Issue by bhoomisatasiya** [eBay/ebayui-core#82]
The menu should provide an option to grow the menu items in reverse.

<img width="1027" alt="screen shot 2018-04-04 at 10 29 04 pm" src="https://user-images.githubusercontent.com/11545472/38386623-0c13b84a-38ca-11e8-85c5-23ac3b36cb3f.png">

<img width="1225" alt="screen shot 2018-04-04 at 10 28 15 pm" src="https://user-images.githubusercontent.com/11545472/38386660-26295a6e-38ca-11e8-8921-d0f4aefcb32e.png">

**Comment by yomed** [comment]
Hi @bhoomisatasiya -- Thanks for reporting this issue. It has been fixed, and will be out in the `0.2.0` release (coming out shortly).
