### ISSUE TITLE
pills: DS6 disabled pills change color on hover

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#821]
# Bug Report

## Description
Disabled Pilled change color on hover. Happens in both secondary and primary.
## Screenshots
https://www.loom.com/share/c97c923056b64b428ed7862f3cb3b0ab

**Comment by msendlakowski** [comment]
@ianmcburnie I'd say we just fix this in 9.0 since we're deprecating pills anyway.

**Comment by msendlakowski** [comment]
Closing this, since the filter button is replacing pills in v9 and the issue does not exist in filter button.
