### ISSUE TITLE
infotip: default icon color is changed to blue

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#822]
# Bug Report

## Description
default icon color is changed in infotip
Pls change the label to bug if this is not an expected change in this release
## Screenshots
https://www.loom.com/share/10cac0b0dbc746259a24c9f421d0be40

**Comment by msendlakowski** [comment]
Is this for DS4 or DS6.  According to the current published version of skin DS6 it looks like the infotip icon is supposed to be blue

**Comment by hramakumar** [comment]
oh ok. I was not sure about that which is why I filed it as a discussion.
Lets close it.
