### ISSUE TITLE
icons: in DS4 , In Iphone some icons when used with infotip, menu etc are truncated

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#823]
# Bug Report

## Description
Some icons look truncated when used infotip  and menu
## Workaround
icon in infotip(testpage), menu(marketplace) and radio(marketplace) are broken in testpage and marketplace
## Screenshots

![AD63F89E-DA1C-41E8-A8D0-A680D57E2E42](https://user-images.githubusercontent.com/13157115/62730206-5b735080-b9d4-11e9-9e5a-d613acac25a9.png)
![F161A4F7-88D2-41EA-8FA0-AC2630E59E6D](https://user-images.githubusercontent.com/13157115/62730207-5b735080-b9d4-11e9-9308-600f06d60f63.png)
![088C1CB1-0966-4353-BB6C-C32EF419637E](https://user-images.githubusercontent.com/13157115/62730208-5b735080-b9d4-11e9-91e3-0d93cf45d747.png)

**Comment by seangates** [comment]
Is that Chrome on iOS?

**Comment by hramakumar** [comment]
in iphone, both chrome and safari has this behavior on ds4  components

**Comment by hramakumar** [comment]
everything works fine except for the info tip icons in the test page.
the second screenshot above.

**Comment by hramakumar** [comment]
closing the blocker. will re-verify this again on 750 is in.
