### ISSUE TITLE
borderless menu and listbox: when expanded the border starts from the left letter 

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#824]
# Bug Report

## Description
borderless menu: when expanded the border starts from the left letter. This makes the options and header look unaligned with each other. The heading text is to the left of the oprions
## Screenshots

![image](https://user-images.githubusercontent.com/13157115/62731690-97f47b80-b9d7-11e9-874b-d6bf1a78c1e0.png)

**Comment by msendlakowski** [comment]
This follows design guidelines.  (Screenshot from the eBay Playbook below.)
![Screen Shot 2019-08-14 at 3 07 03 PM](https://user-images.githubusercontent.com/1562843/63059827-52d3bc00-bea5-11e9-9809-feb30eaec93b.png)
