### ISSUE TITLE
BUG: Dialog is too thin, additional types not accounted for

### ISSUE THREAD

**Issue by seangates** [eBay/ebayui-core#835]
# Bug Report

## Description
The current dialog has a `max-width` of 616px, which constrains it to a very small part of the screen.

<strike>
Per the Design System, it should stretch as much as it needs, but only following some parameters given the dialog "types": question, information, and function.

Type definitions:

- **question dialog** should be used when asking users to answer a single question, confirm a command, or select a task.
- **information dialog** display information by request, show alerts, present feedback or offer progress during the operation.
- **function dialog** should be used when CTAs are needed or complex tasks for users to complete.

Essentially, we pretty much only built the information dialog. So ... we should consider how to accommodate the other two types easily.
</strike>

I've also created a [corresponding Skin issue](https://github.com/eBay/skin/issues/797).

## Workaround
Local overrides of CSS.

## Screenshots

**The design system provides more columns to stretch as needed:**
![image (4)](https://user-images.githubusercontent.com/105656/63790943-9839b580-c8b7-11e9-9523-492bb19aa71f.png)

**The current dialog does not have enough width for a function to be performed:**
![image (3)](https://user-images.githubusercontent.com/105656/63791011-bdc6bf00-c8b7-11e9-9e5a-75cf5b33e623.png)

UPDATED WITH LATEST SPEC FROM PLAYBOOK:

<img width="483" alt="Screen Shot 2020-04-23 at 2 07 44 PM" src="https://user-images.githubusercontent.com/38065/80149773-109e6680-856c-11ea-9535-e8746d6bf949.png">

**Comment by ianmcburnie** [comment]
Investigate and deemed not to be an issue.
