### ISSUE TITLE
the width of the checkbox is reduced

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#838]
# Bug Report

## Description
the checkbox width is reduced
https://www.loom.com/share/9f715d0c30e64a539350356e3fcd6d7a

**Comment by msendlakowski** [comment]
In that pre-release we resized the small icon to be larger.  We updated to have the large icon become smaller, and this doesn't appear to be an issue anymore.
![Screen Shot 2019-09-05 at 2 39 36 PM](https://user-images.githubusercontent.com/1562843/64385387-2bc36280-cfeb-11e9-8fd2-e0e1f1c28d13.png)
