### ISSUE TITLE
Breadcrumbs: Desktop-Broken - when long, the text on the left are truncated

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#852]
# Bug Report

## Description
The bread crumbs are broken
## Screenshots
https://www.loom.com/share/63725bda504d42a1b61f76946a3505da

**Comment by seangates** [comment]
@hramakumar Is that our longest category tree?

**Comment by seangates** [comment]
BTW, this change was intentional, specifically for mobile. I'm just trying to explore what our upper limit is.

**Comment by hramakumar** [comment]
Thats not one of the long tree. Its happens in Desktop version as well

**Comment by hramakumar** [comment]
<ebay-breadcrumb heading-text="Page navigation">
                <ebay-breadcrumb-item href="http://www.ebay.com/">eBay</ebay-breadcrumb-item>
                <ebay-breadcrumb-item href="https://www.ebay.com/rpp/cell-phone-pda">Cell Phones, Smart Watches & Accessories</ebay-breadcrumb-item>
                <ebay-breadcrumb-item href="https://www.ebay.com/b/Smart-Watch-Accessories/182064/bn_16565905">Smart Watch Accessories</ebay-breadcrumb-item>
                <ebay-breadcrumb-item href="https://www.ebay.com/b/Smart-Watch-Bands/182068/bn_16565906">Smart Watch Bands</ebay-breadcrumb-item>
                <ebay-breadcrumb-item href="http://www.ebay.com/">eBay</ebay-breadcrumb-item>
                <ebay-breadcrumb-item href="https://www.ebay.com/rpp/cell-phone-pda">Cell Phones, Smart Watches & Accessories</ebay-breadcrumb-item>
                <ebay-breadcrumb-item href="https://www.ebay.com/b/Smart-Watch-Accessories/182064/bn_16565905">Um Ihnen ein besseres Nutzererlebnis zu bieten, verwenden wir Cookies. Durch Nutzung von eBay stimmen Sie unserer Verwendung von Cookies zu.</ebay-breadcrumb-item>
                <ebay-breadcrumb-item href="http://www.ebay.com/">eBay Cell Phones, Smart Watches & Accessories</ebay-breadcrumb-item>
            </ebay-breadcrumb>

**Comment by msendlakowski** [comment]
@seangates - looks like you're already looking into this. but let me know if not.

**Comment by seangates** [comment]
Yes, I can follow this through.

**Comment by seangates** [comment]
This is as expected.
