### ISSUE TITLE
Filters: Normalize naming for API around pressed/selected/active

### ISSUE THREAD

**Issue by seangates** [eBay/ebayui-core#859]
# Feature Request

## Description
Presently we have a `pressed` and `a11y-active-text` attributes, and also talk about "selected" filters. Make sure that the API and documentation refer to "selected".

## Context
The present setup can be confusing. This work would be able to remove confusion in the API and nomenclature.

**Comment by ianmcburnie** [comment]
Pretty sure this got addressed. Closing.
