### ISSUE TITLE
ebay-button: variable not resolved correctly

### ISSUE THREAD

**Issue by cynthiahhc** [eBay/ebayui-core#860]
# Bug Report

## Description
It does not resolve to the correct `baseClass` and `size`
https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-button/template.marko#L13

## Screenshots
![Screen Shot 2019-09-09 at 11 59 48](https://user-images.githubusercontent.com/12440585/64558771-8addeb80-d2f9-11e9-82eb-4fffaf695dcf.png)

**Comment by msendlakowski** [comment]
@cynthiahhc Can you tell me what version of Marko you're using?

**Comment by cynthiahhc** [comment]
I'm using `marko@4.12.3`.

**Comment by DylanPiercey** [comment]
@cynthiahhc when using legacy Marko v3 components (like eBay-ui) it is best to make sure that you are on the latest version of Marko 4 for the best compatibility. Is there anything preventing you from upgrading to the latest version of Marko?

**Comment by msendlakowski** [comment]
@cynthiahhc Can you try what Dylan suggested, and upgrading your version of Marko, to see if this is still a problem.

**Comment by ianmcburnie** [comment]
Closing due to lack of information/follow-up.
