### ISSUE TITLE
Tool Tip- IOS: clicking on the tool tip the 2nd time wont open up

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#862]
# Bug Report

## Description
in ios clicking on the tooltip the second time won't open up the text

**Comment by msendlakowski** [comment]
Clicking a tooltip shouldn't open the text at all, just hover and focus.  We should also review any accessibility concerns with this behavior.  Discussed with @hramakumar and he said this is a legacy issue, so adding it to the backlog.

**Comment by ianmcburnie** [comment]
Correct. Tooltip only opens on hover. Infotip opens on click.

@hramakumar Was this infotip or tooltip?

**Comment by hramakumar** [comment]
its a tool tip. if its not intended then we need to change the behaviour on touch. It shouldn't respond to touch

**Comment by ianmcburnie** [comment]
Some touch devices will emulate hover. The design system dictates that we don't use tooltip on mweb so we can probably close this. @seangates thoughts?

**Comment by ianmcburnie** [comment]
Closing as per comments.
