### ISSUE TITLE
Carousel paddles are shown on hover even if there aren't enough items to scroll

### ISSUE THREAD

**Issue by t-l9** [eBay/ebayui-core#875]
## Description

If a carousel has the `items-per-slide` set to `X`, but there are only `X` items, the paddles are still shown on hover, but disabled.

## Screenshots
<img width="1178" alt="Screen Shot 2019-09-18 at 6 45 20 PM" src="https://user-images.githubusercontent.com/3270650/65192299-95f4f200-da44-11e9-89c9-c17b4b2f98c4.png">

**Comment by ianmcburnie** [comment]
Done in 4.2.0
