### ISSUE TITLE
Notice: icon is cut at the side

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#883]
# Bug Report

## Description
The info icon on the left of the dismissible notice is not fully formed. The edges are cut and is not clear circle.
https://www.loom.com/share/119a5239f0b9400f8a87a6c7d27952fa

**Comment by hramakumar** [comment]
pls watch the video in full screen

**Comment by agliga** [comment]
@hramakumar Can you provide more info on how this is happening? 
I checked on demo pages for this exact notice, tried to shrink the page, tried multiple browsers and it seems to be working on `4.3.0`. 
![image](https://user-images.githubusercontent.com/1755269/66166894-653cbd00-e5ed-11e9-9683-6466510049a4.png)
![image](https://user-images.githubusercontent.com/1755269/66166898-67068080-e5ed-11e9-898e-176632fda743.png)

**Comment by hramakumar** [comment]
It is not reproducible in market place. But if you go to the generic page and look and ebay-infotip section. you should see it.
![image](https://user-images.githubusercontent.com/13157115/66167224-63bfc480-e5ee-11e9-8471-a8c469b9c481.png)

**Comment by ianmcburnie** [comment]
@hramakumar This issue is for Notice component, which I believe has now been fixed.

**Comment by ianmcburnie** [comment]
Closing ticket. @hramakumar please create a new ticket for infotip if necessary and we can fix in 4.4.0
