### ISSUE TITLE
Storybook: add "playground" story for each component

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#884]
<strike>
Pick a component, convert it to 100% native storybook, deleting old examples.

Part of the challenge will be figuring out how to structure the stories, substories, knobs, etc. in line with how we have structured our components, types, variants.

Actually, it may be best to pick two or three, to identify patterns.
</strike>

UPDATED: It seems like the only piece we really need is a "playground" or "sandbox" story that would allow us to dynamically change the state using "knobs". Scope of this task would be to just do this for one or two components.

**Comment by ianmcburnie** [comment]
Punting to 4.4.0

**Comment by seangates** [comment]
Agree. Thanks!

**Comment by ianmcburnie** [comment]
After discussion I now understand that the current examples, in their current format, are crucial for storybook stories. Let's rename the folder from "examples" to "stories", which will help make it clear that we aren't really deviating away from any Storybook standard, and that these folders are used to generate out stories.

It also seems like that we stand to gain very little, if anything at all, by piecing together the stories by hand instead of using the current script in `.storybook/config.js`.

So, it seems like the only piece we really need is a "playground" story that would allow us to dynamically change the state using "knobs". Scope of this task would be to just do this for one or two components.

**Comment by ianmcburnie** [comment]
@seangates Let's do the renaming of "examples" to "stories" as a standalone PR after all other 4.4.0 PRs are in.

**Comment by darkwebdev** [comment]
For React eBayUI components we're just recreating the stories based on your examples, modifying them a bit if necessary. For example [ebay-tab](https://github.corp.ebay.com/React/ebayui-core-react/blob/master/src/components/ebay-breadcrumb/__tests__/index.stories.jsx)

**Comment by ianmcburnie** [comment]
Going to close this one until we've done v6.0.0 and cleaned up our API and tech debt.
