### ISSUE TITLE
carousel when items per slide is not given- it always shows paddles irrespective of the no of items

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#885]
# Bug Report

## eBayUI Version: 4.2.0
if item-per-slide is not given, based on the item length and default item-per-slide value we  need to decide whether to show or hide the paddles
https://www.loom.com/share/96619916349c45588499b31162a40fff

**Comment by seangates** [comment]
Expected behavior as the paddles should be available for the continuous carousel version. The paddle changes in 9.2.0 were only for the discreet (e.g. using `itemsPerSlide` explicitly) version of the carousel.
