### ISSUE TITLE
Tabs: navigating with arrows automatically selects the tab when using manual type

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#893]
# Bug Report

## Description
I used only the arrows. I did not use space or enter
my code
<ebay-tab index="2" Activation="manual">
               <ebay-tab-heading>Tab 1</ebay-tab-heading>
               <ebay-tab-heading>Tab 2</ebay-tab-heading>
               <ebay-tab-heading>Tab 3</ebay-tab-heading>
               <ebay-tab-panel>
                   <h3>Panel 1</h3>
                   <p>1. Lorem ipsum dolor sit amet</p>
               </ebay-tab-panel>
               <ebay-tab-panel>
                   <h3>Panel 2</h3>
                   <p>2. Lorem ipsum dolor sit amet</p>
               </ebay-tab-panel>
               <ebay-tab-panel>
                   <h3>Panel 3</h3>
                   <p>3. Lorem ipsum dolor sit amet</p>
               </ebay-tab-panel>
           </ebay-tab>

https://www.loom.com/share/c43a8bdc077e486d8d5e41d9709b4e35

**Comment by ianmcburnie** [comment]
Closing as invalid (as per @seangates comment offline)
