### ISSUE TITLE
Notice: dismissable button should not be rendered for inline notice

### ISSUE THREAD

**Issue by abiyasa** [eBay/ebayui-core#895]
# Bug Report

## Description

When you create an inline notice type="inline" and dismissable, the dismissable button is rendered (see attachment below).

```
<ebay-notice
    status="confirmation"
    type="inline"
    a11y-heading-text="Confirmation"
    dismissible>
    <p><strong>Success:</strong> There should not be a close button</p>
</ebay-notice>
```

**Expected**: Dismissable button should not be rendered for inline notice as defined on Playbook.

## Screenshots

<img width="687" alt="dismissable-inline-notice" src="https://user-images.githubusercontent.com/1072047/65992193-08c38b80-e48f-11e9-93f1-b9d6ee9c168d.png">

### Short-term solution

Ignore dismissable props for inline type. The dismissable button will not rendered for inline notice. I created [a branch which does this](https://github.com/eBay/ebayui-core/compare/master...abiyasa:bugfix/dismissable-inline-notice) and if eveything is OK, I can make a PR.

### Long-term solution

This is a design problem where we have [boolean trap on component design](https://spicefactory.co/blog/2019/03/26/how-to-avoid-the-boolean-trap-when-designing-react-components/). 

User of eBayUI Core library could end up with impossible or non-existing component states, for example:

- an inline notice with a dismissable button, 
- a button with priority="primary" but with variant="delete", 
- a fake tab but with href props,
- ...

Of course we could ignore these impossible states but the user then has to read the README or Playbook just to find out if certain combinations of properties are allowed/working.

We could solve this by splitting the component into several smaller ones. For ebay-notice component, I would split it into 2:

- ebay-inline-notice
- ebay-page-notice

The ebay-inline-notice would have fewer properties. Since it will not have a dismissable button, it will not have the following properties:

- dismissable
- a11y-close-text
- type (not necessary anymore)

and no need to emit any events.

We could do the same for other components. This could simplify component implementation, tests, and also documentation. If we integrate TypeScript or auto-complete feature later on, user can get faster feedback during development.

What do you think?

**Comment by seangates** [comment]
@abiyasa This is a fantastic write up. In fact, the line of thinking to create `<ebay-inline-notice/>` and `<ebay-page-notice/>` is something @ianmcburnie and myself were talking about just today.

>Of course we could ignore these impossible states but the user then has to read the README or Playbook just to find out if certain combinations of properties are allowed/working.

This is a great point, and one we want to address for our developers.

Where appropriate we've tried to use enumeration and avoid the boolean problem. Sounds like we missed it in this case. Thanks for bringing it to our attention.

**Comment by ianmcburnie** [comment]
Thanks @abiyasa 

Totally agree regarding the boolean trap. While we do our best to catch these upfront, sometimes they slip in unknowingly, and sometimes knowingly (due to a time crunch we might have to take on the "tech debt"). However, we do recognize this as a code smell, and like any big framework once we identify the smell we take steps to figure out if, how and when to fix it. If we don't, the framework soon becomes an unwieldly mess. I actually think we already have too many of these smells, and so I think we will be addressing this sooner rather than later.

The plan for notices is to split them out into smaller components, exactly as you describe. We will go through and review other components too.

Thanks for the excellent write up. You've saved me the trouble! :-)

**Comment by ianmcburnie** [comment]
Scheduling this for v4.4.0. We should be able to do it in a backwards compatible way as a wrapper around the current component. In time we can discourage use of the underlying component or even remove it from docs.

**Comment by abiyasa** [comment]
Thanks, glad to help!

> a fake tab but with href props,

Sorry, what I meant was **a non-fake tab with href props on its heading** but I think you got the point 😁 

No worries about the tech debt. It's a sign that the library grows which is a good problem to have. 

If you want I could give help identifying the components that need changes and also discussing or implementing the solution. Our team (DE regional team) plan to contribute to eBay open source projects for Q4 and we can even put the works on our backlog. Just DM me on Slack for the details 😉

**Comment by ianmcburnie** [comment]
@abiyasa That sounds great. I would gladly accept your help. Let's chat on Slack. I know this issue has been a concern of @DylanPiercey too, so it would be great for us all to get together and discuss.

**Comment by ianmcburnie** [comment]
I can close this issue as dismissible notice no longer exists, however we are still planning on address these kind of underlying issues. See https://github.com/eBay/ebayui-core/issues/976. In fact we are starting it right now (I will share a document internally).
