### ISSUE TITLE
Menu Button: documented events don't match implementation

### ISSUE THREAD

**Issue by dkallus** [eBay/ebayui-core#902]
# Bug Report

## Description
Documented menu-button events are shown as `menu-expand`, `menu-collapse`, ... However, in implementation the events are actually `menu-button-expand`, `menu-button-collapse`, ...

Documented events: https://github.com/eBay/ebayui-core/blob/v4.2.0/src/components/ebay-menu-button/README.md#ebay-menu-button-events

Implementation: https://github.com/eBay/ebayui-core/blob/v4.2.0/src/components/ebay-menu-button/index.js#L130

## Workaround
Use `menu-button-{event}` instead of `menu-{event}`

**Comment by seangates** [comment]
Thanks. I’ll make the edits as part of my PR.
