### ISSUE TITLE
Menu Button: add configuration to allow focus management to go to first item instead of checked item

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#906]
We'll need a new enumerated attribute. We should keep the current behaviour as the default. This new behaviour is opt-in (we might make it the default in future, when we get the chance).

We are going to try and do this as a 2.9.0 minor version if a simple code change. If not, it will go in latest 4.x.

**Comment by ianmcburnie** [comment]
Actually, another option is to treat this as a bug, and NOT set focus to checked item ever, but always to first item. I'm a bit worried about breaking existing experiences however.

**Comment by ianmcburnie** [comment]
In the case where the page doesn't update the button with the value of the checked item, I can see that we'd want the current behaviour.

In the case where the page does update the button with the value of the checked item, I can see that we'd want the proposed behaviour.

**Comment by seangates** [comment]
This doesn't apply to menu, because menu never updates its own label.
