### ISSUE TITLE
ebay-menu- variant=overflow : no indicator to highlight that the button is selected. 

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#907]
# Bug Report

## Description
unlinke other ebay menu icons this is narrow, usually present on the corner of the page and borderless , when expanded there is no indication the the icon is selected

https://www.loom.com/share/511763b9bd0b4c88be1c18253cab53f7

if you see the above video, the focus does not stay or the button is not highlighted, no color change etc.  

We can probably ask the design team on this. Feel free to close it if you think its ok for it to behave this way.

**Comment by ianmcburnie** [comment]
Focus actually moves from the button to the menuitem. This focus state is not clear due to the fact that we are only using background-colour to indicate focus state. This issue will be fixed as part of https://github.com/eBay/skin/issues/633. Going to close.

**Comment by ianmcburnie** [comment]
Closing this as invalid, as the button should not have any focus state, only the menu item.
