### ISSUE TITLE
infotip: pointer alignment is off

### ISSUE THREAD

**Issue by dkallus** [eBay/ebayui-core#911]
# Bug Report

## Description
* Expected: the pointer/textbox should be near the infotip button with minimal spacing
* Actual: the pointer is off center and has unnecessary spacing between button and textbox

To reproduce, I modified 1 of the infotip examples to use `pointer="top-left"`. I didn't try other `pointer` values, but they also could be affected. Also, I didn't try `tooltip` or `tourtip` components.

## Workaround
None that I tried. Might be able to override styling to fix alignment.

## Screenshots
<img width="919" alt="infotip" src="https://user-images.githubusercontent.com/844822/66504440-ef69a300-ea7d-11e9-9d26-1cf863ec5a65.png">

**Comment by seangates** [comment]
@ianmcburnie I went through and actually did this. Shoot. I didn't realize it had been assigned already. (I was just filling some time this evening. 😞 )

**Comment by ianmcburnie** [comment]
That's fine. Thanks for the fix. Just reassign it to yourself. Lokesh hasn't started on it yet. There's one on the skin side too, not sure if you are tackling that aswell...
