### ISSUE TITLE
menu-variant=overflow: icon not present in ds4 

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#912]
# Bug Report

## Description
just filing this to keep track of the issue we already know

**Comment by dkallus** [comment]
I created https://github.com/eBay/ebayui-core/issues/904 earlier to track.

PR is ready to be merged: https://github.com/eBay/ebayui-core/pull/905

**Comment by ianmcburnie** [comment]
Fix is in 4.3.0-1 release ready for QA. Closing.

**Comment by hramakumar** [comment]
verified
