### ISSUE TITLE
action button in IE 11 is big and takes the entire height of the ebay notice

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#915]
# Bug Report

## Description
the secondary button in page notice takes the entire height of the notice
## Screenshots

![image](https://user-images.githubusercontent.com/13157115/66601169-1d251980-eb5c-11e9-9489-20c2a30122be.png)

**Comment by seangates** [comment]
@hramakumar I don't believe we'll be addressing IE11 bugs like this. Only if it blocks functionality.

**Comment by agliga** [comment]
Im opting as wont fix.
A possible fix would be to set the flex to `1 0 auto`  but did not test
