### ISSUE TITLE
Notice: button alignment issue with guidance notice (iOS, DS4)

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#916]
# Bug Report

## Description
IOS ds4 page notice with button- placement is off
![ds4_mweb_notice](https://user-images.githubusercontent.com/13157115/66603434-0cc36d80-eb61-11e9-821a-ec913930d97b.png)

**Comment by agliga** [comment]
This should be fine, since this is a DS6 button style, we included it in DS4 with minimal markup
However, I think this should not be a blocker since this is a DS6 style and we can patch it later if there is an issue.

**Comment by ianmcburnie** [comment]
I don't think this is a blocker.

**Comment by ianmcburnie** [comment]
Closing due to very low priority.
