### ISSUE TITLE
ebay-button: dynamic attributes are not being added to the button

### ISSUE THREAD

**Issue by BhavinPatel04** [eBay/ebayui-core#918]
# Bug Report

## Description
**Steps to reproduce:**
````
let commonAttrs = {
    priority: "primary",
    data-href: "some-href"
}
let specificAttrs = {
    data-value: "someValue"
}
<ebayui-button ...commonAttrs ...specificAttrs>Button</ebayui-button>
````
**Expected:**
Button should have `priority`, `data-href` and `data-value` attributes
**Actual:**
Button only takes `priority` attribute

## Workaround
````
<ebayui-button  priority="primary" data-href="some-href" data-value="someValue">Button</ebayui-button>
````

**Comment by LokeshRishi** [comment]
@BhavinPatel04 It seems like you are using incorrect attribute names:
- `data-href` -> `href`
- `data-value` -> `value`

Could you please try with the above mentioned changes?

**Comment by BhavinPatel04** [comment]
@LokeshRishi they are some examples of attributes that are not mentioned in the table in README. For example: `data-template`, `_sp`, `anyOtherAttr`

**Comment by BhavinPatel04** [comment]
This issue is not fixed. I am still facing this issue in v4.4.0-1.

**Comment by ianmcburnie** [comment]
We'll look into it and push another pre-release.

**Comment by ianmcburnie** [comment]
Done in 4.5.0.
