### ISSUE TITLE
Utils: event.charCode & event.keyCode are deprecated

### ISSUE THREAD

**Issue by darkwebdev** [eBay/ebayui-core#920]
# Bug Report

## Description

Rather low-priority, not even a bug yet, but will become one day because [KeyboardEvent.keyCode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) and [KeyboardEvent.charCode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/charCode) are deprecated in favor of [KeyboardEvent.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) and [KeyboardEvent.key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key).

Used here: https://github.com/eBay/ebayui-core/blob/master/src/common/event-utils/index.js

`KeyboardEvent.code` doesn't have IE support, so I'd recommend to use `KeyboardEvent.key` or to wait until we don't need IE.

And I would recommend using string enums.

**Comment by ianmcburnie** [comment]
Moving to superbacklog.
