### ISSUE TITLE
ebay-button: API discussion & improvements

### ISSUE THREAD

**Issue by darkwebdev** [eBay/ebayui-core#923]
Some questions:
- Do we want to keep the `delete` value for both `priority` and `variant` property?
- Does it make sense to call a property `priority` if it has a `delete` value?
- Do we need a value `fake-link` for `variant` property when we can just infer it from the `href` property?

Some notices:
- `icon` variant is not in the readme

**Comment by ianmcburnie** [comment]
We were planning on tackling the API as a whole in v6 (we've just started).

But @agliga i think bullets one, three & four could be tackled now, so I'm moving to 5.7.0

**Comment by ianmcburnie** [comment]
Closing as we are addressing this in both #976 & #1165. Thank you @darkwebdev for bringing this to our attention. We are finally getting there ;-)
