### ISSUE TITLE
Carousel: add option to always show paddles

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#934]
Deals & events team has a case where slideshow carousel (i.e. one item per slide) has many slides, resulting in many dots, which does not look good. Ideally they would reduce the amount of items in the carousel, but this is not possible.

Removing the dots removes all kind of affordance (as the paddles only show up on hover in this case). Adding a small peek does not look good either.

So I'm proposing to add an option to always show paddles for this scenario.

Perhaps a `paddles` attribute with the following values to begin with:

* `auto` - automatically determined (default, current behaviour)
* `on` always show

<img width="412" alt="Screen Shot 2019-10-22 at 3 10 31 PM" src="https://user-images.githubusercontent.com/38065/67341432-7ee26d80-f4e4-11e9-81fd-ebae9e43b630.png">

**Comment by sairam0903** [comment]
Can't wait to see this option for the Carousel

**Comment by ianmcburnie** [comment]
So, I was under the impression that the above behaviour was by design on our end. But thinking about it, it doesn't really makes sense. A much simpler proposal from me would have been to just say "always show paddles when `no-dots` and `items-per-slide=1`. Sorry. We could possibly still keep this option as a secret option if we feel it's useful...

**Comment by sairam0903** [comment]
@ianmcburnie So the solution for this issue is, when `items-per-slide=1` and `no-dots` is set, we always show the paddles without any secret option?

**Comment by ianmcburnie** [comment]
@sairam0903 That's correct. Let us know if you foresee any issue with that.

**Comment by sairam0903** [comment]
I think that should be fine, let us know the version to upgrade when this is out.
