### ISSUE TITLE
ebay-menu-button-item: Attributes not being passed along to the rendered link

### ISSUE THREAD

**Issue by tws2000** [eBay/ebayui-core#939]
#909 Bug Report
Attributes added to <ebay-menu-button-item> are not being rendered in the resulting link.

## Description
For instance if I use ```<ebay-menu-button type="fake"><ebay-menu-button-item href="http://www.ebay.com" data-track="123"/></ebay-menu-button>```, I'd like the menu item link to have the data-track attribute and value.

**Comment by ianmcburnie** [comment]
Fix added to 9.4.0-1
