### ISSUE TITLE
Page notice celebration UI mismatch in test app and marketplace

### ISSUE THREAD

**Issue by ushrivastava123** [eBay/ebayui-core#953]
##eBayUI Version: v4.5.0-0 and skin version v9.4.0-1

## Description
Page notice celebration UI mismatch in test app and marketplace
Please see the screenshots

## Screenshots
Actual in test page
![image](https://user-images.githubusercontent.com/57548118/68518601-7f4b6a00-0241-11ea-9ff0-789a4951fc9a.png)

Expected in marketplace
![image](https://user-images.githubusercontent.com/57548118/68518621-8ffbe000-0241-11ea-98eb-2a7cd842092c.png)

**Comment by agliga** [comment]
Issue is that in `@ebay/skin@9.4.0-1` the styles for page notice celebration are not there, but they are in the release version: `@ebay/skin@9.4.0`
