### ISSUE TITLE
Tracking ticket for divergences between 4.x and 5.x branches

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#956]
Let's use this ticket to track anything that has gone into 4.x branch *after* the Marko v4 migrations in 5.0.0 branch were started. So far we have:

* Infotip: location fixes - Storybook examples (#952) (possibly undone, intentionally, by #966)
* Change browser.json to require widget properly #958 (not required in Marko4)
* Upgrade to skin 9.5.0
* Infotip: fixed icon alignment issues #966
* Upgraded devDeps
* Docs: added deprecation guidance #352
* Add click and escape key event handling; (#973)
* Combobox: allow custom ID (#972)

**Comment by ianmcburnie** [comment]
This is an issue that Eamon can potentially help with. NOTE: 4.3.3 release from master will need merging into 4.5.0 before beginning this task. @seangates will take care of that as there were a couple of merge conflicts.

**Comment by ETCaton** [comment]
> Change browser.json to require widget properly #958 (not required in Marko4)

Was this resolved by #959 @agliga?

**Comment by ETCaton** [comment]
> Upgrade to skin 9.5.0

This seems to be the case already in 9.5.0 (introduced as part of #966)

**Comment by agliga** [comment]
> > Change browser.json to require widget properly #958 (not required in Marko4)
> 
> Was this resolved by #959 @agliga?

This isn't needed for `5.0.0` since we have removed all `browser.json` dependencies except for external ones.

**Comment by ETCaton** [comment]
That's what I saw, but I just wanted to make sure I was tracing the issue resolutions correctly; "#959 was the resolution to #958?" is what I meant to ask

**Comment by agliga** [comment]
> That's what I saw, but I just wanted to make sure I was tracing the issue resolutions correctly; "#959 was the resolution to #958?" is what I meant to ask

Yes, one is the issue and the other is the pull request 👍
