### ISSUE TITLE
Should we deprecate "HTML-like" component syntax in favor of pure Marko syntax?

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#962]
Something we've talked about offline is that while the HTML-like syntax makes the components appear more friendly & familiar to HTML developers, by doing so we are slightly obfuscating the Marko workings. This could lead to a reduced understanding of Marko's concepts, and a greater barrier to entry for contributing to the project & framework. As ever...pros and cons!

For discussion.

**Comment by darkwebdev** [comment]
How would the components look like? Could you give me the example?

**Comment by ianmcburnie** [comment]
Closing, as this is part of #976.
