### ISSUE TITLE
Carousel: refactor for Marko v5 & FLUURT

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#963]
We have identified this as one of the components most in need of a refactor.

See also:

https://github.com/eBay/ebayui-core/issues/426
https://github.com/eBay/ebayui-core/issues/361

**Comment by agliga** [comment]
Also on a side note we should consider adding fluurt support to carousel when doing this refactor.

**Comment by agliga** [comment]
Closing for now, this needs to be done but will be done as part of the marko 6 upgrade.
