### ISSUE TITLE
Combobox: support an 'id' to be passed in to associate to a label 'for' attribute

### ISSUE THREAD

**Issue by melquan** [eBay/ebayui-core#968]
# Feature Request

## Description
Support an 'id' to be passed in to associate to a label 'for' attribute.

## Context
Currently the component does not support `id` to be passed so that the app can associate a label to it.  It has `w-id="input"` but due to the nesting, the app cannot have a label with `w-for="input"` as the IDs generated by Marko will not match.  In my case, it is nested 2 levels deep.

## Screenshot
![image](https://user-images.githubusercontent.com/19419138/69675736-2dce1800-1054-11ea-9be7-b311d81a9444.png)

**Comment by ianmcburnie** [comment]
Thanks @melquan 

Scheduling this for v5.0.0, but we can back port to 4.x if needed.
