### ISSUE TITLE
Discussion: v6.0.0 refactoring and breaking changes

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#976]
The primary focus of v6.0.0 will be some cleanup, refactoring and breaking changes. No new features, if possible.

Lots of good background info in this closed ticket too: https://github.com/eBay/ebayui-core/issues/895

This is a list of suggestions/ideas that came from team standup (mostly Dylan!). Feel free to amend and append to this list...

* <strike>P1 Transformers/ issues preventing teams already on Marko v5 upgrading to CoreUI 6
   * Split up icons into individual components
   * All icons dependent on icons</strike> - DONE
* <strike>Reduce strict adherence to HTML tag syntax. Find a middle ground between Marko and HTML
   * Remember: "If you know HTML, CSS, and Javascript, you know Marko"</strike> (Added `<@attribute>` tags)
* <strike>Split up notice components (https://github.com/eBay/ebayui-core/issues/1158)
   * page-notice, inline-notice, section-notice, window-notice</strike> - DONE
* <strike>Split up dialog components (https://github.com/eBay/ebayui-core/issues/1164)
   * lightbox-dialog, panel-dialog, fullscreen-dialog</strike> - DONE
* <strike>The HTML-like API...
   * Revert to pure Marko syntax for nested attribute tag
   * Pass actual types instead of strings</strike>
* <strike>Events
   * Remove event name prefixes (we don’t need this anymore since we removed native DOM events with the imperative API)
   * Revisit event data and make consistent (some of the event data is like a random grab bag of stuff)</strike>
* <strike>Review attr tag usage
   * dialog header
   * drawer header
   * toast header
   * stepper step</strike>

Leave for v7

* Does `ebay-` prefix still make sense?
   * We want to make coreui the North Star for Marko components
   * Maybe ‘core-’ instead
* Button (comments originally from @darkwebdev in #923)
   * Does it make sense to call a property "priority" if it has a delete value? Answer: probably not. Maybe rename to "variant". We could move to even higher level of encapsulation with `ebay-primary-button`, `ebay-delete-button` etc (we already have `ebay-expand-button` and `ebay-cta-button`). See: https://spicefactory.co/blog/2019/03/26/how-to-avoid-the-boolean-trap-when-designing-react-components/
   * Do we need a value fake-link for variant property when we can just infer it from the href property?  Long term it might be best to split `ebay-button` out into `ebay-fake-button`.

Leave for v8

* Need a consistent I18N strategy
   * Remove hardcoded English defaults
   * Perhaps make all strings required at compile time?
   * Align with standard L10N bundle support (`.properties` file)

**Comment by DylanPiercey** [comment]
Something I noticed while refactoring the pagination component:

The `type` attribute API feels awkward. IMO the `previous` and `next` controls should be their own nested tag, and if not specified it just would display a disabled arrow.

Eg instead of

```marko
<ebay-pagination>
    <ebay-pagination-item type="previous" disabled/>

    <for|i| from=0 to=15>
        <ebay-pagination-item current=(i === 5)>
            ${i}
        </ebay-pagination-item>
    </for>

    <ebay-pagination-item type="next"/>
</ebay-pagination>
```

we could do

```marko
<ebay-pagination>
    <ebay-pagination-previous disabled/>

    <for|i| from=0 to=15>
        <ebay-pagination-item current=(i === 5)>
            ${i}
        </ebay-pagination-item>
    </for>

    <ebay-pagination-next/>
</ebay-pagination>
```

There may still be a better API than this also, either way I think it's worth a discussion.

**Comment by DylanPiercey** [comment]
Something else I think would be good to remove is the `html-attributes` attributes. It has always been confusing and is now not necessary after https://github.com/eBay/ebayui-core/pull/946. We can automatically migrate it as well in most cases.

**Comment by ianmcburnie** [comment]
Leaving a note here regarding dialog:

* We should use open/close or hide/show as the event name pairs. Not a mix of the two.
* We need to investigate how we can make it easier to connect up dialog header `id` with `aria-labelledby`

**Comment by ianmcburnie** [comment]
Another one (raised by Andrew):

* Tabs and Fake-Tabs both have `selectedIndex` which is set on the component root (in V6 branch). Tabs and Fake Tabs are always single-select.
* Fake-Menu has `current` which is set at the child element level (in V6 branch). Fake Menu is always zero-select or single-select.
* Menu has `checked` which is set at the child element level - menu can be zero-select (menuitem), single-select (radio) or multi-select (checkbox)

**Comment by ianmcburnie** [comment]
I think we can close this one now. Job well done for v6. Anything leftover is moved to #1233
