### ISSUE TITLE
[BUG] ebay-icon name=search is getting wrong icon

### ISSUE THREAD

**Issue by uachladi** [eBay/ebayui-core#993]
ebay icon search is showing following icon 
<img width="26" alt="Screen Shot 2019-12-16 at 4 58 48 PM" src="https://user-images.githubusercontent.com/13039089/70955352-63e43380-2025-11ea-9a8c-7e1d943f9629.png">

**Comment by ianmcburnie** [comment]
@uachladi Which version of Marko do you use? Can this fix wait until CoreUI v5.0.0? Or do you need it in 4.5.x release?

**Comment by uachladi** [comment]
@ianmcburnie, We use Marko 3. We are planning release a feature with this icon in January 2 week. When will the v5.0.0 available?

**Comment by ianmcburnie** [comment]
@uachladi Thanks for the info. We'll get a patch release out for you ASAP in 4.5.x.

**Comment by ianmcburnie** [comment]
Fixed by Andrew in 4.5.x
