### ISSUE TITLE
Carousal buttons are not seen on IE 11 and IE edge upon hover

### ISSUE THREAD

**Issue by ushrivastava123** [eBay/ebayui-core#998]
# Bug Report
The prev/next btns on ebay-carousel are not working properly on IE 11 and edge, they are not visible when hovering over the slides.

## Description
Open test app on IE 11 or IE edge. Go to Carousal component. Prev/Next are not seen upon hovering.

## Workaround
Scrolling works but the icons don't focus upon hover.

**Comment by agliga** [comment]
Released in `4.5.2`
